### ISSUE TITLE
A non-clickable "figcaptions"?

### ISSUE THREAD

**Issue by egoipse** [dimsemenov/PhotoSwipe#1001]
Hi! Photoswipe is a great plugin. It works delightfully.

There's just one issue we couldn't solve: the captions displayed on thumbnails layout are clickable and they open photoswipe, so it's not possible to add a html link; when the link is clicked (and when any of the "figure" elements displayed on thumbnail layout is clicked too), instead of open the link, photoswipe is open.

You can see the issue in this page: http://agenciasportiva.com/photoswipe.html

Is there any way to change this behaviour? I didn't find any reference to this issue in documentation, faqs or github's threads.

Thanks in advance for the assistance.

Ragards,

Daniel

**Comment by egoipse** [comment]
Nevermind, we finally found the way...

**Comment by Le-future** [comment]
Hello!

I'm having the same trouble, can you tell me how do you dealed with it?

Appreciate
