### ISSUE TITLE
Html from ajax call

### ISSUE THREAD

**Issue by kotchuprik** [dimsemenov/PhotoSwipe#1005]
Hello, your gallery is awesome. I found few use cases in documentation but I have one question — how I could use PhotoSwipe gallery with ajax content?

My use case next:
1. Page has few photos on a page
2. Each photo has details in database (for example, product. link to product and other photos stored in database)
3. Showing cool Html content when user clicked on image

Thank a lot and sorry if unclear. Feel free to ask me about any details.

**Comment by mjau-mjau** [comment]
There is a full API for photoswipe here:
http://photoswipe.com/documentation/api.html

Basically you can trigger your ajax call from one of the photoswipe `change` events, and then populate/replace the caption once your ajax data is loaded.

**Comment by kotchuprik** [comment]
yeah, thanks. I have did it one week ago and I forget to close issue :)
