### ISSUE TITLE
Image Squashed

### ISSUE THREAD

**Issue by vdyo** [dimsemenov/PhotoSwipe#1007]
Hi, images are squashed, we cant work out why. Go here https://screenshowcase.vdyo.co/video/details/three-blind-mice and select images. The fist image wont load as its a TIFF, but the second Image is showing as squashed for some reason, but we are serving a correct size image.

Thanks

Damian

**Comment by dimsemenov** [comment]
Size that you defined in `w` & `h` attributes doesn't match real size of your image.

**Comment by vdyo** [comment]
Hi

When I view source of the page it shows the image call being
https://res.cloudinary.com//vdyo//image//upload//a_0,c_crop,h_1202,w_974,x_-12,y_-378//lu5noolzo0l5h7skvarg

If I load that into a browser the dimensions are correct, is there
something in photoswipe we need to put the dimensions as well?

Regards

Damian

**Comment by vdyo** [comment]
We need to use our crop info, do we must define w & h attributes?

**Comment by vdyo** [comment]
Hi, any ideas? I really like photoswipe and want to us it but we need to deal with the ratio issues.

**Comment by dimsemenov** [comment]
Yes, you must define w & height properties, as I posted in the first reply.

**Comment by vdyo** [comment]
Ok I got it. I just dont know how to nwo get the original dimensions as we are showing a crop version.

**Comment by vdyo** [comment]
It it possible to turn of the sharing and download ?

**Comment by mjau-mjau** [comment]
> It it possible to turn of the sharing and download ?

http://photoswipe.com/documentation/options.html

**Comment by jhabdas** [comment]
@vdyo can this be closed?
