### ISSUE TITLE
Images don't show in Firefox 42, Mac OS

### ISSUE THREAD

**Issue by freiserg** [dimsemenov/PhotoSwipe#1014]
Hi!

When I slide images, second, third images don't show. 

Most likely it's a bug in firefox. When I resize window of browser, image will display.
<img width="1046" alt="firefox_bug" src="https://cloud.githubusercontent.com/assets/1901439/11033245/be2a7492-86f2-11e5-98b4-eaed132a4c65.png">

**Comment by dimsemenov** [comment]
Investigating, thx for report.

**Comment by dimsemenov** [comment]
It seems FF is doing some optimization for elements outside of bounds of another element. Video of isolated issue: https://www.youtube.com/watch?v=wXjdE8BfdMI

Posted a bug on FF bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1223003 

**To fix for PhotoSwipe**: remove one `will-change:transform` style from main CSS file, here - https://github.com/dimsemenov/PhotoSwipe/blob/master/src/css/main.scss#L148 (it won't affect other browsers,as they rely as a fallback on `-webkit-backface-visibility`, which triggers hardware-acceleration the same way).

**Comment by freiserg** [comment]
Thanks. I don't understand, how you find it.

**Comment by mjau-mjau** [comment]
Confirmed. Lazy fix:
```css
.pswp--animate_opacity,
.pswp__bg,
.pswp__container,
.pswp__zoom-wrap {
  will-change: auto;
}
```
Make sure the above css is applied/loaded *after* the default photoswipe css.

**Comment by sebastianbaumann** [comment]
Ahhhh.… it took me 15 minutes to fix the issue by myself. I should have checked the git issues before, but I can confirm the bug on Firefox 42 on OS X 10.11. Behaves like expected in all other browsers. Removed `will-change` and it seems to work again in Firefox.

**Comment by swa66** [comment]
Even if the next FF release does fix this, would it not be better to do a photoswipe release that has the workaround ?
Somebody out there might still be running FF 42 many months from now...

**Comment by dimsemenov** [comment]
@swa66, this repo already has warkaround in CSS file, see commit 1a061a6.
