### ISSUE TITLE
Image Height is stretched on open

### ISSUE THREAD

**Issue by gazarolli** [dimsemenov/PhotoSwipe#1027]
Hi.
Photoswipe is great, thanks!

I have just one problem - when opening the gallery, the height of the first image is stretched. After 1 sec it is ok automatically. When clicking next, this happens again for some other images.

you can see this live under http://zurerinnerung.at/blog/ (black/white pictures in the middle of the page).

is this a problem of slow hardware?
i have tried it on various computers and smartphones. it is the same everywhere!

see also the pic:
![photoswipe-problem](https://cloud.githubusercontent.com/assets/16034736/11426110/f01c7a62-9459-11e5-9ac9-8fb9b5fdaec3.jpg)

thanks and regards
Michael

**Comment by dimsemenov** [comment]
You're focing height:auto on img element.
