### ISSUE TITLE
How to disable Photoswipe Animation for Thumbnails

### ISSUE THREAD

**Issue by mgk89** [dimsemenov/PhotoSwipe#1029]
I do have square thumbnails and due to the animation on clicking on thumbnails the large images are not shown properly because they are stretched.

So I would like to disable the zoom-animation for thumbnails.

How do I have to set these settings?

Thank you

**Comment by dimsemenov** [comment]
Just don't define `msrc` property in slde objects and `getThumbBoundsFn` option.

**Comment by mgk89** [comment]
Hi, thank you for your post. Can you explain that a little bit more in detail? Where are these settings defined?

**Comment by dimsemenov** [comment]
http://photoswipe.com/documentation/options.html

**Comment by ianthedev** [comment]
> Just don't define `msrc` property in slde objects and `getThumbBoundsFn` option.

Could you please explain the solution for v5, which does not have the `msrc` property and `getThumbBoundsFn` option?

**Comment by ianthedev** [comment]
I set the showHideAnimationType option to 'fade', but I still see a blurred image getting replaced by a clear image when the lightbox opens. The blurred image probably is the magnified thumbnail.
