### ISSUE TITLE
Add default_skin.html to dist

### ISSUE THREAD

**Issue by chuv** [dimsemenov/PhotoSwipe#1031]
Hello. I not found default html template in repository. Сurrently it need to add manually (copy/paste from documentation), instead require as dependency. Please add default-skin.html near other files like css/png/svg. Webpack users will say thank you.

**Comment by xiaoma-china** [comment]
Sent from Alto
On 星期一, 十一月 30, 2015 chuv <notifications@github.com> wrote:

Hello. I not found default html template in repository. Сurrently it need to add manually (copy/paste from documentation), instead require as dependency. Please add default-skin.html near other files like css/png/svg. Webpack users will say thank you.

**Comment by dimsemenov** [comment]
I'm planning to include it to separate JS file that would also include basic init code, so closing the issue. Thanks for suggestion anyway.
