### ISSUE TITLE
PhotoSwipe initialization question

### ISSUE THREAD

**Issue by GiuTaeKim** [dimsemenov/PhotoSwipe#1032]
Hello... I'm new at github. Actually this is my first activity.
I'm here to learn about JavaScript. I consider your plugin a __master-piece__. And I'm learning a lot by studying the source-code. Rly appreciate your work to make this aviable to the community.

_This issue is not an issue at all... I just want to understand the core functionality._

In your gallery example... I digg into the code of the handlers you bind to the links.
And find out that in every click, you create a new instance of PhotoSwipe by the __new__ operator.

That confuss me a little bit. Cause this is a very different paradigm than other JS plugins where you create the instance only once... and later you interact with it using public methods. Something like: Creating only one instance of PhotoSwipe, and later open with __myPhotoSwipe.open()__ and close with __myPhotoSwipe.close()__ (maybe with an index in de parameters). Dunno... the gallery being initializated over and over again in the same page... fells a little weird for me.

I know that the developer may have good reasons to follow this paradigm. _But maybe someone have the time to explain me better._

Thanks in advance... and keep the good work. This is the best gallery plugin with pure JavaScript, and take this words from someone that have used a lot of plugins.

**Comment by mjau-mjau** [comment]
I was wondering the same some time ago. To be honest, it does not make much difference one way or the other. Re-initializing the gallery on some click (after close), may take another few milliseconds extra, but it allows a bit more flexibility for dynamic stuff, and frees up memory. See this post #891

**Comment by GiuTaeKim** [comment]
Thanks u very much @mjau-mjau. The post you pointed out makes a lot of sense, specially the memory aspect. Thanks again!
