### ISSUE TITLE
bug on mobile

### ISSUE THREAD

**Issue by simonpeters** [dimsemenov/PhotoSwipe#1033]
WHen I open photoSwipe on a mobile device it seems to scale down the image to a smaller size then the images orignal size. On desktop it alwayse gives the images in its full width and height.

Anyone else that has had this issue?

**Comment by mjau-mjau** [comment]
Not quite sure what you mean. It won't load a different image, unless you have set this specifically. It will scale down the image to fit within the mobile viewport. If it doesn't, then I would like to see an example, because that's how it works from here ...
