### ISSUE TITLE
How to make the "pop out" image effect?

### ISSUE THREAD

**Issue by Cedriking** [dimsemenov/PhotoSwipe#1034]
Hello there,
I'm trying to add the pop out image effect that the homepage of PhotoSwipe has, when you click in the thumbnails the image pop out of the dom to get bigger and be shown as the lightbox, but I'm unable to reproduce this, and I can't find an option in the options page: http://photoswipe.com/documentation/options.html 

Thank you.

**Comment by dimsemenov** [comment]
- define msrc property for slide objects with path to small thumbnail.
- define getThumbBoundsFn option
2 дек. 2015 г. 12:03 AM пользователь "Cedriking" <notifications@github.com>
написал:

**Comment by Cedriking** [comment]
Thank you @dimsemenov it worked! But how can I make it also work on mobile?

**Comment by dimsemenov** [comment]
These options have no difference between desktop and mobile.
