### ISSUE TITLE
Always opens with first image

### ISSUE THREAD

**Issue by mgk89** [dimsemenov/PhotoSwipe#1035]
The script just worked fine as I wanted it, but after implementing it to the rest of the page, a strange thing happened:

It does not matter on what thumbnail I click, Photoswipe ALWAYS opens with the first picture. There is nothing in the settings I changed - before I included it to my page it just worked as it is expected to do.

I'm asking if anybods has a clue what can cause that behavíour before I post links or tons of code ...

Thanks in advance!

**Comment by mgk89** [comment]
here is a link where you can see the issue:

http://bit.ly/1QU5ND8

**Comment by mgk89** [comment]
here is a link where you can see the issue:

http://bit.ly/1QU5ND8

**Comment by WalkMan32** [comment]
I have the same problem. Tell me, please, with a solution
