### ISSUE TITLE
Link in Caption

### ISSUE THREAD

**Issue by YuccaV2** [dimsemenov/PhotoSwipe#1036]
Hello,
Is there a way to have a link in caption, this is the right place for me, but it could be somewhere else ?
Like so :
<figcaption itemprop="caption description"><a href="#" class="myClass" >Link</a></figcaption>
When I do that and clic on my link, photoSwipe close. Thanks in advance.

**Comment by fabiocaccamo** [comment]
Yes, your caption should be a link which calla a function that closes PhotoSwipe: http://photoswipe.com/documentation/options.html and look the `addCaptionHTMLFn` option.
