### ISSUE TITLE
How to change the PhotoSwipe's items dynamically ?

### ISSUE THREAD

**Issue by SimonWang2014** [dimsemenov/PhotoSwipe#1041]
I have some DIV in my html, everytime i click the images in the different div , how can i change the images dynamically ?
I tried to change the items , but errored:
```
Cannot assign to read only property 'initialLayout' of false
```

**Comment by dimsemenov** [comment]
There is a section at the bottom of API documentation on how to add/edit slides dynamically http://photoswipe.com/documentation/api.html

**Comment by EugeneDae** [comment]
It seems to be completely impossible to remove a previous slide via pswp.items.splice(0,1) in beforeChange/gettingData without running into a ton of bugs and errors :(
