### ISSUE TITLE
Problem when combining photoswipe with masonry

### ISSUE THREAD

**Issue by fotorunedotcom** [dimsemenov/PhotoSwipe#1042]
When I use photoswipe with masonry there is a problem when I rotate my touch device twice. It makes the photoswipe fullscreen viewer zoom in a lot so you can't see the whole image.

The problem appear when rotating device from landscape to portrait.

Without masonry it's no problem at all. But I need masonry..

Can you please help me fix this problem?

**Comment by dimsemenov** [comment]
Add overflow hidden to container of your masonry gallery to prevent it from extending beyond the bounds. 

Also, check http://stackoverflow.com/questions/11165460/responsive-site-is-zoomed-in-when-flipping-between-portrait-and-landscape-on-ipa
