### ISSUE TITLE
Issue with gallery not showing full screen on hudl

### ISSUE THREAD

**Issue by buddha-within** [dimsemenov/PhotoSwipe#1043]
![1444037482_photoswipepng 1](https://cloud.githubusercontent.com/assets/1751609/11786917/23f7891e-a281-11e5-967b-371837e97a9a.png)

The gallery is not filling the screen when triggered on a Hudl tablet. This happens on the Chrome and the default browser. Also tested and found same issue on a Nexus 10 (see screenshot which is same as hudl) . Worked fine on a samsung galaxy 5. Any advice would be appreciated.

**Comment by dimsemenov** [comment]
Can you repeat the issue on PhotoSwipe homepage? Is `pswp` element added directly to the body or inside some container?

**Comment by buddha-within** [comment]
No it works fine on the Photoswipe homepage. The pswp element is added
within a container div.
