### ISSUE TITLE
Compatibility with Lazysizes

### ISSUE THREAD

**Issue by kerns** [dimsemenov/PhotoSwipe#1044]
**Lazysizes** is among the best responsive image + lazyload solutions out there, and is very broadly used.

[https://github.com/aFarkas/lazysizes](https://github.com/aFarkas/lazysizes)

I've successfully implemented Lazysizes to lazyload the thumbnails of a Photoswipe gallery on a page, where the thumbnails are created via bg images on figure elements in a masonry style layout. The whole setup works really nicely.

But when the Lazysizes' [bgset plugin](https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/bgset/ls.bgset.js) is introduced in support of responsive BG images for these thumbnails – the Photoswipe images no longer scale up from and back down to their original thumbnail position. Instead they originate from and return to (0,0) – the top left corner of the screen, which looks very weird.

Can anyone see any reason why Lazysizes [bgset plugin](https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/bgset/ls.bgset.js) should interfere with Photoswipe thumbnails in this way? Should make them forget where they come from? Can I assume one of these two libraries is doing something wrong?

I understand you can't be expected to support or accommodate other code libraries outside of Photoswipe, but maybe a quick glance at [the plugin](https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/bgset/ls.bgset.js)  would tell you if it was Photoswipe or Lazysizes that is misbehaving. Or of course, the third option (which we must not entertain) – me.

**Comment by dimsemenov** [comment]
Coordinates are returned by `getThumbsBoundsFn` option that you define during the PhotoSwipe initialization, debug it by yourself and find out if correct coordinates are returned.

http://photoswipe.com/documentation/options.html

Or provide a reduced test case on CodePen or somewhere else, if you won't be able to resolve.

**Comment by kerns** [comment]
Of course, ...I should demonstrate in a CodePen. Thanks.

**Comment by kerns** [comment]
@dimsemenov Here we go...

[http://codepen.io/kerns/pen/wMMwoa](http://codepen.io/kerns/pen/wMMwoa)

The developer of Lazysizes has, based on a description of the problem, said the following (but he hasn't seen the pen, so he's guessing, but it sounds plausible.)

> I couldn't look into this. But I suspect the following: `data-bgset` delegates the actual source selection to the browser using `picture/srcset` and reads the currentSrc property from the img. This property is only updated after the image candidate was successfully loaded. This means the source is written much later to your div element than it would be written using `data-bg`. Which means that photoswipe is working on an empty/none source. Only way I can think of, is that you must delay the animation after the image was loaded.

Any ideas for a workaround?

**Comment by dimsemenov** [comment]
You just have an PICTURE element inside grid item that is hidden via display:none, it's not possible to get coordinates of element that is hidden this way.

You'll need to modify JS init code of PhotoSwipe to fit your markup:
- make sure that `getThumbBoundsFn ` returns correct coordinates (e.g. by making it look for coordinates of FIGURE element, not IMG),
- define `msrc` for slide objects (if you want transition to start from stretched thumbnail).

**Comment by kerns** [comment]
I'm not sure how to do this, but thanks for the input. I'll look for some help with it.

**Comment by kerns** [comment]
@dimsemenov As for **point two**, I am fine with the transitions as they are, as long as they fade out of and into the thumbnails. Regarding **point one**, that was actually fairly easy – I changed...

`var thumbnail = items[index].el.getElementsByTagName('img')[0] || items[index].el, // find thumbnail`

to...

`var thumbnail = items[index].el.getElementsByTagName('figure')[0] || items[index].el, // find thumbnail`

Has me wondering though, because I know I'm not the first person to struggle integrating Photoswipe in a masonry style responsive layout with BG images on a container (as opposed to an img) – why do you use `getElementsByTagName` and not something like `getElementsByClassName` ? Wouldn't that be more flexible and accommodate for more use cases, where the thumb could be an img element *or* some other block level element that is using a bg image (div, figure, etc).

As it is now, if I want to incorporate PS on an inline img element somewhere else in the layout, I'll need to edit this line. Just ...curious why you've taken this rigid approach.

**Comment by nikhiljohn10** [comment]
Hi there @kerns . Did you figured Photoswipe with lazysizes for responsive images? The link you posted if expired. Do you have any better solution for it?

**Comment by acwolff** [comment]
Lazy loading is now supported by modern browsers, see https://web.dev/native-lazy-loading/

**Comment by nikhiljohn10** [comment]
> Lazy loading is now supported by modern browsers, see https://web.dev/native-lazy-loading/

@acwolff I have checked it out. It is not yet compatible with the safari browser and android browsers like firefox and webview.

I am looking for a javascript side of the solution currently used.

**Comment by acwolff** [comment]
For Safari on an iPad you have to install the iOS version 13.6 or later and enable it via Settings / Safari / Advanced / Experimental features / Lazy Image Loading.

See also [my Lazy loading tests](http://jalbum.net/forum/thread.jspa?threadID=56433&tstart=0).
