### ISSUE TITLE
Swipe on iPad2 becomes incrementally slower

### ISSUE THREAD

**Issue by MRolefes** [dimsemenov/PhotoSwipe#1047]
Hi Guys,

I've been playing around with a (performance) issue on my website which I'm currently developing and testing on an iPad2 and iPhone 5s.
It seems like while I'm swiping the photo's the animation becomes slower and slower to the point the swipe gesture isn't recognized and the slider ONLY responds to the left and right button (yes I enabled them to exclude any other possibilities than the swipe gesture ;) ).

On my website I'm using Flexslider for the header and WOW.js for some animation inside this header. However, on the photo pages the header contains of 1 image and no animation is done there. I also pause and start the slider once a PhotoSwipe is 'openend'.
For testing I disabled some initializations of menu, wow.js, flexslider (inside the document.ready)... but nothing seemed to address the issue I'm having.

Overall download of a photo page is about 2MB, images or downsized (for testing) to max 800px, making them about 150KB each.

Maybe it's because to many 'stuff' happening on the page, but I'm running a bit blind now...

Test-url; http://test2.spekscheeters.nl/media/fotos/2015/gala-opbouw (iPad2 having a bad day, iPhone 5S doing ok here)
Test-url2; http://test2.spekscheeters.nl/media/fotos/2015/sleuteloverhandiging (iPad2 starts having trouble at about photo 10, iPhone 5S doing ok here)

Thanks

**Comment by MRolefes** [comment]
test2 subdomain can be removed in the URLs :)

**Comment by dimsemenov** [comment]
Can you please make a reduced test case and exclude all js/css/html code not related to the gallery from page (including slider and menu elements)?

Also, please use the latest version of PhotoSwipe (4.1.1)
