### ISSUE TITLE
Using very large images

### ISSUE THREAD

**Issue by aaa930811** [dimsemenov/PhotoSwipe#1049]
There are strong sense of painting when I use the high resolution pictures on  mobile phone and zoom in it.

**Comment by kivancsahici** [comment]
The following has been mentioned within the [**Performance Tips**](http://photoswipe.com/documentation/performance-tips.html)
* Animation performance dramatically depends on the size of an image. The smaller image – the smoother animation. So don't be lazy and serve responsive images, or at least don't serve images larger than 1200x1200 for phones.

Maybe you should consider this.

**Comment by aaa930811** [comment]
Can you recommend a control that supports large resolution picture for me?

**Comment by dimsemenov** [comment]
@aaa930811, if image is very big – just display it directly on page, without using any JS library with animation. You can also use Leaflet http://leafletjs.com/

**Comment by aaa930811** [comment]
It does not match my request.
