### ISSUE TITLE
Non-Image Content

### ISSUE THREAD

**Issue by Inggo-inHomePortal** [dimsemenov/PhotoSwipe#1052]
Is it possible to use non-image, HTML content?

**Comment by Federico39** [comment]
Sorry,do not know, pls ctc Author direct.
Saludos
Federico

2016-01-07 3:04 GMT+01:00 Inggo-inHomePortal <notifications@github.com>:

**Comment by ondrasak** [comment]
Yes, it is

```javascript
var items = [
    // slide 1 with HTML
    {
        html: '<div><h1>Any HTML <a href="http://example.com">content</a></h1></div>'
    },

    // slide 2 with image
    {
        src: 'path/to/image.jpg',
        w:600,
        h:200
    }
];
```
you can find more info in the documentation http://photoswipe.com/documentation/custom-html-in-slides.html
