### ISSUE TITLE
PhotoSwip's url with ajax?

### ISSUE THREAD

**Issue by fghhfg** [dimsemenov/PhotoSwipe#1053]
I have too many thumbnails, so I try to use lazyload (ajax).
I create multiple pages for thumbnails, and ajax thumbnails one by one in my home page.

If someone shares a url (e.g. xxx.com/#&gid=1&pid=9) to another one, it creates bug, which makes sense.

The image is not loaded yet, so it can't find the image. Instead it would show first image.

How do you guys solve this problem?

**Comment by swa66** [comment]
The easy way is to give ALL images to photoswipe from the start. It will not load them (it’ll load 3 when started, ad the rest as the user interacts).

If you also need/want to show thumbnails on the webpage, you can do that independently from the images you give to photoswipe.
