### ISSUE TITLE
Feature Request Play Button

### ISSUE THREAD

**Issue by Z33** [dimsemenov/PhotoSwipe#1055]
This plugin is packed with features but I noticed there was a lack of a play button. Any chance this could be added for future releases?

**Comment by dimsemenov** [comment]
There are no plans to add toggle autoplay button, as it'll be redundant in many use cases. You may implement it by modifying the default UI, or just via public API http://photoswipe.com/documentation/api.html

**Comment by KennethEvans** [comment]
I wanted this feature and could find nothing on the Internet.  So I did it myself.  I have put it on GitHub in case others would like it or perhaps improve it.  It seems to work for me on the browsers and devices I use.

For more details see the README.md at https://github.com/KennethEvans/PhotoSwipe-Play.
