### ISSUE TITLE
Please use plain MIT instead of custom license

### ISSUE THREAD

**Issue by hoxu** [dimsemenov/PhotoSwipe#1056]
> Script is licensed under MIT license with one exception: Do not create a public WordPress plugin based on it, as I will develop it. If you need to use it for a public WordPress plugin right now, please ask me by email first. Thanks!

I totally understand the reasoning behind this, but custom exceptions like this are a wee bit problematic legally. Please consider using plain MIT (with that wish clearly separate from the license), it would make the usage and incorporation of this library easier.

**Comment by dimsemenov** [comment]
The PhotoSwipe is under MIT license https://github.com/dimsemenov/PhotoSwipe/blob/master/LICENSE The additional note is informal – just something that I ask to do, it's not defended legally.

I guess I should write more clear description on demo page, thanks!
