### ISSUE TITLE
Caption element stays hidden when using custom caption text

### ISSUE THREAD

**Issue by alinnert** [dimsemenov/PhotoSwipe#1057]
I actually already found a solution to my problem but I want to know if that's really how it's supposed to work or if this is a bug. (I'm using the current version 4.1.1)

Photoswipe assumes that the gallery looks similar to this:

~~~html
<a><img src="image.jpg" title="The Caption"></a>
~~~

My gallery looks like this though:

~~~html
<li>
    <a><img src="image.jpg" title="The Caption"></a>
</li>
~~~

Now there's the callback function `addCaptionHTMLFn(item, captionElement, isFake)`. In the first case I think `item.title` should be `"The Caption"`.

In my case though `item.title` is `undefined`. I guess because `item.el` refers to the `<a>` element which doesn't have a `title` attribute. Right?

Then I defined the callback as follows (based on the example from the documentation):

~~~javascript
addCaptionHTMLFn: function (item, captionElement) {
    var caption = item.el.children[0].title;

    if (!caption) {
        captionElement.children[0].innerHTML = '';
        return false;
    }

    captionElement.children[0].innerHTML = caption;
    return true;
}
~~~

After this, the caption element contains the correct caption text. But it's still hidden. After a little debugging I found out that `item.title` is still `undefined`, and that's why the element is still hidden.

So I added this line right before the `return true;`:

~~~javascript
item.title = caption;
~~~

Now it works. But is this really what I should do? Or how is `item.title` supposed to be initialized?

**Comment by fabiocaccamo** [comment]
+1 
if addCaptionHTMLFn is defined caption should displayed also if title value is empty/undefined

**Comment by janeks** [comment]
Same problem with custom cuptions. Added: 
`item.title = true;`
It works now. Better documentation on the captions section would be nice. Have no idea how isFake works
