### ISSUE TITLE
Pass in data attributes to images

### ISSUE THREAD

**Issue by tbhockey** [dimsemenov/PhotoSwipe#1060]
Is there any way to pass in data attributes to the actual `img.pswp__img` img objects when building the gallery?

**Comment by tbhockey** [comment]
Or, is there a way to retrieve the DOM element from the `pswp.currItem` property? I believe that would also achieve what I am needing.

**Comment by tbhockey** [comment]
I was able to find a way around needing to do this.

**Comment by noise2** [comment]
@tbhockey would you care enough to share the work around?

**Comment by tbhockey** [comment]
@noise2 unfortunately I am unable to remember what I was trying to solve in the code here, so I can't remember where to look. If I do run into it though I will let you know.
