### ISSUE TITLE
How to make a long image scrollable?

### ISSUE THREAD

**Issue by SashimiEthan** [dimsemenov/PhotoSwipe#1062]
Hi,

Most of images are very long. I wonder if I can make them scrollable when opened? Right now it freezes every time I scroll.

Thanks very much!

-Ethan

**Comment by dimsemenov** [comment]
As mentioned on homepage, it's not recommended to use PhotoSwipe for very tall images like infographics, or screenshots. Open them in a separate page instead, similar to how Dribbble shows large image attachments. You can't smoothly animate very large image in browser without using tiling.

**Comment by SashimiEthan** [comment]
I see! Thank you very much!

**Comment by Federico39** [comment]
thanks a lot, will try later, have other priorities right now.
Kind regards
Federico



2016-01-25 23:13 GMT+01:00 SashimiEthan <notifications@github.com>:
