### ISSUE TITLE
Remove photo from gallery after it is swiped

### ISSUE THREAD

**Issue by nlepisto** [dimsemenov/PhotoSwipe#1063]
I'm having a hard time getting the removal of an item after it has been swiped. 

I've created a codepen here: http://codepen.io/anon/pen/xZjydo?editors=1111

You can think of my use case as a Tinder app I guess. You can swipe left or right on a photo, but once you've swiped, you can't see that photo again. 

I've read that you advise against removing an item that is current, previous or next - but that is precisely what I need to do. 

Any advice?

**Comment by dimsemenov** [comment]
Your code is missing that if you remove array item before the active slide, the active slide will be shifted by -1. You need to replace it with another, not remove.

Generally speaking, it's not very good idea to use PhotoSwipe for such kind of app, just get HammerJS, stack divs, and remove them after user swipes.
