### ISSUE TITLE
Hash building and Aurelia integration 

### ISSUE THREAD

**Issue by hozn** [dimsemenov/PhotoSwipe#1065]
I'm not sure the best way to fix this, but there's a bit of a mismatch in expectations between Aurelia framework's routers and the hash URL used by PhotoSwipe.

Aurelia has its own router/nav system that appends identifiers as part of the fragment.  For example, my photo gallery URL looks like this:

`http://example.com/#/photos`

When PhotoSwipe loads, it begins to modify the hash to track where it is. These URLs look like this:

`http://example.com/#/photos&gid=1&pid=0`

This works just fine within the gallery itself, but if I were to hit the refresh button, Aurelia chokes up claiming that it cannot find a route for `photos&gid=1&pid=0`

Aurelia, it seems, expects that any query parameters actually look like this:

`http://example.com/#/photos?gid=1&pid=0`

So, it would be wonderful to either have an "Aurelia-compat" flag for the creation of the hash, of if (likely) this is too much of a hack, some generic way to override the hash creation function.  Perhaps there already is a way to do this and I simply missed it.

**Comment by dimsemenov** [comment]
I would recommend to entirely disable/exclude history module (`history:false`) if your app uses navigation with #hashbangs, and write your own using public API. Beside issue that you mentioned, there might be also problems with history.pushState that PhotoSwipe uses for "back button to close" feature.

You can also just try adding `?photoswipe=1` to the end of the route of page with the PhotoSwipe, so `gid` is added after it.

**Comment by hozn** [comment]
OK -- thanks for following up!  I'll use your recommended approach.
