### ISSUE TITLE
shareButtons on mobile – open in native app (if available), not in browser

### ISSUE THREAD

**Issue by jamminjames** [dimsemenov/PhotoSwipe#1066]
When sharing via shareButtons, it brings up website login for social share, instead of device's sharing apps -- is there a way to trigger the device's apps instead from within this plugin?

**Comment by dimsemenov** [comment]
On latest Android versions it does indeed open in a native app.

On iOS, it doesn't. There are some [hacks](http://stackoverflow.com/questions/13675535/how-to-launch-apps-facebook-twitter-etc-from-mobile-browser-but-fall-back-to-h) that might allow this, feel free to send a pull request to the default UI.

**Comment by jamminjames** [comment]
I'm testing on an Android 4.4, is that not a recent enough version? Is there a way to make it work on the older Androids, as well as the iOS hack you linked to?

**Comment by jamminjames** [comment]
I have a new phone running Android 5.0, and the share button still does not open the native apps, only a browser, asking the user to sign in. What am I missing?

**Comment by jamminjames** [comment]
*BUMP* This is still an issue for me. What happens when I try to share an image from PhotoSwipe within my Android app is this: Trying to share via Facebook, it opens FB in a  browser, not the FB app, and a button says, "Get Facebook for Android and browse faster." And there is a place to login for FB in the browser. If I hit the Get Facebook button, it goes to the store, and since I already have it, the Open button is there. That takes me to my FB app, but with nothing to share from my PhotoSwipe instance. 

An attempt at a Twitter share also opens a browser and asks me to log in, but it at least has the Tweet to share from the gallery. Same result with the other types of shares. 

If I have something set up wrong, I really want to fix it, but I can't figure it out. Please help.

The app is live now, so you can check it out yourself: https://play.google.com/store/apps/details?id=com.humortimes.newscartoons.

Your program works great for the app, btw. Thank you! 

If you'd like some info on how I have it set up to be able to update the content without updating the app, let me know.

**Comment by jamminjames** [comment]
Any help would be appreciated! Do I need to hook into PhotoSwipe somehow with another sharing plugin?  As dimsemenov said on Feb 10, "On latest Android versions it does indeed open in a native app." But, it doesn't. As explained further in my recent comment above, it opens a browser login for sharing, not the sharing app.

**Comment by jamminjames** [comment]
I solved this issue, by using another plugin to share. For details, check out:
https://github.com/dimsemenov/PhotoSwipe/issues/1443

**Comment by parthkharecha** [comment]
@jamminjames which plugin use??

**Comment by jamminjames** [comment]
See my last post at the link I gave above, https://github.com/dimsemenov/PhotoSwipe/issues/1443.
