### ISSUE TITLE
Margin left and right

### ISSUE THREAD

**Issue by elalemanyo** [dimsemenov/PhotoSwipe#1094]
Hi,
Is a way to add a margin-left and right to the image? Right now on small screens there is no margin there.
What i want is to have the image always under the topbar but also have some space right and left.

Thanks for your help and for this great plugin.

**Comment by wes-r** [comment]
Well I got something working, bit hacky but it works!

And then the main change is to some css:
```
.pswp__scroll-wrap {
    width: calc(100% - 20px);
    margin-left: 10px;
    overflow: visible;
}
```

This will cause a janky animation when first clicking on an image. To fix that, subtract your padding away from the `left` position in your `getThumbBoundsFn`.

**Comment by anghelos** [comment]
I'm replying here 5 years later, for future reference :
There is a padding option that you give when initiating the script. More info here: https://photoswipe.com/options/#padding

**Comment by dimsemenov** [comment]
better late, than never :)
