### ISSUE TITLE
Pin It functionality doesn't work for images whose filenames contain spaces (even url-encoded)

### ISSUE THREAD

**Issue by svet007** [dimsemenov/PhotoSwipe#1108]
The message I'm getting is below:

Oops!
Parameter 'image_url' (value http:/photo/zachary-2015-11-12/Svitlana%20Svetlitsky%20Photo-1003.jpg) is not a valid URL format.

**Comment by dimsemenov** [comment]
Make sure that you pass absolute URL, not relative, PhotoSwipe default UI has `getImageURLForShare`  option http://photoswipe.com/documentation/options.html

**Comment by svet007** [comment]
Thanks, this helped!
