### ISSUE TITLE
Gallery not functioning correctly on iPhone Plus devices (iOS 9) in Safari while tab bar is visible

### ISSUE THREAD

**Issue by jbye** [dimsemenov/PhotoSwipe#1114]
Hi

This concerns photoswipe 4.1.1

The gallery is not functioning correctly in Safari on iOS 9 while the address bar w/ open tabs is showing.
The transparent backdrop is not visible and the image scale is incorrect. Scrolling down so that the address bar becomes hidden and opening the gallery again "fixes" the issue.

This issue is reproducible on www.photoswipe.com and my own site.

Check the attached screenshot

![img_1490](https://cloud.githubusercontent.com/assets/263004/14284204/c3b39f38-fb46-11e5-9c2c-83ef353ff24b.PNG)

**Comment by dimsemenov** [comment]
- In what exactly version of iOS do you get the issue? 9.3.1?
- Can you repeat the issue every time, or it happens occasionally?

**Comment by jbye** [comment]
I have reproduced it on 9.2.1, going to test 9.3.1 now, and a couple of others via Browserstack. Will report back asap.

**Comment by jbye** [comment]
Alright, I have retested on several other devices now.

- iPhone 6S Plus (NOT OK)
- iPhone 6 Plus (NOT OK)
- iPhone 6S (OK)
- iPad Air (OK)

So it seems that this issue is only occuring on the Plus devices. It seems to me that the issue is somehow related to Safari showing the tab bar for the Plus devices (the regular iPhone devices do not show the tab bar).

**Comment by dimsemenov** [comment]
Oh, these iOS bugs...

It seems `.pswp__bg { transform: translateZ(0); }` fixes it, can you check on your website?

**Comment by jbye** [comment]
Great, that actually seem to have fixed the issue!

Thanks for getting back to me so quickly, and for creating and maintaining this awesome library :)
