### ISSUE TITLE
How to change behavior of Share Facebook Link"

### ISSUE THREAD

**Issue by phuongtailtranminh** [dimsemenov/PhotoSwipe#1118]
Hi

I want to handle when user click on "Share on Facebook" with my behavior, not open a window by default behavior with a link.

I tried to get the reference of link with this jquery but nothing happened:

```
$(".pswp__share--facebook").click(function() {
// todo
});
```

My gallery is dynamically created

**Comment by phuongtailtranminh** [comment]
Finally this is the solution:

I hacked into `photoswipe-ui-default.min.js` file, looking for: `name: 'button--share',`. It will look like this:

var _uiElements = [
...
{
			name: 'button--share',
			option: 'shareEl',
			onInit: function(el) {
				_shareButton = el;
			},
			onTap: function() {
        **pswp.shout('shareButtonClick');**
				_toggleShareModal();
			}
		},
...
]

And in your code, listen to event: 

```
your_gallery_instance.listen('shareButtonClick', function(e, target) {
          console.log("Clicked");
        });
```

**Comment by jhabdas** [comment]
@phuongtailtranminh please close this and reopen on StackOverflow if it's still a question you have
