### ISSUE TITLE
How to implement Photoswipe with Owl Carousel 2.0

### ISSUE THREAD

**Issue by ChristianGerdes** [dimsemenov/PhotoSwipe#1125]
I'm trying to implement Photoswipe with Owl Carousel, but I can't get it to work.

Here's my situation:
I use owl carousel to generate a slider, but at the same time I want to use Photoswipe, but I can't. When I use the Owl carousel plugin, the slider's inserted into the code with a speciel markup, where each item (image) has a class of .item and the image is located 3 layers deep into that div.

How can i tell photoswipe to target the images in their individual .item class.

Thanks!

**Comment by spolischook** [comment]
@ChristianGerdes how you solved this?
