### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: ���� JFIF      �� C ...

### ISSUE THREAD

**Issue by hartey11** [dimsemenov/PhotoSwipe#1144]
Hi,

I'm trying to integrate PhotoSwipe for a gallery page. However, when I click on an image after a few seconds I get a error message with lots of unrecognised characters which is making it hard to debug...

The photoswipe code has been minified and concatenated into lib.js and is initialised in main.js.

The page is: [http://jazz-cafe.kotadev.co.uk]

> Uncaught Error: Syntax error, unrecognized expression: ����JFIF��C   !"$"$��C������    �����o_��[T�QH   PA�q0���!����e�!&Q;b���g1s�-y9��e�p%b��Y��k�x�6!�,ֶS+�D
> �@�Ɩ&�@�H�Q%P�D($�$� ���b[8�vc3�[
> F�LYf5L�K���jN�I��ѹb��~E�h}��c��I�m��:��WJ�L0�����P�QfA�Ɩ@�[���x���((EA@
> �,�C�Y�3��--9�j[mC�5��ӌD�b�Ν�ۘu�Fzm���Sm��T4�a�'   (��aK��I[�RV� J�A@A@" �@�DA
> �+b�Ε�Da,&ۢ�=C�����_���r����n���!�i��"Vc9�֪D���� �NS������i�N4���D� @AR�PH�X�D@P$Cb5,#i�cr-��6'D�����!������t�I������Ѻ��xoV����e0��_m���`(��d�(��R�+u�(�� �PPPPK
> �&q�l�
> �2�Y"�&��m��
> �7�=f��֕>���
> f����������޶֜��$�    Y&6Z�f� PƖo[��D@
> ���(��
> ��'��a��1=��Y�+L���v��/�6>m,��F��m^���;��:�����c�Ѫ,� ����C�P2�@H�c[DȐT"U
> "D(��V   0�

**Comment by FranzSkuffka** [comment]
Seems like you are getting some binary data here. Trying it with different pictures might do the trick. Alternative, use the dev version of the library.

**Comment by pixelmachine** [comment]
@hartey11 did you manage to solve this? I'm having exactly the same issue.
