### ISSUE TITLE
Working with Photoswipe in meteor init() function not working properly

### ISSUE THREAD

**Issue by sylverfyst** [dimsemenov/PhotoSwipe#1151]
I keep getting an error that states "spectrum_photoswipe.js:63 Uncaught TypeError: Cannot read property 'className' of undefined"  It's refrencing this block of code: 
    
     removeClass: function(el, className) { var reg = new RegExp('(\\s|^)' + className + '(\\s|$)');
      el.className = el.className.replace(reg, ' ').replace(/^\s\s*/, '').replace(/\s\s*$/, '');  }

My code is passing items and options correctly like so:

```
    var listingId = template.data.listingId,
    imgs = ListingCollection.findOne({_id: listingId}).images;
    var items = [];
    for(var i =0; i < imgs.length; i++) {
        var tempImg = new Image();
        tempImg.src = imgs[i];
        var itemObject = {"src": "", "w": "", "h": ""};
            itemObject.src = imgs[i];
            itemObject.w = tempImg.width;
            itemObject.h = tempImg.height;
        items[i] = itemObject;
    }
    var options = {
        index: 0,
        history: false,
        focus: false,
        showAnimationDuration: 0,
        hideAnimationDuration: 0
    };

    var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
    gallery.init();
```

And I've checked to make sure that the pswp element is in the DOM.  I'm not really sure what's going on here.  Any help would be greatly appreciated

**Comment by chesio** [comment]
Hi,

It would help if you could provide stack trace for this error message. The `removeClass` method is invoked on several different elements in several different context - in one of them, the element is not properly initialized (as it is undefined), but it's hard to tell what's wrong only from the sample you posted.

Greets,
Česlav

**Comment by sylverfyst** [comment]
Hi,

Thanks for taking a look, the call stack before the breakpoint looks like:

![screen shot 2016-05-27 at 8 50 37 am](https://cloud.githubusercontent.com/assets/616011/15608485/2168fd0c-23e8-11e6-86a5-10ce4a151807.png)

**Comment by chesio** [comment]
The error is triggered when class of preloader element is changed. Do you use default PhotoSwipe UI? If so, does your PS template have an element with class `pswp__preloader`?

**Comment by sylverfyst** [comment]
Thank you! That was the issue, one of the commented out sections in the pswp uses -- in the comment:

''

 and that commented out the pswp__preloader class.  You might want to consider changing that comment in the documentation.  Thanks for the help!

**Comment by chesio** [comment]
Well, I'm not the plugin author :) Btw. in #1128 someone already mentioned issues with `--` in comment. Glad you got it working!
