### ISSUE TITLE
Remove hash change ?

### ISSUE THREAD

**Issue by EduardJS** [dimsemenov/PhotoSwipe#1172]
Hello! I'm not interested in having the hash at all.. is it possible for me to actually disable / remove it ?

**Comment by chesio** [comment]
Hello, have a look at [PhotoSwipe options](http://photoswipe.com/documentation/options.html) and search for `history` option, should be what you're aiming for.

**Comment by EduardJS** [comment]
Hey! I did not see that, sorry. Though, I just manually stripped out the history module from the javascript file.
