### ISSUE TITLE
How to assign your own action for tap image.

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1183]
I did extend the jAlbum [PhotoSwipe skin](http://jalbum.net/en/skins/skin/PhotoSwipe) with a Slide Show function, see [this example](http://andrewolff.jalbum.net/Reestdal_PS/#&gid=1&pid=4) The Slide Show starts if you click the Play button in the upper right corner and you stop the Slide Show by clicking the pause button in the upper right corner. This works fine on a PC.

It works also on my iPad, but clicking the Pause button has a side effect: the image is zoomed-in. I have no idea thus this causes. Any idea how to prevent this?

The Start/Stop function is executed in a function playpause(). To get rid of this side effect I like to use the single tap event on the image to execute my playpause() function.

In the [PhotoSwipe documentation](http://photoswipe.com/) it is said under 'Touch gestures'' :

**You can assign your own actions for tap and double-tap gestures.**

But I can't find any documentation how to do this!

So please show me the code how to bind my playpause() function to the click / tap event on the image.

**Comment by dimsemenov** [comment]
If you bound simple click event, make sure that you call preventDefault and stopPropagation on it, to prevent ghost click from happening.

PhotoSwipe default UI uses `click` and `pswpTap` events, you may check how they work in source https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/ui/photoswipe-ui-default.js#L603

**Comment by acwolff** [comment]
I used onGlobalTap instead of _onControlsTap:

	ui.onGlobalTap = function(e) {
		e = e || window.event;
		var target = e.target || e.srcElement;	
		if  ((framework.hasClass(target, 'pswp__img')) && !PC) {
				if(!_controlsVisible) {
					 ui.showControls();
					 setTimeout(function() {
						ui.hideControls();
					 }, 2000);
				}
			    playpause();
			    return;	
		}

To see the result open the [PhotoSwipe sampe album](http://andrewolff.jalbum.net/Reestdal_PS/).
