### ISSUE TITLE
Update the current item picture

### ISSUE THREAD

**Issue by JoffreyT** [dimsemenov/PhotoSwipe#1193]
Is there a way to update the current picture displayed.

The use case here is that I added a button in the gallery to rotate the picture. So the picture is rotated on the server side but then I would like to update the picture in the client side.

Thanks a lot for any help on this !

**Comment by dimsemenov** [comment]
```js
pswp.currItem.src = 'image.jpg';
pswp.currItem.w = 123;
pswp.currItem.h = 456;
pswp.currItem.needsUpdate = true;
pswp.updateSize(true);
```

**Comment by JoffreyT** [comment]
Thanks for your prompt reply.
Indeed this is working but I have an issue with the server connection because the picture is well rotated in the server but when I do the update in the gallery, the picture does not change.
If I try to display another picture I can see the update is working.

**Comment by JoffreyT** [comment]
The only way I found is to manually delete the src attr before refreshing: 
$(".pswp__img[src='"+ source +"']").attr("src", "");

**Comment by JoffreyT** [comment]
That's ok, finally, I choose another way which is to add "?"+random_number at the end of the image url so that it is changing the url and the browser is "forced" to get the picture from the server.

**Comment by caseyjhol** [comment]
@dimsemenov This was really helpful - any way we can get `needsUpdate` added to the documentation?

**Comment by vinicioaraujo** [comment]
> ```js
> pswp.currItem.src = 'image.jpg';
> pswp.currItem.w = 123;
> pswp.currItem.h = 456;
> pswp.currItem.needsUpdate = true;
> pswp.updateSize(true);
> ```

Congratulations on working with photoswipe, it's amazing! But I'm in the same situation as colleague Jofrey T, please, how do I do the same thing with version 4 of Photoswipe that is triggered by masonryGallery (https://masonry.desandro.com/)? I am using from Stack Admin Template.
