### ISSUE TITLE
Preload first image

### ISSUE THREAD

**Issue by joDelicious** [dimsemenov/PhotoSwipe#1210]
Hi Dim !

I have seen documentation about preloading previous/next images but not about preloading the first one.
I have tried a few stuff with no success,  like creating a fake `<img>` to preload the full url.

I always get a one second delay on the first image.
During that one-second-delay it shows me the `pswp__img--placeholder--blank` background.
Of course if i get out of photoswipe and get back in, i have no more delay.

Any ideas ?

Thank you !

Johan

**Comment by dmaus** [comment]
Hey Johan. I had the same problem, while building the gallery with a custom image array. When I added "msrc" to it, there was no more delay!


```
  msrc: 'path/to/small-image.jpg', // small image placeholder,
                        // main (large) image loads on top of it,
                        // if you skip this parameter - grey rectangle will be displayed,
                        // try to define this property only when small image was loaded before
```

**Comment by joDelicious** [comment]
Well found, thank you !

It should be added in the docs...

**Comment by joDelicious** [comment]
Well found, thank you !

It should be added in the docs...
