### ISSUE TITLE
I want use only the zoom icon in the top bar, is possible ?

### ISSUE THREAD

**Issue by SaulBurgos** [dimsemenov/PhotoSwipe#1211]
Hi great plugin

I want to disable the zoom in the images and containers, and only allow users to make zoom using the top bar icon. is this possible ?

**Comment by tomdav999** [comment]
Anything is possible but just wondering why you would want to take core user functionality away?  If you are going to let them zoom via the zoom button why not let them zoom via more user friendly methods (mouse click or double tap).  I would venture to guess the vast majority of photoswipe users do not actually click on the small zoom button when they want to zoom in.  It is easier to double tap on mobile or click or desktop.  Similarly for the other controls.  It is easier to hit the back button or Esc vs. clicking on the X.  It is easier to swipe left or right on mobile or use the keyboard arrow buttons on desktop vs. clicking on the arrows.

**Comment by SaulBurgos** [comment]
Sorry to bother you, you are right is not correct remove that cool functionality.   I have already fix it playing with the z-index with CSS and everything is working like I want.

To answer your question:  I have a little service that allow you create 360 tours:
http://www.paneek.net/

I am using your plugin to show gallery of images and videos in this moment. But I am creating I new feature that will allow users use plan floor in their tours , So I want use your plugin like a viewer for the plan floors. 

These plan floors will have hotspots inside of the image that will allow users click on them and load a 360 view for that area. I have made a tiny modification to your plugin to accept this.

http://imgur.com/wmk7ZHu
http://imgur.com/wCxCPoF
http://imgur.com/vwgLBkN

I am still in the developing process but it will be cool. Anyway thanks for you rapid advice

**Comment by tomdav999** [comment]
Good to hear you figured it out.  Just so there is no confusion, I am not the developer.  I am just another user of the plugin.

**Comment by jhabdas** [comment]
@SaulBurgos can this be closed?
