### ISSUE TITLE
Page being refreshed if I click on any button

### ISSUE THREAD

**Issue by chilluk7** [dimsemenov/PhotoSwipe#1214]
If I click on any button, be it the buttons to scroll between images, the full screen button, or the close button itself the viewer closes and the page behind is refreshed.

If clicking on one of the scroll buttons the new image is loaded briefly before the page is refreshed and the viewer is closed.

I have tried fiddling with options to no avail.

This is using .Net webforms.

Thanks.

**Comment by chilluk7** [comment]
Hmm it seems that the buttons were submitting the asp.net form every time - I just changes the buttons to <a> tags and it seems to have solved the issue.

**Comment by dimsemenov** [comment]
You may also just add `type="button"` attribute to `<button>` elements.

**Comment by SulaimanZahir94** [comment]
> 
> 
> You may also just add `type="button"` attribute to `<button>` elements.

Thanks Its Work fine Now
