### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by exileAU** [dimsemenov/PhotoSwipe#1223]
Following your documentation I have come into this error while working at step 3. Any help would be appreciated.

Pastebin: http://pastebin.com/Yu6RV6pD

**Comment by dimsemenov** [comment]
Your code is correct, make sure that you add JS after .pswp element or in document.ready.

Closed, duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/833

**Comment by exileAU** [comment]
Hey Mate, thanks for the reply. I also just ran into another error. 
Uncaught ReferenceError: PhotoSwipe is not defined
Any help is appreciated.
