### ISSUE TITLE
mobile vs computer browser

### ISSUE THREAD

**Issue by zhiwan** [dimsemenov/PhotoSwipe#1227]
Hello,

First of all, thank you so much for this plugin. It is one of the best lightboxes I have ever used. 

One thing I notice is how the lightbox has a different setting for mobile. The image tends to fill up the screen all the way from the left to right right edges. This is an issue because I have captions and they overlap with the image. You can see a screen capture here:

http://grayswartzel.com/test-phone.png

But on the browser, the lightbox image shrinks and keeps a left, right, and bottom margin from the edges of the screen, even when I shrink the browser to have a width of 200px or less. As a result, it also never overlaps with the captions. You can see a screen capture of what it looks like on chrome with a small window:

http://grayswartzel.com/test-browser.png

I would like to turn off the mobile setting. Is there a way to do that? Thanks.

**Comment by mjau-mjau** [comment]
Why are you not using semi-transparent backgrounds behind the captions, as is default? Furthermore, the caption is "toggled" visible on screen-tap, to view the full image.

The margins don't exist on mobile, because if they did, it would make the image extremely small, as it would need to resize proportionally within the available area after your caption/topbar. For the visitor, this is not useful, as their main focus is to view the image. Caption/topbar can be toggled on click/tap, and should have a background-color (preferably semi-transparent).

**Comment by zhiwan** [comment]
@mjau-mjau I am aware I can change the backgrounds and the "toggled" screen as well as the conceptual basis for why the margins don't exist on mobile, but I still want to go ahead with what I originally stated. I purposely linked those two images as to show I did export what it would look like on an iphone 5 screen (smaller than an iphone 6), and the final display seemed acceptable while maintaining the caption. Can you or someone help with that? 

I have thought a lot about the small image issue, but I personally don't think there really is an ideal way to show nice images on the phone with text, as a "toggle" isn't intuitive. I read nytimes on my phone all the time and they use the toggle for their images. It is a pain to have to tap/toggle after scrolling to each new image for new text and then without text. Alternatively I have seen websites hide the caption option completely in mobile and just have the image. I have made a conscious decision to try to have both caption and image all on the screen. I don't think there really is a "right" way to do it. 

I just want to know if it can be done at this point.

**Comment by mjau-mjau** [comment]
There is a setting, that only applies for screens larger than 1200px:
```javascript
// Size of top & bottom bars in pixels,
// "bottom" parameter can be 'auto' (will calculate height of caption)
// option applies only when mouse is used, 
// or width of screen is more than 1200px
// 
// (Also refer to `parseVerticalMargin` event)
barsSize: {top:44, bottom:'auto'}
```
If you want to apply it for mobile, you would need to duplicate **photoswipe-ui-default.js**:
http://photoswipe.com/dist/photoswipe-ui-default.js

... and customize it from:
```javascript
_fitControlsInViewport = function() {
  return !pswp.likelyTouchDevice || _options.mouseUsed || screen.width > 1200;
}
```
to:
```javascript
_fitControlsInViewport = function() {
  return !true;
}
```

... and then of course load your custom UI js file, instead of photoswipe-ui-default.js.

**Comment by mjau-mjau** [comment]
Perhaps better, would be to use the **parseVerticalMargin** event in Photoswipe API:
```javascript
// Allows overriding vertical margin for individual items
pswp.listen('parseVerticalMargin', function(item) { 
    // For example:
    var gap = item.vGap;

    gap.top = 50; // There will be 50px gap from top of viewport
    gap.bottom = 100; // and 100px gap from the bottom
})
```

You would need to set **gap.bottom** to the current height of your caption. I don't have exact code for you to use here, without spending some time testing.

**Comment by zhiwan** [comment]
@mjau-mjau Thanks for the suggestions. I tried creating a custon **photoswipe-ui-default.js** with the change in the code:

```
_fitControlsInViewport = function() {
  return true;
}
```

But it doesn't seem to change anything in my tests and the image still expands out to the edges of the screen. Do you have any ideas?

I am hesitant to use the **parseVerticalMargin** event only because I don't know the height of the caption as that may change based on the image. I am counting on the image to shrink proportionally should the caption be a line or two longer than what I normally write, which again, I'm fine with a slightly smaller image.

**Comment by mjau-mjau** [comment]
> But it doesn't seem to change anything in my tests and the image still expands out to the edges of the screen. Do you have any ideas?

Sorry, not really no. Did you clear cache if using the same file name? Do you have bars.bottom = 'auto'? The following function is what sets the automatic gap at bottom based on caption height, as long as  **_fitControlsInViewport()** returns true, and the other conditions are met:
```javascript
_applyNavBarGaps = function(item) {
	var gap = item.vGap;

	if( _fitControlsInViewport() ) {
		
		var bars = _options.barsSize; 
		if(_options.captionEl && bars.bottom === 'auto') {
			if(!_fakeCaptionContainer) {
				_fakeCaptionContainer = framework.createEl('pswp__caption pswp__caption--fake');
				_fakeCaptionContainer.appendChild( framework.createEl('pswp__caption__center') );
				_controls.insertBefore(_fakeCaptionContainer, _captionContainer);
				framework.addClass(_controls, 'pswp__ui--fit');
			}
			if( _options.addCaptionHTMLFn(item, _fakeCaptionContainer, true) ) {

				var captionSize = _fakeCaptionContainer.clientHeight;
				gap.bottom = parseInt(captionSize,10) || 44;
			} else {
				gap.bottom = bars.top; // if no caption, set size of bottom gap to size of top
			}
		} else {
			gap.bottom = bars.bottom === 'auto' ? 0 : bars.bottom;
		}
		
		// height of top bar is static, no need to calculate it
		gap.top = bars.top;
	} else {
		gap.top = gap.bottom = 0;
	}
}
```

> I am hesitant to use the parseVerticalMargin event only because I don't know the height of the caption as that may change based on the image. I am counting on the image to shrink proportionally should the caption be a line or two longer than what I normally write, which again, I'm fine with a slightly smaller image.

You would need to calculate height dynamically, something like:
```javascript
gap.bottom = $(your_caption_element).height();
```
Problem is, I am not 100% sure the caption is already rendered once parseVerticalMargin triggers, in which case you would need to create some fake containers to measure the height. Sorry, I just haven't toyed around with this ...

I'm not really up for an online debate, but personally I think you should forget about it. I have the entirely opposite opinion as you, and have even removed caption-margins on desktop ALSO ([see example](https://demo.flamepix.com/examples/features/exif/)). Images are already small on mobile devices, so why make them TINY by limiting their render area? I would hate to view images that small and always have captions in my face ...

> It is a pain to have to tap/toggle after scrolling to each new image for new text and then without text. 

Did you try photoswipe on mobile? The visible state of caption is **persistent** when swiping between images. 1. Images originally start with captions visible. 2. While swiping images, captions are still visible. 3. Images are nice and big, and I can see them at full size. 4. If the caption annoys me, I can "tap" the screen, and view the image (at full size) without captions.

In your case, user is stuck to small images (2x smaller at least), and always forced to see the caption. In my professional opinion, that is just wrong.

**Comment by zhiwan** [comment]
@mjau-mjau Thanks for all the info. I got it working. It was a cache issue. 

I understand where you are coming from with small images. Something I will consider in the near future ;)
