### ISSUE TITLE
Can't close photoSwipe

### ISSUE THREAD

**Issue by Tusko** [dimsemenov/PhotoSwipe#1231]
hey guys!
Thank you for a great plugin.

I have a small problem, I can't close a PhotoSwipe.

After click on overlay the `.pswp` block has classes `pswp pswp--supports-fs pswp--open pswp--animate_opacity pswp--notouch pswp--css_animation pswp--svg pswp--visible pswp--zoom-allowed`

How I can fix it?

The example here [https://arsmoon.com/ua/works/enjoying-life-travel-around-the-world/](Arsmoon)

**Comment by Tusko** [comment]
+1

**Comment by mjau-mjau** [comment]
I checked the link, and photoswipe seems to operate as usual, including *close* functionality. I am not quite sure what you mean "After click on overlay" ...

**Comment by Tusko** [comment]
I don't know how, but now it works fine.
Sorry :)

**Comment by Tusko** [comment]
hey @mjau-mjau 
There is the same problem http://trachuk.dev0.site/projects/showman/

**Comment by mjau-mjau** [comment]
That web page is not operating Photoswipe properly. After closing Photoswipe, the photoswipe element remains in DOM with class `.pswp--open`. http://d.pr/i/kIt2

**Comment by Tusko** [comment]
How I can fix it?
The same code is at https://arsmoon.com/ua/works/enjoying-life-travel-around-the-world/
but there works perfectly

**Comment by mjau-mjau** [comment]
I don't even know where your code is, and I can't hunt down the issue for you. Create an isolated example on codepen, and I can look at it.

**Comment by Tusko** [comment]
my initialization code was in `$(window).on('pageshow load', function(){ /* ... */ });`, I just moved it inside `$(document).ready(function () { /* ... */ });`

Thank you for answers, now all are working fine!
