### ISSUE TITLE
Photoswipe 4.1.1 mobile compatible

### ISSUE THREAD

**Issue by ricksen21** [dimsemenov/PhotoSwipe#1242]
Photoswipe 4.1.1 doesn't work for mobile devices. I can't open a picture. On the browser from the computer, everything works fine. I thing it is not compatible for mobile browsers. How can I make it compatible? I have tried some things but for now, nothing helps. Anyone now what I can do to solve this problem?

**Comment by uncovery** [comment]
Works fine here. Maybe you should write what browser / OS you are using?

**Comment by ricksen21** [comment]
Photoswipe 4.1.1 doesn't work on the mobile devices. I has test it with
some different android devices and different versions of chrome. When it
doesn't work on the mobile device, where should i watch or does the code
need some extra framework for mobile compatebilty?

Kind regards,

Rick
Op 24 nov. 2016 06:35 schreef "Uncovery" <notifications@github.com>:

**Comment by ricksen21** [comment]
It also can be that I forget something. Because I didn't use all the files in the package.
Which files are responsible for mobile browsing? Gruntfile.js?

**Comment by widoz** [comment]
Gruntfile.js is for tasks.

What you need to make the plugin work properly is described here http://photoswipe.com/documentation/getting-started.html

- photoswipe.css
- default-skin/default-skin.css
- photoswipe.js
- photoswipe-ui-default.js

I tested the plugin on iPad running iOS 10.1.1 and work well, also with chrome 52.0.x on Android version 5.0.x.

**Comment by ricksen21** [comment]
Oke I use all the four files and test it with  android 4.4.x with chorme
49.0 and also test it with android 5.0.x and chrome 53.0.
and it doens't work.


2016-11-26 23:40 GMT+01:00 Guido <notifications@github.com>:

**Comment by ricksen21** [comment]
I suppose you has used the plugin from github? What kind of version have
you tested?

2016-11-27 16:14 GMT+01:00 Rick Kwast <rickkwast88@gmail.com>:

**Comment by ricksen21** [comment]
It still doesn't work. Anyone also problems with mobile compatibility?

**Comment by widoz** [comment]
@ricksen21 Yes, downloaded via bower from github, version v4.1.1.

Have you errors on console or may be some other plugin cause a conflict?
There is a link where we can see the issue?

**Comment by ricksen21** [comment]
oke, I found the follow error in mine console:

Uncaught TypeError: Cannot read property 'src' of undefined(…)

 else {
				        item.src = item.m.src;         (At this line by .src is something going wrong)
				        item.w = item.m.w;
				        item.h = item.m.h;
				    }

**Comment by widoz** [comment]
@ricksen21 Not found any string with *item.src = item.m.src;* pattern.

The console should show you the file and the line where the error appear. Are you sure it is a photoswipe issue or you are not running an holder version of it?

**Comment by ricksen21** [comment]
https://github.com/dimsemenov/PhotoSwipe/blob/master/website/index.html

line 842 - 846 

that part of the script gives for me trouble
