### ISSUE TITLE
Q: How to create photoswipe on ul/li/figure/img markup?

### ISSUE THREAD

**Issue by Siton-Systems** [dimsemenov/PhotoSwipe#1244]
Never mind - i succeed. Thanks

**Comment by Glumanda99** [comment]
@Ezra-Siton-UIX how did you succeed? This won't help anyone.

**Comment by Ezra-Siton-UIX** [comment]
See my example her: 
https://codepen.io/ezra_siton/pen/XNpJaX

See her: `el.tagName.toUpperCase() === "LI";`

**Comment by Glumanda99** [comment]
@Ezra-Siton-UIX Thanks a lot! Such a great combination! :+1:

**Comment by Glumanda99** [comment]
@Ezra-Siton-UIX Oh, I just noticed you got rid of the figure element :cry:

**Comment by Ezra-Siton-UIX** [comment]
Sorry. I dont find how to solve this with `ul/li/figure/img` only `ul/li/img` (Zero docs about this issue)
