### ISSUE TITLE
Image does not display with angularJS framework.

### ISSUE THREAD

**Issue by zhangzhenyi** [dimsemenov/PhotoSwipe#1247]
I use it only pure JS code, and the below error occurred,  one image was set.
_TypeError: Cannot read property 'x' of undefined
    at La (photoswipe.min.js:4)
    at bc (photoswipe.min.js:4)
    at a.setContent (photoswipe.min.js:4)
    at a.init (photoswipe.min.js:4)
    at initialData (PhotoSwipe-angular.js:14)_

the following is initial code (Items value had been checked and correct)
_items.push({
		src: e.fileUrl, // path to image
		w: 100, // image width
		h: 100, // image height
		msrc: e.thumbnailUrl, // small image placeholder,
		title: e.showName,
		author: e.createUserName
});
_var options = {
				// optionName: 'option value'
				// for example:
				index: 0 // start at first slide
			},
var pswpElement = document.querySelectorAll('.pswp')[0];
		var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options);
		gallery.init();__

I don't know what happened as the error message is not clear. 
Thanks a lot for any suggestion.

**Comment by SaulBurgos** [comment]
I am using it in this project with angularjs to show a floor plan .
http://www.paneek.net/#/tour/view/40

I can tell you some advices:

- Wait until the DOM is ready or the element created
- Do not run the plugin until all images were previously loaded
- Check in all moment the events of the plugins, can give you a sign of the problem

**Comment by zhangzhenyi** [comment]
Thanks very much, and I want to confirm about that "Do not run the plugin until all images were previously loaded", it is said that the  API "gallery.init();" cannot be called before all images loaded? 

If yes, then how to load them before init()?  

I add all event listenings and the running result is :

_updateScrollOffset
PhotoSwipe-angular.js:34 resize
PhotoSwipe-angular.js:70 parseVerticalMargin
PhotoSwipe-angular.js:56 initialZoomIn
angular.min.js:103 TypeError: Cannot read property 'x' of undefined
    at La (photoswipe.min.js:4)
    at bc (photoswipe.min.js:4)
    at a.setContent (photoswipe.min.js:4)
    at a.init (photoswipe.min.js:4)
    at PhotoSwipe-angular.js:15
    at angular.min.js:138
    at e (angular.min.js:40)
    at angular.min.js:44(anonymous function) @ angular.min.js:103(anonymous function) @ angular.min.js:76(anonymous function) @ angular.min.js:139e @ angular.min.js:40(anonymous function) @ angular.min.js:44
PhotoSwipe-angular.js:30 imageLoadComplete_

The div with  ".pswp" had been added several seconds before (content get from step 2: add PhotoSwipe (.pswp) element to DOM).
[http://photoswipe.com/documentation/getting-started.html](http://photoswipe.com/documentation/getting-started.html)

**Comment by SaulBurgos** [comment]
Yes do not call any method of the plugin until you have :  dom elements ready, images loaded, and  images dimensions 

The images dimensions is very important because the plugin need them to do some calculations.
 I use this to preload the images before call the plugin 

https://www.bennadel.com/blog/2597-preloading-images-in-angularjs-with-promises.htm

You need modify a little bit the code to know the images dimensions once they are loaded. exactly in the line 330  instead of returning only the src. you can return the height and width

**Comment by zhangzhenyi** [comment]
Thank you very much.
I got the cause, I put display: none in the parent DIV (I forgot that). 
And the way of getting image size is useful to me.  Thank you again.
