### ISSUE TITLE
Grey placeholder

### ISSUE THREAD

**Issue by studiobtbob** [dimsemenov/PhotoSwipe#1266]
Hello. While the images are loading there is a grey placeholder (I think it's the name) on the page and, with Chrome, I don't have the scroll bar (I have it on Explorer). When all the images are loaded the grey placeholder disappear and you can use the gallery.  It's not like this on the example of photoswipe.com

My page : www.studiobtbob.com/wordpress/portfolio-items/photos-de-mariage/

It not really good for the use of the gallery. Maybe it's normal because on photoswipe website they say : "Smart loading indicator. Just a stretched thumbnail or gray placeholder is used, with the full image progressively loaded over top."

Is it possible to change it, maybe to have just the images loaded one after another?

I use the wordpress plugin with a wordpress gallery.

Thank you.

**Comment by jhabdas** [comment]
> I use the wordpress plugin with a wordpress gallery.

The author states on the home page of the PhotoSwipe website this software is not licensed for a WordPress plug-in. As such, whatever your using is unofficial and may be subject to later removal from the plug-in gallery.
