### ISSUE TITLE
disable history

### ISSUE THREAD

**Issue by Mexikaner9** [dimsemenov/PhotoSwipe#1267]
what is the simpliest way to disable history?

**Comment by chesio** [comment]
Have you tried `options.history = false;` ?

**Comment by xor-gate** [comment]
Its documented here: http://photoswipe.com/documentation/options.html

**Comment by Mexikaner9** [comment]
this  doesnt work

<Code>
<script src='js/photoswipe.min.js'></script>
<script src='js/photoswipe-ui-default.min.js'></script>
<script src="js/index.js"></script>
<script>
var options = {
    history: false
};
gallery.init();
</script>
</Code>
sorry, I'm not an Expert

**Comment by xor-gate** [comment]
You need to set config on the instance of a gallery:

```js
var gallery = new PhotoSwipe( someElement, PhotoSwipeUI_Default, someItems, options);
gallery.init();

// Note that options object is cloned during the initialization.
// But you can access it via `gallery.options`.
// For example, to dynamically change `escKey`:
gallery.options.escKey = false;

// etcetera......
```

**Comment by Mexikaner9** [comment]
ok, thank you!

**Comment by Mexikaner9** [comment]
can you help me please?
my example doesnt work
http://dauten.server29.vorschauseite.eu/PhotoSwipe/

**Comment by Mexikaner9** [comment]
please help me.
I'm just a beginner in js

**Comment by xor-gate** [comment]
I'm sorry but screaming for help on github is just like drowing in the midatlantic ocean without boats passing by. Probably you should first learn some javascript before integrating existing applications. W3schools has some nice tutorials including javascript: http://www.w3schools.com/js/

**Comment by Mexikaner9** [comment]
Learning Javascript has no priority for me. There are better things in life. I would like to use PhotoSwipe, but I can also use http://cornel.bopp-art.com/lightcase/

**Comment by jhabdas** [comment]
@dimsemenov this is not an issue and can be closed
