### ISSUE TITLE
Support for other media

### ISSUE THREAD

**Issue by Boscop** [dimsemenov/PhotoSwipe#1273]
Does this support other media than images on each slide?
Such as videos or webgl canvases?
What kind of data is accepted for the src field?

(I want to build an app with a swipable gallery of webgl canvases.)

**Comment by vincentorback** [comment]
You can read more about what you’re looking for here: http://photoswipe.com/documentation/custom-html-in-slides.html

**Comment by jhabdas** [comment]
@dimsemenov this can be closed
