### ISSUE TITLE
Different aspect ratio thumbnail and original image cause visual artifacts.

### ISSUE THREAD

**Issue by silentzawr** [dimsemenov/PhotoSwipe#1282]
If the thumbnail has a different aspect ratio than the large image, the animation looks very broken. You can test this on the website's default PhotoSwipe but simply changing one of the thumbnails to an image with different aspect ratio than the large image.  

A realistic scenario is to have a list of thumbnails with the same size (e.g. 200x200) displayed in a row, but each full width image has different ratio (e.g. one is 1920x1080, the other is 400x900).

**Comment by michael-e** [comment]
RTFM: http://photoswipe.com/documentation/faq.html

**Comment by silentzawr** [comment]
My bad. Thanks.

**Comment by seltix5** [comment]
Hello,
I'm facing this issue.
Even with the options in the FAQ (showHideOpacity: true, getThumbBoundsFn: false) the cropped version is shown stretched before showing the large image.
Is there a solution for this?
Thanks!
