### ISSUE TITLE
Show Multiple Items(images) at one time?

### ISSUE THREAD

**Issue by weilinzung** [dimsemenov/PhotoSwipe#1284]
Can this plugin show multiple images on one slide?  or automatic to fill the slides on a full-responsive screen?

I want to create a blocked gallery that when I click on image then open as lightbox, but seems I need to combine Lightbox plugin with Owl Carousel. 

thanks!

**Comment by jhabdas** [comment]
@weilinzung please consider asking your question on StackOverflow.
