### ISSUE TITLE
Why path has changed  "/shop/lib/photoswipe/default-skin/default-skin.png"?

### ISSUE THREAD

**Issue by zhangjiahao93** [dimsemenov/PhotoSwipe#1293]
"default-skin.png". In the application of PNG, "PhotoSwipe-master/dist/default skin/default-skin.png"
Why do path "into/shop/lib/photoswipe/default skin/default-skin.png"

**Comment by jhabdas** [comment]
@zhangjiahao93 I read this three times and still have no idea what you're asking. are you talking about a source file change, or a change in the `/dist`?
