### ISSUE TITLE
Scroll top after closing gallery

### ISSUE THREAD

**Issue by FlorianBurgevin** [dimsemenov/PhotoSwipe#1294]
Hello,

I have a problem when I'm closing the gallery. 
In any way, the page scroll top after closing it. (even via x cross or mouse scroll)

Do you have an option to prevent this? Or is it the expected behabiour?

Thank you

**Comment by FlorianBurgevin** [comment]
It's ok with option history: false sorry

**Comment by towersxu** [comment]
I meet same problem, but fixed it with option focus: false
