### ISSUE TITLE
2 different options on 'close'

### ISSUE THREAD

**Issue by VitoXY** [dimsemenov/PhotoSwipe#1296]
Hi!

I used browser's back after 'close':
gallery.listen('close', function() { window.history.back(); });

For 'normal' use it is fine. But if I share direct link to FB, screen goes blank. 

In this case I would like to have 
gallery.listen('close', function() { window.location.href = 'HOMEPAGE'; });

I can not make it work in both ways. Please advice.

Vito

**Comment by jonnitto** [comment]
You could check the history like that 
```
const HAS_HISTORY = (() => {
	const REFERRER = document.referrer;
	const HOST = REFERRER ? REFERRER.split('/')[2] : '';
	return (HOST == location.host && history.length > 1);
})();
```

and then, in the function:

```
gallery.listen('close', function() {
  if (HAS_HISTORY) {
    history.back();
  } else {
    location.href = 'YOUR_URL_HERE'
  }
});
```

**Comment by VitoXY** [comment]
Nice! Thank you!

**Comment by VitoXY** [comment]
Strange. It works fine on my computer, but I just realised that it does not
work on my mobile. PhotoSwipe has a problem, it shows just blank screen. On
my computer it works great!

**Comment by VitoXY** [comment]
Works in Chrome and FireFox on both (mobile and 'normal') platforms. Not working on I/E on computers, HTC and Samsung Explorers. Any idea what to do with them?

I have no Mac to try.
