### ISSUE TITLE
How to clear items after close or before open?

### ISSUE THREAD

**Issue by johndavedecano** [dimsemenov/PhotoSwipe#1310]
How to clear items after close or before open. I want to clear the images inside of 
```

<div className="pswp__item"/>
            <div className="pswp__item"/>
            <div className="pswp__item"/>
```

**Comment by jhabdas** [comment]
@johndavedecano please ask your question on StackOverflow and close this issue. there are 267 open issues and many are questions which are more appropriate for SO. /cc @dimsemenov

**Comment by jhabdas** [comment]
TYVM

**Comment by brandlewco** [comment]
was looking for the answer to this and can't find the stackoverflow. Can you update with solution?
