### ISSUE TITLE
how to detect if the presentation is in normal or in fullscreen mode? 

### ISSUE THREAD

**Issue by fedyd** [dimsemenov/PhotoSwipe#1314]
I would need to detect if the presentation is in normal or fullscreen mode and/or when it is toggled.
Is there a switch variable that is changed when this happens?
Thank you, Federico

**Comment by jhabdas** [comment]
@fedyd When PhotoSwipe enters fullscreen using the JS provided in the example (which is a very clever piece of work, might I add), it adds fragment identifiers to the url. the DOM will trigger the following event whenever that happens you can add a listener for: http://devdocs.io/dom_events/hashchange

**Comment by fedyd** [comment]
@jhabdas Thank you very much for your reply. Unfortunately the solution you suggested doesn't work for me; I have tried to detect the hashcahnge but it seems to be fired when PhotoSwipe gallery starts and close before than when the gallery toggles between normal screen and full screen modes.
After having read a little bit the source code of PhotoSwipe (I am not a very skilled coder), I have tried to use the PhotoSwipe API, and in particular the property pswp.ui. With that you can access an object given by pswp.ui.getFullscreenAPI(). This object has a property that is called isFullscreen() and I supposed it returned what I wanted, i.e., calling pswp.ui.getFullscreenAPI().isFullscreen(), I expected a boolean value but I didn't have luck: my supposition was due also to the fact that, instead, if I want to esc from full screen mode via code, the method pswp.ui.getFullscreenAPI().exit() works fine.
Anyway I solved my problem listening for class change in the root pswp dom element, as the class pswp--fs is dynamically added and removed to this element when the gallery toggles between normal and fullscreen modes.
Using MutationObserver object and some variables I did in this way:

`var isFullScreen = false,
    pswpObsConfig = {attributes: true, childList: false, characterData: false},
    pswpTarget = document.getElementsByClassName("pswp")[0],
    MutationObserver = window.MutationObserver || window.WebKitMutationObserver
                       || window.MozMutationObserver,
    pswpObserver = new MutationObserver(function(mutations) {
        mutations.forEach(function(mutation) {
            if (mutation.attributeName === "class") {
                if ($(".pswp").hasClass("pswp--fs")) {          
                     isFullScreen = true;
                }
                else {
                     isFullScreen = false;
                  }
                }
            }
        });
    });
pswpObserver.observe(pswpTarget, pswpObsConfig);`  

Putting this code in a script of the same document in which PhotoSwipe is used, works pretty good (at least for me) to detect if the gallery is shown in fullscreen or normal mode and when it toggles between the two.

**Comment by jhabdas** [comment]
> Putting this code in a script of the same document in which PhotoSwipe is used, works pretty good (at least for me) to detect if the gallery is shown in fullscreen or normal mode and when it toggles between the two.

Thanks for sharing. It's nice to know you were able to find a solution that worked for you. Cheers!
