### ISSUE TITLE
z-index bug

### ISSUE THREAD

**Issue by LukeMadhanga** [dimsemenov/PhotoSwipe#1320]
Hi guys,

Great bit of kit this is. I've encountered a problem that is only evident on [expletive] iPhones. In the attached image, you can see that the white login bar has above the controls and background. However, that login bar only has a z-index of 100 and appears in the DOM before PS. PS however, has a z-index of 1500. 

As stated before, it is being displayed correctly Android devices and on desktop browsers. iPhones are known to have a z-index issue and this particular is apparently known.

<img width="640" alt="screen shot 2017-04-05 at 10 46 53" src="https://cloud.githubusercontent.com/assets/7837788/24699838/41fa9aca-19ed-11e7-806d-725ec907383d.png">

**Comment by LukeMadhanga** [comment]
Alright, so I know what causes the issue and the solution is probably easy:

The problem occurs when there is a `-webkit-overflow-scrolling: touch`. Would, on open, adding a `body { -webkit-overflow-scrolling: auto !important; }` and then removing it on close solve the issue? That's how I solved this for my own problem

**Comment by jhabdas** [comment]
@LukeMadhanga great job. could you please close this issue now that you've solved your problem?

**Comment by LukeMadhanga** [comment]
Hi, I will close. Do you think it would be worth adding it as a note in the documentation somewhere or building it into the software as I'm sure that someone else will end up having this problem
