### ISSUE TITLE
goTo Bug

### ISSUE THREAD

**Issue by Alf21** [dimsemenov/PhotoSwipe#1326]
Hey,

I want to open the gallery with javascript.
After closing the gallery, i have an event on a button that calls 
```
gallery.goTo(0);
```

But the gallery wont open.
Its curious because if i use the script on bottom of this page (http://photoswipe.com/documentation/getting-started.html), I can click on an image and it will open (figure element).

How to fix this? I tried to clear the Interval or sth, but nothing happens :/ If i call gallery.destroy, gallery.goTo(1), gallery.next() or so on, i get a strange exception: 'ba is null'...

Thanks

**Comment by dimsemenov** [comment]
After gallery is closed it's automatically destroyed. The instance is kept in memory only while gallery is open.

Which means the instance should be created each time you open a gallery. And no method should be called after `close` or `destroy`.

**Comment by Alf21** [comment]
Okay, i understand. I thought it will only get hidden or removed instead of clearing the reference / destroying it. Thanks, i will take another way (just creating the gallery again).
:)

**Comment by ianthedev** [comment]
> After gallery is closed it's automatically destroyed. The instance is kept in memory only while gallery is open.
> 
> Which means the instance should be created each time you open a gallery. And no method should be called after `close` or `destroy`.

Could you please demonstrate "the instance should be created each time you open a gallery"? I only know to create the instance through this way:
```javascript
const lightbox = new PhotoSwipeLightbox({
    // options here
});
```

And I guess "each time you open a gallery" is referring to the `beforeOpen` event:
```javascript
lightbox.on('beforeOpen', () => {
    // photoswipe starts to open
});
```

But I don't understand how to create the instance by using the `beforeOpen` event.
