### ISSUE TITLE
How can I get the real-time information of the image in a gallery, such as: x, y, w, h.

### ISSUE THREAD

**Issue by YuLiangZhao** [dimsemenov/PhotoSwipe#1336]
How can I get the real-time information of the image in a gallery, such as: x, y, w, h?I want to synchronize the image information to another computer in real time.Thank you very much!

**Comment by marko-avlijas** [comment]
This is a question for stackoverflow. Please check this link: http://photoswipe.com/documentation/responsive-images.html

This is the part of code you should check out:

    // gettingData event fires each time PhotoSwipe retrieves image source & size

**Comment by YuLiangZhao** [comment]
@marko-avlijas Thanks for your reply! What i wanted is a page playing on frist PC just like :http://example.com/#&gid=1&pid=2&w=800&h=600&etc=SomethingElse,in the url have all information of the image(&gid=1&pid=2) ,and i can share this url to another PC,it will be playing as same as the first PC.In short,"Clone" and Show.

**Comment by marko-avlijas** [comment]
Please close the issue and ask on stackoverflow. Too many open issues such as these, which are not really issues but questions which belong on stackoverflow, cause open source project authors to waste their time and stop responding to issues at all.

On stackoverflow there are plenty of people who would be happy to answer your question.

**Comment by YuLiangZhao** [comment]
@marko-avlijas Ok.I'll close the issue and ask on stackoverflow.Thank you very much!
