### ISSUE TITLE
How to do than .close () function do not modify the url

### ISSUE THREAD

**Issue by LeGoffMael** [dimsemenov/PhotoSwipe#1341]
Hi,

I have links has the position of "photo" in your exemple. When i click on this link i have an "Cannot read property 'center' of undefined" error.

So i close the gallery with .close function but i can't redirect to the page that i want because the .close function change the hash.

As an author do you have a solution to offer me?

Thank

**Comment by dimsemenov** [comment]
Disable the history option entirely, or make your changes to the URL after PhotoSwipe is destroyed.

**Comment by LeGoffMael** [comment]
What do you mean by entirely ?
not just `gallery.options.history = false;` ?

**Comment by dimsemenov** [comment]
I mean set `history:false` during the initialization. Or exclude the history module itself.

**Comment by LeGoffMael** [comment]
Thank you very much it works well (and thank for shared your job) ^^
