### ISSUE TITLE
Refresh the display contents in the light box

### ISSUE THREAD

**Issue by LeGoffMael** [dimsemenov/PhotoSwipe#1358]
Hi,

Is there a function that when called restarts the light box at the current item?
The aim being to refreshes the displayed items (for example source or description)

Thank

**Comment by dimsemenov** [comment]
You can modify items array directly, check "Adding slides dynamically" section at the end of API section http://photoswipe.com/documentation/api.html

**Comment by LeGoffMael** [comment]
I tried doing this :
`            gallery.invalidateCurrItems();
            gallery.updateSize(true);
            gallery.ui.update();`
But this didn't change any thing.
To explain more easily what I want to do: [link](http://legoffmael.fr/projets/galleries/index.php)
When I vote on an image I have to close and then reopen the light box to display the new score, yet the gallery in background is updated.

Is I incorrectly applying the code explained in the documentation?

Thanks for your help

**Comment by dimsemenov** [comment]
I'm not sure if I understand where do you update the actual value of caption content.

At first, you need to do something like `gallery.items[0].title = "new caption content";` (where `0` is index of a slide) and only then call invalidate/update methods.

And btw, if you update only UI, you don't need to call `invalidateCurrItems` or `updateSize`, as they refresh the content of the slide itself (which is just an image in your case). You need only `gallery.ui.update()`.

**Comment by LeGoffMael** [comment]
Thanks I managed to do what I wanted!

But I still have a little problem :
<pre>
        $('div.score a').click(function (e) {
            var newScore = $("#" + ControllerGallery.getCurrentGallery() + " a:nth-child(" + index + ")").attr('data-score');

            if (score != newScore) {
                pswp.currItem.score = newScore;
                console.log(pswp.currItem.score);
                pswp.ui.update();
            }
}
</pre>

The code works only once and I feel it is because of  pswp.ui.update();

**Comment by LeGoffMael** [comment]
Well I finally changed completely my method I use directly html() method of jquery ^^
Thank you for your help I thanks to you better understood some working of Photoswipe
