### ISSUE TITLE
Scrolling to anchor on close [iOS < 10]

### ISSUE THREAD

**Issue by irudoy** [dimsemenov/PhotoSwipe#1370]
When `history` option is enabled, and anchor hash presents in URL, the page is scrolling to anchor when PhotoSwipe gallery closed.

Reproduces in Safari (iOS versions 7, 8, 9).

![repro](https://media.giphy.com/media/xUPGcL4y4b0jsPEXg4/giphy.gif)

Repro: https://codepen.io/rudoy/pen/OgpPLY (switch to debug view)

**Comment by irudoy** [comment]
@dimsemenov seems like the issue is there: https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/history.js#L190

**Comment by irudoy** [comment]
@dimsemenov maybe this one? https://github.com/irudoy/PhotoSwipe/commit/093a61d4df744fe2015b2e1102446639ed2eb373
It's a bit dirty but seems to be working fine

**Comment by dimsemenov** [comment]
Thanks for providing the solution and reduced test case. 

At first glance, your solution looks fine, But it needs to be tested in all browsers, I'm not sure if others will behave the same way.

And, your code may cause a memory leak. If scroll event will never fire - removeEventListener won't be called. Maybe unbind it with short `setTimeout` in `destroy` event.

Or disable `history` option entirely if anchors are a crucial part of your site/app.

**Comment by irudoy** [comment]
This fix now works in production, so we'll get feedback if something goes wrong. Also, I'll check this manually in all browsers supported by PhotoSwipe. In another case, we can detect the version of iOS, and do all the dirty tricks.

Should I create a PR for this?

Unfortunately, at the moment we need both PhotoSwipe history feature and anchors.

**Comment by dimsemenov** [comment]
You may send PR, in case someone else will need it. But it's unlikely that I'll approve it right away.
