### ISSUE TITLE
WordPress Plugin Discussion

### ISSUE THREAD

**Issue by jhabdas** [dimsemenov/PhotoSwipe#1381]
https://wordpress.org/support/topic/is-this-plugin-a-violation-of-copyright/

@dimsemenov fyi

**Comment by dimsemenov** [comment]
@jhabdas, I wasn't contacted by the developer of the plugin that you are referring (to either decline or approve the usage), so not sure if I understand the issue. There are already some plugins on wp.org that you may use till official one is released, for example https://ru.wordpress.org/plugins/photoswipe-masonry/

**Comment by jhabdas** [comment]
Awesome. That's what I was looking to know. I'll let the support channels take it from here - I don't want to stir up too much of a ruckus on the WP side as I've already been doing my share of toe-stepping currently. Appreciate the pointer and will take a look at the unofficial blessed plugin for the time-being. Cheers to you @dimsemenov.

**Comment by Ipstenu** [comment]
Just FYI from the WP Plugins team, this request doesn't compute with the MIT license:

> Do not create a public WordPress plugin based on it, as I will develop it. 

IANAL, but in my experience with this, you'd have to have done this GPLv3 for that addendum to fly (and if you did, then the plugin/code wouldn't be permitted in the WP.org repository). THAT SAID! If we see a plugin that runs without your permission, we're happy to close it since we believe it to be a reasonable and sane request :)

So as a license add-on, that's no good. As a polite request to the world, we're in fully agreement and would enforce it to help be good open source stewards.

**Comment by louy** [comment]
Hi @dimsemenov, I've emailed you before about this. Luckily I still have the email.

<img width="894" alt="screen shot 2017-07-02 at 18 17 23" src="https://user-images.githubusercontent.com/349850/27772068-45cf5d56-5f53-11e7-9cd4-9b711e45f29e.png">

I think @jhabdas was concerned that this plugin might be a copyright violation after he saw the notice on the website and didn't want to use it before checking.

Kind regards,

**Comment by jhabdas** [comment]
Pretty sure the creator of a creative work can do whatever they want, as long as they're alive.  Building FOS does not require man to be an attorney to protect their work.

**Comment by Ipstenu** [comment]
No but the license you release your code under has laws. MIT isn't one of the ones where you can slap extra rules on it. The owner can re-license if they want to a more restrictive license, in **future** releases, but everything that was released MIT is free to be used however:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: (that they leave this notice in it. The end. )

That's the MIT license, so saying "but not for WordPress plugins" is **technically** violating the license, and per the license is unenforceable. My lawyer comment was that I can't remember if GPLv3 is the one that lets you say "use for everything but not this..." or not. That's all. 

Anyway. I would recommend not using the library in a WordPress plugin because it's morally the right thing to do. So we agree on that :)

**Comment by jhabdas** [comment]
Where law is concerned, at least in the US, intent, and not technicalities, is what is important. It's clear Louy saw the intent of message (regardless of license) and asked for permission. Where I believe many lawyers fail is they focus so hard on what's correct they miss the thing often right in front of them: what's right.

**Comment by jhabdas** [comment]
@Ipstenu thanks for the info. I'm doing some research on opensource.stackexchange.com because I want a terse license for some of my libraries where I can put conditions similar to what Dmitry has done here, whether it be in spirit to the the letter of the law. I will follow-up once I have found a solution for providing FLOSS with some minimal conditions which to do actively contribute to license proliferation.

@dimsemenov when Hugo got popular enough they switched to Apache 2 license. I think you have more stars than the Hugo project currently, if that means anything to you.

**Comment by jhabdas** [comment]
https://opensource.stackexchange.com/questions/5689/adding-conditions-to-a-terse-permissible-open-source-license

**Comment by dimsemenov** [comment]
- The license is MIT, and always was, I'm not planning to change it. This license file is always in repo root -  https://github.com/dimsemenov/PhotoSwipe/blob/master/LICENSE and in source JS/CSS files.
- The statement "please do not make public WordPress plugin, ask me first" Is just a human request on promo page of the PhotoSwipe added for obvious reasons. If you contradict it, no one will sue you, I just won't help or promote your work, with further consequences. 

I haven't told anyone who asked for usage "no you can't use it" yet. There are even a few commercial gallery plugins that use PhotoSwipe. Some popular open source projects are also using it, for example WooCommerce. I'm not getting any profit from those, and I'm totally fine with that. 

My email is always open for discussion, if you're having some issue.

**Comment by jhabdas** [comment]
Has Automattic donated to you, Dmitry, for your time and continued effort? I can assure they're making money using your software. One does not require greed in order to ask what is required to feed themselves based on their work.

**Comment by dimsemenov** [comment]
> Has Automattic donated to you, Dmitry, for your time and continued effort? I can assure they're making money using your software.

@jhabdas, no, but as I posted before - I'm totally fine with that. The plugin gets public exposure, which is more important to me than one-time profit.

**Comment by jhabdas** [comment]
Seems you should see a dividend. But such as it is it seems MIT is inadequate based on my research on Stack. Sigh. Time to pursue anew license. Thanks for all your hard work Dmitry.

**Comment by jhabdas** [comment]
@dimsemenov I understand you may not have any interest, but I wanted to let you know this conversation and the info I learned on Stack spurred me to submit a new license to the SPDX Legal Team today. You can read about it here: https://medium.com/@jhabdas/introducing-the-btc-license-28650887eb11

**Comment by dimsemenov** [comment]
@jhabdas, interesting, thanks for sharing.
