### ISSUE TITLE
Event when the current item change

### ISSUE THREAD

**Issue by LeGoffMael** [dimsemenov/PhotoSwipe#1382]
Hi !

Is there a way to know when the current item change ?
Currently i used the event
`pswp.listen('beforeChange', function() { });`
but it react too many times (when I click on links in the caption area for example), Is there a better method?

Thanks by advance

**Comment by dimsemenov** [comment]
Store index (`pswp.getCurrentIndex()`) somewhere and check if it was changed in this event, if it's crucial for you.

**Comment by LeGoffMael** [comment]
Thank you for your answer !

But what do you call "somewhere"? In a variable? In the DOM?

**Comment by dimsemenov** [comment]
```js
var prevIndex;
pswp.listen('beforeChange', function() {
  if(prevIndex !== pswp.getCurrentIndex()) {
      ...
      prevIndex =  pswp.getCurrentIndex();
  }
});
```

**Comment by LeGoffMael** [comment]
Oh yes like that... sorry for the silly question
Thank you very much for your help
