### ISSUE TITLE
Dynamically add images to existing gallery

### ISSUE THREAD

**Issue by andreszs** [dimsemenov/PhotoSwipe#1385]
I'm using **PhotoSwipe** for a relatively large gallery (+1000 photos) which are **not** provided initially to optimize resources. Is there some way to initialize PhotoSwipe with a gallery of **100 photos** and **dynamically add another 100 items somehow**, when user is visiting the last photos? Thanks.

**Comment by dimsemenov** [comment]
You can, scroll to the end of API section http://photoswipe.com/documentation/api.html

**Comment by andreszs** [comment]
Thanks! I missed that page, sorry.
