### ISSUE TITLE
Image zooms out if you click a link or button on a touch screen

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1386]
If you click on a menu item on a touch screen device like an ipad, the image is enlarged. You don't see this effect on a PC.

You can see this effect in the PhotoSwipe demo gallery: http://photoswipe.com/#&gid=1&pid=1 Click on a touch screen device on the menu arrow and select 'Share on Facebook' a new tab opens, but if click the tab of the Demo gallery, you see that the image is enlarged.

This effect cause problems in my jAlbum PhotoSwipe skin, see for instance in this example:
http://andrewolff.jalbum.net/AmsterdamJodenbuurt/#&gid=1&pid=9
Click on a touch screen device on the menu arrow and select 'Show/Hide EXIF data'.
You see that the EXIF data are displayed (what you expect), but you see too that the image is enlarged (what I you did not ask and did not expect).
You see the same effect if you click the expand button in the middle: the image is expanded to the full screen height, as programmed, but if you return to the original display by clicking the white cross in the upper left corner, you see that the original image is enlarged.

How can I prevent this mis-behavior ?
Why do I see this only on a touch screen device  and functions it fine on a PC?

**Comment by tomdav999** [comment]
https://github.com/dimsemenov/PhotoSwipe/issues/1198

**Comment by acwolff** [comment]
Yes this works!
Thank you very much for this fix!

If somebody else like to use this: Enclosed are the corrected photoswipe.js and photoswipe.min.js files.
[PhotoSwipe-4.1.2_corrected.zip](https://github.com/dimsemenov/PhotoSwipe/files/1150895/PhotoSwipe-4.1.2_corrected.zip)
