### ISSUE TITLE
Navigation Icons not loading - iphone 4

### ISSUE THREAD

**Issue by peahi** [dimsemenov/PhotoSwipe#139]
Hey there,

We love photoswipe but we are having some strange issues. Things seem to work as expected but on my new iPhone 4, when iside the galley, it does not show the icons/spinning wheel.

I tested the gallery on iphone3 and it worked. Tested on android and it does work but after the first swipe, the icons disappear again.

You can see a simple example we've been testing here:

http://gomobot.com/PJ-VCJSMRNM3WCZ

It's very strange because your sample does seem to work on the iphone4 but I compared my my code to yours and after many hours, haven't be ablet to fix this. Could you please help us? we really want to use this!

Thanks in advance for your time and work on this!

**Comment by JPustkuchen** [comment]
For me the reason was simply that the "icons-2x.png" file was completely missing in my downloaded library... It's only being loaded on retina displays so it worked perfectly on Chrome... -.-
