### ISSUE TITLE
getCurrentIndex() returns wrong index

### ISSUE THREAD

**Issue by davidenco** [dimsemenov/PhotoSwipe#1394]
I cannot find an event or method that tells you the direction, previous index and next index. Therefore I am trying to write my own process.

However calling getCurrentIndex() in either the afterChange or beforeChange event handlers returns the same number.

```
// Current index is 0; I'm swiping to the next index
gallery.listen('beforeChange', function () {
    oldIndex = gallery.getCurrentIndex();
    console.log(oldIndex); // returns 1
});
gallery.listen('afterChange', function () {
    newIndex = gallery.getCurrentIndex();
    console.log(newIndex); // returns 1
});
```

**Comment by dimsemenov** [comment]
This is by design. if you want to retrieve "previous" index, just store it in some variable and update it in `afterChange`.
