### ISSUE TITLE
How to prevent that the gallery closes?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1401]
For an embedded gallery like in [this example](http://www.andrewolff.nl/TestAlbum/Embedded_PS/), I like to prevent that the viewer closes the gallery.

So I removed the close button and the other buttons:
defaultUIOptions = { 
closeEl: false,
captionEl: true,
fullscreenEl: false,
zoomEl: false, 					
shareEl: false,

and disabled a number of options:
    var options = {       
closeOnVerticalDrag: false, closeOnScroll: false,  pinchToClose: false,

But On a PC I can still close the galley via the Esc key and by clicking in the area next to the image.

How can I prevent the close by these two actions?
Is there a better way to prevent all close actions?

**Comment by dimsemenov** [comment]
You can always just override `close` method if you don't need it for anything (`yourPhotoSwipeInstance.close = function() {};`).

**Comment by acwolff** [comment]
Yes, that works!
Thanks!
