### ISSUE TITLE
iOS11: Swiping affects background page

### ISSUE THREAD

**Issue by mfis** [dimsemenov/PhotoSwipe#1425]
Since iOS11, sometimes swipes start to affect the background page. Horizontal swipes do nothing, vertical swipes scrolling background page. Closing and new starting of the Photoswipe gallery fixes the problem just shortly. After a few swipes or device rotation the effect starts again.

**Comment by acwolff** [comment]
Please give a link to your gallery, because I don’t see this under iOS with my albums, see for instance here https://andrewolff.jalbum.net/Terschelling_PS/index.html

**Comment by mfis** [comment]
I continued to test and found out that the problem only appears when the side is running as a WebApp. (iOS: Share -> To Homescreen)
Needs to have the following tag in the html head:
<meta name="apple-mobile-web-app-capable" content="yes"></meta>
See my test gallery under https://fimatas.de/PhotoExposition/
Login with test / test
I have made a screen recording showing the issue. See scroll bars on the right:
https://www.dropbox.com/s/6ydvloni41mtaph/IMG_1487.TRIM.MOV?dl=0

**Comment by dimsemenov** [comment]
@mfis, does preventing touchmove event globally help? 

(e.g. `document.ontouchmove = function (e) { e.preventDefault()
}`)

**Comment by mfis** [comment]
@dimsemenov This solved the problem for me, thank you!
