### ISSUE TITLE
Availability of WordPress plugin

### ISSUE THREAD

**Issue by arnowelzel** [dimsemenov/PhotoSwipe#1441]
I am well aware about #1381 - but since this is already a while ago: any information about when the "official" WordPress plugin will be available? I created my own plugin to use PhotoSwipe in my own (non-commercial) sites. It's not public, but having it public in the WP repo would make things much easier (e.g. update handling for multiple WP sites etc.).

And no - the available plugins don't work for me since I don't need a gallery plugin using PhotoSwipe. I just wanted to have existing pictures shown in PhotoSwipe - regardless if they are inside a gallery or single images - and I also need localization support, as I also run multi language site installations.

Who develops the "offical" WP plugin? Is there already a kind of beta version? When is a release expected?

If there is fact no development going on for a WP plugin on your side, please change at least the text of your request to something more sensible "please don't create commercial WordPress plugins without contacting me first" or similar. Or is it really not allowed to create even free plugins?

**Comment by dimsemenov** [comment]
> Who develops the "offical" WP plugin? Is there already a kind of beta version? When is a release expected?

I'm making it, and really hope to release it close to the Christmas, or short after it, you may subscribe here to get notified (if you haven't yet) http://dimsemenov.com/subscribe.html

> is it really not allowed to create even free plugins?

It is allowed, you just need to get permission from me, I haven't denied anyone yet there are even a few commercial plugins that you PS. I've seen email that you sent me yesterday, just replied to it.

---

Closed, as a duplicate.
