### ISSUE TITLE
In Android app, hook in to a social share plugin like cordova-plugin-x-socialsharing from PhotoSwipe

### ISSUE THREAD

**Issue by jamminjames** [dimsemenov/PhotoSwipe#1443]
While I love PhotoSwipe for many reasons, the built-in social sharing functions seem to be lacking when using it in an Android app. For example, as I've noted in another recent issue thread, Pinterest sharing is no longer working. Also, trying to share brings up logins for the website versions of things like Twitter and Facebook, rather than the device's Twitter and Facebook apps. 

So, I'd like to hook into a plugin my app is already using, cordova-plugin-x-socialsharing. I've tried various things, but not having much luck. Can anyone give me some hints on how I could hook into such a sharing plugin from inside of PhotoSwipe, to share images?

**Comment by acwolff** [comment]
I made a similar implementation with the [AddThis plugin](http://www.addthis.com/index-ab1?utm_expid=12961876-30.3Yz5Ca8WQGCada4nTc960A.1) for share buttons, see [this album](https://andrewolff.jalbum.net/Eerde_PS/). View the source code to see how it has been implemented

**Comment by jamminjames** [comment]
I don't get it, it looks like you're just using the regular PhotoSwipe share code. It uses the same share menu, same share coding for all the social media choices, as far as I can see. You've got the AddThis js script line, but I don't see that it's doing anything.

**Comment by acwolff** [comment]
<img width="315" alt="addthiswithphotoswipe" src="https://user-images.githubusercontent.com/8150784/32368516-3e3f67ea-c086-11e7-86c5-45e515bed339.PNG">
See screenshot: 5 share buttons in the upper left corner!

**Comment by jamminjames** [comment]
Hmm, didn't see those when I visited your link...

Anyway, I found another good solution, which works great inside an app, if anyone is interested. I do it using this SocialSharing-PhoneGap-Plugin.

The place to hook in is in the photoswipe-ui-default.js file, about line 447, in the onTap: function, like so:
```
onTap: function() {
    imageshare = pswp.currItem.src; //may not need to save as variable, but I did, declaring it on the first line of the js file: var imageshare = '';
    window.plugins.socialsharing.share('message', 'subject', imageshare, 'https://your-url.com');
} 
```
This will share the image you're on in the gallery.
