### ISSUE TITLE
problem displaying SVG in gallery mode..

### ISSUE THREAD

**Issue by selimonat** [dimsemenov/PhotoSwipe#1469]
tested successfully the latest version of photoswipe with .jpg images. works wonderfully.

When using SVG files as images, I can initially see the SVG files in tiled format. However, when I click on one of them, during the entrance into the gallery mode, the clicked image fades out, leaving me with a black background... 

I would appreciate, if someone could provide me a hint on how to approach this problem...

thx

**Comment by mrbluecoat** [comment]
@selimonat, did you ever get this resolved?  http://codepen.io/dimsemenov/pen/yyQrYv doesn't work for me

**Comment by fatmarker** [comment]
I'm experiencing the same exact problem when trying to load SVGs. It appears for a millisecond and quickly shrinks into blackness. The dimensions of the SVG are ignored.
