### ISSUE TITLE
360° View with PhotoSwipe

### ISSUE THREAD

**Issue by MetalCar** [dimsemenov/PhotoSwipe#1477]
Hi all,

I'm currently searching for a image swipe framework that supports also 360° Views. So my question is, if it's possible to show 360° Views within PhotoSwipe. I saw, that videos are possible, but 360° Views? Hope someone can help me with this. Is that even possible?

**Comment by Yafimau** [comment]
I have implemented Spritespin plugin inside Photoswipe adding frame with 360 as custom html. At the moment the only difference is navigation: next/previous buttons work great while spritespin swiping is conflicting with Photoswipe swiping.

Related link: http://spritespin.ginie.eu/

**Comment by MetalCar** [comment]
Hey @Yafimau! is there an example for using photoswipe with spritespin? Maybe I find a solution to fix this bug.

**Comment by Yafimau** [comment]
Unfortunately, it is production code and I don't have rights to share this.

**Comment by MetalCar** [comment]
Ok, then it will took more time to find it out by myself :) Thank you for your help and the information. :)

**Comment by acwolff** [comment]
My [PhotoSwipe](https://jalbum.net/nl/skins/skin/PhotoSwipel) skin supports 360 degrees panoramas, both cylindrical and spherical, see these example albums:
https://andrewolff.jalbum.net/PS_SpherePan/ and
https://andrewolff.jalbum.net/Pan-360-inline_PS/

**Comment by frydo** [comment]
Hello @Yafimau. it is now possible to get an example for using Spritespin with Photoswipe.
