### ISSUE TITLE
"Added non-passive event listener" Chrome violation

### ISSUE THREAD

**Issue by silverbackdan** [dimsemenov/PhotoSwipe#1478]
When opening photoswipe there are a couple of violations in Chrome:
```
Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

This repeats for the `mousewheel` event too

I believe it originates from this line:
https://github.com/dimsemenov/PhotoSwipe/blob/703c415b1b97e8983fff217644888062f07d308b/src/js/framework-bridge.js#L15

I don't think this is a duplicate issue but it may be related to https://github.com/dimsemenov/PhotoSwipe/issues/1217

As it doesn't call `preventDefault` it seems worth it to add this in, thoughts? It'd just be changing it to:
```js
if(type[i]) {
  target[methodName]( type[i], listener, ['mousewheel', 'wheel'].indexOf(type[i]) === -1 ? false :
 {passive: true});
}
```

**Comment by Larzans** [comment]
Why don't you create a pull-request and hope that @dimsemenov  gets to incorporating it :)

**Comment by silverbackdan** [comment]
I don't think this is still happening. Sorry for the delay in replying @Larzans - I should have done that but fortunately it looks as though it's been resolved.

**Comment by mstratman** [comment]
I'm still seeing these warnings with 4.1.3

**Comment by mhluska** [comment]
I'm also seeing these with 4.1.3 on Chrome 79.0.3945.130

**Comment by andreszs** [comment]
This problem persists with 4.1.3 and Chrome 80.0.3987.116.

Is there no possible workaround? This (and other plugins) are causing Chrome to fill up the console with more and more warnings that make debugging a real pain.
