### ISSUE TITLE
Heavy request on slide change

### ISSUE THREAD

**Issue by psntr** [dimsemenov/PhotoSwipe#1481]
Hi,

I noticed that everytime I'm switching image on Photoswipe a new request to fetch the image was created. I do not understand the logic behind that. Why re-creating the same instance? 
This is from the last version of the photoswipe.js (line 3155).

`else if(item.src && !item.loadError) {
// image object is created every time, due to bugs of image loading & delay when switching images			
 img = framework.createEl('pswp__img', 'img');
 img.style.opacity = 1;
  img.src = item.src;
 _setImageSize(item, img);
 _appendImage(index, item, baseDiv, img, true);
}`

As you can notice on my screenshot the same image is being requested again and again on each previous or next event.

So I wonder if there is specific settings to avoid that? 
<img width="1680" alt="screen shot 25" src="https://user-images.githubusercontent.com/20617539/35687709-c2743e50-07b2-11e8-9a62-fedc3194e3a1.png">

**Comment by dimsemenov** [comment]
Setup proper cache headers and browser won't send a request for the same image if it was loaded recently.

**Comment by psntr** [comment]
I see, so it's a correct behaviour. I feel so much relived. Thank you.
