### ISSUE TITLE
_indexIndicator is undefined

### ISSUE THREAD

**Issue by S1SYPHOS** [dimsemenov/PhotoSwipe#1483]
When commenting out `div.pswp__counter`, navigating slides stops working, throwing `_indexIndicator is undefined` and/or `item.vGap is undefined`.

**Comment by andi34** [comment]
To hide the counter you simply need to add `counterEl: false,` to your options.

**Comment by S1SYPHOS** [comment]
Thanks, I figured that eventually, but never cleared it out - as this project is unmaintained, I switched to other projects .. been three years, anyway

**Comment by andi34** [comment]
Don't worry, old issue but was still open so I thought at least posting a solution 👍  I've started a fork and applied a lot of changes which never made it into the project here, so going around the issues here and see what needs to be fixed
