### ISSUE TITLE
Is this repo still maintain? need update about this library

### ISSUE THREAD

**Issue by jimblue** [dimsemenov/PhotoSwipe#1490]
Hi @dimsemenov,

It's been almost a year since last release.
There are so many issues unsolved and a lot of them didn't got any answer.
Also there is a bunch of PR to help improve Photoswipe, some are pretty old and many didn't got any answer too.

@dimsemenov can you give a little feedback to `Photoswipe` user to let us now if you still plan to maintain it or not?

I think a lot of people love `Photoswipe` like I do but hesitate to use it because this repo seems dead.

Which is crazy for an almost 16000 stars repo!!

Hope you understand what I'm looking for, just feedback basically.

Thank you so much,

Cheers

**Comment by dimsemenov** [comment]
I'm rewriting a large part of the script atm,  dropping support of old browsers (IE, Android kitkat), implementing easier initialization and built-in srcset support. It will be backwards compatible - existing API won't change much. I might publish alpha branch if someone wants to help. Regarding the current version - I'll fix only critical bugs if any will be found.

**Comment by jimblue** [comment]
Hey @dimsemenov !

Thank you so much for fast answer!

I'll be happy to help you with alpha branch and I'm pretty sure many other people would be happy to back you also.

You have such a great community you should use it.

Maybe create a more official Issue than this one to explain your roadmap and ask for help 😄 !!

Looking toward this alpha branch! Cheers

PS: your website seems dead

**Comment by dimsemenov** [comment]
back online, thanks!

**Comment by jimblue** [comment]
Hey @dimsemenov any update about the alpha branch?

**Comment by jimblue** [comment]
Hey @dimsemenov any update about the alpha branch?

**Comment by jimblue** [comment]
Hey @dimsemenov !

Can we have some update please?

Thank you

**Comment by dimsemenov** [comment]
I'll publish the finished version as soon as I can, currently busy with work stuff. If someone wants to support the development - feel free to send a proposal via email.

**Comment by jimblue** [comment]
Hey @dimsemenov, thanks for the update!

I'll be happy to help and probably others too.

What about publish your current dev branch as a beta version?

Also why don't you make an official post about the situation so more peoples can help you with development? (I bet nobody is reading this close issue)

Cheers

**Comment by jimblue** [comment]
Hi @dimsemenov!

Could you please give update 😞...

Thanks

**Comment by jimblue** [comment]
@dimsemenov this is just a friendly ping... It's been a long time without any news...
Why don't you use the community help to rewriting Photoswipe, this is what open source is all about!
If you already have an alpha branch let the community test it and improve it.
We are a lot behind you, please just don't ignore it 😅 ! (this should be reopen...)
