### ISSUE TITLE
[BUG] Image jump when scrolling to close PhotoSwipe lightbox

### ISSUE THREAD

**Issue by jimblue** [dimsemenov/PhotoSwipe#1492]
Hi @dimsemenov,

You can check this bug on your demo page by simply open an image and scroll down.

You'll notice that the image do not return to the exact placeholder position then jump to it.

I found another library that have the same zooming effect without this bug you should have a look:

https://desmonding.me/zooming/

You can maybe found the fix inside the code.

Cheers

**Comment by HunterGraubard** [comment]
I can confirm this.

**Comment by gordonwes** [comment]
You need to delay the unbind of the scroll listener until the close animation finish.
Change this code inside the function _unbindEvents in photoswipe.js:

```
framework.unbind(window, 'resize scroll orientationchange', self);
```

to:  

```
setTimeout(function () {
     framework.unbind(window, 'resize scroll orientationchange', self);  
}, 400);
```

**Comment by jimblue** [comment]
Thanks @gordonwes try your fix

**Comment by jimblue** [comment]
Just been testing your solution @gordonwes and it's working great 😄 

@dimsemenov, is it possible to create a new release with a fix so we can close this issue?

Thank you so much!

**Comment by jimblue** [comment]
This bug is almost 1 year old so I am wondering... is this lib still maintain?
