### ISSUE TITLE
Difficulties with the code

### ISSUE THREAD

**Issue by Nic787** [dimsemenov/PhotoSwipe#1525]
Hi,

I currently use Justified Gallery to my website and want to add photoswipe to it.

My current HTML code is:
`<div id="mygallery" >
   <a href="../images/image1.jpg">
                    <img alt="Title 1" src="../images/image1.jpg"/>
                </a>
                <a href="../images/image2.jpg">
                    <img alt="Title 2" src="../images/image2.jpg"/>
                </a>
                <a href="../images/image3.jpg">
                    <img alt="Title 2" src="../images/image3.jpg"/>
                </a>
                <a href="../images/image4.jpg">
                    <img alt="Title 2" src="../images/image4.jpg"/>
                </a>
                <a href="../images/image2.jpg">
                    <img alt="Title 2" src="../images/image2.jpg"/>
                </a>
                <a href="../images/image4.jpg">
                    <img alt="Title 2" src="../images/image4.jpg"/>
                </a>
                <a href="../images/image1.jpg">
                    <img alt="Title 2" src="../images/image1.jpg"/>
                </a>
                
            </div>`

I read the "getting started" page for photoswipe, but I don't really understand all the codes I should put.
What I understood is that I need to add this at the end of my <body> tag.

` 
<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        
        <div class="pswp__bg"></div>
    
        
        <div class="pswp__scroll-wrap">
    
            
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>
    
            
            <div class="pswp__ui pswp__ui--hidden">
    
                <div class="pswp__top-bar">
    
                    
    
                    <div class="pswp__counter"></div>
    
                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
    
                    <button class="pswp__button pswp__button--share" title="Share"></button>
    
                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
    
                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
    
                    
                    
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                          <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                          </div>
                        </div>
                    </div>
                </div>
    
                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div> 
                </div>
    
                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>
    
                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>
    
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div> 
    </div>`

After that, I tried to figure how to make photoswipe work with my current link around image, but I don't really understand the JS code. Why is the code so complicated? I plan to add caption to my photo, but like I said, don't know what to do.

Thank you for your help.

**Comment by acwolff** [comment]
The easiest solution is to use the [jAlbum program](https://jalbum.net/en/software) with my [PhotoSwipe skin](https://jalbum.net/en/skins/skin/PhotoSwipe), in which case you can make an album with a justified gallery of thumbnails and a PhotoSwipe light-box as you can see in [this example album](https://andrewolff.jalbum.net/PS_JustifiedGallery/).

If you like to do it yourself, investigate the items array code of module https://andrewolff.jalbum.net/PS_JustifiedGallery/slidePage.js

**Comment by Nic787** [comment]
Well, I found this https://codepen.io/alienlebarge/pen/Kdrxga but not sure to understand how to make it works with my code. I don't have "figure" element in my HTML and I'm going straight into "a" and "img".
I know that there is some lightbox code you just need to add one line of code to make it work, but I want to use Photoswipe for mobile friendly.

I will send you the page I have difficulties with: 
[project.zip](https://github.com/dimsemenov/PhotoSwipe/files/2077296/project.zip)

Just open albums folder to see the current page I'm working on. to call photoswipe is in scripts.js near the end (before my commented code - test code).


Is it not possible to just call photoswipe when clicking on "a" tag, get the "alt" of the link and put it as "caption" in PS?

Thank you

**Comment by acwolff** [comment]
@Nic787 to see an album with your image, open page https://andrewolff.jalbum.net/Nicolas_Duclos/ and investigate the items code in page https://andrewolff.jalbum.net/Nicolas_Duclos/slidePage.js

**Comment by acwolff** [comment]
@Nic787 I could also repair your own files:

It contains two wrong links, the correct lines 20 and 21 are:

        <script src="../js/photoswipe.js"></script> 
        <script src="../js/photoswipe-ui-default.js"></script> 

I replace in file scripts.js your statement " var container = [];" by

	var items = [
  {
    src: '../images/image1.jpg',
    w: 1920,
    h: 1080,
      
    title:
       '<strong>Deep forest Waterfall in Kanchanaburi, Thailand</strong>' +
		 '<br>' 
		  
     
  }, 
  {
    src: '../images/image2.jpg',
    w: 1920,
    h: 1080,
      
    title:
       ''  
     
  }, 
  {
    src: '../images/image3.jpg',
    w: 1920,
    h: 1080,
      
    title:
       ''  
     
  }, 
  {
    src: '../images/image4.jpg',
    w: 1920,
    h: 1080,
      
    title:
       '<strong>Badwater Basin</strong>' +
		 '<br>' 
		  
     
  }, 
  {
    src: '../images/background1.jpg',
    w: 1920,
    h: 1080,
      
    title:
       ''  
     
  }, 
  {
    src: '../images/background2.jpg',
    w: 1920,
    h: 1080,
      
    title:
       ''  
     
  }, 
];

and did initialize PhotoSwipe by:

    var gallery = new PhotoSwipe($pswp, PhotoSwipeUI_Default, items, options);

You see the result here:
https://andrewolff.jalbum.net/Nicolas_Duclos/project/albums/islande.html

**Comment by Nic787** [comment]
Thank you!
