### ISSUE TITLE
What is the status of development?

### ISSUE THREAD

**Issue by arnowelzel** [dimsemenov/PhotoSwipe#1528]
I created a pull request with changes nearly 8 months ago (https://github.com/dimsemenov/PhotoSwipe/pull/1455) - and nothing happened so far yet.

Is this repository still maintained? What's the status of the development? Any roadmap? Any news about the "official" WordPress plugin?

**Comment by dimsemenov** [comment]
I'm rewriting the large part of the project in preparation for v5 release, which will also include WP plugin. Regarding the current version - only critical bugs will be listed. 

I apologize for not communicating it properly, I don't have free time to fully support v4 and review minor fixes atm.

You may subscribe [here](http://dimsemenov.com/subscribe.html) to get notified about the release.

**Comment by arnowelzel** [comment]
Thanks for the update. Maybe you should also add this information to Readme.md, so people don't spend time to submit feature updates or minor fixes.

**Comment by iBobik** [comment]
@dimsemenov If there are some volunteers, how they can help your with maintaining this awesome project?

**Comment by ahmadalfy** [comment]
I second @iBobik

**Comment by arnowelzel** [comment]
I did a number of changes in Photoswipe for my WordPress plugin (sliding images for desktop view, integrated some fixes, custom sharing links etc.): https://github.com/arnowelzel/lightbox-photoswipe

My fork of Photoswipe is at https://github.com/arnowelzel/photoswipe already quite outdated since I did not merge all my changes for the WordPress plugin back to it and I don't really have time to maintain another project besides the many thing I already do - but having  a maintained repo for Photoswipe outside WordPress would be nice!
