### ISSUE TITLE
iPhone X sidebars in portrait mode on safari

### ISSUE THREAD

**Issue by swa66** [dimsemenov/PhotoSwipe#1535]
Photoswipe does not appear to control the sidebars that safari shows in portrait mode on the iPhone X (those bars go into the area for the infamous "notch").

It also happens on http://photoswipe.com/ .

As a suggestion toward a resolution: those sidebars can be controlled: e.g. here: https://stephenradford.me/removing-the-white-bars-in-safari-on-iphone-x/
https://benfrain.com/css-environment-variables-iphonex/

After adding "viewport-fit=cover" to the viewport meta tag in the head section:
`<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover">`
and this to the CSS
`body { padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);}`
making sure it's not overruled further on.  Can get rid of the ugly white bars in portrait mode, without the rest of the site disappearing underneath the notch.

As a side effect this also makes zoomed-in image to use all of the screen (including the "bar" areas). And I suppose should you have really wide aspect ratio pictures, they'd go under the notch too (not tested myself).

I don't know of other browsers on an iPhone nor other (future?) notched devices.

Hope this helps others as well.

**Comment by swa66** [comment]
Closing it myself as I don't think there's much that photoswipe should/could do aside of documentiung how to work around this "feature" of modern phones.

**Comment by arnowelzel** [comment]
@swa66 did you test this modification with "regular" phones as well? I think I'll use that for my [WordPress plugin](https://github.com/arnowelzel/lightbox-photoswipe) (also see the WP repo https://wordpress.org/plugins/lightbox-photoswipe/).

**Comment by swa66** [comment]
@arnowelzel I don't have many phones to test with unfortunately, further testing still to be done (integrated into other tests)
