### ISSUE TITLE
PhotoSwipe stops working when display width is <600px

### ISSUE THREAD

**Issue by congkim94** [dimsemenov/PhotoSwipe#1536]
Hello,

For some reason PhotoSwipe stopped working when the display is less then 600px. Still haven't able to figure out what the problem is.

Here's the page.
http://congkim.com/life.html

Thanks!

**Comment by weavermedia** [comment]
FYI, works ok for me at 500px and 320px.

**Comment by linhub15** [comment]
Also works for me at iPhoneX 375px
Macbook, Chrome

**Comment by congkim94** [comment]
thanks. but I actually switched to lightgallery.

**Comment by linhub15** [comment]
@congkim94 Okay, I think we can close?
