### ISSUE TITLE
Image disappear after opening in new chrome (dev branch) 

### ISSUE THREAD

**Issue by Matysh** [dimsemenov/PhotoSwipe#1541]
1. Install chrome dev (69.0.3493.3 at this moment)
2. Open image via gallery

Actual result:
Image disappear after opening (on demo site also can be reproduce)

On stable chrome everything ok (yet)

**Comment by dimsemenov** [comment]
I was able to reproduce. Looks like an issue on a side of browser rendering engine.

`will-change:transform` on main PhotoSwipe img element seems to help. Hiding placeholder seems to help too. 

I'll open issue on Chromium.

**Comment by dimsemenov** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=865415

**Comment by dimsemenov** [comment]
fixed on Chrome side https://bugs.chromium.org/p/chromium/issues/detail?id=865415#c11 , closing.
