### ISSUE TITLE
PhotoSwipe Inline demo is broken?

### ISSUE THREAD

**Issue by psntr** [dimsemenov/PhotoSwipe#1582]
Was reading through the FAQ, bumped on the "How to implement inline gallery display", it shows a live codepen, but sadly it seems not to work.

Any ideas on how to make it work again?
http://codepen.io/dimsemenov/pen/JogxWM

Found in:
http://photoswipe.com/documentation/faq.html

**Comment by travismiller** [comment]
The linked codepen is loading photoswipe from an S3 bucket that appears hijacked. The CSS files 403 and the JavaScript files look highly suspect.

All of these scripts are the same, and well…
- http://photoswipe.s3-eu-west-1.amazonaws.com/pswp/dist/photoswipe.js
- http://photoswipe.s3-eu-west-1.amazonaws.com/pswp/dist/photoswipe.min.js
- http://photoswipe.s3-eu-west-1.amazonaws.com/pswp/dist/photoswipe-ui-default.min.js

![image](https://user-images.githubusercontent.com/494017/58210010-d8ccd600-7cad-11e9-88c7-fc23bb758123.png)

![image](https://user-images.githubusercontent.com/494017/58210083-fb5eef00-7cad-11e9-995d-82d8e3784c6f.png)

![image](https://user-images.githubusercontent.com/494017/58210228-7c1deb00-7cae-11e9-98f2-ce5b9a503be4.png)

/cc @dimsemenov

**Comment by dimsemenov** [comment]
Fixed, thank you for ping @travismiller
