### ISSUE TITLE
Show image as large as possible

### ISSUE THREAD

**Issue by uvula** [dimsemenov/PhotoSwipe#1602]
Show image as large as possible

May somebody help me, I'm not so deep in JS/CSS.
When using Photoswipe, everything is running fine.
When I click to a photo, it will be enlarged, but I have on top and bottom the "bars", showing index + sharing and caption.
The images is in between, reduced by the size of the two bars.
When I click to the image (zoom), the image is enlarged to 100%. The bars are overlay the image (with opacity).

I want use Photoswipe in this way: when I start clicking a image, it should always be as large as possible.

Can I do this by CSS only, use some option feature or must the code be changed?

Thanks in advanced.

Uwe

**Comment by acwolff** [comment]
Try this:

		_options,
		_defaultUIOptions = { 
			barsSize: {top:0, bottom:0},

**Comment by uvula** [comment]
Wow. Great. You are my hero :-)
It works phantastic, exactly what I want.

Mmmmmmmany thanks.

**Comment by RStoroy** [comment]
Where to put these options?
