### ISSUE TITLE
My Way To Supported Rotation

### ISSUE THREAD

**Issue by zhangzicao** [dimsemenov/PhotoSwipe#1623]
I watch the project for a long time,rotation is still not supported.I will still looking forward to it.
No way out,I have to write a javascript library to do that.Here I provide the code,and I hope it can help  those who need it.[https://zhangzicao.github.io/createPhotoSwipe/](https://zhangzicao.github.io/createPhotoSwipe/)

**Comment by ffaerian** [comment]
adding this to the css might provide exif support - it's probably the way to go forward.

img {
   image-orientation: from-image;
   object-fit: contain;
}
