### ISSUE TITLE
Photoswipe doesn't work on mobile device with the bootstrap meta tag

### ISSUE THREAD

**Issue by vibejena** [dimsemenov/PhotoSwipe#1670]
I've implemented to a website the Photoswipe library and everything works fine on the pc. Even with the chrome device tool, the photoswipe is opening up properly. But on phones it won't work. I've noticed that when I delete the bootstrap meta, it's working even on phones
meta name="viewport" content="user-scalable=no,width=device-width, initial-scale=1, shrink-to-fit=no"
but the problem is that the website is not properly displayed because of the lack of the meta. What can I do to make both the meta tag and the photoswipe lib work together?

**Comment by bertini36** [comment]
Hi @vibejena! 
I think I have the same problem. Did you find a solution? Can you share it? Thanks!

**Comment by vibejena** [comment]
@bertini36 
Yes, I solved the problem.

So I assume that Photoswipe works for you on Desktop but not on phone. Well... in my case i didn't added the data-med and data-med-size attributes to the a tag:

Wrong a tag:
<a href="foo.jpg" data-size="1920x1080" data-author="bar" class="demo-gallery__img--main">

Right a tag:
<a href="foo.jpg" data-size="1920x1080" data-med="foo.jpg" data-med-size="1920x1080" data-author="bar" class="demo-gallery__img--main">


This worked for me. Let me know if it helped

**Comment by bertini36** [comment]
Thanks @vibejena! It worked for me too!
