### ISSUE TITLE
touch, drag event is not working on mobile Safari after navigate back to page where pswp was open

### ISSUE THREAD

**Issue by jayjnu** [dimsemenov/PhotoSwipe#1684]
Device tested: latest iphone xs, iphone 8 safari
How to replicate:
- open pswp viewer
- navigate to any site
- go back to page where pswp was open
- try swipe actions 
- nothing works

**Comment by acwolff** [comment]
Confirmed!

**Comment by jayjnu** [comment]
It seems `window.requestAnimationFrame` works not as expected. 

Safari remote debugger show no consecutive `gestures._dragUpdateLoop` calls when I replicated the steps to cause bug.

So I tried using `window.setTimeout/clearTimeout` instead, and it works perfectly.

I will close the issue because it does not look like this library's fault.

**Comment by acwolff** [comment]
?? I think you should explain better how to solve this bug!

**Comment by jayjnu** [comment]
@acwolff 

I just found that iOS update 13.4 fixed this issue. I tested with a handful of iphones and the result was consistent.

If you are not in position where you just wait for the users to update their os and you are totally okay to modify original photoswipe code, which I wouldn't do, you can override the default [implementation](https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/framework-bridge.js#L218) of `framework.detectFeature()`. 

**AS-IS**  

```javascript
if(!features.raf) {
 var lastTime = 0;
 features.raf = function(fn) {
	var currTime = new Date().getTime();
	var timeToCall = Math.max(0, 16 - (currTime - lastTime));
	var id = window.setTimeout(function() { fn(currTime + timeToCall); }, timeToCall);
	lastTime = currTime + timeToCall;
	return id;
   };
  features.caf = function(id) { clearTimeout(id); };
}
```

**TO-BE**  
```
// remove if statement so that _requestAF is always setTimeout
 var lastTime = 0;
 features.raf = function(fn) {
	var currTime = new Date().getTime();
	var timeToCall = Math.max(0, 16 - (currTime - lastTime));
	var id = window.setTimeout(function() { fn(currTime + timeToCall); }, timeToCall);
	lastTime = currTime + timeToCall;
	return id;
   };
  features.caf = function(id) { clearTimeout(id); };
```

**Comment by acwolff** [comment]
Ok thanks for your solution.
Waiting for the new iOS version is not a problem for me, so I choose that solution.
