### ISSUE TITLE
Buttons not showing on top bar

### ISSUE THREAD

**Issue by drod18** [dimsemenov/PhotoSwipe#1690]
I downloaded an HTML template that contained PhotoSwipe but the button controls (zoom, share, close, etc.) are not showing up. They are there because I can click them, but for some reason the icons don't show up in white how they are supposed to. Any idea how to fix? Site: https://new.rockhoppercreative.com/

**Comment by YOBA1112** [comment]
Without any provided info i can just recommend to check that all necessary css files are included in your html file like so:
`<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/default-skin/default-skin.min.css">`

**Comment by drod18** [comment]
That was the issue. Thank you so much!!!
