### ISSUE TITLE
How to fit images with lower resolution than screen to fullscreen?

### ISSUE THREAD

**Issue by suiluj** [dimsemenov/PhotoSwipe#1698]
hello i would like to fit every image to fullscreen.

this is working when the resolution of an image is higher than the monitor resolution.

but it does not work when the image resolution is smaller than the monitor.

of course i want to keep the aspect ratio of the image.

so either it is edge to edge vertical or horizontal.

at the moment an image with lower resolution is centered in the middle:
![small resolution photo not fullscreen](https://user-images.githubusercontent.com/13067545/84813130-bec80900-b00f-11ea-8e81-e9e8933269a0.png)

image scale fit like this does not work for me.

```
imageScaleMethod: "fit",
```

Does someone know how to solve this?

**Comment by suiluj** [comment]
i think it is a problem with the theme of my photo gallery software. photoswipe is not the problem.

gallery software: piwigo  
piwigo theme: piwigo-bootstrap-darkroom

**Comment by xikeqian** [comment]
barsSize: { top: 0, bottom: 0 }, // set image distance of top and bottom in options params

**Comment by suiluj** [comment]
@xikeqian yes, thanks for the hint. I added this setting to the options in the piwigo theme.

https://github.com/tkuther/piwigo-bootstrap-darkroom/pull/253
