### ISSUE TITLE
Open gallery completely disappear below 768px res

### ISSUE THREAD

**Issue by masiorama** [dimsemenov/PhotoSwipe#1712]
I guess I am really missing something basic here, but I can't understand what is wrong with my config.
I properly set the library to show my gallery, and open it on a button click.
The problem I am experiencing is that as soon as I test on low/mobile resolutions, the gallery completely disapper, as you can see from the gif attached. If I go below 768px width simply the gallery is not shown, even if it exists in the DOM, and reappears as I go up with the resolution:

![photoswip_mobile](https://user-images.githubusercontent.com/731916/92098119-243ec100-edd9-11ea-9c17-b988e4e91546.gif)

Before digging into the code, could anybody give me an hint on what I should pay attention to? 
Am I missing, dunno, a mobile ui configuration? 
Thanks in advance!

**Comment by andi34** [comment]
If you have php installed & enabled you could test if it works on this:
https://github.com/andi34/PhotoSwipeGallery

**Comment by masiorama** [comment]
@andi34 thanks but it was not necessary. It was my fault, totally messing up with stylesheets.
Thanks!
