### ISSUE TITLE
Is it possible to overlay caption on the images?

### ISSUE THREAD

**Issue by ianthedev** [dimsemenov/PhotoSwipe#1723]
Precisely, I need to overlay the caption element on the images (at the bottom of each image) and the caption element also needs to have linear gradient background color.

I think there should be a `div` wrapping the image and is relatively positioned in CSS so that the caption inside can be absolutely positioned at its bottom.

**Comment by apriljunge** [comment]
Hi @ianthedev. There is already an option to provide captions for each image. Have a look at the "All controls" example on https://photoswipe.com/
