### ISSUE TITLE
Library seems stale. No updates in more than a year.

### ISSUE THREAD

**Issue by GoudekettingRM** [dimsemenov/PhotoSwipe#1731]
Is this library still actively maintained? It looks like it has not been updated/maintained for a while and also no issues or PR are being looked at.

**Comment by andi34** [comment]
I noticed the same and added a lot of the open PRs to [my fork of PhotoSwipe](https://github.com/andi34/PhotoSwipe) - i am currently also not that active on the fork, but I am using it on a Photobooth project especially for the Raspberry Pi I am working on.

**Comment by apriljunge** [comment]
Hi @dimsemenov, are there any plans to maintain this really great lib (still the best image gallery ever)? :)

**Comment by dimsemenov** [comment]
Posted an update - https://github.com/dimsemenov/PhotoSwipe/issues/1749
