### ISSUE TITLE
jQuery.fn.load() is deprecated

### ISSUE THREAD

**Issue by patrick-abc** [dimsemenov/PhotoSwipe#1734]
It seems that you use the deprecated function jQuery.fn.load which in jQuery 3.0 was not yet available.
I think you have to use the .on('load',function()...
Also see here: https://api.jquery.com/load-event/

**Comment by apriljunge** [comment]
This function is pretty sure not used in the current PhotoSwipe version as PhotoSwipe does not use jQuery at all

**Comment by patrick-abc** [comment]
You are right. Shame on me, it's in my implementation where I use the Photoswipe Plugin.
