### ISSUE TITLE
Is it possible to start the gallery zoomed in?

### ISSUE THREAD

**Issue by Verhoeckx** [dimsemenov/PhotoSwipe#1736]
Hello PhotoSwipe developers,

Is it possible tot start the gallery zoomed in?
Or in other words: zoomed in at 100%?

I couldn't find any information about this.

Regards,

Verhoeckx

**Comment by apriljunge** [comment]
Hi @Verhoeckx , have you seen `pswp.zoomTo(destZoomLevel, centerPoint, speed, easingFn, updateFn);` in the [API documentation](https://photoswipe.com/documentation/api.html)? You can programatically zoom on startup. I think it will solve your usecase.

**Comment by Verhoeckx** [comment]
Hello @apriljunge ,

I tried as you suggested but what I notice, is that it's only zoomed at the first image but when you go to the second image, the original zoom level ('fit image in viewport') is restored. I also noticed that despite being zoomed in at startup, the zoom in cursor/button (+) is shown while that's not possible anymore.  It should show a zoom out cursor/button (-) instead.

**This is the code that I used**
```
gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options);
gallery.init();
galler.zoomTo(1);
gallery.options.escKey = true;
```

I think I will keep the default settings because that works better. 

Thanks for thinking along!!

**Comment by Verhoeckx** [comment]
Ideally the settings would be like this (IMHO):

If the width of the image is less than the wide of the screen: show image at 100%.
If the width of the image is larger than the wide of the screen: zoom out of the image until it fits.

**Comment by Verhoeckx** [comment]
Is there a solution to the problems mentioned in above comments?
If not, I think this issue can be closed.

**Comment by dimsemenov** [comment]
This is now possible in v5:

- https://github.com/dimsemenov/PhotoSwipe/issues/1749
- https://photoswipe.com/v5/docs/adjusting-zoom-level/
