### ISSUE TITLE
afterClose event?

### ISSUE THREAD

**Issue by ianthedev** [dimsemenov/PhotoSwipe#1737]
I would like to do something when a gallery finishes closing. An `afterClose` event would be helpful. Thanks.

**Comment by apriljunge** [comment]
Hi @ianthedev. Have you tried `pswp.listen('close', function() { });` or `pswp.listen('destroy', function() { });` from the [API documentation](https://photoswipe.com/documentation/api.html)?

**Comment by ianthedev** [comment]
Hi @apriljunge I had tried it. The `close` event launches when the closing animation starts rather than when the closing animation finishes.

**Comment by apriljunge** [comment]
Yep. You're right. There's no event fired after the instance and animations are completly destroyed

**Comment by ianthedev** [comment]
I see. Thanks for explaining.
