### ISSUE TITLE
Enable image viewer long-press context menu on iOS Safari 

### ISSUE THREAD

**Issue by jkgeyti** [dimsemenov/PhotoSwipe#1748]
On desktop browsers, you can right click images to get a context menu that includes a "Copy image" context menu, but on iOS Safari, long-clicking to show the long-press context menu is disabled because `-webkit-touch-callout: none` is set.

As a quick hack, adding the following css and long-clicking images produces the context menu shown in the screenshot below. I'm not sure if there's any good justification for disabling the context menu on mobile devices, but if not, it'd be really convenient if it could be enabled 🙏 . There's an old ticket from 2011 that makes a similar request, but touch events didn't seem to be broken by re-enabling long-click support, so maybe things have improved since then, and the feature can be reconsidered?

```
.pswp__img {
    -webkit-touch-callout: default !important;
}
```

<img src="https://user-images.githubusercontent.com/617033/116137732-d100e200-a6cb-11eb-89be-b1b6a094ae41.png" width="250" />

Related:
https://github.com/dimsemenov/PhotoSwipe/issues/99
https://github.com/photoprism/photoprism/issues/1233

**Comment by dimsemenov** [comment]
It should be fixed in v5 version, please test and report back if you'll have a minute. https://github.com/dimsemenov/PhotoSwipe/issues/1749

**Comment by jkgeyti** [comment]
I can confirm that long-pressing works in iOS Safari on the sample galleries at https://photoswipe.com/v5/docs/getting-started :tada: 

Closing issue and eagerly awaiting a release :+1:
