### ISSUE TITLE
The code after build has errors.

### ISSUE THREAD

**Issue by zsdycs** [dimsemenov/PhotoSwipe#1754]
An anonymous function expression is used as the global variable "supportsImageDecode" of "util.js", and will appear in "photoswipe-lightbox.esm.js" in an error form after the build. 

https://github.com/dimsemenov/PhotoSwipe/blob/4bf028196a59f80eac0eeb8b135826e9543d7d75/src/js/util/util.js#L123

![image](https://user-images.githubusercontent.com/44798353/120770782-15945e80-c551-11eb-9b5a-e33e8d0bbf43.png)

I can't understand this question. I think this is a "rollup" error, but I think this way of writing is not standardized.

**Comment by dimsemenov** [comment]
Thanks, it seems like a transpiler issue. 

`util.js` is used both by core `photoswipe.js` and by `photoswipe-lightbox-.js`.

Your pull request will break `isImageDecoded` and `decodeImage` functions https://github.com/dimsemenov/PhotoSwipe/blob/4bf028196a59f80eac0eeb8b135826e9543d7d75/dist/photoswipe.esm.js#L127-L150 

Also, I want the `decode` support detection to happen only once, and not for each image individually.

**Comment by zsdycs** [comment]
> Also, I want the support detection to happen only once, and not for each image individually.

How about using the prototype chain?

For example:

```javascript
Image.prototype.hasDecode = ('decode' in new Image())
```

**Comment by zsdycs** [comment]
> I want the support detection to happen only once, and not for each image individually.

I see.
