### ISSUE TITLE
v5-beta - Responsive images with srcset : sizes not updated with zoom gesture

### ISSUE THREAD

**Issue by BilouMaster** [dimsemenov/PhotoSwipe#1761]
While zooming with the fingers on the mobile phone, the `sizes` parameter of the `pswp__img` is never updated so the right image resolution cannot be loaded : `sizes` parameter is updated with the Zoom-in button / double-tap action only.

**Comment by BilouMaster** [comment]
I tried to fix it with PR #1762

**Comment by dimsemenov** [comment]
Thanks, https://github.com/dimsemenov/PhotoSwipe/commit/eadfb7f1fd7b16eaf932dfeea9e3b017485ac1f7 should fix it.

**Comment by BilouMaster** [comment]
Working! ✅ 👍
