### ISSUE TITLE
v5-Beta Errors reproducing the demo example

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1770]
I try on my Windows 10 PC to reproduce the demo example with the next code:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
    </head>
    <body>
        <div class="pswp-gallery pswp-gallery--single-column" id="gallery--simple">
            <a href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/2/img-2500.jpg" data-pswp-width="1669" data-pswp-height="2500" target="_blank">
             <img src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/2/img-200.jpg" alt="" /> 
            </a>

        
        <a href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/7/img-2500.jpg" data-pswp-width="1875" data-pswp-height="2500" data-cropped="true" target="_blank">
            <img src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/7/img-200.jpg" alt="" /> Cropped
        </a>

        
        <a href="https://unsplash.com" data-pswp-src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/3/img-2500.jpg" data-pswp-width="2500" data-pswp-height="1666" target="_blank">
            <img src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/3/img-200.jpg" alt="" />
        </a>

        
        <a href="http://example.com" data-pswp-src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/5/img-2500.jpg" data-pswp-width="2500" data-pswp-height="1668" target="_blank">
          No thumbnail
        </a>

        
        <div>
            <a href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/6/img-2500.jpg" data-pswp-width="2500" data-pswp-height="1667" target="_blank">
                <img src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/6/img-200.jpg" alt="" />
            </a>
        </div>
    </div>
	<script type="module">
        import PhotoSwipeLightbox from '../PhotoSwipe-5-beta/dist/photoswipe-lightbox.esm.js'; 
		const options = { 
		  gallerySelector: '#gallery--simple', 
		  childSelector: 'a', 
		  pswpModule: '../PhotoSwipe-5-beta/dist/photoswipe.esm.js', 
		  pswpCSS: '../PhotoSwipe-5-beta/dist/photoswipe.css'
        }; 
		const lightbox = new PhotoSwipeLightbox(options); 
		lightbox.init();
    </script>
</body>
</html>`

However if I click on a thumbnail in my webpage https://www.andrewolff.nl/Test_Photopswipe_V5/T1/index.html and next click F12 I see next errors:
photoswipe-lightbox.esm.js:230 GET https://www.andrewolff.nl/Test_Photopswipe_V5/PhotoSwipe-5-beta/PhotoSwipe-5-beta/dist/photoswipe.esm.js net::ERR_ABORTED 404
dynamicImportModule @ photoswipe-lightbox.esm.js:230
preload @ photoswipe-lightbox.esm.js:628
loadAndOpen @ photoswipe-lightbox.esm.js:611
onThumbnailsClick @ photoswipe-lightbox.esm.js:557
index.html:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://www.andrewolff.nl/Test_Photopswipe_V5/PhotoSwipe-5-beta/PhotoSwipe-5-beta/dist/photoswipe.esm.js
Promise.then (async)
preload @ photoswipe-lightbox.esm.js:660
loadAndOpen @ photoswipe-lightbox.esm.js:611
onThumbnailsClick @ photoswipe-lightbox.esm.js:557

What do I wrongly?

BTW:
My index.html file is in folder 
I:\Users\Andre\Documents\Mijn websites\andrewolff.nl\Test_Photopswipe_V5\T1

and file photoswipe.esm.js  is in folder:
I:\Users\Andre\Documents\Mijn websites\andrewolff.nl\Test_Photopswipe_V5\PhotoSwipe-5-beta\dist

So why is the code looking on the server for:
https://www.andrewolff.nl/Test_Photopswipe_V5/PhotoSwipe-5-beta/PhotoSwipe-5-beta/dist/photoswipe.esm.js  
while the code is in
https://www.andrewolff.nl/Test_Photopswipe_V5/PhotoSwipe-5-beta/dist/photoswipe.esm.js ??

**Comment by BilouMaster** [comment]
```javascript
 		  pswpModule: '../PhotoSwipe-5-beta/dist/photoswipe.esm.js', 
 		  pswpCSS: '../PhotoSwipe-5-beta/dist/photoswipe.css'
```

If your html file is in `/dist/` then you should just do :

```javascript
 		  pswpModule: 'photoswipe.esm.js', 
 		  pswpCSS: 'photoswipe.css'
```

Mind the way local paths are evaluated

**Comment by acwolff** [comment]
> ```js
>  		  pswpModule: '../PhotoSwipe-5-beta/dist/photoswipe.esm.js', 
>  		  pswpCSS: '../PhotoSwipe-5-beta/dist/photoswipe.css'
> 
I use that code!
And my index.html file is not in  /dist/.

**Comment by acwolff** [comment]
This code works:
    	<script type="module">
    		import PhotoSwipeLightbox from '../PhotoSwipe-5-beta/dist/photoswipe-lightbox.esm.js';
		const options = { 
		  gallerySelector: '#gallery--simple', 
		  childSelector: 'a', 
		  pswpModule: './photoswipe.esm.js', 
		  pswpCSS: './photoswipe.css'
        }; 
		const lightbox = new PhotoSwipeLightbox(options); 
		lightbox.init();
    </script>`

**Comment by BilouMaster** [comment]
A good practice (shown in the documentation) would be to  put the resources like PhotoSwipe in a root folder like:

`/pswp/`, `/src/pswp/`, `/lib/pswp/` or `/dist/pswp/`

And then make : 
```javascript
import PhotoSwipeLightbox from '/pswp/photoswipe-lightbox.esm.js';
const options = {
  pswpModule: '/pswp/photoswipe.esm.js',
  pswpCSS: '/pswp/photoswipe.css',
  (...)
};
```

If your website is "www.example.com", then it will search pswp in "www.example.com/pswp/" in all cases.

Using `/foo/` instead of `./foo/` nor `../foo/`, your path will no longer be relative, this way you can point the same folder for multiple gallery in different location in the tree of your website.

I do the same for quite everything, common css, images, etc.

To test it without uploading on your ftp, you must run a local server, if you just open your html file in navigator instead of using localhost it will not resolve the global paths like `/pswp/'.

For example I am using python to run my local server with the command line `python -m http.server`, you have the equivalent in other languages like node.js.

**Comment by acwolff** [comment]
> To test it without uploading on your ftp, you must run a local server, if you just open your html file in navigator instead of using localhost it will not resolve the global paths like `/pswp/'.

@BilouMaster  Thanks for your hints!

However if I use VSCODE and run it locally with the Go Live extension on a local server http://127.0.0.1:5500/T1/index.html I get still errors, see above.

**Comment by BilouMaster** [comment]
Be sure you run the local server in the root folder of your website...

For the type MIME error, this one could be an issue with pswp indeed, You can disable strict MIME checking with Go Live.
I haven't ran into this kind of error,.. What do you think, @dimsemenov ?

**Comment by acwolff** [comment]
Well my goal is to update the [jAlbum Photoswipe skin](https://jalbum.net/nl/skins/skin/PhotoSwipe) to version 5.
If the index.html file is in a folder \Album, the resources, so also the Photoswipe js and css files,  are in a directory \Album\res, the thumbs are in a folder   \Album\thumbs and the large images are in in a folder  \Album\slides. So if that is not possible with version V5, I can't update my skin.

**Comment by dimsemenov** [comment]
I'm not sure how jAlbum works, but if you want to include JS file locally, you'd need to convert ES6 module to ES5.

For example, you may use code:

```js
import PhotoSwipeLightbox from 'photoswipe/dist/photoswipe-lightbox.esm.js';
import PhotoSwipe from 'photoswipe/dist/photoswipe.esm.js';

const options = {
  gallerySelector: '#gallery--simple',
  childSelector: 'a',
  pswpModule: PhotoSwipe
};
const lightbox = new PhotoSwipeLightbox(options);
lightbox.init();
```

and run it through Babel to convert to es5.

CSS file can be just included via style tag.

**Comment by acwolff** [comment]
Thanks  @dimsemenov I will try this later, except the use of Babel, because that is never used by me. I hope I can test without that program.

But many times I get this message:
_favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)_

I have no idea why I get this, I don't use a favicon.ico:, so it must come from a Photoswipe file.

**Comment by dimsemenov** [comment]
Well, photoswipe doesn't change or include favicon, nor its demo site.

`favicon.ico` can be automatically fetched by the browser, if it's not defined in `<head>`.

**Comment by acwolff** [comment]
OK thanks for the info.

I am glad that I have found code which works with my folder configuration:

    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
    <link href="res/photoswipe.css" rel="stylesheet">
    </head>

    <body>
        <div class="pswp-gallery pswp-gallery--single-column" id="gallery--simple">
            <a href="slides/Vecht_121027_1205-2_130930_1334.jpg" data-pswp-width="1466" data-pswp-height="1080" target="_blank">
                <img src="thumbs/Vecht_121027_1205-2_130930_1334.jpg" width="217" height="160" alt="" title="" />
            </a>
        <a href="slides/Vecht_121027_1205-2_130930_1335.jpg" data-pswp-width="1043" data-pswp-height="1080" data-cropped="true" target="_blank">
            <img src="thumbs/Vecht_121027_1205-2_130930_1335.jpg" width="154" height="160" alt="" title="" />
        </a>
    </div>
    <script type="module">
        import PhotoSwipeLightbox from './res/photoswipe-lightbox.esm.js'; 
        const options = { 
            gallerySelector: '#gallery--simple', 
            childSelector: 'a', 
            pswpModule: './photoswipe.esm.js' 
        }; 
        const lightbox = new PhotoSwipeLightbox(options); 
        lightbox.init();
    </script>
</body>

</html>`

See the result: https://www.andrewolff.nl/Test_Photopswipe_V5/T1-res-localimages/
