### ISSUE TITLE
React in v5

### ISSUE THREAD

**Issue by jodik** [dimsemenov/PhotoSwipe#1771]
Hi,

Is there a way how to run v5 with React?

Thanks.

**Comment by jodik** [comment]
Or is there any downside to importing photoswipe directly in "public/index.html"?

**Comment by dimsemenov** [comment]
For now, you may import it like this https://github.com/dimsemenov/PhotoSwipe/pull/1764#issuecomment-867453153

Likely, there will be a more detailed guide on how to use v5 with React when it'll be released.

**Comment by irudoy** [comment]
Updated [react-photoswipe-gallery](https://github.com/dromru/react-photoswipe-gallery/tree/photoswipe-v5) wrapper to support PhotoSwipe v5. You can give it a try using `next` tag, as described [here](https://github.com/dromru/react-photoswipe-gallery/tree/photoswipe-v5#installation). Still in the alpha stage and not finished yet, but it [works pretty good](https://dromru.github.io/react-photoswipe-gallery/photoswipe-v5/).

**Comment by dimsemenov** [comment]
@irudoy thank you, it looks great!

**Comment by jodik** [comment]
@irudoy Thanks a lot!

**Comment by irudoy** [comment]
Just released [react-photoswipe-gallery v2](https://github.com/dromru/react-photoswipe-gallery) with full PhotoSwipe v5 support 🚀

It has opt-in hash navigation and captions, and it supports all of the new options. The documentation with examples also improved a lot.

**Comment by dimsemenov** [comment]
@irudoy thanks, linked it in docs https://photoswipe.com/react-image-gallery/

**Comment by irudoy** [comment]
@dimsemenov thanks!
