### ISSUE TITLE
V5-Beta Caption example simplified

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1774]
@dimsemenov   I tried to use your [Caption example](https://photoswipe.com/v5/docs/caption/), but the link in a caption was not working for me. So I tried to use a data-caption attribute for the caption:

    <div id="gallery" class="thumbs-jg thumbsgallery" >

    <a  href="slides/Vecht_121027_1205-2_130930_1334.jpg" data-pswp-width="1920" data-pswp-height="1414" id="0" 
    data-caption= 'Herfst, dus veel  paddestoelen! Dit is de <a href="https://nl.wikipedia.org/wiki/Gewone_zwavelkop " target="_blank">Gewone zwavelkop</a>'>
    <img src="thumbs/Vecht_121027_1205-2_130930_1334.jpg"  width="108" height="80"  />
    </a>

I adapted your code as follows:

    lightbox.on('uiRegister', function() {
        lightbox.pswp.ui.registerElement({
          name: 'custom-caption',
          order: 9,
          isButton: false,
          appendTo: 'root',
          html: 'Caption text',
          onInit: (el, pswp) => {
            lightbox.pswp.on('change', () => {
              const currSlideElement = lightbox.pswp.currSlide.data.element;
              let captionHTML = '';
              if (currSlideElement) {
                  captionHTML = currSlideElement.dataset.caption;
              }
              el.innerHTML = captionHTML || '';
            });
          }
          });
        });

Now my link in a caption works as you can see in [this test album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/).

What do you think about this implementation?

**Comment by dimsemenov** [comment]
Pretty sure HTML tags aren't valid within `alt` attribute, unlike `data-` attribute, that's why it works.

Your example is fine, but don't forget to add `alt` attribute to your thumbnail for accessibility.

Example in docs has alternative version of markup:

```html
<div class="pswp-gallery__item">
    <a  
      href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/2/img-2500.jpg" 
      data-pswp-width="1669" 
      data-pswp-height="2500" 
      target="_blank">
      <img src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/2/img-200.jpg" alt="Caption 1" />
    </a>
    <div class="hidden-caption-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="https://example.com" target="_blank" rel="nofollow">Test link &rarr;</a></div>
  </div>
```

(which uses element `hidden-caption-content`)

**Comment by acwolff** [comment]
> Your example is fine, but don't forget to add `alt` attribute to your thumbnail for accessibility.

Yes, I left it away in this code to keep it short, but in the album I use both an alt and title attribute. You can see thar by hovering over the first thumb.

A related question, why argument   target="_blank"? Is is allowed to remove that?

**Comment by BilouMaster** [comment]
> A related question, why argument   target="_blank"? Is is allowed to remove that?

I think it's just in case you want that the link opens in new English, if you want it to open in the current tab you remove it ...

**Comment by acwolff** [comment]
Thanks @BilouMaster, I have a single html5 album, so I will remove it.

**Comment by acwolff** [comment]
You can also diplay the caption at the top of the page, see [this test album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5-FSI/).

To implement this, remove the line 'appendTo: 'root',' statement and use this CSS code:


    .pswp__custom-caption {
      background-color: rgba(51,51,51,0.6);
      color: #ffffff;
      padding: 2px 8px;
      border-radius: 4px;
      position: absolute;
      top: 0px;
      left: 50%;
      transform: translateX(-50%);
    }

Most of this CSS code comes from the [Caption doc section](https://photoswipe.com/v5/docs/caption/).

I have no idea what the effect should be of  the ' transform: translateX(-50%);' statement, I see no animation effect.

@dimsemenov  could you please explain why you added this line?
