### ISSUE TITLE
v5-Beta How to hide and show the lightbox  container?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1775]
I try to update the [jAlbum Photoswipe skin](https://jalbum.net/en/skins/skin/PhotoSwipe) to version 5.

I use currently this code:

    <script type="module">
    	import PhotoSwipeLightbox from './res/photoswipe-lightbox.esm.js';
    	const options = {
    	  gallerySelector: '#gallery',
    	  childSelector: 'a',
     	  pswpModule: './photoswipe.esm.js'
     	};
	const lightbox = new PhotoSwipeLightbox(options);
    lightbox.on('uiRegister', function() {
        lightbox.pswp.ui.registerElement({
          name: 'custom-caption',
          order: 9,
          isButton: false,
          appendTo: 'root',
          html: 'Caption text',
          onInit: (el, pswp) => {
            lightbox.pswp.on('change', () => {
              const currSlideElement = lightbox.pswp.currSlide.data.element;
              let captionHTML = '';
              if (currSlideElement) {
                  captionHTML = currSlideElement.dataset.caption;
              }
              el.innerHTML = captionHTML || '';
            });
          }
        });
        lightbox.pswp.ui.registerElement({
          name: 'locationButton',
          order: 12,
          isButton: true,
                              html: {
              isCustomSVG: true,
              inner: '<path d="m 8.4067795,3.2881351 c -4.4179997,0 -7.99999981,3.582 -7.99999981,7.9999999 0,4.417999 3.58200011,8.000001 7.99999981,8.000001 4.4179995,0 7.9999995,-3.582002 7.9999995,-8.000001 0,-4.4179999 -3.582,-7.9999999 -7.9999995,-7.9999999 z m 0.666667,10.7046659 v -2.037998 h 1.9959995 c -0.03933,0.761998 -0.141334,1.493332 -0.304,2.185998 -0.548666,-0.08 -1.1159996,-0.125332 -1.6919995,-0.148 z m 1.3046675,1.441332 c -0.332668,0.886669 -0.7726676,1.664671 -1.3046675,2.304001 v -2.413333 c 0.444,0.01868 0.8793327,0.05401 1.3046675,0.109332 z M 9.0734465,10.621467 V 8.6114681 c 0.5786669,-0.02267 1.1473335,-0.06867 1.6986655,-0.149333 0.158667,0.684667 0.259334,1.407333 0.297334,2.1593319 z m 0,-3.3426649 V 4.8381352 c 0.5373329,0.646 0.9806665,1.433333 1.3140005,2.3306669 -0.4280008,0.056 -0.8666675,0.09133 -1.3140005,0.11 z M 10.875446,5.1008022 c 0.824666,0.330666 1.569333,0.818666 2.193333,1.4306659 -0.428,0.156 -0.874,0.294667 -1.346,0.404667 C 11.493446,6.2748022 11.206112,5.6628022 10.875446,5.1008022 Z M 6.0481135,14.140801 c -0.162667,-0.692666 -0.2653337,-1.424 -0.3040004,-2.185998 h 1.9960004 v 2.037998 c -0.576667,0.02266 -1.142667,0.068 -1.692,0.148 z m 1.692,1.184 v 2.413333 c -0.532,-0.63933 -0.972,-1.417332 -1.304667,-2.304001 0.425333,-0.05533 0.860667,-0.09066 1.304667,-0.109332 z M 5.7441131,10.621467 c 0.038,-0.7519989 0.138,-1.4746649 0.2973334,-2.1593319 0.551333,0.08067 1.12,0.126667 1.698667,0.149333 V 10.621467 Z M 6.4267795,7.1688021 c 0.333334,-0.8973339 0.776667,-1.6846669 1.313334,-2.3306669 v 2.4406669 c -0.447334,-0.01867 -0.886,-0.054 -1.313334,-0.11 z M 5.0901131,6.9354681 c -0.472,-0.11 -0.918,-0.248666 -1.3453333,-0.404666 C 4.3694465,5.9188022 5.1134465,5.4308022 5.9381135,5.1001352 5.6074465,5.6628022 5.3201131,6.2748022 5.0901131,6.9354681 Z m -0.366,1.278667 c -0.176,0.767333 -0.2893333,1.573333 -0.328,2.4073319 h -2.622 c 0.11,-1.1053319 0.4926667,-2.1313319 1.078,-3.0119989 0.5866667,0.240667 1.2106667,0.446667 1.872,0.604667 z m 0.006,6.1746659 c -0.6586666,0.157332 -1.28,0.361332 -1.8646666,0.6 C 2.2721131,14.103469 1.8847798,13.069467 1.7741131,11.954803 h 2.6226667 c 0.038667,0.84333 0.154,1.658664 0.3333333,2.433998 z m 0.3686667,1.278003 c 0.228,0.650664 0.512,1.253998 0.8379997,1.808 -0.815333,-0.326668 -1.5506664,-0.807334 -2.1706664,-1.410002 0.424,-0.152666 0.866,-0.289998 1.3326667,-0.397998 z m 6.6159992,0 c 0.466667,0.108666 0.908,0.244666 1.332667,0.397998 -0.620667,0.602002 -1.356,1.083334 -2.171334,1.410668 0.326,-0.554668 0.61,-1.158002 0.838667,-1.808666 z m 0.368667,-1.278003 c 0.18,-0.775334 0.294666,-1.590668 0.334,-2.433998 h 2.622666 c -0.111333,1.114664 -0.498666,2.148666 -1.092,3.033998 -0.584666,-0.238668 -1.206666,-0.442668 -1.864666,-0.6 z m 0.334,-3.767334 c -0.03867,-0.8339989 -0.152667,-1.6399989 -0.328,-2.4073319 0.661333,-0.158 1.286,-0.364 1.872666,-0.604667 0.584667,0.880667 0.967334,1.906667 1.077334,3.0119989 z"/>'
          + '<path fill="currentColor" class="pswp__location-icon" d="M13 12h2v6h-2z"/>',
              outlineID: 'pswp__location-icon'
          },
          title: 'Show location',
          onClick: (event, el) => {
            slide_index=lightbox.pswp.currSlide.index;
            showLocation();
          }
        });
    });
    lightbox.init();
    </script>`

In the last section I try to show the photo location in Google Maps as I do in the current released version, see [this test page](https://andrewolff.jalbum.net/PS_JustifiedGallery_white/#&gid=1&pid=1). If you click on the Globe button, the  lightbox closed and a GoogleMaps window is displayed. If you close the Google Maps window, the  lightbox is again opened.

As a first test I implemented as text button, see [my V5 test album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/). After the Location button is clicked, the next functions in file indexPage.js are called:

    function showLocation() {
        alert("showLocation for slide: " + slide_index);
        if (typeof(gMap) != "undefined") {
            if (gMap[slide_index].length > 0) {
                if ((!apiKeyExists) || showLocationNewTab) {
                    window.open('https://maps.google.com/?q=' + gMap[slide_index]);
                } else {
                    OpenMapDiv(gMap[slide_index]);  // Here we should swap windows
                }
            }
        }
    }

    function OpenMapDiv(latlngStr) {
        lightbox.pswp.close();  // How to hide or close the  lightbox?
        ShowMapDiv();
        latlngStr = latlngStr.split(',', 2);
        latlng = { lat: parseFloat(latlngStr[0]), lng: parseFloat(latlngStr[1]) };
        if (useGeocodingAPI) {
            initMapGeocodinAPI();
        } else initMap();
    }

    function closeMap() {
        $('#mapDiv').hide();
        $('#indexDiv').show();
        mapShown = false;
        if (LocationsGM) { LocationsGM = false } else {
          lightbox.pswp.open();  // How to show or open the  lightbox at the current slide?
        }
    }

In guessed something, see the lines with the "// How to" comment, but that did not work.

So please help me and show me the code I should use instead.

In a next phase I have to replace trhe location text button by [this google-maps.svg icon](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/res/google-maps.svg), a hint how to do that is appreciated!

Thanks in advance!

Update: I implemented a first version of an location icon.
What should a change to improve the vertical alignment with the other buttons?

**Comment by dimsemenov** [comment]
>  How to hide and show the lightbox container?

You may hide the root element of PhotoSwipe via CSS (`.pswp [ visibility:hidden }`). Or close it via API. Or overlap the map on top of gallery. Up to you.

> What should a change to improve the vertical alignment with the other buttons?

svg viewbox of default icons is 32x32px, size if icon itself is 16x16px (which is centered within the viewbox).

**Comment by acwolff** [comment]
@dimsemenov thanks for your hints!
I created 2 simple functions to hide and show the lightbox:

    function pswpHide() {
    var x = document.querySelector('.pswp');
        x.style.display = "none";
    }
    function pswpShow() {
    var x = document.querySelector('.pswp');
    if (x.style.display === "none") {
        x.style.display = "block";
        }
    }
and I added the location button with this code:

        lightbox.pswp.ui.registerElement({
          name: 'locationButton',
          order: 8,
          isButton: true,
          html: {
              isCustomSVG: true,
              inner: '<path d="M16 8c-4.413 0-8 3.587-8 8s3.587 8 8 8 8-3.587 8-8-3.587-8-8-8zm5.949 11.785c-.805-.383-1.816-.675-2.951-.86.125-.774.197-1.6.215-2.452h3.823a7.006 7.006 0 01-1.088 3.312zM16 22.839c-.507 0-1.067-.684-1.497-1.837a10.295 10.295 0 01-.379-1.268A18.935 18.935 0 0116 19.637c.641 0 1.273.035 1.875.095a10.295 10.295 0 01-.378 1.269c-.43 1.153-.99 1.837-1.497 1.837zm0-4.146c-.71 0-1.398.034-2.06.107a17.21 17.21 0 01-.206-2.327h4.532a17.935 17.935 0 01-.206 2.327 19.936 19.936 0 00-2.06-.108zm-7.037-2.22h3.824c.021.852.095 1.677.215 2.451-1.14.185-2.15.478-2.95.86a7.006 7.006 0 01-1.088-3.311zm1.089-4.258c.804.383 1.815.675 2.95.86a17.75 17.75 0 00-.215 2.452H8.963a7.006 7.006 0 011.089-3.312zM16 9.162c.507 0 1.067.683 1.497 1.836.146.387.27.813.379 1.269a18.935 18.935 0 01-1.876.095 18.935 18.935 0 01-1.875-.095 10.295 10.295 0 01.378-1.269c.43-1.153.99-1.836 1.497-1.836zm0 4.145c.71 0 1.398-.034 2.06-.107a17.21 17.21 0 01.206 2.327h-4.533a17.935 17.935 0 01.207-2.327c.662.069 1.35.107 2.06.107zm3.213 2.22a19.182 19.182 0 00-.215-2.451c1.14-.185 2.15-.478 2.95-.86a7.006 7.006 0 011.089 3.311zm2.159-4.09c-.696.305-1.574.546-2.555.705a11.586 11.586 0 00-.434-1.48c-.237-.632-.517-1.148-.822-1.543a7.068 7.068 0 013.811 2.318zm-6.934-2.315c-.309.396-.585.912-.821 1.544a11.586 11.586 0 00-.434 1.48c-.981-.16-1.859-.4-2.555-.706a7.017 7.017 0 013.81-2.318zm-3.81 11.442c.697-.305 1.574-.547 2.555-.705.12.532.267 1.027.434 1.478.237.633.516 1.149.821 1.544a7.068 7.068 0 01-3.81-2.318zm6.934 2.314c.309-.396.585-.912.821-1.544.168-.452.314-.947.434-1.48.981.159 1.859.4 2.555.705a7.017 7.017 0 01-3.81 2.318z" id="pswp__location-icon" />'
          + '<path fill="currentColor" class="pswp__location-icon" />',
              outlineID: 'pswp__location-icon'
          },
          title: 'Show location',
          onClick: (event, el) => {
            slide_index=lightbox.pswp.currSlide.index;
            showLocation();
          }
        });

You see the result  [here](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/0. Click on the first thumbnail to see the location button. It is a 16x16 button in a 32x32 viwbox, but to get it properly aligned I had to add this css code:

button.pswp__button--locationButton {
     padding-top:4px;
}

For the GPS location function I have to add one final function: if the images does not have GPS coordinates, the location button should be hidden.
In your previous function I did this in the 'afterChange 'event:

	pswp.listen('afterChange', function() { 
		slide_index = pswp.getCurrentIndex();
		if (typeof(pswp.currItem.gps) == "undefined"){ gpsLocation = ""; 
		if (showLocationButton)  $('#gmaps').hide();}


How do I get this event in vesion 5?

I tried this, without succes:

    lightbox.init();
    lightbox.on('afterChange', function() {
        alert("afterChange");
    });

**Comment by krestaino** [comment]
> You may hide the root element of PhotoSwipe via CSS (`.pswp [ visibility:hidden }`). Or close it via API. Or overlap the map on top of gallery. Up to you.

What is the method to close the lightbox?
