### ISSUE TITLE
v5-Beta How to open the lightbox in my own js code?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1776]
Sorry for this stupid question, but I  am not a professional js programmer and I  have no experience at all in ES6 modules!

I can't find how to open the PhotoSwipe 5 lightbox in my own old version 4 ndexSlide.js  file with the program structure I discussed [here](https://github.com/dimsemenov/PhotoSwipe/issues/1775).

I you click on one of the thumbnails in [my test gallery](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/) the lightbox opens automatically, but sometimes I have to open the  lightbox  in one of the functions in  a separated  js file.  

How can I do that?

**Comment by dimsemenov** [comment]
You can trigger click on a link that should open a lightbox, for example `document.querySelector('#gallery a').click()`.

Or you can assign to global variable, with something like `window.myLightbox = new PhotoSwipeLightbox(...`, and then access it anywhere via `window.myLightbox`.

**Comment by acwolff** [comment]
@dimsemenov thanks for your fast response!

I use now this function:

    function openLightbox(slideNr) {
        var x = document.querySelectorAll("#gallery a");
        x[slideNr].click();
    }
