### ISSUE TITLE
How can I remove the zoom button?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1785]
I like to remove completely the zoom button.

I tried option   zoomSVG:'',  but that removes only the icon, but I can still zoom by clicking the background area of the zoom button,

I tried Ilko this code in the change event:

    const z = document.querySelector('#pswp__icn-zoom'); 
    z.style.display = "none"; 

but this gives the same effect: No icon, but still a click-able background area.

Is there a simple method to remove the icon and the icon background area?

**Comment by acwolff** [comment]
Sorry I used the wrong selection, this works:

    const z = document.querySelector('.pswp__button--zoom');
    z.style.display = "none";

**Comment by BilouMaster** [comment]
You can just add `zoom: false` in the options of the lightbox.

**Comment by acwolff** [comment]
Yes, that works too and is I think a better solution.

Thanks for your hint!
