### ISSUE TITLE
v5-beta Question: Which Event before or after slide is shown

### ISSUE THREAD

**Issue by marwl** [dimsemenov/PhotoSwipe#1786]
Hi,
I am looking for an event that is activated just before the current slide is shown or after.
(I want to update an indicator and button)
I think I could use itemData, but I think it gets called once for every slide that is preloaded.
What do you think, which event should I use?
Thanks

**Comment by dimsemenov** [comment]
You may use `change` https://github.com/dimsemenov/PhotoSwipe/blob/v5-beta/src/js/main-scroll.js#L254

`itemData` is indeed called when nearby slides are preloaded.

**Comment by marwl** [comment]
Thank you
