### ISSUE TITLE
 v5-beta How to translate UI hints?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1789]
What is the best way to translate the mouse hints   "Previous", "Next", "Close" and "Zoom (z)" etc. into another language?

**Comment by dimsemenov** [comment]
That's something that's not been implemented yet.

I'm not sure what's the best way to do it  - to just add another set of options (like with Counter indicator https://github.com/dimsemenov/PhotoSwipe/blob/v5-beta/src/js/ui/counter-indicator.js), or to do something else.

If s1 wants to do it - feel free to submit a PR.

**Comment by acwolff** [comment]
Well, it are just a few strings, so you can make a simple option for this like:

    translatedText: ‘Vorige’ | ‘Volgende’ | ‘Sluit’ ,

I have no experience with a PR, so I will not submit a PR

**Comment by dimsemenov** [comment]
This should now be fixed by 5.1 - https://photoswipe.com/v5/docs/styling/#adjusting-button-title

Please test when you'll have some time.

Btw, there is a breaking change - dynamic CSS file loading was removed https://photoswipe.com/v5/docs/getting-started/#initialization

**Comment by acwolff** [comment]
I don't think that the translation is correctly working.
I use this code:

	import PhotoSwipeLightbox from './res/photoswipe-lightbox.esm.js';
	const options = {
	  gallerySelector: '#gallery',
	  childSelector: 'a',
	  counter: false,
	  closeTitle: 'Sluit',  // TODO strings from text properties
	  zoomTitle: 'Zoom in / uit',
	  arrowPrevTitle: 'Vorige',
	  arrowNextTitle: 'Volgende',
	  mouseMovePan: true,
	  initialZoomLevel: 'fit',
	  secondaryZoomLevel: 'fill',
	  maxZoomLevel: 1,
 	  pswpModule: './photoswipe.esm.js'
 	};
It is applied in [this album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/), but the close button still shows English text ( I have still to do the translation for the button I added).

I have seen it working a few times, but it looks whether the translations do fall back to the English text after a while.

I use Tippy tooltips for the Titles which are initialized as follows:

    lightbox.on('afterInit', () => {
         const x = document.querySelector('.pswp__container')  // I hope this is the correct place to append to!!
        tippy('[title]', {
            touchHold: true,
            arrow: true,  // false gives problems
            flipBehavior: "flip",
            size: 'large',
            duration: 500,
            theme: 'user',
            animation: 'scale',
            appendTo : x,
   	   zIndex : 99999
        });
    })

But these Tippy hints show always the Englishtext as you can see in [my video test album](https://www.andrewolff.nl/Test_Photopswipe_V5/PhotoSwipe-5-beta/PSP5_video/)

I hope you can find the problem!

**Comment by dimsemenov** [comment]
Nice, thanks for testin'
