### ISSUE TITLE
V5 Beta Dynamic caption plug-in shifts text down

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1793]
If you click on the first thumbnail in [this test album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/) and you make the window smaller, you see that the right side panel text shifts down until it moves to a position below the slide.

The element.style of class  pswp__dynamic-caption show initially top: 0px which is OK, but next the value grows and the caption text shifts down:

![SidePanelShift](https://user-images.githubusercontent.com/8150784/127222513-ee7714f0-e98c-4d66-a2f7-185fdbc8a3d3.png)

Is there a way to prevent this?

This does not help:

    .pswp__dynamic-caption--aside {
      top: 0px;
    }

**Comment by dimsemenov** [comment]
This is controlled by the margin style https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/blob/main/photoswipe-dynamic-caption-plugin.css#L26

Please keep open the issues about the plugin in the corresponding repo if you'll have any in future. (https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/).

**Comment by acwolff** [comment]
> This is controlled by the margin style https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/blob/main/photoswipe-dynamic-caption-plugin.css#L26

So I can't do anything to prvent a shift?

> Please keep open the issues about the plugin in the corresponding repo if you'll have any in future. (https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/).

Sorry, I did not realize that I should use the other repo.

**Comment by dimsemenov** [comment]
> So I can't do anything to prvent a shift?

When the caption is "aside" - it's aligned to the top-right edge of the image, the margin just shifts it down a bit more.
