### ISSUE TITLE
V5 Beta How to change the cursor?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1795]
To make the PC version consistent with the iPad version, I added option

	  imageClickAction: 'toggle-controls',  

But if I move now with the mouse over the slide image, I see a zoom-out cursor.
I like so change that in a pointer cursor.

How can I do that?

I tried this without success:

    .pswp__scroll-wrap {
       cursor: pointer;
    }

**Comment by dimsemenov** [comment]
Cursors are defined just from the stylesheet, you can look up default styles in `photoswipe.css`.

**Comment by acwolff** [comment]
This works:

    .pswp__img {
     	cursor: pointer;
    }
