### ISSUE TITLE
V5 Beta How to call the 'toggle-controls' function from my own code?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1798]
I did implement a slideshow function, see [this album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/).

If I start the slideshow by clicking the play button in the upper right  corner I like too to call the   'toggle-controls' function to hide automatically the buttons.

The slideshow should stop (via a function playpuse) if the user clicks in the image, so I tried this option code:

    imageClickAction: (releasePoint, e) => { if (playing) playpause(); else 'toggle-controls' },  

but of course this is not working.

What should I do to implement the proposed functions?

**Comment by BilouMaster** [comment]
Have you tried something like `lightbox.pswp.toggle-controls()`?

**Comment by acwolff** [comment]
> Have you tried something like `lightbox.pswp.toggle-controls()`?

Yes, but that is no valid function.

**Comment by dimsemenov** [comment]
It's just a class toggle, so you can do `lightbox.pswp.template.classList.toggle('pswp--ui-visible');`

**Comment by acwolff** [comment]
Great!, this option works now:

    imageClickAction: (releasePoint, e) => {  if (playing) playpause(); else pswp.template.classList.toggle('pswp--ui-visible') }, 

To see it working : click on a thumbnail in [this album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/) and next click the play button. The slideshow starts now. To stop it click on the image.

@dimsemenov thanks for your help!
