### ISSUE TITLE
V5 Beta Are the srcsets correctly working?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1799]
I did implement srcset with the next code for the 4th image of [this album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5ss/):

    <a  href="slides/Vecht_121027_1205-2_130930_1334.jpg"
    data-pswp-srcset="slides/Vecht_121027_1205-2_130930_1334-3308w.webp 3308w,slides/Vecht_121027_1205-2_130930_1334.jpg 3308w,slides/Vecht_121027_1205-2_130930_1334-1920w.webp 1920w,slides/Vecht_121027_1205- 2_130930_1334-960w.webp 960w"data-pswp-width="3308" data-pswp-height="2437" id="3"data-caption='Herfst, dus veel  
    paddestoelen!  Dit is de <a href=&quot;https://nl.wikipedia.org/wiki/Gewone_zwavelkop &quot; 
    target=&quot;_blank&quot;>Gewone zwavelkop</a>'>
    <img src="thumbs/Vecht_121027_1205-2_130930_1334.jpg" width="217" height="160" alt="2013-09-30" title="2013-09-30" />
    </a>

The used images contain in the middle a text string indicating the size of the image:
On my 4k 3840x3640 laptop I see there 1920x1414 webp
On my 2560x1440 desktop I see also image 1920x1414 webp
On my iPad pro I see also image 1920x1414 webp
On my iPhone XR I see also image 1920x1414 webp 
On an old 1280x800 Android tablet I see the very first time 960x707 but later also 1920x1414 webp

If I zoom-in on my 4k laptop I get 3308x2437
If I zoom-in on my iPad I get 3308x2437
if I zoom-in on my iPhone and Android tablet  I get 3308x2437

Is this what you expect?
I am surprised about the large images used on the iPhone!

And the loading times are sometimes very long!

**Comment by BilouMaster** [comment]
I think the images should be referenced from smallest to largest, and I'm not sure we can mix the formats. 

srcset works correctly in my (beta album)[http://test.biloumaster.fr/creations/tradi]

**Comment by acwolff** [comment]
> I think the images should be referenced from smallest to largest, and I'm not sure we can mix the formats.

If I do that I get the same results, so it makes no difference.
> 
> srcset seems to work correctly in my [beta album](http://test.biloumaster.fr/creations/tradi)

How did you check that the correct image was loaded?

> You should reach the maximum size while zooming with the fingers on pad/mobile

That is correct, I see in that case image 3308x2437 webp

**Comment by BilouMaster** [comment]
> How did you check that the correct image was loaded?
I just checked on my Android phone, by downloading the image or copying the image url (long pression on the img). By the way I still have to look for a way to prevent downloading if it's possible. 😁

**Comment by acwolff** [comment]
> By the way I still have to look for a way to prevent downloading if it's possible. 😁

I use that in [my album](https://www.andrewolff.nl/Test_Photopswipe_V5/PSP5/) by calling initExtra() in my $(document).ready(function(): 

    function initExtra() {
       $('body').bind('contextmenu', function(e) {
        return false;
      });
    }

**Comment by dimsemenov** [comment]
PhotoSwipe only adjusts `sizes` attribute based on current image width, it does not modify `srcset` attribute in any way (so any valid markup is allowed https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset ).

The code is at https://github.com/dimsemenov/PhotoSwipe/blob/v5-beta/src/js/slide/slide.js#L363

**Comment by acwolff** [comment]
> PhotoSwipe only adjusts `sizes` attribute based on current image width, it does not modify `srcset` attribute in any way (so any valid markup is allowed 

Sorry  @dimsemenov  I don't undestand what you are here saying.

Do my observations about the used images on the variouis devices correspond with what you expect?

And is the sequence of images in the srcset, from large to small, allowed or should that alway be from small to large?
