### ISSUE TITLE
V5-Beta why did loading css using module got removed?

### ISSUE THREAD

**Issue by picarica** [dimsemenov/PhotoSwipe#1800]
so i updated to newest version of photoswipe i was at 5.0.3 version before and my gallery stoppe working chceckout out changes and it seems that loading css and .js files were removed, why is that ? i dont see docs updated it was just remvoed from source code

so now we have to manually load css and .js ? for it to work ?

**Comment by dimsemenov** [comment]
It added unnecessary complexity - browsers don't have a simple API to load CSS dynamically. And the performance impact of CSS file is much less than JS. So it was removed in 5.1.

The documentation should be updated, if you find some page where it isn't - please let me know.

Apologies for the inconvenience, but this might happen during the beta.

**Comment by picarica** [comment]
> It added unnecessary complexity - browsers don't have a simple API to load CSS dynamically. And the performance impact of CSS file is much less than JS. So it was removed in 5.1.
> 
> The documentation should be updated, if you find some page where it isn't - please let me know.
> 
> Apologies for the inconvenience, but this might happen during the beta.

thanks for answering i was just curious why the feature was removed, so thank you for explanation 
i just looked here https://github.com/dimsemenov/PhotoSwipe/issues/1749 and saw linking ot css in main post is still present and thats where i came from, but i just noticed it's been updated also in the new test demo page so that's it
