### ISSUE TITLE
V5-beta: How to prevent that the esc key closes the lightbox?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1804]
I see that pressing the esc key closes the lightbox, this leads to  problems in some of my modal dialogue boxes.
So with which code can  prevent that pressing the esc key closes the lightbox?

Which other fast keys are used in V5-beta?

**Comment by dimsemenov** [comment]
You can look up the source here https://github.com/dimsemenov/PhotoSwipe/blob/v5-beta/src/js/keyboard.js

To disable esc key use option: `escKey: false`.

You may also use PhotoSwipe `keydown` event to override the default behavior.

**Comment by acwolff** [comment]
> You may also use PhotoSwipe `keydown` event to override the default behavior.

I tried this:

    lightbox.on('keydown', (e)  => {
        if (e.which == 27 ) e.preventDefault();
    });

But this does not prevent that the lightbox closes.

What do I wrongly?

**Comment by dimsemenov** [comment]
You're probably looking for `e.keyCode`, not `e.which`.

**Comment by acwolff** [comment]
> You're probably looking for `e.keyCode`, not `e.which`.

No i tried both with the same result

**Comment by dimsemenov** [comment]
If you're accessing PhotoSwipe event, you can reach native keydown via `originalEvent` property, so the code should be:
 
lightbox.on('keydown', (e)  => {
    if (e.originalEvent.keyCode === 27 ) e.preventDefault();
});

I guess it's a bit confusing, I'll update docs.

**Comment by acwolff** [comment]
Yes this works!
I could now prevent that the lightbox was closed with the esc key while a modal window was open:

    lightbox.on('keydown', (e)  => {
      if ((e.originalEvent.keyCode === 27 ) && captionShown) e.preventDefault();
    });

Thank you very much for your help!
