### ISSUE TITLE
v5-beta: Allow passing an Element instead of gallerySelector

### ISSUE THREAD

**Issue by tobyzerner** [dimsemenov/PhotoSwipe#1812]
I already have a reference to the Element I want to use for the gallery, and it would be much easier to be able to just pass this into the lightbox options rather than have to assign it an ID to select.

I think the ideal API for the options would look like this:

```ts
type Options = {
    // If string, convert into a NodeList via document.querySelectorAll
    gallery: string | Element | NodeList | Array;
    children: string | Element | NodeList | Array;
};

// example
new PhotoSwipeLightbox({
    gallery: myGalleryElement,
    children: 'a',
    pswpModule: PhotoSwipe
});
```

I'd be happy to do a PR if this is a change you would welcome.

**Comment by dimsemenov** [comment]
I like this idea, it does make sense.

Maybe the naming of properties `gallery` and `children` can be improved somehow as well.

**Comment by tobyzerner** [comment]
I've just done a PR - #1813. Let me know if you have any other suggestions for the naming and I can update it – as well as the docs.

**Comment by dimsemenov** [comment]
Thank you, I pushed it to 5.1.3. Will update the docs too.
