### ISSUE TITLE
V5 beta Event for next / previous slide

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1818]
I have to stop a video if the user selects another image.
Which event can I use to stop a video before the next image is loaded?

**Comment by dimsemenov** [comment]
There are events `slideActivate` and `slideDeactivate` which might be helpful https://github.com/dimsemenov/PhotoSwipe/blob/afc1683f316107c9d10927e60679934d51fca5b0/src/js/slide/slide.js#L292

**Comment by acwolff** [comment]
Yes with the slideDeactivate event I can stop a video if required.
Thanks for your help.
