### ISSUE TITLE
V5 Beta: How to switch off preloading?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1822]
From the[documentation](https://photoswipe.com/v5/docs/options/) I thougth that I could switch off the preloading with option

	  preload: [0,0], 

but I don't think that switches  off completely the preloading

To see this open [this jukebox sample album](https://andrewolff.jalbum.net/Jukebox_PS/) and click on the second thumbnail.

The captions of these images contains an audio control which starts an mp3 track automatically:

    <a href="slides/190730-111333_Portulaca.jpg" data-pswp-width="957" data-pswp-height="1080" data-caption='<p>&#39;Happy rock&#39;</p>
      <audio controls autoplay  controlsList=&quot;nodownload&quot;>  <source src=&quot;bensound-happyrock.mp3&quot; type=&quot;audio/mpeg&quot;></audio>'>
      <div class="box"  style = "width:71px">
        <img src="thumbs/190730-111333_Portulaca.jpg" width="71" height="80" alt="2: 190730-111333_Portulaca" title="2: 190730-111333_Portulaca"  /><br>
      <div class="thumbText"><strong>'Happy rock'</strong><br></div>
      </div>
    </a>

But you hear two or tracks simultaneously (you hear only one track if you click on the pause button).

I think therefor that two images with audio tracks have been loaded.

How can I prevent that?

**Comment by dimsemenov** [comment]
Two nearby slides are always present. You may use `slideActivate` and `slideDeactivate` events to control playback. Dynamic caption plugin is also special, as it creates a fake caption for each slide to measure its size. Consider detaching the player from the caption completely.

**Comment by acwolff** [comment]
Ok thanks for your quick reply.
I think you should at least correct the documentation, because [0,0] suggests 0 slides on each side.

I will try to get another solution.
