### ISSUE TITLE
v5: Clicking the surrounding element always opens the first image of the gallery

### ISSUE THREAD

**Issue by yunusabd** [dimsemenov/PhotoSwipe#1823]
Here's an example: https://codepen.io/yunusabd/pen/wveybRb

Clicking anywhere in the gallery except a thumbnail image will always open the first image of the gallery.

It works correctly only when `childSelector` is a direct descendant of the gallery element, so I'm guessing that's the problem?

**Comment by dimsemenov** [comment]
Good catch, I'll fix it soon, Prob the latest patch broke it.

**Comment by dimsemenov** [comment]
Should be fixed by 5.1.4

https://codepen.io/dimsemenov/pen/yLXvmEQ

**Comment by yunusabd** [comment]
Nice one, thanks! This solves my issue.

One a slightly related note, using a class name as `childSelector` only seems to work with `a`-elements, i.e. it doesn't work for `div` or other element types. Might be worth looking into as well, I worked around it by just using `a`.

**Comment by dimsemenov** [comment]
`<a>` is a requirement due to accessibility (https://photoswipe.com/v5/docs/getting-started/#required-html-markup)

You can adjust this via API though https://photoswipe.com/v5/docs/data-sources/#custom-html-markup

**Comment by yunusabd** [comment]
Ah gotcha, makes sense for accessibility. So I think I'll just keep using `<a>`. Thanks again!
