### ISSUE TITLE
V5 Beta: What is the next event after the 'change' event?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1824]
I have an audio control in my caption.
I like to start the audio track automatically.
I tried to do that in the 'change' event, but that is too early because the caption is not visible at that moment.

So my question is, what is the first event after the change event where the custom and dynamic caption is displayed?

**Comment by dimsemenov** [comment]
It's generally the last in event in the chain, you may try using an event from caption https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin/blob/main/photoswipe-dynamic-caption-plugin.esm.js#L360, or delay the execution by one frame via settimeout.

**Comment by acwolff** [comment]
Yes that solves my problem!

I use now this code:

    lightbox.on('dynamicCaptionUpdateHTML', () => {
      try {
	    if (lightbox.pswp.currSlide.data.element.dataset.audio) {
	      slide_index=lightbox.pswp.currSlide.index;
	      startAudio("a" + slide_index);
	    }
      }
        catch(err) {}
    });

To see it in action, click on the 6th thumbnail in [this album](https://andrewolff.jalbum.net/PhotoSwipeVideoTest/).

Thank you very much for your help!
