### ISSUE TITLE
Duplicate CSS declaration

### ISSUE THREAD

**Issue by jimblue** [dimsemenov/PhotoSwipe#1825]
Duplicate declaration

https://github.com/dimsemenov/PhotoSwipe/blob/1574d11941761aa40b380ad94e2e0e0430d2cc47/src/photoswipe.css#L28

and 

https://github.com/dimsemenov/PhotoSwipe/blob/1574d11941761aa40b380ad94e2e0e0430d2cc47/src/photoswipe.css#L87

**Comment by picarica** [comment]
why not just make a pull request ?
