### ISSUE TITLE
Dynamic import of pswpModule without having to copy files manually - v5 beta

### ISSUE THREAD

**Issue by BryceMehring** [dimsemenov/PhotoSwipe#1829]
The v5 beta of PhotoSwipe should dynamically import 'photoswipe/dist/photoswipe.esm.js' as needed without having to specify a manual path to this file. Right now you can just statically import photoswipe.esm.js by passing in the module as a property to the PhotoSwipeLightbox constructor. This would make using the v5 beta of photoswipe much easier if you are using bundlers like rollup and webpack. Both bundlers know how to process these dynamic imports and can target browsers that don't support these dynamic imports.

**Comment by dimsemenov** [comment]
That would be so great. I wanted to solve this before I publish v5 on NPM. Can you provide an example of how to do this properly? Or maybe some other library that does that?

**Comment by acwolff** [comment]
> That would be so great. I wanted to solve this before I publish v5 on NPM. 
Well I hope you still allow to copy the files manually, that is required for my application!

**Comment by BryceMehring** [comment]
> That would be so great. I wanted to solve this before I publish v5 on NPM. Can you provide an example of how to do this properly? Or maybe some other library that does that?

What if when the user didn't specify a `pswpModule` option it got dynamically imported? For example:

```js
export function dynamicImportModule(module) {
  if (!module) {
    return import('./path/to/photoswipe.esm.js');
  }
  if (typeof module === 'string') {
    return import(/* webpackIgnore: true */ module);
  }

  return module;
}
```

> > That would be so great. I wanted to solve this before I publish v5 on NPM.
> > Well I hope you still allow to copy the files manually, that is required for my application!

That should still be possible as from the example above.

**Comment by dimsemenov** [comment]
So what's the path should be (`'./path/to/photoswipe.esm.js'`)? Just `./photoswipe.esm.js` relative to the lightbox JS file?

I think we might need two separate repositories, one for Lightbox and one for PhotoSwipe core to solve this.

Also need some elegant way to import plugins, preferably dynamically as well.

**Comment by BryceMehring** [comment]
> So what's the path should be (`'./path/to/photoswipe.esm.js'`)? Just `./photoswipe.esm.js` relative to the lightbox JS file?

`import('./photoswipe.esm.js')` should work for this particular case.

**Comment by dimsemenov** [comment]
But what if someone will want to use Webpack magic comments like:

```js
import(/* webpackPrefetch: true */ './photoswipe.esm.js')
```

And other bundlers also use similar stuff.

Also, how would you load plugins? There might be plugins that modify the behavior of `photoswipe.esm.js`, others modify only `photoswipe.lightbox.esm.js`, and some modify both.

Maybe something like this?

```js
import PhotoSwipeLightbox from './path/to/photoswipe-lightbox.esm.js';

const lightbox = new PhotoSwipeLightbox({
  gallery: '#gallery',
  children: 'a',

  pswpModule: () => import('./path/to/photoswipe.esm.js'),

  plugins: [
    {
      pluginModule: () => import('some-plugin.js'),
      initOnOpen: true,
      pluginOptions: {
        option: 'value'
      }
    },
    {
      pluginModule: () => import('another-plugin.js'),
      initOnOpen: true,
      pluginOptions: {
        option: 'value'
      }
    },
  ]
});

lightbox.init();
```

And if developer doesn't want to dynamically load stuff, it can be:

```js
import PhotoSwipeLightbox from './path/to/photoswipe-lightbox.esm.js';
import PhotoSwipe from './path/to/photoswipe.esm.js';
import SomePlugin from 'some-plugin.js';
import AnotherPlugin from 'another-plugin.js';


const lightbox = new PhotoSwipeLightbox({
  gallery: '#gallery',
  children: 'a',

  pswpModule: PhotoSwipe,

  plugins: [
    {
      pluginModule: SomePlugin,
      initOnOpen: true,
      pluginOptions: {
        option: 'value'
      }
    },
    {
      pluginModule: AnotherPlugin,
      initOnOpen: true,
      pluginOptions: {
        option: 'value'
      }
    },
  ]
});

lightbox.init();
```

And then `Promise.all()` all dynamic imports. 

Do you like this? Or is it too scuffed/complicated? Is it clear what `initOnOpen` does?

**Comment by BryceMehring** [comment]
> But what if someone will want to use Webpack magic comments

If they want to have that behavior they can provide their own dynamic import or static import function for `pswpModule`. From a usability point of view, importing `pswpModule` within photoswipe without the user having to manually import the module would be much easier for them.

> Do you like this? Or is it too scuffed/complicated? Is it clear what `initOnOpen` does?

The plugin loading makes sense to me

**Comment by dimsemenov** [comment]
This should be fixed by [v5 release](https://photoswipe.com).
