### ISSUE TITLE
5 beta errors

### ISSUE THREAD

**Issue by nikgrebnev** [dimsemenov/PhotoSwipe#1833]
We tried to download version 4 but we could not make it work, the fifth version is much better and implemented much quicker. But there are two errors. 
1. Vertical images are shown with the bottom cut. Scaling is done by the width of the screen and not by the longside of the picture. 
2. If a picture is small, it tries to enlarge to the   width of the screen that lead to the bad quality of the image. 
3. When we enter the gallery you can see a cross in the right top corner and the number of pictures in the gallery, but when you try to click on any part (for example on the cross), then all the buttons disappear and you can't do anything and even move to the next picture.

**Comment by dimsemenov** [comment]
Please provide a reduced test case, or at least the link to the page with the problem. 

Also, please open a separate issue for each discovered problem if they are not related to each other.
