### ISSUE TITLE
v5-beta: race condition when quickly swiping between images

### ISSUE THREAD

**Issue by thexeos** [dimsemenov/PhotoSwipe#1834]
**Uncaught TypeError: cannot use 'in' operator to search for 'decode' in null**

![image](https://user-images.githubusercontent.com/2260539/140263140-6634fc71-3468-422f-ae81-86eee720d666.png)

<details>
  <summary>More screenshots</summary>

![image](https://user-images.githubusercontent.com/2260539/140263252-f986fc2f-302f-4685-844a-63e367d00327.png)

![image](https://user-images.githubusercontent.com/2260539/140263417-29ed2ffa-88d4-4e4a-8389-4b529e566797.png)

![image](https://user-images.githubusercontent.com/2260539/140263503-1aebe8ab-be19-478b-8ba3-3d2862b3befd.png)
</details>

Does not happen when using arrows to navigate.

Adding something like this to `ImageContent`:

```
  appendTo(container) {
    this.isAttached = true;

    if (!this.element) {
      this.load()
    }
```

resolves the issue, and image is always loaded, however for swiping transitions, the grey placeholder is visible for a long time.
As in, the grey placeholder is not replaced until `onComplete` from `pswp.animations.startSpring` is triggered.

So the more appropriate solution is somewhere else - `load()` (or `lazyLoad()`) should be triggered earlier in the loop, I am guessing immediately after new slide is created when handling the swiping transition.

**Comment by thexeos** [comment]
By swiping at about 3 slides per second, I get into this state:

![image](https://user-images.githubusercontent.com/2260539/140266739-74a410c2-3fd8-4ed1-b8e2-f8509ca7ba52.png)

All slides are in motion, they were all "handed off" to contain following images, however before the transition completes, the `slideInit` is not executed. So if the animation can be "discarded" at the same the the contents of the slide are cleared, and the animation ended callback can be called, then the issue should, in theory, be solved.

**Comment by thexeos** [comment]
Here is an interesting observation:

`pswp.currIndex` remains unchanged even after sufficient time had passed for a transition to run. In the screenshot below I am doing slightly less than 3 swipes per second, so eventually one handler completes and the position is updated – it advances the 3 places that it had "pending".

![image](https://user-images.githubusercontent.com/2260539/140269606-3ee3bf42-9134-4717-8dac-1a2705095a14.png)

So very possibly, swiping before "first" transition completes essentially makes the code use `pswp.currIndex` which is already in the process of being transitioned, and in turn it resets the active transition's state and extends the "timeout" by another ~1/3 of a second.

I hope this helps in finding the cause of this issue.

**Comment by dimsemenov** [comment]
This should be fixed by [v5 release](https://photoswipe.com).
