### ISSUE TITLE
v5-beta: slideActivate event triggered too early when loop is enabled

### ISSUE THREAD

**Issue by thexeos** [dimsemenov/PhotoSwipe#1835]
![image](https://user-images.githubusercontent.com/2260539/140268007-9c21db2b-080b-48dc-b95e-5c482362680a.png)

There are 6 elements in the gallery. The code that produced the above output is roughly:

```
lightbox.on('moveMainScroll', () => {
  console.log('moveMainScroll', lightbox.pswp.currIndex)
})
lightbox.on('slideActivate', ({ slide }) => {
  console.log('slideActivate', slide.index)
})
```

<details>
  <summary>"Regular" call stack</summary>

![image](https://user-images.githubusercontent.com/2260539/140268456-f79a90c4-8562-4349-bb2e-43fa8df508e2.png)
</details>

<details>
  <summary>"Premature" call stack</summary>

![image](https://user-images.githubusercontent.com/2260539/140268411-82b35925-232d-4f49-9820-4b6e58630ba7.png)

</details>

And the culprit is:

![image](https://user-images.githubusercontent.com/2260539/140268642-10672b84-e448-4a9a-ae6d-45a94b9a6154.png)

Changing it to this:

![image](https://user-images.githubusercontent.com/2260539/140268981-ca32f3ca-a639-4d98-a4aa-eca3d57c8e55.png)

resolves the mentioned issue, however slide loading is not any better – as in https://github.com/dimsemenov/PhotoSwipe/issues/1834#issuecomment-960487844 I can quickly swipe over images and no content gets loaded until transition completion code runs.

**Comment by dimsemenov** [comment]
This should be fixed by [v5 release](https://photoswipe.com).
