### ISSUE TITLE
V5 Beta. Using a data source alongside clickable thumbnails

### ISSUE THREAD

**Issue by rctneil** [dimsemenov/PhotoSwipe#1836]
Hi,

Great job on V5 so far!

I have a grid of 30 images by default, with which I use Infinite Scroll to automatically add more images when a button under the grid is clicked.

The way I have it so far is that, PhotoSwipe initialises using a JSON array of ALL the images. This allows a user to open up any of the first 30 but then to keep navigating through without having to add all images into the grid first and then open PhotoSwipe.

I've just been trying to convert my project to use V5 locally and it works fine but this aspect does not work.

Is there a way I can get this to work in V5?

My current attempt is:

```
            const lightbox = new PhotoSwipeLightbox({
                gallery: '.my-gallery',
                children: 'figure',
                dataSource: buildPhotosObjectFromServer(),
                pswpModule: PhotoSwipe
            });
            lightbox.init();
```

An example of one of the keys in the `dataSource` object is:

```
h: 1950
height: "1950"
msrc: "https://farm66.staticflickr.com/65535/51555703700_47d2565009_n.jpg"
src: "https://farm66.staticflickr.com/65535/51555703700_47d2565009_b.jpg"
title: "IMG_0229"
w: 2600
width: "2600"
```

If I remove the `gallery` or `children` keys from the options object then the click on any of the thumbnails fails.

An example of how it works currently (pre V5) can be found here: HTTP://neiltonge.co.uk/gallery/collections/into-the-abyssus-19th-25th-sep-2021/albums/day-6-energylandia-and-legendia

Any ideas would be very greatly appreciated!

**Comment by dimsemenov** [comment]
Better late than never... but I've made an example in docs on how to deal with this (in Data Sources section) https://photoswipe.com/v5/docs/data-sources/#separate-dom-and-data 

feel free to re-open if the issue is not resolved

**Comment by rctneil** [comment]
@dimsemenov Many many thanks for taking the time to look into this.   I hope to actually put this in action in the coming weeks once my current phase on my app is completed. This will be next.

Thanks again!

**Comment by rctneil** [comment]
@dimsemenov Just been trying this out. It works perfectly!  Thank you for a fantastic library!
