### ISSUE TITLE
PhotoSwipe v5 Beta - Zoom bug - Opens awkwardly

### ISSUE THREAD

**Issue by da-kicks-87** [dimsemenov/PhotoSwipe#1838]
Hello,

I am testing out PhotoSwipe v5 Beta on my local setup and I noticed a bug that doesn't occur on the websites examples.

When using the zoom or fade animation settings, on open,  it appears that 2 images loads. 1 at the bottom and another in the center overlapping it. The bottom on then will disappear, giving it a awkward jumping visual. It’s not smooth looking.

I have set data-pswp-width and data-pswp-height correctly. I'm not sure why it behaves this way. 
Any suggestions?

**Comment by dimsemenov** [comment]
PhotoSwipe displays an image placeholder from the thumbnail (`msrc`), make sure that its aspect ratio matches your large image.

**Comment by da-kicks-87** [comment]
Cool. Having the same aspect ratio works. 

But what if I don't want the thumbnails to have same aspect ratio as the large image ? Which I believe would be a common scenario in a multi image gallery.

**Comment by da-kicks-87** [comment]
Never mind I found info about cropping in the docs.

Thanks for the help.  :)
