### ISSUE TITLE
Lightbox for website image viewing with navigation in two dimensions: Possible with PhotoSwipe?

### ISSUE THREAD

**Issue by porg** [dimsemenov/PhotoSwipe#1845]
Hi @dimsemenov et al,

I asked at StackOverflow if someone knows a [readymade solution](https://stackoverflow.com/questions/70454190/lightbox-for-website-image-viewing-with-navigation-in-two-dimensions) (copy below) and am currently awaiting an answer.

Meanwhile I wanted to ask here at PhotoSwipe as a popular lightbox plugin whether something like this:
- would be possible with current functionality? If so with what configuration?
- worth pursuing in a special operation mode? Or possibly as a fork?

Regards, porg

----

# Lightbox for website image viewing with navigation in two dimensions
- First axis for navigating photo sets (i.e. up/down)
- Other axis for navigating photos within sets (i.e. left/right)

### Use cases: Presentation of screenshots series with a two dimensional nature
 - **Responsive Web Design**: Dimension device size (Mobile, Tablet, Laptop, Desktop) with other dimension page (home, products, services, contact)
 - **Multi Platform Software**: Dimension software platform (Mac, Linux, Windows) with other dimension use case (open file, do action X, save file)
 - **Visual Version History**: Dimension version (Mac OS 7, Mac OS 9, Mac OS X 10.1, macOS 11) with other dimension use case (Open file, Browse folder, Default text editor, Restart computer)

<br>

![2-axial lightbox](https://i.stack.imgur.com/KR5gS.png)

**Comment by dimsemenov** [comment]
It's not something that's supported. Such functionality will take a significant amount of dev time to implement.

**Comment by porg** [comment]
Thanks for the info.
