### ISSUE TITLE
V5 beta : iOS chrome and safari - first loaded image is truncated

### ISSUE THREAD

**Issue by david-raine** [dimsemenov/PhotoSwipe#1846]
On chrome v96.0.4664.101 on iOS 15.2, also safari 15.2.

The first image loaded shows the expanded thumbnail and then, as it loads, gets truncated somewhere after 50%. This image then always shows this size until the lightbox is restarted. Sometimes other images then get truncated at the same size as the first one, as if the viewport is being calculated badly.

I have a public gallery (I am a photographer) up at [houseofhoney.org](https://houseofhoney.org/archive/give2019archive) - this is a large gallery of large images, but none over 1500 on the long side. 

I have tried various things - standard config, preloadFirstSlide true and false, adding native fullscreen, adding padding or not, changing various things. It all works as I want it on desktop but not iOS.

I have added one line to the library, in photoswipe.esm.js, at line 4978, I changed the close() function to destroy the lightbox as it was not working after being closed. The same issue was occurring before this change.

```
close() {
    if (!this.opener.isOpen || this.isDestroying) {
      return;
    }
    this.isDestroying = true;
    this.dispatch('close');
    this.events.removeAll();
    this.opener.close();

    this.destroy(); // added line

}
```

**Comment by dimsemenov** [comment]
Hi, please check if this helps:

@@@
.pswp img {
  background: rgba(255,255,255,0.01);
}
@@@

**Comment by david-raine** [comment]
Hi, yes indeed that does resolve it. Thank you.
