### ISSUE TITLE
V5: How to open lightbox at a given index from a link/button outside gallery HTML

### ISSUE THREAD

**Issue by icreatestuff** [dimsemenov/PhotoSwipe#1848]
I can see from the V5 documentation that it's possible to use simple text links, thumbnail links or a combination to launch the lighbox gallery as long as they are all children of the parent gallery element. 

I'd like to know if it's possible to open the lightbox for example at image 2 (index 1?) from a link  or button that is not associated or within the gallery element.

For example with this HTML markup how could I make a click on the button load and open the lightbox?

```html
<div class="gallery">
    <a href="https://domain.com/image1.jpg" data-pswp-width="1000" data-pswp-height="800" data-cropped="true">
        <img src="https://domain.com/image1-thumb.jpg" width="100" height="100">
    </a>

    <a href="https://domain.com/image2.jpg" data-pswp-width="1000" data-pswp-height="800" data-cropped="true">
        <img src="https://domain.com/image2-thumb.jpg" width="100" height="100">
    </a>

    <a href="https://domain.com/image3.jpg" data-pswp-width="1000" data-pswp-height="800" data-cropped="true">
        <img src="https://domain.com/image3-thumb.jpg" width="100" height="100">
    </a>
</div>

<button>View Gallery</button> 
```

and the Javascript

```js
import PhotoSwipeLightbox from '/v5/photoswipe/photoswipe-lightbox.esm.js';

const lightbox = new PhotoSwipeLightbox({
    gallery: '.gallery',
    children: 'a',
    pswpModule: '/v5/photoswipe/photoswipe.esm.js'
});

lightbox.init();
```

I tried using the following as described [here](https://photoswipe.com/v5/docs/data-sources/)

```js
document.querySelector('button').onclick = () => {
    lightbox.loadAndOpen(0); // open the first image
};
```
however that errored with `Uncaught TypeError: ContentClass is not a constructor at PhotoSwipeLightbox.createContentFromData` I presume because I haven't initialised the lightbox with a datasource within the options.

Is there an API event that I've missed in the docs that would achieve this?
Many thanks for an awesome library.

**Comment by dimsemenov** [comment]
The easiest way is to just trigger a click `document.querySelector('.gallery a').click();`.

`lightbox.loadAndOpen(0);` doesn't work because there might be multiple `.gallery` on a page, you can also do:

```js
lightbox.loadAnOpen(0, {
  gallery: document.querySelector('.gallery')
});
```

**Comment by icreatestuff** [comment]
Thanks for the really quick response @dimsemenov. They work perfectly 👍.
