### ISSUE TITLE
Next slide on click / tap ?

### ISSUE THREAD

**Issue by carlo-fontanos** [dimsemenov/PhotoSwipe#1849]
Hi,

The default mouse click behavior currently zooms-in if the image is not at 100% scale. Is there an option to have the mouse click go to the next image in the slideshow? This would set the aforementioned behavior false, and zooming would then be accessible only using the toolbar icon or via double-tap.

Carl

**Comment by dimsemenov** [comment]
refer to Click Actions section of docs https://photoswipe.com/v5/docs/click-and-tap-actions/#click-on-image-moves-to-the-next-slide
