### ISSUE TITLE
v5 missing width/height confusion

### ISSUE THREAD

**Issue by bobobo1618** [dimsemenov/PhotoSwipe#1850]
Thanks for writing this project, it suits my needs exactly!

I've been trying out v5 and ran into a problem: when the `data-pswp-width` and `data-pswp-height` attributes are missing, many things break in odd ways, but silently:

- When animations are enabled (the default), they don't work
- When animations are enabled (the default), closing the gallery doesn't work (the UI overlay disappears but the image remains)
- When opening images, they open zoomed in quite far but act as if they're not (can't zoom in/out or pan)

I would suggest this could be improved by adding a check [here](https://github.com/dimsemenov/PhotoSwipe/blob/60040164333bd257409669e715e4327afdb3aec7/src/js/core/base.js#L166-L167) that the width and height are not `NaN` and log an error if they are.

But this is due to my own inattentiveness so I understand if such a message is deemed unnecessary.

**Comment by dimsemenov** [comment]
It's required to provide the width and height properties of images. Do you suggest having some other way to define them (alongside `data-` HTML attributes)?

**Comment by bobobo1618** [comment]
No, I just want some kind of feedback (e.g. a warning in the console log) that the width and height are missing if I forget them.
