### ISSUE TITLE
Disable Image Zoom-in and Zoom-out Animation?

### ISSUE THREAD

**Issue by carlo-fontanos** [dimsemenov/PhotoSwipe#1852]
We want to disable the animation effect when clicking / double-tapping an image in PhotoSwipe. We checked PhotoSwipe options but didn't find anything there.

CodePen: https://codepen.io/dimsemenov/pen/gbadPv

On the browser developer console we noticed that the zooming uses `transform: translate3d(...); `- we believe this is what causes the animation.

**Comment by dimsemenov** [comment]
If you're using v5 or above, please refer to "Opening or closing transition" section of the documentation. https://photoswipe.com/v5/docs/opening-or-closing-transition/

Closing this issue, feel free to re-open.
