### ISSUE TITLE
v5 - HTML Slide TypeError

### ISSUE THREAD

**Issue by end2endi** [dimsemenov/PhotoSwipe#1855]
I encountered a TypeError when including a HTML slide in a gallery. If you traverse the gallery a second time, for example going backwards through the slides, the HTML slide will trigger the error below when you are 2 slides away from the HTML slide.

![photoswipe1](https://user-images.githubusercontent.com/76557148/155879203-1b19e746-40f3-4792-b6bf-ab6662529688.png)

It appears to be related to the slide cache. I'm not certain, but it looks like the HTML slide does not exist in the cache when attempting to preload it.

![photoswipe2](https://user-images.githubusercontent.com/76557148/155879212-8bdfa7cd-98b0-45d8-bfae-283ec1aac3e9.png)

 I'm happy to provide more details, just let me know.

**Comment by dimsemenov** [comment]
Should be fixed by the latest build (5.2.0-beta.2). The beta branch is also on npm now.
