### ISSUE TITLE
More galleries on same page?

### ISSUE THREAD

**Issue by tiomanisland** [dimsemenov/PhotoSwipe#1859]
I would like to use PhotoSwipe for more galleries on same page and I don't know how to change that class.

Example: I have website where it shows classified ads on one page, there are 50 classified ads, each item for sale has 1-10 photos. I would like PhotoSwipe to work on all those 50 ads (galleries) - they are on same HTML page.

If I use same ID or class in that div, PhotoSwipe will think all 50 photos must be displayed in slide show. How to separate?

**Comment by BilouMaster** [comment]
I think you can use the same id. Did you try it?

**Comment by tiomanisland** [comment]
i didnt. i gave up and i am looking for something else.

**Comment by tiomanisland** [comment]
> I think you can define a class instead of an id, then photoswipe use that class to operate on each gallery

i dont know how to do that and there is no instrucions on the page.

**Comment by BilouMaster** [comment]
The parameter take a common selector, so...
`gallery: '.my-gallery'` instead of `gallery: '#my-gallery'`

**Comment by dimsemenov** [comment]
If you're using v5, you can do something like:

```js
import PhotoSwipeLightbox from '/v5/photoswipe/photoswipe-lightbox.esm.js';
const options = {
  gallery: 'a.my-image-link',
  pswpModule: () => import('/v5/photoswipe/photoswipe.esm.js')
};
const lightbox = new PhotoSwipeLightbox(options);
lightbox.init();
```

and all elements like:

`<a class="my-image-link" href="large-image.jpg" data-pswp-width="800" data-pswp-height="600">...`

will open PhotoSwipe.
