### ISSUE TITLE
Even more custom captions 

### ISSUE THREAD

**Issue by kamilkloch** [dimsemenov/PhotoSwipe#186]
While the toolbar & caption bar look OK on a phone, in my belief they are not the most elegant solution on the desktop. 

What about restyling the caption container so that:
- its width is exactly the width of the picture (that's what I mean: http://www.boston.com/bigpicture/)
- it is being 'swiped' together with the picture (see http://mikematas.com)
- its style is defined in styles.css, to ease further modifications.

**Comment by axelson** [comment]
I'd definitely want the caption to be the same exact width as the image as well, and swiping the two together would a great bonus.
