### ISSUE TITLE
Buttons need to be of type='button'

### ISSUE THREAD

**Issue by creativetags** [dimsemenov/PhotoSwipe#1863]
In the docs you say to add PhotoSwipe (.pswp) element to DOM and include code for some buttons. I found an issue with buttons submitting a form unless the button was defined with type="button"

all these:
<button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
should be:
<button type="button" class="pswp__button pswp__button--close" title="Close (Esc)"></button>

**Comment by dimsemenov** [comment]
This is fixed by [the v5](https://photoswipe.com).
