### ISSUE TITLE
v5: data-cropped NOT working

### ISSUE THREAD

**Issue by piotrbox** [dimsemenov/PhotoSwipe#1864]
Hi I love how data-cropped works in new version.. at least in your demo..

for some reason it does not wor for me loccaly.

I have exact same setup,  data pswp heigt, width, i have width an height in thumbnails, ... and it desnt work (or workse the same weather I add data-cropped or not... )

any ideas?  

my html:

`<a href="http://ddmmed.test/wp-content/uploads/2022/03/tpk3.jpg" data-pswp-width="3840" data-pswp-height="2160" data-cropped="true" target="_blank">
    <img class="" width="448" height="420" src="http://ddmmed.test/wp-content/uploads/2022/03/tpk3-448x420.jpg" srcset="http://ddmmed.test/wp-content/uploads/2022/03/tpk3-448x420.jpg 1x, http://ddmmed.test/wp-content/uploads/2022/03/tpk3-896x840.jpg 2x" alt="a to alt">
</a>`

and js init:

`
<link rel="stylesheet" id="photoswipe-css" href="/app/photoswipe/dist/photoswipe.css" type="text/css" media="all">
    <script type="module">
        // Include Lightbox 
        import PhotoSwipeLightbox from '/app/photoswipe/dist/photoswipe-lightbox.esm.js';

        const lightbox = new PhotoSwipeLightbox({
            // may select multiple "galleries"
            gallery: '.galeria',

            // Elements within gallery (slides)
            children: 'a',

            // setup PhotoSwipe Core dynamic import
            pswpModule: () => import('/app/photoswipe/dist/photoswipe.esm.js')
        });
        lightbox.init();
    </script>
`

PS. greets from Poland 

EDIT:

OK, i Think I understand now.. so the thumbnail cant be cropped server side rather in CSS only... is this correct? 
I think that needs some explanation in demo..

**Comment by dimsemenov** [comment]
Hi, yes, thumbnails should be cropped via CSS. I'll adjust docs.

**Comment by dimsemenov** [comment]
Oh, you're from Poland. I hear daily that a lot of Polish people are helping Ukrainians that had to leave their homes and just supporting us in general. Thanks for that!  ❤️
