### ISSUE TITLE
ChunkLoadError: Loading chunk vendors-node_modules_photoswipe_dist_photoswipe_esm_js failed.

### ISSUE THREAD

**Issue by ThomsonCoding** [dimsemenov/PhotoSwipe#1870]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/67236266/161274904-bb8040fc-def5-418a-a773-5a67abeaf816.png">

Using V5 of PhotoSwipe, my code runs fine locally on my PC (With the fantastics features that PhotoSwipe provide), although when I use it on my Shopify website site it provides the error message shown in the image. The error message will only occur when I have clicked on the images that it is applied on.

To install I have used: npm i photoswipe --save

I'm importing PhotoSwipe via: 
```
import PhotoSwipeLightbox from "photoswipe/lightbox";
import "photoswipe/style.css";
```

Implementing it with:  
 ```
 const lightbox = new PhotoSwipeLightbox({
    gallery: "#my-gallery",
    children: "a",
    pswpModule: () => import("photoswipe")
  });

  lightbox.init();
```
I have tried: 
- Clearing the Cache/Using different browsers/etc. 
- deleting the following files assets, config, layout, locales, node_modules, sections, snippets, templates
and then doing the following: npm install,  npm run build, and then shopify theme push.
- Many other suggestions from articles online.

**Comment by dimsemenov** [comment]
Please check if any other dynamic import works for you.

**Comment by ThomsonCoding** [comment]
Hello, turns out for this site I am working on, the webpack build doesn't support dynamic imports via the method I had carried out before. So to resolve this I had to change my code to the following: 

```
import PhotoSwipeLightbox from 'photoswipe/lightbox';
import PhotoSwipe from 'photoswipe';
import 'photoswipe/style.css';

const initMedia = () => {
  const lightbox = new PhotoSwipeLightbox({
    gallery: '#my-gallery',
    children: 'a',
    pswpModule: PhotoSwipe,
  });

  lightbox.init();
```

Hopefully this will help anyone with a similar issue. Thank you for your reply, appreciate all the hard work that has gone into this.
