### ISSUE TITLE
How to include PhotoSwipe in a simple HTML page

### ISSUE THREAD

**Issue by kapooramit** [dimsemenov/PhotoSwipe#1874]
Hi @dimsemenov,

I don't have a way to include the library as mentioned in the docs. The tool I use breaks the code as it fails to understand the import. It simply converts the script tag content into a comment and done. 

The only thing I can do it is include the scripts and css in head and then call the method/initialize it etc. in the body. Can you tell me how to do this? I have tried a few things but I am getting nowhere...

My final HTML looks like this once processed. 

```
<head>
        <script src="../Scripts/photoswipe-lightbox.esm.js"></script>
        <script src="../Scripts/photoswipe.esm.js"></script>
        <link rel="stylesheet" href="../Stylesheets/photoswipe.css"/>
        <script src="../Scripts/myproject.js"></script>
....
</head>

<body>
.....
.....
</body>
```
What I can do and usually do is initialize the libraries in the `myproject.js` and do the HTML/DOM processing in there. But now, I don't know how to call photoswipe in `myproject.js` to start using it etc. Please help.

**Comment by acwolff** [comment]
I have here an example https://www.andrewolff.nl/TestAlbum/Embedded_PS/PS_SlideShow_inline.html

**Comment by kapooramit** [comment]
Thank you @dimsemenov. Your response solved my issue perfectly and all is working now. :)

**Comment by kapooramit** [comment]
@dimsemenov : In an ideal world where our customer could run a local http server and then open HTML pages, the above setup works as required. However, I just found out that unlike other scripts included in <head>, the scripts - `init-gallery.js, photoswipe.esm.js, photoswipe-lightbox.esm.js` are throwing CORS error when the HTML is opened from disk which would be the case for 95% of our customer base. 

````
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///D:/myproject/Scripts/photoswipe-lightbox.esm.js. (Reason: CORS request not http).
````

How do I fix this except asking the customer to disable CORS in their browser.

**Comment by dimsemenov** [comment]
I don't think there is a way to load ES modules locally like this.

> Is that a way out? If so, is there any easy way to do it?

For now, you may use Webpack/Babel. I might include a transpiled version of the script in the future.

**Comment by kapooramit** [comment]
Thank you. Today, being a novice, it took me a couple of hours in trying to transpile but I failed. Maybe in a day or two, I will get lucky :-). 

Thank you for considering to add the transpiled version in future. For users like me where customers cannot access internet, file:// protocol is the default for accessing product documentation (installed with product) and then, transpiled version is the only thing that will work. 

Thank you @dimsemenov .

**Comment by kapooramit** [comment]
Hi @dimsemenov - I failed again. I am doing something wrong and nothing is helping. I tried various methods to transpile after setting up node and npm on the scripts but in vain. Is it possible for you to share the transpiled version of the library that would work for file:/// protocol without throwing CORS error? I won't need to update the library at my end at least for next 8-10 months unless some critical bug comes my way which I is highly unlikely. So if you share the version, it will be good for me for a 8-10 months until I would need to update. 

Else, I will have to switch to Magnific and put conditions in place to use PhotoSwipe instead only when CORS error won't show up (only for 5% our customer base that would host docs on some server). Or, maybe use Magnific only. 

Thank you!

**Comment by dimsemenov** [comment]
[Here](https://gist.github.com/dimsemenov/972018fcbedfcd0b8f9a57962b346945) is transpiled untested version, use on your own risk. But I'd recommend generating it yourself, if you're new - try to follow webpack hello world https://webpack.js.org/guides/getting-started/

**Comment by kapooramit** [comment]
Hi @dimsemenov : You are a savior! Thank you so much. I could not ask for more!! 
Yes - I will use it at my own risk. It is working flawlessly at the moment and I will try again to create the transpiled version myself. I think the best way would be setup this whole project at my end and create it. 

Thank you again! :1st_place_medal:  :-)
