### ISSUE TITLE
How to check whether the lightbox is open?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1885]
In the landing page index.html  of my webpage I use this code:

`<script src="res/initGallery.js" type="module"></script> `

Fle  initGallery.js contains all lightbox code.

For the rest of the code in index.html I need a function to check whether the ligthbox is open. I use now this:

```
function lightboxIsOpen() {
    if (typeof pswp == 'undefined') return false;
    else return true;
}
```
However that works not always as expected if the ligthbox is just opened.

In an earlier version, all the ligthbox code was in my index.html file and I used the following code:

```
var lboxIsOpen = false; 

 lightbox.on('loadComplete', () => {
        lboxIsOpen= true;
  });

lightbox.on('close', () => {
  lboxIsOpen= false;
});

function lightboxIsOpen() {
    return lboxIsOpen;
}
```

But this does no longer work after I put all lightbox code in nitGallery.js,  lboxIsOpen is inaccesable.

So my question is:
What is a what is the best code for function lightboxIsOpen()?

**Comment by acwolff** [comment]
> What exactly do you mean by "open"? When the initial animation ends?

If the loadComplete event is ready

**Comment by acwolff** [comment]
If I use
```
function lightboxIsOpen() {
    return lightbox.pswp && lightbox.pswp.opener.isOpen;
}
```
I get an error: indexPage.js:1146 
        
       Uncaught ReferenceError: lightbox is not defined

**Comment by dimsemenov** [comment]
You'll need to expose it to some global variable, like:

```
window.lightboxIsOpen = () => window.pswp && window.pswp.opener.isOpen;
```

and then you may `window.lightboxIsOpen()`

**Comment by acwolff** [comment]
I am not sure I understand you.
I tested it with this code in initGallery.js

```
var lboxIsOpen = false; 

 lightbox.on('loadComplete', () => {
        lboxIsOpen= true;
  });

lightbox.on('close', () => {
  lboxIsOpen= false;
});

function lightboxIsOpen() {
    return lboxIsOpen;
}

window.lightboxIsOpen2 = () => lboxIsOpen; 
```
If I call in index.html

`alert(window.lightboxIsOpen2());`

The response is always 'false' , with and without an open lightbox.

So what do I wrongly?

**Comment by dimsemenov** [comment]
Sorry, I can't debug the code for you. If you've found some bug/issue - please create a test case.

**Comment by dimsemenov** [comment]
And whether the image is loaded or not, you can do `pswp.currSlide.content.state === 'loaded'`.

**Comment by acwolff** [comment]
Well there is another problem:
I have this code:
```
    lightbox.on('loadComplete', () => {
        lboxIsOpen= true;
         console.log("loadComplete lboxIsOpen: ", lboxIsOpen) ;
    });
```
This event is in my case not always called after opening the lightbox. Is that correct?

That is the reason that my function
```
function lightboxIsOpen() {
    return lboxIsOpen;
}
```
Is sometimes noy working!

**Comment by dimsemenov** [comment]
loadComplete is an event of a slide that can be loaded (such as an image). You're likely using a HTML slide, which is just appended to DOM without any pre-loading.

**Comment by acwolff** [comment]
OK, that was a misunderstanding from my side.!

Thank you for your help, your patience and your great library!
