### ISSUE TITLE
TypeScript type definitions for PhotoSwipe v5

### ISSUE THREAD

**Issue by irudoy** [dimsemenov/PhotoSwipe#1888]
There are no type definitions for v5 currently available.

The package with type definitions [@types/photoswipe](https://www.npmjs.com/package/@types/photoswipe) for v4 currently has about 30k weekly downloads.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/5372690/163121114-5a81df27-b54e-45f9-9bf3-dc4f869c35ae.png">

Meanwhile, the [photoswipe](https://www.npmjs.com/package/photoswipe) package itself has about 100k weekly downloads on NPM.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/5372690/163121202-9d9fbe1b-2fa5-47f6-9ce6-f6c139f897e5.png">

It means that almost a third of users need it.

It would be great to have built-in type definitions for v5, right in the PhotoSwipe package.

I see some ways to achieve this:

1) Make the `.d.ts` file manually in this repo.
Pros: it's easy; no need to modify an existing codebase.
Cons: it's hard to keep it in sync; no typechecking for the PhotoSwipe source.

2) Rewrite the PhotoSwipe source code to TypeScript.
Pros: strongly-typed codebase; automatically generated type definitions.
Cons: a lot of work; more complex build stage; inevitable use of TS compiler.

3) Use of a hybrid approach with TypeScript and JSDoc
Pros: easy to implement; automatically generated type definitions; somewhat strongly-typed codebase;
Cons: need to document all the sources with JSDoc 🤔

https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html
https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
https://github.com/webpack/webpack/blob/main/lib/AsyncDependenciesBlock.js

I think that the third approach is the best option for this project. For example, webpack went this way successfully and it seems like this is a good working solution.

I can do a PR for it 😉

**Comment by dimsemenov** [comment]
That seems like a lot of work, so if you have time and will to make such PR - go for it. JSDoc solution seems good.
