### ISSUE TITLE
Request for Official Transpiled Version

### ISSUE THREAD

**Issue by sayontan** [dimsemenov/PhotoSwipe#1892]
Hello,
This is a feature request rather than a bug. 

Along the lines of issue #1874, I would like to request an officially supplied non-ESM PhotoSwipe version, even if it is in ES6 as opposed to ES5. 

The reason is, developers typically tend to cover various scenarios wherein they need to transpile their code. When a script such as PhotoSwipe is invoked via an import, the transpiling program will end up bundling the whole PhotoSwipe code in the same file. When a second developer building a separate library also uses a transpiler, they will end up bundling PhotoSwipe with their code too. So, when the code is deployed, PhotoSwipe will be deployed twice via two separate bundles, which ends up causing various impacts. 

By having a non-ESM version, developers will be able to use the PhotoSwipe and PhotoSwipeLightbox functions without importing the module, so they can prevent the bundling from occurring if they run their code via a transpiler. Then, the code can included this way:

```
<script type='text/javascript' src='https://path/to/photoswipe'></script>
<script type='text/javascript' src='https://path/to/bundle-1-without-pswp'></script>
<script type='text/javascript' src='https://path/to/bundle-2-without-pswp'></script>
```

Instead, now we have to do this:

```
<script type='text/javascript' src='https://path/to/bundle-1-with-pswp'></script>
<script type='text/javascript' src='https://path/to/bundle-2-with-pswp'></script>
```

I know that the recommended approach is rather this:

```
<script type='module' src='https://path/to/esm-1-importing-pswp'></script>
<script type='module' src='https://path/to/esm-2-importing-pswp'></script>
```

However, as indicated in #1874, this can cause some issues. Moreover, there may be other reasons for developers to deliver bundled scripts.

**Comment by dimsemenov** [comment]
That makes sense, I'll probably add a umd version at some point.

**Comment by jasonkhanlar** [comment]
https://github.com/jasonkhanlar/mediawiki-extensions-PhotoSwipe/

I just started working on this a few days ago, but otherwise if an ES5 version existed, I think it would be a lot easier to work with integrating this to exist in MediaWiki environment correctly. I'm still new to developing with MediaWiki, so I don't really know what I'm doing exactly, but I'm gonna keep doing it until I get a functional environment to use PhotoSwipe in MediaWiki with external hotlinked images being presented in a slideshow gallery. Otherwise I've probably been annoying the MediaWiki dev/social media team on Libera.chat IRC and Discord quite a lot, trying to work with the ES6 release that requires `<script type="module"></script>`

**Comment by jasonkhanlar** [comment]
Thanks to assistance from Krinkle on Libera.chat (also reacted above), apparently I can use this to create an ES2015 version of the JS files from this library.

```
curl 'https://raw.githubusercontent.com/dimsemenov/PhotoSwipe/master/dist/photoswipe-lightbox.esm.js' | esbuild --target=es2015 --format=cjs --bundle --outfile=modules/ext.photoSwipe/lib/photoswipe-lightbox.cjs.js
curl 'https://raw.githubusercontent.com/dimsemenov/PhotoSwipe/master/dist/photoswipe.esm.js' | esbuild --target=es2015 --format=cjs --bundle --outfile=modules/ext.photoSwipe/lib/photoswipe.cjs.js
etc.
```

but still it kinda doesn't seem as convenient as a CommonJS release (or if it is possible to have an ES6 release that doesn't require import, and usable in `<script type='text/javascript'></script>` containers

**Comment by ajssd** [comment]
@dimsemenov any update on the non-ESM (ideally, UMD) version of the library?

**Comment by dimsemenov** [comment]
UMD version is added in 5.2.8 - https://github.com/dimsemenov/PhotoSwipe/tree/master/dist/umd

Please report if you find any issues with it.

**Comment by ajssd** [comment]
Thanks for that info ... looking forward to 5.2.8!

FYI, I see 5.2.7 on the "versions" tab of https://www.npmjs.com/package/photoswipe, but over at https://github.com/dimsemenov/PhotoSwipe/releases I don't see anything past 5.2.2.  And without a "changelog" file, it's hard to know what changed.

**Comment by rubjo** [comment]
A 5.2.8 version on npm would be very much appreciated :)

**Comment by dimsemenov** [comment]
Should be up, apologies
