### ISSUE TITLE
Dynamically Populating Height and Width

### ISSUE THREAD

**Issue by sayontan** [dimsemenov/PhotoSwipe#1893]
Hello,
In quite a few cases, it is not possible to know the size of the full image upfront. E.g. I might have a gallery of small thumbnails, which, upon clicking, show me larger images. Specifically if you are trying to get photos from an arbitrary source via an API call, there might not be explicitly defined attributes for the height and width. So, if the gallery markup is being generated from the server using PHP code, quite possibly you will not be able to assign `data-pswp-width` and `data-pswp-height` to the `a` tag. 

Consequently, since `data-pswp-width` and `data-pswp-height` are mandatory attributes, not providing them leads to ugly results. 

I know that in v4 there was a way to listen for the `gettingData` event, wherein you could cycle through all the items and set their sizes. Can something similar be done in v5? What would be the right event for it?

**Comment by dimsemenov** [comment]
PhotoSwipe is designed around pre-defined image size - features such as zoom transition, placeholder, progressive loading, and scaling all require it. At the current state, if you cannot pre-define image sizes - please do not use PhotoSwipe.

In the future, there might be a feature that loads images and only then opens PhotoSwipe, but it requires a lot of work.

**Comment by sayontan** [comment]
Thank you for responding. 

For my setup this took a good bit of effort - I tried playing around with different events such as `beforeOpen`, `gettingData`,  `contentInit`, `loadComplete` etc., and filters such as `itemData`. Nothing worked. 

Eventually I made use of a function I have that waits for images to load before rendering galleries - I set that function to assign these attributes once the image was fetched, which is done before I bind PhotoSwipe to the images.

**Comment by dimsemenov** [comment]
You may also technically replace or append a new slide once image is loaded, there is example here https://photoswipe.com/methods/#dynamically-adding-or-removing-slides But you lose some interactivity, ye...

You also mentioned that you use PHP, you may use it to read the first few bytes of each image and retrieve size.
