### ISSUE TITLE
How to reinitialize PhotoSwipe v5 after ajax call

### ISSUE THREAD

**Issue by Solmaz-ahmadi** [dimsemenov/PhotoSwipe#1895]
Last night, for the first time I used PhotoSwipe v5 in my project. It works great. But after ajax call, unfortunately it stops working and it needs reinitializing. After ajax call, all the images are rendered well but when I click on them, the images open in a new window and they act like anchor tags.
I would be grateful if someone tells me **how to reinitialize** PhotoSwipe **v5** after ajax call.

**Comment by dimsemenov** [comment]
There is no option to "reinitialize", you initialize it again for the new element that you added, or use `gallery` option from the parent element that is not changing via ajax calls.

**Comment by Solmaz-ahmadi** [comment]
Yes, you are right. I had chosen a div as the parent element which was affected by ajax call. When **I changed the parent element** (by means of gallery option) with a div which was not affected by ajax, then it started working great like the first time and there was no need to reinitialize it. 
You helped me a lot. 
PhotoSwipe is awesome.
**Thanks a lot.**
