### ISSUE TITLE
Can i avoide type="module" ?

### ISSUE THREAD

**Issue by Sello-2k** [dimsemenov/PhotoSwipe#1897]
Iam sorry if my question is dumb, iam pretty new in librays like this

**I want to include the Library directly like this:**
<script type='text/javascript' src='/lib/photoswipe/dist/photoswipe-lightbox.esm.js'></script>
<script type='text/javascript' src='/lib/photoswipe/dist/photoswipe.esm.js'></script>
 
 
**But this causes an error:**
photoswipe-lightbox.esm.js:1381 Uncaught SyntaxError: Unexpected token 'export' (at photoswipe-lightbox.esm.js:1381:1)
photoswipe.esm.js:5278 Uncaught SyntaxError: Unexpected token 'export' (at photoswipe.esm.js:5278:1)

Because i dont have the type="module"

**Normally i should include it like this:** 
<script type="module">
import PhotoSwipeLightbox from '/lib/photoswipe/dist/photoswipe-lightbox.esm.js';
const lightbox = new PhotoSwipeLightbox({
  gallery: '#my-gallery',
  children: 'a',
  pswpModule: () => import('/lib/photoswipe/dist/photoswipe.esm.js')
});
lightbox.init();
</script>

**Right?**

**Comment by acwolff** [comment]
I use this:

`<script src="res/initGallery.js" type="module"></script>`

and in initGallery I have all the PhotoSwipe code like:

```
	import PhotoSwipeLightbox from './photoswipe-lightbox.esm.min.js';
	const options = {
	  gallerySelector: '#gallery',
	  childSelector: 'a',
	  counter: false,
	  bgOpacity:  1.0,
	  paddingTop: 60,
	  paddingBottom: 60,
	  loop:  true,
	  imageClickAction: (releasePoint, e) => {  playpause() },
	  tapAction: (releasePoint, e) => { if (isImage) playpause() },
	  mouseMovePan: true,
	  initialZoomLevel: 'fit',
	  secondaryZoomLevel: 'fill',
	  maxZoomLevel: 1,
	  mainClass:  'pswp--buttons-visible',
 	  pswpModule: () => import('./photoswipe.esm.min.js')
 	};
	const lightbox = new PhotoSwipeLightbox(options);
  etc.
```

**Comment by Sello-2k** [comment]
Thank you @acwolff acwolff, that helps me really well.

**Comment by dimsemenov** [comment]
To anyone who finds this, PhotoSwipe now has a UMD version https://github.com/dimsemenov/PhotoSwipe/tree/master/dist/umd
