### ISSUE TITLE
How to refresh the lightbox contents?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1903]
I try to implement a spherical panorama viewer in the PhotoSwipe lightbox.

The first result is here: https://andrewolff.jalbum.net/PS_SpherePan_PSV4/?1
You see that the image does not fill the whole lightbox.
To fill the whole lightbox with the image I have to shift an edge of the lightbox a little so that a resize is executed.

My question is how can I do that with code, so is there a Refresh() function?

**Comment by dimsemenov** [comment]
To force-update size of PhotoSwipe - `pswp.updateSize(true)`. However, pretty sure that you need to update size of your panorama viewer, and not the PhotoSwipe itself.

**Comment by acwolff** [comment]
> However, pretty sure that you need to update size of your panorama viewer, and not the PhotoSwipe itself.
True, but I can’t find it yet how to do that.

Thanks for your help.

**Comment by acwolff** [comment]
@dimsemenov  I could solve the problem by delaying the creation of the Spherical Panorama Viewer in container #Pan_container untill, I think, the container's dimensions are  finalized:

    lightbox.on('contentActivate', (e) => {
          const spano = e.content.element.querySelector('#Pan_container');
            if (spano) {
	        if (!initCompleted) {  // set in event  'afterInit'
	                setTimeout(function() {
	                showSpherPan(spano);
	              }, 600);
	        }
	        if (initCompleted) {
	                showSpherPan(spano);
	        }
	}

But on a PC I can't navigate through the panorama with the mouse, I think there is a focus problem on a PC (It is OK on an iPad), see [my test album](https://andrewolff.jalbum.net/PS_SpherePan_PSV4/?1).

Do you have a hint for me how to solve this focus problem?

**Comment by dimsemenov** [comment]
To prevent default PhotoSwipe drag behavior you can do:

```js
pswp.on('pointerDown', (e) => {
  e.preventDefault();
});
```

You'll probably need to check for the target of the event (e.originalEvent.target) or the current slide.

**Comment by acwolff** [comment]
Yes, this solves the problem, see [this test album](https://andrewolff.jalbum.net/PS_SpherePan_PSV4/).

Thanks again  for your help!

**Comment by acwolff** [comment]
@dimsemenov  although your solution solves the focus problem, there are some unwanted site effects, because pointerdown is no longer working for normal images.

I apply your solution as follows:

I call showSpherPan(spano) in the 'contentActivate' event as shown above.
In function  showSpherPan I apply your solution:

```
function showSpherPan(div) {
     var PSV = new PhotoSphereViewer.Viewer({
                panorama: srcImg[slide_index],
                container: div,
      });
      pswp.on('pointerDown', (e) => {
        e.preventDefault();
      });
}
```

But if this function is once executed, the pointerdown function is no longer working for next normal images.

So I need a method to restore  the default pointerDown behaviour.

I tried this:

```
    lightbox.on('contentDeactivate', (e) => { 
      pswp.on('pointerDown', (e) => {
        return true;
      });
    });
```

But this does not work.

So I have these questions:

How can I restore the  default pointerDown behaviour?

I did not understand your remark “You'll probably need to check for the target of the event (e.originalEvent.target) or the current slide.”, but I should like if the preventDefault() action was only working for the panorama container. 
So I tried in function  showSpherPan:

```
      pswp.on('pointerDown', (e) => {
        div.preventDefault();
      });
```

div is set in the 'contentActivate' activate: e.content.element.querySelector('#Pan_container');

But tis is not working,.
So my question is how can I get this working for  only the panaorama container div?

**Comment by dimsemenov** [comment]
As I mentioned, you need to check for either event target or current slide data, something like:

```js
pswp.on('pointerDown', (e) => {
  if (e.originalEvent.target.classList.contains('something')) {
    e.preventDefault();
  }
});
```

or 

```js
pswp.on('pointerDown', (e) => {
  if (pswp.currSlide.data.type == 'something') {
    e.preventDefault();
  }
});
```

**Comment by acwolff** [comment]
OK @dimsemenov I will add that code.

Thanks for your help and your great libray,
