### ISSUE TITLE
Installation with NPM: Build pipeline

### ISSUE THREAD

**Issue by vielhuber** [dimsemenov/PhotoSwipe#1905]
In our build pipeline (which uses basic npm scripts with browserify and babelify) code from packages from node_modules are *not* transpiled (this is the default behaviour).

`import PhotoSwipeLightbox from 'photoswipe/lightbox';`

results in 

` Cannot find module 'photoswipe/lightbox'`

and

`import PhotoSwipeLightbox from 'photoswipe/dist/photoswipe-lightbox.esm.js';`

results in

`ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

It's not recommended to transform all of our files in node_modules so we expect to have a bundled version, which can be installed with npm.

Are there any plans for supporting this in the future?

**Comment by dimsemenov** [comment]
I'm not sure why this is happening, as you see on most setups work (for example https://codesandbox.io/s/vigorous-matan-zxok9x?file=/src/index.js).

If someone has any input on how to fix it - please let me know.

**Comment by vielhuber** [comment]
Thanks, that helped me.

I got it now to work: I needed to tell my build pipeline to transform the external dependencies in node_modules/photoswipe.
