### ISSUE TITLE
Close Photoswipe when focus leaves 

### ISSUE THREAD

**Issue by lmoeni** [dimsemenov/PhotoSwipe#1906]
Hi,

as far as I know it's currently (v5.2.4) possible to close Photoswipe by pressing "esc" or the close button. 
Alternatively, it would be great for keyboard-users to be able to close it when the focus leaves the Photoswipe element. 
Would it be possible to add this?

Kind regards

**Comment by dimsemenov** [comment]
Focus is trapped within PhotoSwipe on purpose, it's returned back to the original element when PhotoSwipe is closed. Not sure if it's a good idea to disable traping and auto-close PhotoSwipe.
