### ISSUE TITLE
Dfference between lightbox.pswp.currSlide.index and  pswp.currIndex?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1907]
I use a variable slide_index to fetch all data of a slide. This variable is fetched in the 'contentActivate' event:
slide_index=lightbox.pswp.currSlide.index; 

This was working fine if all my slides were images.

But if the first slide and next slides contains html code, it was not correctly working.

To see the problem, open [this test album](https://andrewolff.jalbum.net/PS_SpherePan_PSV4/), open the console (F12) and click on the first thumbnail. 
An html slide with a Spherical Panorama Viewer is displayed.
In the console myou see the lines:

lightbox.pswp.currSlide.index:  0  
pswp.currIndex:  0

This is generated by this code:

```
    lightbox.on('contentActivate', (e) => {
        slide_index= lightbox.pswp.currSlide.index;   
        console.log('contentActivate, element:', e.content.element, ' type:', e.content.type);
        console.log('lightbox.pswp.currSlide.index: ', lightbox.pswp.currSlide.index, ' pswp.currIndex: ', pswp.currIndex);
```

If you next click on the right arrow to display the next slide, you see that the displayed slide does not change except for the counter field.

In the console you see:

lightbox.pswp.currSlide.index:  0  
pswp.currIndex:  1

My html code is fetched with variable slide_index=lightbox.pswp.currSlide.index; which explains why the display is not changed.
The counter field is fetched with the value pswp.currIndex, so that is changed.

With the next clicks on the right arrow, both variables are raised by one, the difference stays equal to 1.

This problem is solved if  I use slide_index=pswp.currIndex

So my question is:

What is the dfference between lightbox.pswp.currSlide.index and  pswp.currIndex?

**Comment by dimsemenov** [comment]
`currSlide` property is assigned after `contentActivate` event that's why you see the difference. I might change this in future.

If you want to do something after the slide is switched, use `change` event.
