### ISSUE TITLE
How to fetch the caption of a html slide?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1908]
I use the  [Caption example code](https://photoswipe.com/caption/), which works fine if an image is displayed.
However in case the slide element is html code like a video, currSlideElement  in the code below is undefined.

```
            lightbox.pswp.on('change', () => {
              const currSlideElement = lightbox.pswp.currSlide.data.element;
              console.log('Caption change', currSlideElement) ;
              let captionHTML = '';
              if (currSlideElement) {
                  captionHTML = currSlideElement.dataset.caption;
              }
```

What should I change so that this works too for html contents?

I have the same problem in the Dynamic Caption plugin.

BTW Where can I find a description of lightbox.pswp.currSlide.data.element?

**Comment by dimsemenov** [comment]
`data` property contains all info that you provide, it's up to you how to parse and use it. 

`data.element` is defined when you initialize PhotoSwipe from dom (via options `gallery` and `children`), and it contains the reference to the corresponding element (generally a link). You may use various filters like `domItemData` to parse some custom properties https://photoswipe.com/data-sources/

**Comment by acwolff** [comment]
@dimsemenov  thanks for your quick answer to my last question, but you did not answer my first main question how to fetch the caption of a html slide in your example and in the Dynamic caption plugin.

**Comment by dimsemenov** [comment]
It's up yo you how to store and fetch it, dynamic caption plugin retrieves it based on `captionContent` option https://github.com/dimsemenov/photoswipe-dynamic-caption-plugin#captioncontent-pswp-caption-content

**Comment by dimsemenov** [comment]
> the caption is not retrieved for the 2nd slide, which is an html slide

Well if you provide the data to slide like this:

```
{
  html: '<div>My html slide</div>'
}
```

you'll need to adjust it to something like


```
{
  html: '<div>My html slide content</div>',
  myCaption: 'my caption content'
}
```

and then you can do  `slide.data.myCaption` to retrieve it.

As you see PhotoSwipe does not control such data, it's up to you how you provide it.

**Comment by acwolff** [comment]
Well, I did investigate it again and noticed that
`slide.data.element.dataset.caption; `  
did give the correct caption for a html slide, but apparently the rest of the dynamic caption plugin can't handle html contents, the plugin works only for images correctly.

I hope you will correct this in the future, but for now I will no longer use the Dynamic Caption Plugin if  there are html slides.

Thanks for the information you supplied.

**Comment by dimsemenov** [comment]
Dynamic caption plugin positions the text based on the dimensions of the image, so it does not work for content that has no size provided.
