### ISSUE TITLE
When trying to import photoSwipe to vue 3, it gives an error

### ISSUE THREAD

**Issue by Roman-00** [dimsemenov/PhotoSwipe#1918]
I want to use a photo swipe in my project, but when importing to vue 3 it gives an erro
![photo-swipe1](https://user-images.githubusercontent.com/58338625/168565228-17655a47-d64f-4ed3-99ae-d881196c55aa.jpg)
![photo-swipe-import](https://user-images.githubusercontent.com/58338625/168565242-7b0d5098-dd54-4643-820e-4791dfd8dbb0.jpg)
r

**Comment by wokalek** [comment]
It's types, not code
