### ISSUE TITLE
Make Images Fit Perfectly

### ISSUE THREAD

**Issue by TimoB2005** [dimsemenov/PhotoSwipe#1922]
Hello, i want to fit some images perfectly so that there is no weird free space.

Here is an example what i want:
![image](https://user-images.githubusercontent.com/83423736/170254936-fd1e2036-6d70-44ab-8394-8efdfacd4899.png)

What i get:
![image](https://user-images.githubusercontent.com/83423736/170255060-4d102f5c-93b9-4a61-aebc-d6d29c39bb95.png)

My HTML and PHP Code:

```
<div class="pswp-gallery pswp-gallery--single-column" id="gallery--werkbilder">
  <?php
  foreach ($dataProvider->getData() as $werk) {
      $srcImg = "/index.php?r=werke/downloadimagewatermark&id=" . $werk["werk_id"] . "&format=800x800&faketype=.png";
      $thumbImg = "/index.php?r=werke/downloadimagewatermark&id=" . $werk["werk_id"] . "&format=300x300&faketype=.png";
      
      echo '<a href="' . $srcImg . '" data-pswp-width="800" data-pswp-height="564" target="_blank">';
          echo '<img src="' . $thumbImg . '" alt="werkbild"/>';
      echo '</a>';
  }
  ?>
</div>
```

Is there an solution?

**Comment by dimsemenov** [comment]
Hi, I dont really understand why do you ask this in PhotoSwipe repo, but you might wanna look into https://github.com/flickr/justified-layout
