### ISSUE TITLE
PhotoSwipe on local MAMP (not connected to internet) not working

### ISSUE THREAD

**Issue by cleuenberg** [dimsemenov/PhotoSwipe#1925]
Hi there! For a tiny gallery script that reads some images from a folder via PHP we tried to implement PhotoSwipe. It's working perfectly as long as it's served through a public web server. When we try to serve this tiny script via a local environment based on MAMP, the lightbox is not functioning anymore. Any ideas on this? Javascript is not throwing any errors, it's just not working and opening the images in a new browser window.

This is how we setup PhotoSwipe in the HTML head:

```
<link rel="stylesheet" href="/vendor/photoswipe/photoswipe.css">
<script type="module">
    import PhotoSwipeLightbox from '/vendor/photoswipe/photoswipe-lightbox.esm.js';
    const lightbox = new PhotoSwipeLightbox({
        gallery: '#wsm-gallery',
        children: 'a',
        pswpModule: () => import('/vendor/photoswipe/photoswipe.esm.js')
    });
    lightbox.init();
</script>
```

The PHP script is looping the JPGs in a directory and writing links with thumbnails into our HTML output, container element has id `wsm-gallery`. As written above, working perfectly on our public server but not on a local webserver (that is not connected to the internet).

I would appreciate some help!
Thanks in advance!

**Comment by dimsemenov** [comment]
Likely, you're trying to load ES modules locally, and due to CORS of the browser or MAMP itself, the request is blocked.

PhotoSwipe now has an official UMD version - https://github.com/dimsemenov/PhotoSwipe/tree/master/dist/umd , which should help with this issue.
