### ISSUE TITLE
loadAndOpen: currSlide is undefined

### ISSUE THREAD

**Issue by jakedowns** [dimsemenov/PhotoSwipe#1927]
Has anyone else run into this issue when trying to open the lightbox v5 programmatically?

If i click the image, it opens, but if i try and open it via `loadAndOpen` i get this error:

![image](https://user-images.githubusercontent.com/1683122/171519232-55404775-3e65-40e6-9d0b-76b31798dd73.png)

```
photoswipe.esm.js?a03f:3657 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'content')
    at PhotoSwipe.updatePreloaderVisibility (photoswipe.esm.js?a03f:3657:1)
    at eval (photoswipe.esm.js?a03f:4288:1)
    at Array.forEach (<anonymous>)
    at PhotoSwipe.dispatch (photoswipe.esm.js?a03f:4287:1)
    at PhotoSwipe.init (photoswipe.esm.js?a03f:5902:1)
    at PhotoSwipeLightbox._openPhotoswipe (photoswipe-lightbox.esm.js?f827:1727:1)
    at eval (photoswipe-lightbox.esm.js?f827:1661:1)
```

**Comment by dimsemenov** [comment]
Can you please provide a reduced test case? You can fork any of playgrounds in docs https://photoswipe.com/getting-started/#initialization

**Comment by jakedowns** [comment]
@dimsemenov thanks for getting back to me so quickly

https://codepen.io/jakedowns/pen/NWyzNVM?editors=0011

it seems like it happens for me with the most basic example 

![image](https://user-images.githubusercontent.com/1683122/171718227-2e29c349-7c4a-4d8b-b4ce-fdfd060af0e8.png)

i guess i just don't know where in the lightbox lifecycle it's okay to call loadAndOpen

**Comment by jakedowns** [comment]
i've cloned the Data Sources example to a code pen: https://codepen.io/jakedowns/pen/NWyzNVM?editors=0011
 
 i guess the thing that i was missing is that in my project, i'm trying to use the `gallery` and `children` options, (parsing from a+img tags in dom)
 
 so, i guess i can just call a .click() on the image to trigger things, or change my project to use the DataSource array option
 unless there's a _different_ command i can use to load a specific slide without DataSource defined

**Comment by dimsemenov** [comment]
I guess documentation of `loadAndOpen` can be improved. 

If you use `gallery` and `children` options, `loadAndOpen` doesn't know which exactly gallery to use, since there might be multiple galleries on a page. Instead you can do something like:

```js
lightbox.loadAndOpen(0, {
  gallery: document.querySelector('.your-gallery-selector');
});
```

or just trigger click, as you mentioned.

**Comment by jakedowns** [comment]
awesome, thanks so much for taking the time to clarify. thanks for a GREAT library. currently upgrading a project that has used it for years to v5. 🙇‍♂️🙏🙌

**Comment by Thr0nSK** [comment]
I have the same issue but it happens whenever I call the init() method. I have everything in the onMounted() hook in a vue component. Any ideas what could be causing it?
```
onMounted(() => {
    lightbox = new PhotoSwipeLightbox({
        // set the gallery id
        gallery: props.galleryId.startsWith("#") ? props.galleryId : `#${props.galleryId}`,
        children: 'a',
        pswpModule: () => import('photoswipe')
    })

    lightbox?.init()
})
```

**Comment by Findus23** [comment]
@Thr0nSK Just in case it helps you:
I had the same error when I accidently imported the wrong module:
`import PhotoSwipeLightbox from "photoswipe"` instead of `import PhotoSwipeLightbox from "photoswipe/lightbox";`

**Comment by Thr0nSK** [comment]
> @Thr0nSK Just in case it helps you: I had the same error when I accidently imported the wrong module: `import PhotoSwipeLightbox from "photoswipe"` instead of `import PhotoSwipeLightbox from "photoswipe/lightbox";`

Thank you! This solved it but now typescript is unhappy 😅 ` Cannot find module 'photoswipe/lightbox' or its corresponding type declarations`
