### ISSUE TITLE
Use each image individually slide with dataSource

### ISSUE THREAD

**Issue by nicolasmatias** [dimsemenov/PhotoSwipe#1944]
Hi i try to use  image individually slide (https://photoswipe.com/getting-started/#open-each-image-individually) with dataSource content and not gallery ( i need infinite scroll in my page), but with dataSource photoswipe open all images and i can slide.

is there a method to do the same with a gallery ? ( gallery: '#gallery--individual a') ) Or a method to disable the right/left swipe to give the illusion?

**Comment by dimsemenov** [comment]
If your dataSource is an array - all you need is to pass one item per each gallery instance.
