### ISSUE TITLE
There is a way to trigger something when we click on the image to zoom in?

### ISSUE THREAD

**Issue by julesvaulont** [dimsemenov/PhotoSwipe#1945]
Hello,
There is a way to trigger something when we click on the image to zoom in?
I would love to remove arrows when we are "zooming" on the image.

**Comment by dimsemenov** [comment]
PhotoSwipe gets class `pswp--zoomed-in` when zoomed.

You can also listen for event `zoomPanUpdate` or use click actions -  https://photoswipe.com/click-and-tap-actions/

**Comment by julesvaulont** [comment]
Thank you so much for your answer and great lib!
