### ISSUE TITLE
V5: Zoom icon sometimes does not change to "(-)" when zooming in

### ISSUE THREAD

**Issue by arnowelzel** [dimsemenov/PhotoSwipe#1946]
It can happen, that the zoom icon stays in its initial "(+)" state when manually zooming an image partially with a pinch gesture on mobile devices or in desktop mode with [Ctrl]+[Mousewheel up].

See for example: https://wordpress-demo.arnowelzel.de/lightbox-with-photoswipe-5/

This can be reproduced with all images on that page.

It seems that the icon only changes to "(-)" if a certain zoom level is reached. However this is confusing as one would expect, that the "(+)" icon always means "zoom in" and its behaviour is not depending on how far the image was zoomed in yet.

The expected behaviour would be that the icon always reflects the action it will trigger when clicking it. So if the icon is "(+)" this means "zoom in" no matter  if the image is already zoomed in or not. If clicking the icon triggers "zoom out" then it should always be "(-)".

**Comment by arnowelzel** [comment]
Sample images - original state, zoomed partially, zoomed in full:

![image](https://user-images.githubusercontent.com/6613614/178220983-c12978dc-fb32-4384-856f-e773185fa0ac.png)

![image](https://user-images.githubusercontent.com/6613614/178221066-d3f503ac-47ac-4d0b-ba73-8180a0227194.png)

![image](https://user-images.githubusercontent.com/6613614/178221122-cc639b77-0b43-4bdb-8277-ced82b87da29.png)

**Comment by arnowelzel** [comment]
This is also reproducable with the sample images on https://photoswipe.com - so it seems this behaviour is be design(?).

**Comment by dimsemenov** [comment]
Yea, it's a bug for sure, I'll look into that.

**Comment by arnowelzel** [comment]
Just as a hint:

I just checked the example on https://photoswipe.com/adding-ui-elements/ which adds the zoom level as info in the lightbox. It seems the zoom icon will only change to "(-)" if the zoom level as at least 100%.

**Comment by dimsemenov** [comment]
Should be fixed now, thanks!
