### ISSUE TITLE
I want to get a long press event on the mobile side

### ISSUE THREAD

**Issue by WangJiaBin-LGX** [dimsemenov/PhotoSwipe#1948]
I want to get a long press event on the mobile side,And take the corresponding index as an argument,But it didn't,Is there any way to get it.

**Comment by dimsemenov** [comment]
PhotoSwipe doesn't listen for a long press, so you'll need to manually bind it, or use `pointerDown` PhotoSwipe event.

It also allows default browser action that allows saving/sharing the image, if you want to disable this - call preventDefault in pointerDown.

**Comment by WangJiaBin-LGX** [comment]
> PhotoSwipe doesn't listen for a long press, so you'll need to manually bind it, or use `pointerDown` PhotoSwipe event.
> 
> It also allows default browser action that allows saving/sharing the image, if you want to disable this - call preventDefault in pointerDown.

thanks

**Comment by WangJiaBin-LGX** [comment]
thanks
