### ISSUE TITLE
Missing release note or changelog.md

### ISSUE THREAD

**Issue by jimblue** [dimsemenov/PhotoSwipe#1959]
Hi,

I was wondering before upgrading to the freshly released `v5.3.2` (thank you btw 🙏🏼 ), what's new/breaking but I didn't found such informations on the repo.
It could be nice to keep tracking each releases [on the repo](https://github.com/dimsemenov/PhotoSwipe/releases) or maybe simply adding a `CHANGELOG.md` to the project ?

Cheers.

**Comment by dimsemenov** [comment]
You're right, I should totally add a changelog. The last update was a technical one, related to package.json, so there were no direct changes to the library.

**Comment by jimblue** [comment]
ok tks for the update 🙏🏼
