### ISSUE TITLE
Transitions are not working on an iPad

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#1973]
[This album](https://andrewolff.jalbum.net/LG_JustifiedGallery/) with transitions of 5 sec works correctly (although sometimes the image disappears during the transitions) on a Windows 10 PC and on my iPhone with iOS 16, but on my iPad with iOS 15.6.1 it is not working: I see no animations!

see also my post in issue #1966

**Comment by dimsemenov** [comment]
Please provide a reduced test case, from your demo it's hard to tell what might be causing this (especially "sometimes the image disappears" part). You may fork any of the playgrounds ([StackBlitz](https://stackblitz.com/edit/js-o1vrod?file=index.js), [CodeSandbox](https://codesandbox.io/s/vigorous-matan-zxok9x?file=/src/index.js), [CodePen (with unpkg)](https://codepen.io/dimsemenov/pen/ZEvypBw)).

Or try to disable third-party components/plugins temporarily.

**Comment by acwolff** [comment]
Here is an example: https://codepen.io/acwolff/pen/vYjaBwo which shows no transitions on my iPad

**Comment by acwolff** [comment]
No

**Comment by dimsemenov** [comment]
I'm unable to reproduce, open this page and let me know what alert do u get https://codepen.io/dimsemenov/pen/vYjaYwg

**Comment by acwolff** [comment]
Motion disabled.

What does that means, where can I enable it?

**Comment by acwolff** [comment]
You are correct, after a google search I could switch it on and the animation works.
I don’t know how this was switched off. And I was not aware that such a setting did exist!
