### ISSUE TITLE
V5 data-pswp-src not working in not is <a>

### ISSUE THREAD

**Issue by PersonalityFox** [dimsemenov/PhotoSwipe#1976]
Hi!

if use basic [example](https://photoswipe.com/getting-started/#basic-vanilla-js-example) and changed `<a>` tag to `<div>`, `<picture>` or something else

Prop `thumbSelector` doesn't change situation

sandbox https://stackblitz.com/edit/js-nlnaea?file=index.html,index.js

Maybe im use incorrect?

**Comment by dimsemenov** [comment]
For accessibility reasons the `<a>` is required by default. https://photoswipe.com/getting-started/#required-html-markup

If you want to use different markup there is a `domItemData` filter. Parsing `element` should help your case - https://photoswipe.com/data-sources/#custom-html-markup

**Comment by PersonalityFox** [comment]
Thanks for answer. 
I guess i got the solve to my problem.
