### ISSUE TITLE
How to add children as button ?

### ISSUE THREAD

**Issue by ProdesignerAgency** [dimsemenov/PhotoSwipe#1977]
Hello - amazing script :)

i have a problem with children elements:

const options = {
  gallery:'#gallery--click-to-next',
  children:'button',

How to add children as button ?

**Comment by dimsemenov** [comment]
For accessibility reasons the `<a>` is required by default. https://photoswipe.com/getting-started/#required-html-markup

If you want to use different markup there is a `domItemData` filter. Parsing `element` and should help your case - https://photoswipe.com/data-sources/#custom-html-markup
