### ISSUE TITLE
Opening or Closing Transition not working on your examples

### ISSUE THREAD

**Issue by carlo-fontanos** [dimsemenov/PhotoSwipe#1985]
On your website: https://photoswipe.com/opening-or-closing-transition/ the transitions on your examples don't seem to be working. I treid on other browsers and it's the same. it just opens the image without any animation. I also tried it personally with the code below but no transitions can be noticed. 

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/5.3.3/photoswipe.min.css">

<div class="pswp-gallery" id="my-gallery">
    <a
      href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/1/img-2500.jpg"
      data-pswp-width="1875"
      data-pswp-height="2500"
      target="_blank"
    >
      <img
        src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/1/img-200.jpg"
        alt=""
      />
    </a>
    <a
      href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/2/img-2500.jpg"
      data-pswp-width="1669"
      data-pswp-height="2500"
      target="_blank"
    >
      <img
        src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/2/img-200.jpg"
        alt=""
      />
    </a>
    <a
      href="https://cdn.photoswipe.com/photoswipe-demo-images/photos/3/img-2500.jpg"
      data-pswp-width="2500"
      data-pswp-height="1666"
      target="_blank"
    >
      <img
        src="https://cdn.photoswipe.com/photoswipe-demo-images/photos/3/img-200.jpg"
        alt=""
      />
    </a>
</div>

<script type="module">
import PhotoSwipeLightbox from 'https://cdnjs.cloudflare.com/ajax/libs/photoswipe/5.3.3/photoswipe-lightbox.esm.js';

const lightbox = new PhotoSwipeLightbox({
    gallery: '#my-gallery',
    children: 'a',
    showHideAnimationType: 'zoom',
    pswpModule: () => import('https://cdnjs.cloudflare.com/ajax/libs/photoswipe/5.3.3/photoswipe.esm.js'),
});

lightbox.init();
</script>
```

**Comment by cuixiping** [comment]
This bug also exists now.

**Comment by dimsemenov** [comment]
> This bug also exists now.

Perhaps you have https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion ?

**Comment by acwolff** [comment]
Animations do work, see this sample album:
https://www.andrewolff.nl/FotoSerie/IJsland/06/index.html

I use this code:

    import PhotoSwipeLightbox from './photoswipe/photoswipe-lightbox.esm.min.js'; 
    import PhotoSwipeDynamicCaption from './photoswipe/photoswipe-dynamic-caption-plugin.esm.min.js';
    const options = { 
    	  gallerySelector: '#gallery', 
    	  childSelector: 'a', 
    	  counter: false, 
    	  showHideAnimationType: 'zoom',
    	  showAnimationDuration: 800,
    	  hideAnimationDuration: 800,

**Comment by cuixiping** [comment]
@dimsemenov : CSS animation demos on MDN all work well in my browser.
@acwolff : The open(show) and close(hide) animations do not work on your link,

I tested in 2 web browsers: Chrome 138.0.0.0 + Firefox 141.0,  OS: Windows 10

**Comment by acwolff** [comment]
It works at my place under Windows 11 with the Chrome Browser Versie 138.0.7204.185 (Officiële build) (64-bits),
Firefox  141.03 64bits and Edge Versie 139.0.3405.86 (Officiële build) (64-bits)

It works too on my iPad ith the latest version of Chrome, Brave, Firefox and Edge.
