### ISSUE TITLE
No 'Download' link for source files

### ISSUE THREAD

**Issue by temirfe** [dimsemenov/PhotoSwipe#1990]
In official website inside Docs or Getting Started page there is no link to download source files (and no cdn links). It starts explaining straight from importing, but to import shouldn't I first download somewhere?

I see there is a way to download with npm or yarn, but those should not be de facto ways to download, what if I don't have npm or yarn and don't want to install them?

**Comment by acwolff** [comment]
Try the green button on this page: https://github.com/dimsemenov/PhotoSwipe
