### ISSUE TITLE
Is the showHideOpacity option still available in v5?

### ISSUE THREAD

**Issue by ianthedev** [dimsemenov/PhotoSwipe#1993]
My carousel has its left and right chevrons partially overlays on the left and right edges, respectively, of the active carousel item. And when PhotoSwipe is opening/closing, the chevrons are being partially overlayed by the PhotoSwipe element, too. Therefore, I need the [`showHideOpacity` option in v4](https://photoswipe.com/v4-docs/options.html) to make the latter overlay not noticeable.

I cannot find the `showHideOpacity` option in the [documentation of v5](https://photoswipe.com/options/). Is it still available in v5?

**Comment by dimsemenov** [comment]
Opening/closing transition is slightly changed from v4, you can read about it here https://photoswipe.com/opening-or-closing-transition/

`showHideOpacity` which allows animating scale and opacity at the same time is still available to partly allow backward compatibility but might be removed in the future.

If you have elements over your thumbnail - you can use techniques like https://photoswipe.com/opening-or-closing-transition/#hiding-elements-that-overlap-thumbnails to hide them while PhotoSwipe is opening. 

If you have elements within PhotoSwipe itself, check https://photoswipe.com/adding-ui-elements/ , or add class `pswp__hide-on-close` that will make the element fade in/out along with PhotoSwipe UI.
