### ISSUE TITLE
Broken animation on Chrome iOS after tab has been inactive

### ISSUE THREAD

**Issue by jeroenkroese** [dimsemenov/PhotoSwipe#2002]
**Reproduction steps**
- On iOS Chrome, navigate to https://photoswipe.com/
- Create a new tab and actively use tab for a while. (I navigated to a news page and clicked on 1 or 2 articles) 
- Go back to original photoswipe.com tab

**Result**
After having returned to the original tab, the transition animation now seems to have broken. The broken animation persists after reloading the page even. It can only be restored by force closing the browser.

I've implemented a workaround by listening to the `document:visibilitychange` event and re-initializing photoswipe in case `document.visibilityState === 'visible'`

**Comment by jeroenkroese** [comment]
After some more digging, this seems to be caused by a known bug in iOS Webkit. 

For further information:
https://bugs.webkit.org/show_bug.cgi?id=228333
https://bugs.chromium.org/p/chromium/issues/detail?id=1231712
https://bugs.chromium.org/p/chromium/issues/detail?id=899130
https://bugs.chromium.org/p/chromium/issues/detail?id=1249723

**Comment by dimsemenov** [comment]
ty for sharing

**Comment by brunodeangelis** [comment]
Hi, I'm having this issue even if the tab is active and just loaded. Is it still the same WebKit bug or maybe a bug in PhotoSwiper? Thanks

**Comment by brunodeangelis** [comment]
> @brunodeangelis  possibly your mobile device has "reduced motion" setting on?

Unfortunately no, double checked. If you happen to own an iOS 16.3 device, if you go to photoswipe homepage and just try it, does it work well? It doesn't for me.

Thanks for your help!

**Comment by dimsemenov** [comment]
yep, it works for me on 16.3. Check if this page works for you https://webkit.org/blog-files/prefers-reduced-motion/prm.htm

**Comment by brunodeangelis** [comment]
> yep, it works for me on 16.3. Check if this page works for you https://webkit.org/blog-files/prefers-reduced-motion/prm.htm

yes so the last video on that site is playing as soon as I open the page, which means that `prefers-reduced-motion` is supported and off. 

I've just checked my phone again and now it seems to be working fine 🤔 the only relevant change I made recently is I removed `overflow-x: hidden;` from the body tag. Perhaps that has something to do with it?
