### ISSUE TITLE
issues with custom data sources and webp

### ISSUE THREAD

**Issue by JoshBauguss** [dimsemenov/PhotoSwipe#2005]
I've been trying to implement photoswipe on a site that already uses picture elements.   So I had to use the dataSource option and some custom code to build a data source out of the existing list of picture elements.   I then implemented the webp code from the documentation so that the lightbox utilized responsive image sets.

I'm having a problem though.   When opening the lightbox, the second image viewed (via prev or next) is missing its style="width:x; height:y;" settings.  image gets displayed unconstrained and breaks the bounds of the lightbox. 

Click an image here
https://devsite.santafedrygoods.com/product/alonpi-cashmere-degrade-puka-poncho-with-leather-trim-in-black-brown/

once you cycle thru all the images however, the image shows up fine.  Can't figure out why this would be happening.

here is my code to build the options and init photoswipe

`<script type="module">

    let productImages = document.querySelectorAll(".images .image");

    import PhotoSwipeLightbox from '/wp-content/themes/sfdg/js/photoswipe-lightbox.min.js';

    var photoSwipeDataSource = new Array();

    for(var i=0; i < productImages.length; i++) {
      /*
        our images:
        small 550 x 791
        medium 800 x 1150
        large 1510 x 2170
      */
      
      if ( window.matchMedia("(min-width: 1400px)").matches ) {

        photoSwipeDataSource.push({
          srcset: '/images_products/pl/' + productImages[i].dataset.imageName + '_pl.jpg 1400w',
          webp: '/images_products/pl/' + productImages[i].dataset.imageName + '_pl.webp 1400w',
          src: '/images_products/pl/' + productImages[i].dataset.imageName + '_pl.jpg',
          width: 1510,
          height: 2170
        });

      } else if( window.matchMedia("(min-width: 768px)").matches ) {
        photoSwipeDataSource.push({
          srcset: '/images_products/pm/' + productImages[i].dataset.imageName + '_pm.jpg 1x, /images_products/pl/' + productImages[i].dataset.imageName + '_pl.jpg 2x',
          webp: '/images_products/pm/' + productImages[i].dataset.imageName + '_pm.webp 1x, /images_products/pl/' + productImages[i].dataset.imageName + '_pl.webp 2x',
          src: '/images_products/pm/' + productImages[i].dataset.imageName + '_pm.jpg',
          width: 1510,
          height: 2170
        });
      } else {
        photoSwipeDataSource.push({
          srcset: '/images_products/pm/' + productImages[i].dataset.imageName + '_pt.jpg 1x, /images_products/pm/' + productImages[i].dataset.imageName + '_pm.jpg 2x',
          src: '/images_products/pm/' + productImages[i].dataset.imageName + '_pt.jpg',
          webp: '/images_products/pm/' + productImages[i].dataset.imageName + '_pt.webp 1x, /images_products/pm/' + productImages[i].dataset.imageName + '_pm.webp 2x',
          width: 1510,
          height: 2170
        });
      }

    }

    const photoSwipeOptions = {
      dataSource: photoSwipeDataSource,
      showHideAnimationType: 'zoom',
      preload: [2, 2],
      pswpModule: () => import('/wp-content/themes/sfdg/js/photoswipe.min.js')
    }

    // use <picture> instead of <img>
    lightbox.on('contentLoadImage', (e) => {
        const { content, isLazy } = e;

        if (content.data.webp) {
          // prevent to stop the default behavior
          e.preventDefault();

          content.pictureElement = document.createElement('picture');
          
          const sourceWebp = document.createElement('source');
          sourceWebp.srcset = content.data.webp;
          sourceWebp.type = 'image/webp';

          const sourceJpg = document.createElement('source');
          sourceJpg.srcset = content.data.srcset;
          sourceJpg.type = 'image/jpeg';

          content.element = document.createElement('img');
          content.element.className = 'pswp__img';
          content.element.src = content.data.src;
          content.element.setAttribute('alt', '');

          content.pictureElement.appendChild(sourceWebp);
          content.pictureElement.appendChild(sourceJpg);
          content.pictureElement.appendChild(content.element);

          content.state = 'loading';

          if (content.element.complete) {
            content.onLoaded();
          } else {
            content.element.onload = () => {
              content.onLoaded();
            };

            content.element.onerror = () => {
              content.onError();
            };
          }
        }
    });

    // by default PhotoSwipe appends <img>,
    // but we want to append <picture>
    lightbox.on('contentAppendImage', (e) => {
      const { content } = e;
      if (content.pictureElement && !content.pictureElement.parentNode) {
        e.preventDefault();
        content.slide.container.appendChild(content.pictureElement);
      }
    });

    lightbox.init();

    //lightbox.loadAndOpen(0);
    jQuery(".images .image").on("click", function() {
      lightbox.loadAndOpen( jQuery(this).attr('data-image-number') - 1 );
    });

  </script>`

**Comment by JoshBauguss** [comment]
here is a screenshot as I see the image of the first instance of "next image" on my mac and my pc.   a coworkers computer showed the second image much smaller but still a little larger than the rest of the images.   
![image](https://user-images.githubusercontent.com/1903796/210107907-a01b851b-d733-4939-aa67-26155fab864b.png)

**Comment by JoshBauguss** [comment]
i've decided to take a different tactic and just show webp as normal images instead of picture elements, reverting to jpg if JS identifies iOS < version 14.   Hopefully a code maintainer will see this and see that the picture demo code via the documentation is broken.  For starters, the issue i had above with images not getting their style=width,height settings added.   second, when you loop thru images, it stops utilizing the picture element and reverts back to the standard img tag usage.   I didn't report this second issue until now as it was a later discovery.

**Comment by thomasnavarro** [comment]
Hi !
I've created a PR to fix the documentation, if it helps, try changing the name of your events (look at #2024)

Thomas
