### ISSUE TITLE
Avoid black frame before bigger image is loaded

### ISSUE THREAD

**Issue by step135** [dimsemenov/PhotoSwipe#2006]
For more consistency, all images before higher resolution image is loaded, should show lower resolution image from preview and not black frame. It can be also allowed to be able to set it how much blurry it will be. It is currently only the first image that behaves so.

**Comment by dimsemenov** [comment]
This is done on purpose, if you need a different behavior you may use `placeholderSrc` filter, https://photoswipe.com/filters/#placeholdersrc
