### ISSUE TITLE
Question: Proper way to inhibit panning / translate on html slides?

### ISSUE THREAD

**Issue by jchnkl** [dimsemenov/PhotoSwipe#2022]
After digging through the source I've found two (undocumented) ways for adding a custom html slide that's 100% in width and height while positioned at 0, 0:

1) return an initialZoomLevel object that evaluates to true with `!`:

The expression in L246 in `updateContentSize()` in [slide/slide.js#L241](https://github.com/dimsemenov/PhotoSwipe/blob/beb4810b17e90b8b01a8331974b4c66169cd23a5/src/js/slide/slide.js#L241) will evaluate to true and the function returns before any zooming and panning is applied. Actually, the transform property never gets set.

2) Use the undocumented `zoomPanUpdate` event to set `e.slide.pan = { x: 0, y: 0 };` which does basically the same, but sets the transform property, just with 0 values.

Which one should I use given that both are undocumented? The 2. method seems more reliable, but I like that the 1. method just skips setting the properties.

**Comment by dimsemenov** [comment]
I dn not fully understand your case, since if slide content is 100% in width and height while positioned at `0, 0` it cannot be panned, since there is nowhere it pan. To make it pannable, you need content to be wider or taller than the viewport.

You can create HTML slide with dimensions like:

```js
{
  type: 'my-custom-slide',
  html: '<div class="custom-html-slide">This is custom HTML slide</div>',
  width: 2000,
  height: 2000
}
```

... then you can make it zoomable by changing content or just via filter:

```js
lightbox.addFilter('isContentZoomable', (isContentZoomable, content) => {
  if (content.type === 'my-custom-slide') {
    return true;
  }
  return isContentZoomable;
});
```

... and lastly you can change zoomLevel to something like `fill` as with images https://photoswipe.com/adjusting-zoom-level/

The API/options that control pan position aren't implemented well yet, which I'd like to get changed, but you can check [initialZoomPan](https://github.com/dimsemenov/PhotoSwipe/blob/beb4810b17e90b8b01a8331974b4c66169cd23a5/src/js/slide/slide.js#L443) event. By default, it sets the pan position to `center`.

**Comment by jchnkl** [comment]
Hi Dmytro,

sorry if I phrased my question poorly. I'll try to do better.

I have a custom html slide, let's call it a product slide:

![Screen Shot 2023-03-06 at 14 19 50](https://user-images.githubusercontent.com/1392715/223121457-ef8301f6-3c61-4d9b-988c-eab8bc2a9fbb.png)

The markup looks roughly like this:

```html
<div class="product">

  <div class="product_image">
    <img alt="Ear of the Wind" src=".." width="2048" height="2048">
  </div>

  <div class="product_summary">
    <!-- more stuff -->
  </div>

</div>
```

I'm achieving this through a the `contentInit` and `contentLoad` event:

(Side question: should I prefer the `imageData` filter over the `contentInit` event? I couldn't find a compelling reason for distinguishing between them, besides that `contentInit` is called earlier)

```javascript
pswpLightbox.on('contentInit', e => {
  // 'product_id' is a custom property that I set elsewhere
  if ('product_id' in e.content.data) {
    e.content.type = 'html';
  }
});

pswpLightbox.on('contentLoad', e => {
  if ('product_id' in e.content.data) {
    e.preventDefault();
    e.content.element = document.createElement('div');

    jQuery.post(.., .., response => {
      e.content.element.innerHTML = response;
      const img = e.content.element.querySelector('.product_image img');
      img.src    = e.content.data.src;
      img.width  = e.content.data.width;
      img.height = e.content.data.height;
    });
  }
});

```

Naturally, I don't want to zoom in or pan around on that content unless the user clicks on the image and a separate lightbox opens (but that's a different topic).

I've tried different ways to achieve this:

1) This method will not set the CSS transform at all because of the way `updateContentSize()` works.

(Side remark: The documentation says that you can return the strings `fit` or `fill` but this doesn't actually work. Only numbers are accepted)

```javascript
initialZoomLevel: zoomLevelObject => {
  if ('product_id' in zoomLevelObject.itemData) {
    return 'nozoom';
  }
  return zoomLevelObject['fit'];
}
```

The DOM then looks like this:

![image](https://user-images.githubusercontent.com/1392715/223129355-66774d42-3144-4fa0-95f1-10328dfb5715.png)

2) Overriding the slide's pan information using the `zoomPanUpdate` event:

```javascript
pswpLightbox.on('zoomPanUpdate', e => {
  if ('product_id' in e.slide.data) {
    e.slide.pan = { x: 0, y: 0 };
  }
});
```
The DOM then looks like this:

![image](https://user-images.githubusercontent.com/1392715/223130233-2273db8c-a442-487e-a32d-99cf1ea8f798.png)

I prefer how the DOM looks like on the 1. method, but the 2. method seems to be much nicer implementation wise.

That's why I wanted to hear your opinion on this topic. :)

**Comment by dimsemenov** [comment]
Either is fine, but it's probably better to use `calcBounds` for this. It calculates where slide content is positioned by default (`bounds.center` coordinates), and how far it can be panned (`bounds.min` and `bounds.max`). It updates to the current zoom level and scale.

```js
lightbox.on('calcBounds', (e) => {
  const { bounds } = e.slide;

  bounds.center.x = 0;
  bounds.center.y = 0;

  console.log(`
    Zoom level ${bounds.currZoomLevel}
    Default pan x ${bounds.center.x}
    Min pan x ${bounds.min.x}
    Max pan x ${bounds.max.x}
  `);
});
```

> Side question: should I prefer the imageData filter over the contentInit event? I couldn't find a compelling reason for distinguishing between them, besides that contentInit is called earlier

Use `contentInit` if you're just overriding the content type.

**Comment by jchnkl** [comment]
Thanks for your help so far. I couldn't get any more work done on this in the past weeks so I'm closing this for now.
