### ISSUE TITLE
Are two arguments required for `loadAndOpen()`?

### ISSUE THREAD

**Issue by arayutw** [dimsemenov/PhotoSwipe#2026]
Hello. Thank you for your wonderful project.

I would like to check if the second argument of loadAndOpen(), DataSource, can be omitted.
Which is correct, types or the documentation?

```js
loadAndOpen(index: number, dataSource: DataSource, initialPoint?: import("../photoswipe.js").Point | null | undefined): boolean;
```
https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/types/lightbox/lightbox.d.ts#L85

```js
// Open slide by index
lightbox.loadAndOpen(0);
```
https://photoswipe.com/methods/#photoswipelightbox-methods

**Comment by dimsemenov** [comment]
Hi, I just added a section in the documentation with an example and some clarifications, let me know if it helps- https://photoswipe.com/methods/#open-lightbox-via-external-button-with-loadandopen

Types should be looked at as well.

**Comment by BeeMargarida** [comment]
The data source argument is not defined as optional, so it throws out an error when using it as `.loadAndOpen(0)`. As mentioned in https://photoswipe.com/methods/#photoswipelightbox-methods

**Comment by BeeMargarida** [comment]
That's great, thank you!
