### ISSUE TITLE
Typescript Error: "Cannot find module or its corresponding type declarations"

### ISSUE THREAD

**Issue by jnthnk** [dimsemenov/PhotoSwipe#2029]
**Hi devs.**

I'm running a react project with next.js v13 with typescript v5. And I keep getting a TS error even with the suggestions of this related issue: https://github.com/dimsemenov/PhotoSwipe/issues/1983.

If compilerOptions.moduleResolution is "node" the ts error is: "Cannot find module 'photoswipe/lightbox' or its corresponding type declarations.ts(2307)"

Is compilerOptions.moduleResolution is "node16" or "nodenext" the ts error is: "The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("photoswipe/lightbox")' call instead. To convert this file to an ECMAScript module, add the field "type": "module" to 'd:/project/package.json'.ts(1479)"

I mean... the code works and I even get types autocompletion, but i dont know the origin of the error. I supose that is related to some kind of incompatibility between compilation sources.

The only solution I find right now is setting a // @ts-ignore in the line above the import.

NEXTJS v13.2.4
REACTJS v18.2.0
TYPESCRIPT v5.0.2
PHOTOSWIPE v5.3.7

**Comment by dimsemenov** [comment]
Hi,

I'll look into it, possibly this will help you for now - https://github.com/dimsemenov/PhotoSwipe/pull/1957#issuecomment-1465595281

**Comment by jnthnk** [comment]
Hi @dimsemenov. Thx for your time.
The solution that recommend the cited comment doesn't work for me.
The error still remains: "Cannot find module 'photoswipe/dist/photoswipe-lightbox.esm.js' or its corresponding type declarations"

**Comment by spencerchang** [comment]
> Hi @dimsemenov. Thx for your time. The solution that recommend the cited comment doesn't work for me. The error still remains: "Cannot find module 'photoswipe/dist/photoswipe-lightbox.esm.js' or its corresponding type declarations"

Same issue.

**Comment by Yama-Tomo** [comment]
same issue.
My workaround was to create the ambient file.


```typescript
// src/types/photoswipe.d.ts
declare module 'photoswipe/lightbox' {
  import PhotoSwipeLightBox from 'photoswipe/dist/types/lightbox/lightbox'
  export default PhotoSwipeLightBox
}
```

```typescript
// src/some.tsx
import PhotoSwipeLightbox from 'photoswipe/lightbox'
...
// pswp is `PhotoSwipe` type
const pswp = new PhotoSwipeLightbox({ ... })
```

**Comment by DigitalNaut** [comment]
Is there a way to integrate this into the main library? It seems that many people are running into this issue

**Comment by smoglica** [comment]
The problem seems coming from `typesVersions` property from `package.json`

```
  "typesVersions": {
    "<4.7": {
      "lightbox": [
        "dist/types/lightbox/lightbox.d.ts"
      ]
    }
```

Right now types are working only with `typescript` < 4.7. Using `*` instead of `<4.7` should fix the problem, and types will be available for all typescript versions.
