### ISSUE TITLE
Custom content like WebP switches back to simple <img> with initial href source if you navigate next/prev fast

### ISSUE THREAD

**Issue by solemone** [dimsemenov/PhotoSwipe#2030]
Hello everyone,

thanks for the great work! PhotoSwipe is a beautiful!

I noticed something and I think it’s a bug. When I use custom content to display WebP images, the next/previous navigation doesn't work correctly. As soon as I **click next button or navigate with arrow keys very fast**, the custom `<picture>` markup is no longer used. Instead, the initial href source loads in a simple `<img>` tag.

I created a demo: https://photoswipe-demo.ivoherrmann.com/

To reproduce:
1. click on image in the demo
2. click next button or use arrow keys **fast multiple times**
3. inspect .pswp__zoom-wrap container, image is no `<picture>` tag

If I click slowly or open the image from the page it works. But not if I click fast.

I used the example code from: https://photoswipe.com/custom-content/#using-webp-image-format

**Comment by dimsemenov** [comment]
Possibly related to the recent PR, it seems this part isn't working

```js
lightbox.on('contentAppend', (e) => {
  const { content } = e;
  if (content.pictureElement && !content.pictureElement.parentNode) {
    e.preventDefault();
    content.slide.container.appendChild(content.pictureElement);
  }
});
```

since pictureElement`` has a parent even after the slide is removed, try adding something like:

```js
lightbox.on('contentRemove', (e) => {
  const { content } = e;
  if (content.pictureElement && content.pictureElement.parentNode) {
    content.pictureElement.remove();
  }
});
```

**Comment by solemone** [comment]
Hi @dimsemenov,

thanks for the fast response. I added:

```js
lightbox.on('contentRemove', (e) => {
  const { content } = e;
  if (content.pictureElement && content.pictureElement.parentNode) {
    content.pictureElement.remove();
  }
});
```
the `<picture>` is there but now the `<img>` is missing. Looks like this:

```html
<picture>
  <source srcset="/img/02-128.webp 128w, /img/02-256.webp 256w, /img/02.webp 1024w" type="image/webp">
  <source srcset="http://localhost:3000/img/02.png" type="image/png">
</picture>
```

I’ve updated the demo: https://photoswipe-demo.ivoherrmann.com/

Do I need to add the `<img>` in the `contentAppend` function?

**Comment by dimsemenov** [comment]
I'll look into it later, but `preventDefault()` the event should help at first glance.

**Comment by solemone** [comment]
Yes! It works! Thanks a lot @dimsemenov 

This is the complete block:

```js
lightbox.on('contentRemove', (e) => {
  const { content } = e;
  if (content.pictureElement && content.pictureElement.parentNode) {
    e.preventDefault();
    content.pictureElement.remove();
  }
});
```

**Comment by sorachan** [comment]
thanks for pointing me to `contentRemove`, followed the instructions in ["Custom Content"](https://photoswipe.com/custom-content/) to add video functionality to the gallery in [my repo](https://github.com/sorachan/soradru.ms) but `contentRemove` wasn't mentioned and I experienced glitchy behaviour when navigating the gallery, you should definitely add it there!
