### ISSUE TITLE
Are the selected images for a device in a SrcSet too small?

### ISSUE THREAD

**Issue by acwolff** [dimsemenov/PhotoSwipe#2032]
Dear Dimitry, I hope you are well, despite the terrible war the Russians are waging against your country! I find it very remarkable that despite all this misery you can manage to maintain your awesome  PhotoSwipe library!

I made [this PhotoSwipe test album](https://andrewolff.jalbum.net/Test_SrcSets_PS/) to test  your library with srcsets. For the first image there are 5 WEBP images and 1 jpg image generated. The WEBP images indicates the size as a string in the middle of the image. The largest image with a size 4000x3000 contains the text: 2.0: 4000x3000 (WEBP).
 For the first image I use the next code:

```
<div id="gallery" class="thumbs-jg thumbsgallery" >
<!-- Index table of images for a Jusified Gallery -->

<a id="s0" href= "slides/221122-134228_Cacela-MG.jpg" 
data-pswp-width="4000" data-pswp-height="3000" data-pswp-srcset="
slides/221122-134228_Cacela-MG-4000w.webp 4000w,
slides/221122-134228_Cacela-MG-3000w.webp 3000w,
slides/221122-134228_Cacela-MG-2600w.webp 2600w,
slides/221122-134228_Cacela-MG-2000w.webp 2000w,
slides/221122-134228_Cacela-MG.jpg 2000w,
slides/221122-134228_Cacela-MG-1000w.webp 1000w" 
data-caption=''>
<img src="thumbs/221122-134228_Cacela-MG.jpg" width="213" height="160" alt="" title="" />
</a>

```
For the first image are initially different sizes selected for  different devices:
iPhone XR:  0.5x: 1000x750 (WebP)
iPhone 13: 1.0x: 2000x1500 (WebP)
PC Monitor: 1.0x: 2000x1500 (WebP)
4k Laptop:  1.3x: 2600x1950 (WebP)

What I in particular like in your library: if I make the image larger on an iPhone with my fingers, automatically a larger image is selected!

However I think the images selected are too small for the used devices
For instance my laptop has a 4k monitor (3840x2160).
Your library selects for that monitor a WEBP image of 2600x1950, while I did expect that the 2x: 4000x3000 (WEBP) image should be selected.

I used these images too for testing the FancyBox light-box, see [this FancyBox test album](https://andrewolff.jalbum.net/Test_SrcSets_FB/) and the LightGallery light-box, see [this LightGallery test album](https://andrewolff.jalbum.net/Test_SrcSets_LG/).
Both libraries do select these images:

iPhone XR:   0.5x: 1000x750 (WebP)
iPhone 13:   1.0x: 2000x1500 (WebP)
PC Monitor: 1.3x: 2600x1950 (WebP)
4k Laptop:   2.0x: 4000x3000 (WebP)

Could you please explain why PhotoSwipe selects the smaller images?

Best regards,

André Wolff

**Comment by acwolff** [comment]
I am not sure what you mean or how I can select the requested width.
The selected image is  2300x1950. I see toolbars, but if I select full screen, you see that image 1.5: 3000x2250 (WEBP) is selected. I guess it has something to do with the  height of the image: if you display image 8 I see the expected image: 2.0x: 4000x1575 (WEBP).
Is the selection based on the width only or on the width and height of the screen?

**Comment by dimsemenov** [comment]
PhotoSwipe loads images corresponding to their displayed size. It takes into account both viewport size/dpi and image size.

For example, if the size of your gallery viewport is 3000x2000px and the image is a large square, the optimal image size would be 2000x2000 (assuming that you have a "fit" zoom level). So the browser will load the image at 2000px or larger.

The other two lightbox scripts that you linked assume that every image is as wide as the viewport. They do not know the size of images until they are loaded, so they cannot predict the optimal size. Thus in the above example, they'll load a variant that is larger or equal to 3000px, while PhotoSwipe will load >=2000px version.

I hope that makes sense...

If for whatever reason you want to load larger images than the actual displayed size, you can use filter [`srcsetSizesWidth`](https://github.com/dimsemenov/PhotoSwipe/blob/beb4810b17e90b8b01a8331974b4c66169cd23a5/src/js/slide/content.js#L299).

**Comment by acwolff** [comment]
Thanks for explaining, stay safe and healthy!
