### ISSUE TITLE
umd version, doesn't work without connection

### ISSUE THREAD

**Issue by JoranTab** [dimsemenov/PhotoSwipe#2041]
I'm using Photoswipe on a local website for an interactive kiosk that won't be connected to the Internet. 
I use the umb version (I have ajax navigation and can't do anything else).
I have both js locally (photoswipe.umd.min.js and photoswipe-lightbox.umd.min.js). Everything works fine when I'm connected to the Internet, but as soon as I disconnect the computer, photoswipe no longer launches. Any ideas?

**Comment by dimsemenov** [comment]
Can you show the source of your HTML page, please?

**Comment by JoranTab** [comment]
To make sure this isn't another problem with my site, I ran a test with the simple code you suggest, but with local images.
I tested it by putting it on my local server or on a normal folder and I'm having the same problem.  
Lightbox work when It's connected to Internet. As soon I disconnected, lightbox doesn't work anymore, even if I didn't reload the page...

Here is the code :


```
<!DOCTYPE html>
<html>
  <head>
    <title>Test Gallery</title>
  </head>
  <body>

    <script src="./photoswipe.umd.min.js"></script>
    <script src="./photoswipe-lightbox.umd.min.js"></script>
    
    <link rel="stylesheet" href="./photoswipe.css">

    <div class="test-gallery">
      <a href="./img-big.jpg" data-pswp-width="588" data-pswp-height="800">
        <img src="./img-small.jpg" alt="" />
      </a>
     
    </div>
    
    <script type="text/javascript">
      var lightbox = new PhotoSwipeLightbox({
        gallery: '.test-gallery',
        children: 'a',
        // dynamic import is not supported in UMD version
        pswpModule: PhotoSwipe 
      });
      lightbox.init();
    </script>

  </body>
</html>
```

**Comment by dimsemenov** [comment]
I'm not sure, what do you have in Console and any failed requests in Network?

**Comment by dimsemenov** [comment]
It might be because of `window.navigator.onLine` detection here https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/lightbox/lightbox.js#LL81C12-L81C35

I wonder if there should be an option to disable this feature detection or if it should be removed entirely.

**Comment by JoranTab** [comment]
It works when I remove this condition.
Thanks !
