### ISSUE TITLE
Remove pswp.mainScroll.isShifted() condition in appendHeavy() safe ?

### ISSUE THREAD

**Issue by JoranTab** [dimsemenov/PhotoSwipe#2043]
Hi !
I use the customGoTo to have a transition animation with the prev next arrow.

```
const customGoTo = (index, animate = false) => {
  const ctx = lightbox.pswp;
  index = ctx.getLoopedIndex(index);
  const indexChanged = ctx.mainScroll.moveIndexBy(index - ctx.potentialIndex, animate);

  if (indexChanged) {
    ctx.dispatch('afterGoto');
  }
}
lightbox.on('uiRegister', () => {
  lightbox.pswp.next = () => customGoTo(lightbox.pswp.potentialIndex + 1, true);
  lightbox.pswp.prev = () => customGoTo(lightbox.pswp.potentialIndex - 1, true);
});
```
It's work well.
But when you click quickly, there's a slight delay before the image is displayed every two images due to the condition : pswp.mainScroll.isShifted() in the appendHeavy().
(There's the same behavior if you swipe quickly to change image)

If I delete the condition, it doesn't append anymore.
But can it lead to other problems? 

Thanks !

**Comment by acwolff** [comment]
@dimsemenov what is your planning to include transition animation in the official version of PhotoSwipe?
What should I do to change the transition animation time in the code presented above?

**Comment by JoranTab** [comment]
@acwolff 
If you want to slow down the animation :
(i didn't success with css...)
The function moveIndexBy(); contains the code for the animation.
It's possible to slow the animation by lowering the value of naturalFrequency
     
 ```
pswp.animations.startSpring({
        isMainScroll: true,
        start: this.x,
        end: destinationX,
        velocity: velocityX || 0,
        naturalFrequency: 30,
        dampingRatio: 1, //0.7,
        onUpdate: (x) => {
          this.moveTo(x);
        },
        onComplete: () => {
          this.updateCurrItem();
          pswp.appendHeavy();
        }
      });
```

**Comment by acwolff** [comment]
@JoranTab, thanks for your help, I will certainly test this.

But I use minified versions, I don't like to change these files.

I hope that @dimsemenov will implement a way to change the naturalFrequency via an option, so that _ don't have to change the code of the library.
