### ISSUE TITLE
Missing "maxZoomLevel" in API > Options documentation

### ISSUE THREAD

**Issue by JPustkuchen** [dimsemenov/PhotoSwipe#2052]
https://photoswipe.com/options/ is missing the "maxZoomLevel" option described (only) at https://photoswipe.com/adjusting-zoom-level/ (or code-wise: https://github.com/search?q=repo%3Adimsemenov%2FPhotoSwipe%20maxZoomLevel&type=code)

You'd expect that https://photoswipe.com/options/ contains all options. As documentation shouldn't be duplicated for maxZoomLevel perhaps, perhaps link the page for details?

**Comment by joshsedl** [comment]
Agreed! Documenting this option would be really helpful! 👍

**Comment by JPustkuchen** [comment]
Here's the according pull request: https://github.com/JPustkuchen/PhotoSwipe/pull/1

**Comment by JPustkuchen** [comment]
Now the right one... https://github.com/dimsemenov/PhotoSwipe/pull/2053

**Comment by JPustkuchen** [comment]
Another thing that might be fixed is to document the (in code) defaults for the three values. I think they are not totally clear from the documentation?

**Comment by dimsemenov** [comment]
I adjusted the docs slightly and accepted the pr, thanks! If you feel like more changes are needed - feel free to submit another pr.

**Comment by JPustkuchen** [comment]
Thank you @dimsemenov  :)
