### ISSUE TITLE
Unexpected token '.' on iOS 12

### ISSUE THREAD

**Issue by ilikali** [dimsemenov/PhotoSwipe#2054]
Faced with this error on next js project on iOS 12 and lower

Unexpected token '.'
./node_modules/photoswipe/dist/photoswipe.esm.js
/_next/static/chunks/node_modules_react-photoswipe-gallery_dist_index_js.js:18:5

Maybe someone knows how to handle this issue.

Thanks

**Comment by dimsemenov** [comment]
Should be fixed by #2058

**Comment by ilikali** [comment]
Thanks
