### ISSUE TITLE
Can't add data-pswp-* to my images

### ISSUE THREAD

**Issue by popeating** [dimsemenov/PhotoSwipe#2056]
The pages im trying to use PhotoSwipe on, is coming (already in HTML formatted) from an API i can't modify.
I can initialize the lightbox correctly (i know the id/class of the gallery and of the children), but not having the data-pswp-width and data-pswp-height the images are opened in wrong size and filled to screen
i'm pretty sure the images are all quiete big, so i can force the w and h to (for example) 1200, but is there a way i can force and tell PhotoSwipe something like "if the data-pswp-width is missing use 1200"?

Thank you

**Comment by dimsemenov** [comment]
Unfortunately, PhotoSwipe isn't able to display images with unknown dimensions, a lot of its optimizations are based on the size of images. There are ways around it - https://github.com/dimsemenov/PhotoSwipe/issues/1988 But I'd suggest looking into other scripts if you're unable to retrieve the size.

**Comment by KnIfER** [comment]
you can add `data-pswp-*` attributes on click.
like so : 

```
var imgArr = [];
 // ...
function click_img(e){
	var H = parseInt(window.innerHeight)*2; // big H for zooming
	for(var i=0;i<imgArr.length;i++) {
		e = imgArr[i];
		var h = e.offsetHeight;
		e.setAttribute('data-pswp-width', parseInt(e.offsetWidth/h*H));
		e.setAttribute('data-pswp-height', parseInt(e.offsetHeight/h*H));
	}
}

div.addEventListener('click', click_img, true);
```

I am using it on my page, saving my time.

__
