### ISSUE TITLE
Use original image size and place it in the center

### ISSUE THREAD

**Issue by bsor-dev** [dimsemenov/PhotoSwipe#2063]
Is it possible to use the original image dimension? It looks like all available options needs to have width and height. And if I didn't include it, it forced to stretch and make the image full screen.

In lightgallery for [example](https://stackblitz.com/edit/lightgallery-react?file=index.tsx) you don't have to specify width and height and its responsive out of the box.

Is it doable here?

**Comment by bsor-dev** [comment]
Looks like dataSource html can do the thing

**Comment by acwolff** [comment]
> In lightgallery for [example](https://stackblitz.com/edit/lightgallery-react?file=index.tsx) you don't have to specify width and height and its responsive out of the box.

In lightgallery you give the width and height in the data-lg-size attrbute as you can see in your own example!
