### ISSUE TITLE
Photos not opening on Safari iOS 17

### ISSUE THREAD

**Issue by anergit** [dimsemenov/PhotoSwipe#2072]
I've implemented PhotoSwipe and it works great, but not in Safari on my iOS 17-device. When tap'ing the 'child', nothing happens.

iOS version: 17.0.3
Device: iPhone 14
PhotoSwipe version: 5.4.2
Browser: Safari
Browser agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0.1 Mobile/15E148 Safari/604.1"

Implementation:
        <script type="module">
          import PhotoSwipeLightbox from '/assets/vendor/photoswipe/photoswipe-lightbox.esm.js';
          const lightbox = new PhotoSwipeLightbox({
            gallery: '#items',
            children: '.lightItem',
            pswpModule: () => import('/assets/vendor/photoswipe/photoswipe.esm.js')
          });
          lightbox.init();
        </script>

Children:
<div id="items">
...
<a href="photo_lg.jpg" class="lightItem" data-pswp-width="320" data-pswp-height="320">
  <img src="photo_th.jpg">
</a>

I have tested my code with the following browsers and seen zero issues:
- Safari on iPadOS Version 16.2 ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15")
- Safari on macOS Version 16.4 (18615.1.26.110.1)
- Firefox Developer Edition on macOS 119.0b7 (64-bit)
- Chrome on Android 10 ("Mozilla/5.0 (Linux; Android 10; Android SDK built for arm64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Mobile Safari/537.36")

I've tried using a, div, span, etc. as children, yet the PhotoSwipe is never triggered

Please let me know if you need further information or testing on my part.

Thanks!

**Comment by anergit** [comment]
After spending hours trying to resolve the issue, PhotoSwipe suddenly works on Mobile Safari on iOS 17.0.3.

I have no clue what the issue was, other than a cache on my device. Sorry for the potential waste of time.

**Comment by zaaack93** [comment]
do you have any idea, because I'm facing the same issue :/ ?

**Comment by T-Damer** [comment]
Same issue on latest ios26.0 both in Safari WebView of Safari browser - lightbox simply won't open

https://github.com/user-attachments/assets/c7e242fd-3895-4a82-8b51-97319c19f991

**Comment by T-Damer** [comment]
Using onClick works:
```TSX
import 'photoswipe/style.css'
import PhotoSwipe from 'photoswipe'
import PhotoSwipeLightbox from 'photoswipe/lightbox'

const dataSource = photos.map((photo) => ({
  src: photo.url,
  width: photo.width,
  height: photo.height,
}))

const lightBox = new PhotoSwipeLightbox({ pswpModule: PhotoSwipe, dataSource, ... })
lightBox.init()
const onClick = (index: number) => lightbox.loadAndOpen(index)
<a onClick={onClick} />
```
But `showHideAnimationType: 'zoom'` turns into `fade`, which is not ideal
