### ISSUE TITLE
ImageClickAction function not triggered by tap on iPhone

### ISSUE THREAD

**Issue by tektsu** [dimsemenov/PhotoSwipe#2073]
When imageClickAction is set to a function, that function is triggered correctly when the image is clicked on with a mouse on a web browser. However, on my iPhone 11, tapping the image does not trigger the function. Instead, it shows the image with surrounding UI elements.

**Comment by dimsemenov** [comment]
This is by design, `imageClickAction ` and `bgClickAction` trigger only for mouse clicks.

```
tapAction: (releasePoint, e) => {}
```

https://photoswipe.com/click-and-tap-actions/
