### ISSUE TITLE
Support for CSP Policy

### ISSUE THREAD

**Issue by TheGreatestJannet** [dimsemenov/PhotoSwipe#2080]
I have a CSP Policy on my site to block inline `<script>`. I have tried to add the code to the JS file and add it to the HTML with `<script type="module" src="photoswipe-load.js"></script>` but this doesn't seem to work. Is there a way to load Photoswipe if script-src is blocking inline scripts?

**Comment by dimsemenov** [comment]
There are no PhotoSwipe-specific instructions, you may always put "inline" JS within a file, or bundle everything together.
