### ISSUE TITLE
Photoswipe with grid

### ISSUE THREAD

**Issue by Anunnaki26** [dimsemenov/PhotoSwipe#2085]
I would like to use Photoswipe in a static website.
 I like a picture gallery with a grid like https://wordpress.org/plugins/justified-gallery/ 
 unfortunately this is a WordPress plugin
 Is there also an overall solution for a static website where I can use an image gallery with photoswipe to create a grid?

**Comment by acwolff** [comment]
Yes, you could use jAlbum: https://andrewolff.jalbum.net/PS_Samples_AA/

**Comment by Anunnaki26** [comment]
thank you!
