### ISSUE TITLE
Html code for a simple gallery

### ISSUE THREAD

**Issue by Anunnaki26** [dimsemenov/PhotoSwipe#2086]
What is the HTML code for a simple image gallery???

**Comment by dimsemenov** [comment]
You can find it here https://photoswipe.com/getting-started/#basic-vanilla-js-example Playgrounds available there as well.

**Comment by dimsemenov** [comment]
It's hard to tell, I'd suggest looking at playgrounds such as https://codepen.io/dimsemenov/pen/ZEvypBw

**Comment by Anunnaki26** [comment]
Thank you for your answer.

 I have just seen that my html code is not displayed.
 Somehow it doesn't work.

 The example on Codepen works, but when I download the example, it doesn't work anymore

 My example is attached because I don't have a website yet.
 I would be very happy if you could let me know what I have to change.
 Thank you very much!

best regards, Isabell

[Beispiel.zip](https://github.com/dimsemenov/PhotoSwipe/files/13848952/Beispiel.zip)

**Comment by dimsemenov** [comment]
The selector for the gallery is not correct, you're using  `gallery: '#my-gallery'`, but it should be `gallery: '#galerie'` according to your HTML markup.

**Comment by Anunnaki26** [comment]
Thank you very much for your answer!
 I totally overlooked that.

 If I load the scripts from the CDN, it works.
 However, I would like to load the scripts from my own web space or locally on the computer, but unfortunately this does not work yet.

 How should the following line be?

`import PhotoSwipeLightbox from '/galerie/photoswipe-lightbox.esm.js';`

[Beispiel.zip](https://github.com/dimsemenov/PhotoSwipe/files/13852545/Beispiel.zip)

**Comment by Anunnaki26** [comment]
Unfortunately, that doesn't work either

`pswpModule: () => import('./galerie/photoswipe.esm.js')`
