### ISSUE TITLE
How should the relative path be?

### ISSUE THREAD

**Issue by Anunnaki26** [dimsemenov/PhotoSwipe#2087]
if I load the scripts from the CDN, it works.
However, I would like to load the scripts from my own web space or locally on the computer, but unfortunately this does not work yet.

How should the following line be?

`import PhotoSwipeLightbox from '/galerie/photoswipe-lightbox.esm.js';`

Unfortunately, that doesn't work either

`import PhotoSwipeLightbox from './galerie/photoswipe-lightbox.esm.js';`

[Beispiel.zip](https://github.com/dimsemenov/PhotoSwipe/files/13857891/Beispiel.zip)

**Comment by dimsemenov** [comment]
Note that you need a server to load a file this way, otherwise, the browser will likely block it via CORS policy. If you aren't sure about the path - use absolute path instead of relative, or learn how to use some JS bundler.

**Comment by Anunnaki26** [comment]
Thank you for this information!
 Have a nice day
