### ISSUE TITLE
Left/Right/Up/Down keys do not work in the textarea after closing PhotoSwipe.

### ISSUE THREAD

**Issue by txbsywcq** [dimsemenov/PhotoSwipe#2088]
In the latest version of PhotoSwipe, the normal sample code includes the following:
`<textarea rows="5" cols="50">
    This is a multi-line
    text with
    line breaks.
</textarea>`
The Left/Right/Up/Down keys work well in the textarea before opening PhotoSwipe, but they don't work after clicking to open and then close PhotoSwipe.

**Comment by dimsemenov** [comment]
Please provide a live example and let me know in which browser are you experiencing the issue, you may fork any of [the playgrounds](https://photoswipe.com/getting-started#initialization) in docs. As I'm unable to reproduce with the textarea that you posted.

**Comment by txbsywcq** [comment]
Sorry, I found that it's because of Tampermonkey v4.5. I disabled Tampermonkey and everything is OK.
