### ISSUE TITLE
Allow access to original keydown event when closing

### ISSUE THREAD

**Issue by dweerd** [dimsemenov/PhotoSwipe#2101]
Thanks for this great library! I use PhotoSwipe inside an overlay, which can normally be closed by pressing the escape key. But when I now close the PhotoSwipe gallery with escape, it also closes the overlay, since they both listen to the same keydown event. Could you make it possible to access the original keydown event that triggered the closing, so that I can call `stopImmediatePropagation` on it?

**Comment by dimsemenov** [comment]
PhotoSwipe has its own `keydown` event, you can `preventDefault` it https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/keyboard.js#L88

Or you can disable option `escKey` and bind native event manually.

**Comment by dweerd** [comment]
Thanks for your fast response. Your comment helped me solve it 👍.
