### ISSUE TITLE
The picture doesn't show up   （https://photoswipe.com/methods/#loadandopenindex-datasource-point）

### ISSUE THREAD

**Issue by chengwei123456** [dimsemenov/PhotoSwipe#2103]
In the demo case of loadAndOpen method under the Methods of documentation, I quickly used the mouse to switch the picture, and the picture would not be displayed. Note that I used the mouse to drag the picture instead of clicking the left and right button

**Comment by dimsemenov** [comment]
Thank you, I've managed to reproduce, should be fixed in 5.4.4 by https://github.com/dimsemenov/PhotoSwipe/commit/a0298e3b2b58cd01e678f8627142b15a7750f69d

**Comment by chengwei123456** [comment]
Thanks, it's very much in line with my expectations
