### ISSUE TITLE
Zoom factor and pswp.currSlide.zoomTo possible issues

### ISSUE THREAD

**Issue by Oleksandr-Dubiv** [dimsemenov/PhotoSwipe#2115]
Hi! Слава Україні і дякую за чудовий плагін!

Please, I wanted to know if I do something wrong or there's an issue in PhotoZoom v5.

There are 4 images 500x500 with corresponding 2560x2560 images. What I want to achieve: on lightbox **first opening** I need to see enlarged (~130%) image. All next images when I slide inside - should be regular ('fit'). Even if I go to next and then return back to previous - it should have zoom discarded (to 'fit') just like after manual zooming.
If you open it on mobile (that is the main target) you can see my attempts failing. I wanted to use on('change' event together with pswp.currSlide.zoomTo() but seems there are some issues (interface is stuck and zoom is blurred). Setting initialZoom is also not very good (please see comments to JS code). 
And also wanted to ask about strange math behind zoomFactors. My zoom factors are always less than 1 (0.14, 0.3). Seems like instead of intuitive 1, 2.5x mentioned in Docs - I need to specify scale relative to LAGEST image size. So 1 is always the size of 2560 image in my case. I was expecting them to be relative to small image (the one that is now 500px as thumbnail).

Thanks in advance!

tests are done in Chrome, Windows, devtools in mobile iPhoneSE view (reproducible on iOS too)

**Comment by dimsemenov** [comment]
PhotoSwipe does not have a direct API to adjust the zoom level of an inactive slide, since it does not render all at once. But you can look for it and reset its zoom level within `mainScroll.itemHolders`.

Your code `zoomLevelObject.index === lastClickedIndex ? 0.2 : 'fit'` isn't correct, since  `initialZoomLevel` function should return number, not a string.

Here is your example adjusted, hope it helps:

```js
let initialIndex;
let resetZoomLevel;

const lightbox = new PhotoSwipeLightbox({
  gallery: ".slider-mobile-pdp",
  children: "a",
  bgOpacity: 1,
  zoom: false,
  showHideAnimationType: 'fade',

  initialZoomLevel: (zoomLevels) => zoomLevels.index === initialIndex ? 1 : zoomLevels.fit,
  secondaryZoomLevel: 1,
  maxZoomLevel: 1.5,

  spacing: 0,
  pinchToClose: false,
  closeOnVerticalDrag: false,
  pswpModule: PhotoSwipe
});

lightbox.init();

lightbox.on('initialLayout', () => {
  resetZoomLevel = true;
  initialIndex = lightbox.pswp.currIndex;
});

lightbox.on('change', () => {
  if (resetZoomLevel && initialIndex !== lightbox.pswp.currIndex) {
    // find slide if it's rendered
    const holder  = pswp.mainScroll.itemHolders.find((holder) => {
      if (holder.slide && holder.slide.index === initialIndex) {
        return true;
      }
      return false;
    });

    if (holder) {
      // zoom it to the desired level
      holder.slide.zoomTo(holder.slide.zoomLevels.fit);
    }

    resetZoomLevel = false;
    initialIndex = null; // reset index
  }
});

```

> And also wanted to ask about strange math behind zoomFactors. My zoom factors are always less than 1 (0.14, 0.3). Seems like instead of intuitive 1, 2.5x mentioned in Docs - I need to specify scale relative to LAGEST image size. So 1 is always the size of 2560 image in my case. I was expecting them to be relative to small image (the one that is now 500px as thumbnail).

`1` is an original image size (2560px in your case). If you want it to be based on viewport size, rather than image size - feel free to calculate it. https://photoswipe.com/adjusting-zoom-level/#supported-values

**Comment by dimsemenov** [comment]
> whenever image is zoomed in on iOS - it's flickering for a half of second at the moment when max resolution image appears

Try reducing the size of the image itself, or the rendered size. You'll likely end up with issues like this if you try to animate 2600x2600 images on an older iOS phone.

> when initial slide is zoomed in (like in code we have now) - you can't zoom out it by pinch

Option `pinchToClose`. Double tap zoom is controlled based on `secondaryZoomLevel`.
