### ISSUE TITLE
Close photoswipe on background click on mobile

### ISSUE THREAD

**Issue by purpleFade** [dimsemenov/PhotoSwipe#2126]
Hello everyone! I'm curious if it is possible to close image when I click on background on mobile? Need this functionality, but didn't find it on docs. Thanks!
@dimsemenov

**Comment by acwolff** [comment]
I use this option:

```
	  imageClickAction: (releasePoint, e) => {  playpause() },    
	  tapAction: (pt, evt) => {
 	    if (evt.target.classList.contains('pswp__img')) {
	        if (isImage) playpause();
 	    } else {
	        pswp.close();
 	    }
	  },
```

**Comment by purpleFade** [comment]
> I use this option:
> 
> ```
> 	  imageClickAction: (releasePoint, e) => {  playpause() },    
> 	  tapAction: (pt, evt) => {
>  	    if (evt.target.classList.contains('pswp__img')) {
> 	        if (isImage) playpause();
>  	    } else {
> 	        pswp.close();
>  	    }
> 	  },
> ```

thank you for reply
Actually, I found out how to solve my problem. Just add to new instance of PhotoSwipeLightbox nexto code :

```
tapAction: (pt, e) => {
    if (e.target.classList.contains('pswp__img')) {
        pswp.next();
    } else {
        pswp.close();
    }
},
```
