### ISSUE TITLE
HTML captions

### ISSUE THREAD

**Issue by superlooper** [dimsemenov/PhotoSwipe#242]
I'm an absolute beginner when it comes to JS unfortunately and have a deadline so no express JS courses sadly... Has anyone modified the script to support HTML captions? This is how my HTML is setup:

```
<a href="images/full/001.jpg" title="insert title here" alt="insert alt here" />
<div id="details">
<h3>Some title</h3>
<ul>
<li>Credit: Unknown Photographer</li>  
<li>Medium: silver gelatin photograph</li> 
<li>Collection: lorem ipsum</li>  
<li>Catalogue #: xxxxxxxx-xx</li>
</ul>
</div>
<img src="images/thumb/001.jpg" alt="insert alt here" /></a>
```

How would you grab the 'details' div and insert it into the caption area? And do this for multiple different images/details so they are linked up. I've narrowed it down to altering the getImageCaption function on line 2322 of the script but as I said, I'm a noob :( Would you have to give the details div an class for the styles and an id number so the script knows which image relates to which description? Appreciate any help or to hear from anyone who has successfully implemented HTML captions into this awesome almost perfect gallery

**Comment by felipekp** [comment]
I still have this issue. Anyone solved it? (I did look into the other threads and found nothing).
