### ISSUE TITLE
Prevent photoswipe from ever hiding the toolbar

### ISSUE THREAD

**Issue by RomaDotDev** [dimsemenov/PhotoSwipe#319]
Even I set up  

captionAndToolbarAutoHideDelay: 0
and
captionAndToolbarHide: false

the caption and toolbar hides automatically when I start slideshow or just click an image.

I got the same issue as discussed here: 
http://stackoverflow.com/questions/9876744/prevent-photoswipe-from-ever-hiding-the-toolbar

Could you please add new feature to the code preventing photoswipe from ever hiding the toolbar?

P.S.

I found lifehack solution to prevent hiding via css:

```
.ps-caption{
    opacity:0.8 !important;
    display:block !important;
}

.ps-toolbar{
    opacity:0.8 !important;
    display:table !important;
}   
```

but there should be a way doing it programmically.

**Comment by mrbluecoat** [comment]
For anyone looking for a fix with a more recent version:

```
.pswp__top-bar, .pswp__button {
    opacity:1 !important;
}
```

**Comment by VARGA-Peter** [comment]
This could be also implemented as an option. Somehow it reminds me on WordPress where you need also _hundreds of CSS hacks_ in order to get the page working the way you want to.
