### ISSUE TITLE
Is this project still alive? - ideas requests for a fork

### ISSUE THREAD

**Issue by chrisben** [dimsemenov/PhotoSwipe#322]
I haven't seen any code change or even issues / pull requests processed for several months now (6 months since last release).

If the code maintainers don't have further plans to support this project, please let us know so that we can keep photoswipe alive and extend it into a new separate fork.
If I get no reply to this message, that will mean a No..

**Comment by brendanfalkowski** [comment]
See these:

* https://twitter.com/PhotoSwipe/status/444134042787930113
* https://github.com/dimsemenov/photoswipe#about

"Old PhotoSwipe" is for issues before the plugin (which looked dead) was rewritten. The new version is a big improvement.

**Comment by jareware** [comment]
Got it, thanks!

**Comment by apuntovanini** [comment]
The questions is still valid now though, isn't it? @dimsemenov
