### ISSUE TITLE
Linking to a specific image. How?

### ISSUE THREAD

**Issue by NiklasBr** [dimsemenov/PhotoSwipe#387]
I am looking for documentation on how to link to a certain photo in the carousel (from links in the caption) but every sliver of documentation found has been of not help unfortunately :(

This is the code I have been trying:

var options = { enableMouseWheel: false , enableKeyboard: true, captionAndToolbarShowEmptyCaptions: false, captionAndToolbarAutoHideDelay: 2500, captionAndToolbarFlipPosition: true, imageScaleMethod: "fitNoUpscale" };

var widescreenPhotoSwipe = $("#gallery a.widescreen").photoSwipe(options);

$(document).on('click', '.ps-caption a', function(event) {

event.preventDefault();

// Does not work  
//widescreenPhotoSwipe[1].instance.carousel.show();

// Does not work
//widescreenPhotoSwipe[0].instance.carousel.show(1);

// Does not work
//widescreenPhotoSwipe.photoSwipeInstance.show(1);

// Does not work
//Code.widescreenPhotoSwipe.activeInstance.carousel.show(1);

});

**Comment by prabhathAmila** [comment]
hi 
please tell how to add jump to page input field in this photoswipe gallery

Thnkyou
