### ISSUE TITLE
Using PhotoSwipe Plugin for hundreds of images effectively 

### ISSUE THREAD

**Issue by kinjal-codes** [dimsemenov/PhotoSwipe#448]
I am creating a mobile site which consumes and API of images using jquery ajax . I have database of about 10,000 images . I will be fetching 10 images json at a time . JSON array contains image url and title . Once user reaches last image of those images  . I need to make another json call to fetch next 10 images . How can I do this ?

Also if I can call that ajax while I am on 8th image so that user dont wait on every 10th image it would be great . Also while user is looking at 1st image is it possible to download next 5 image so user don't have to wait ?

**Comment by 3zzy** [comment]
I need this as well, what did you end up doing?
