### ISSUE TITLE
Dragging Thumbnails Inside Carousel Triggers PhotoSwipe FullScreen

### ISSUE THREAD

**Issue by mcnejef** [dimsemenov/PhotoSwipe#512]
I'm trying to use PhotoSwipe on thumbnails that are displayed in a draggable touch carousel.  So, if I grab the touch carousel and move it left/right, and I happen to be grabbing on one of the thumbnails and not the margins between photos, when I let off the click it triggers the PhotoSwipe gallery to open.

I'm guessing this is due to how PhotoSwipe is binding to click events.  I don't see any options that set click speed or even something that disables click when a swipe distance is detected.  Anyone tried to use PhotoSwipe like this and found a solution?  If not, I'm wondering if this can be a feature request...

**Comment by tedw** [comment]
@dimsemenov For people using PhotoSwipe in a carousel that supports dragging/swiping, how can we avoid opening the lightbox inadvertently? For example, if I click on an image and drag, that image will open in the lightbox on mouseup. I can’t seem to find a way to tell PhotoSwipe not to open under certain conditions. I saw the [Click Actions](https://photoswipe.com/click-and-tap-actions/) page but those only appear to work when the lightbox is open. Any suggestions would be much appreciated.

Thanks for all of your work on this plugin!
