### ISSUE TITLE
Feature Request: Swipe using next/previous button

### ISSUE THREAD

**Issue by pratik91s** [dimsemenov/PhotoSwipe#519]
Hi,

Currently on click of next/previous button, images are changes directly without slide/swipe effect (like it does with mouse/finger swipe left/right).

Is it possible to add swipe effect (so that images will slide from left/right) on next/previous button click?

Please suggest.

**Comment by Larzans** [comment]
This setting does not exist anymore, does anybody know how to do the pan animation to the next / previous slide?

**Comment by HimanshuParekh** [comment]
Hello,
Owl Carousel Slider not working  in Photo Swipe next previous Button Please Help Me
