### ISSUE TITLE
Photoswipe for Phoca Gallery

### ISSUE THREAD

**Issue by petjez** [dimsemenov/PhotoSwipe#521]
Hi,

Has someone already tries to embed Photowsipe into Phoca Gallery. Phoca Gallery is a Joomla component. http://www.phoca.cz/phocagallery

Patrick

**Comment by PhocaCz** [comment]
Hi, Photoswipe is now implemented in Phoca Gallery, see demo:
http://www.phoca.cz/phocacartdemo/phoca-gallery
You can enable it in Options of Phoca Gallery.

Anyway, thank you very much for this great library.

Jan
