### ISSUE TITLE
Photoswipe initiates and then goes blank

### ISSUE THREAD

**Issue by designjockey** [dimsemenov/PhotoSwipe#56]
I just wanted to log this issue in case someone else bumped into this problem! I spent a day troubleshooting this bug and finally found out what was causing this.

Issue: When clicked on the thumbnail, the Photoswipe gallery would initiate for a couple of seconds and then go completely blank and show a blank page throwing a "e.document.body is null" error in Firebug.

Troubleshooting find: When initiated, Photoswipe was immediately getting re-directed to another page which was blank. The blank page would just show a busy icon, as if it were loading the page.

Cause and solution: Eventually I found out that the Google Analytics javascript was causing this issue, when Photoswipe initiated, it was firing the GA pixel which would redirect to a blank page and get stuck in an infinite loop. I removed the GA code and this issue was fixed!

**Comment by SulaimanZahir94** [comment]
I am using ASP.Net Web Forms and I have tried all the themes mentioned but to no avail !
can you help me please ?
