### ISSUE TITLE
Integration with angularjs

### ISSUE THREAD

**Issue by dbuarque** [dimsemenov/PhotoSwipe#580]
Hi, i have tried to integrate photoswipe and angularjs but at the moment i have found some problems.

When i click in an image Photoswipe rewrite the url adding an anchor to current url 

Current URL:
http://localhost:8000/#/view2

After Click:
http://localhost:8000/#/view2#PhotoSwipe1375822623328

When i click in an image Photoswipe rewrite the url adding an anchor to current url.
AngularJs uses # to create routes and when a route is not found it try to redirect to another url.

This problem not occurs in chrome, i don't know why.

I would like to know if is possible remove this behaviour of PhotoSwipe or if someone have a trick.

Regards!

**Comment by thesafetylemur** [comment]
For those who are stumbling across this now or in the future, it looks like the "backButtonHideEnabled" has been replaced with "history":
`{history: false}`

**Comment by nozreh** [comment]
Hi any sample code for this? been looking to implement this the right way in Angular

**Comment by luismanuel001** [comment]
any angular directive for photoswipe?

**Comment by Patrick-Fieger** [comment]
Thanks guys, saved me hours too :+1:

**Comment by maxime1992** [comment]
@dbuarque can you share your implementation within Angular ? :smile:

**Comment by mutac** [comment]
:+1: :beers:

**Comment by diogomachado** [comment]
Thanks @thesafetylemur!
