### ISSUE TITLE
Photo position on scroll down

### ISSUE THREAD

**Issue by rodi01** [dimsemenov/PhotoSwipe#60]
Steps to reproduce:
1. Using safari mobile, go to http://examples.oncemade.com/ps_test/jquery-mobile.html
2. Scroll down to the bottom of the page
3. tap on any of the images on the last row.

If you tap on any photo without scrolling the page, it works just fine.

thanks
Rodrigo

**Comment by vinodkumar30** [comment]
I am also having the same issue on android browsers (default, Chrome & Firefox) & iphone 4s (safari). iphone 5c (safari) works fine. I am using v4.0
