### ISSUE TITLE
Photoswipe not working with in iFrame in desktop as well as mobile/tablets

### ISSUE THREAD

**Issue by hussainv** [dimsemenov/PhotoSwipe#616]
Put http://www.photoswipe.com/latest/examples/04-jquery-mobile.html#Gallery1 URL in Iframe and try to use in either divices ..

Window is opening direct image URL instead of photoswipe player.

**Comment by tmli3b3rm4n** [comment]
This should be reopened.

**Comment by theonlylawislove** [comment]
I agree. PhotoSwipe needs to support iFrames for the people willing to deal with the site effects.
