### ISSUE TITLE
Multiple Galleries

### ISSUE THREAD

**Issue by bilal-karim** [dimsemenov/PhotoSwipe#654]
I am trying to enable multiple galleries, but can’t seem to get them to work. I thought using the same class (`.my-simple-gallery`) would do the trick. I reckon it must be related to `document.querySelectorAll`? If I change the index to 1, then the second gallery works, but not the first one. My forked CodePen can be found here: http://codepen.io/anon/pen/XJXgax

Thanks for creating this fantastic gallery. It’s really smooth.

**Comment by rugor** [comment]
Building off the 'multiple galleries' notion, anyone know how to do a multiple _inline_ gallery implementation?

**Comment by rugor** [comment]
In case anyone's wondering, the answer seems to be to add and remove the .pswp template to the relative parent div dynamically.
