### ISSUE TITLE
Scrollable caption / Prevent default event?

### ISSUE THREAD

**Issue by fidoboy** [dimsemenov/PhotoSwipe#657]
I'm trying to modify the ui javascript. I wan't to prevent default or stop propagation when user drag over the caption, to allow overflow-y scroll... how can i prevent default behaviour to stop image dragging? I suppose that i should use the _listen function to catch the _shout event but i'm not sure about how to do it

**Comment by rkumarat** [comment]
If you check the link http://www.internationaltravellermag.com/five-uniquely-salzburgian-experiences/#&gid=1&pid=1

this has the pswp__scroll-wrap as 80% and the caption sa 20% but still it has disabled the mouse wheal scrolling.

Cant figure it out . 

Please suggest.

**Comment by zerodburn** [comment]
@rkumarat I have been tasked to come up with a design that is extremely similar to that one, thanks for that link. Basically I'd like the photoswipe section to be on the left at around 80% with 20% caption/text desc area, but only when the viewport is wide enough, e.g. min-width: 1024px. I promise to create a codepen after or during my project showing a basic stripped down version of it.

**Comment by acwolff** [comment]
See my solution: [#1408](https://github.com/dimsemenov/PhotoSwipe/issues/1408)
