### ISSUE TITLE
gif animation can not be played on iOS 8

### ISSUE THREAD

**Issue by liuweifeng** [dimsemenov/PhotoSwipe#662]
Sorry for my poor English.
If the gif is the first image, no problem; if you slide from the other image to th gif, the gif not be played on iOS 8

[Demo is here ~](http://codepen.io/anon/pen/MYKqwL)

**Comment by andfinally** [comment]
@dimsemenov PhotoSwipe is great, thanks! With animated GIFs, I wonder if it would reduce repaints and improve performance to apply visibility: hidden to the parents of non-current images?

**Comment by andfinally** [comment]
@dimsemenov PhotoSwipe is great, thanks! Have you considered applying visibility: hidden to the parents of non-current images? Maybe this will reduce repaints and improve performance when some of the images are animated GIFs.

**Comment by dimsemenov** [comment]
@andfinally, PhotoSwipe keeps only 3 slides in DOM, I don't think that hiding 2 nearby slides will increase performance much, but it should be tested to tell for sure. You can hide them in `afterChange`  event `gallery.itemHolders[0]`, `gallery.itemHolders[2]` are prev and next slide DOM elements.

**Comment by andfinally** [comment]
@dimsemenov I see, thanks!
