### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by pyronaur** [dimsemenov/PhotoSwipe#666]
_I've already solved the problem, adding here to document the problem, in case someone runs into this as I did_

`Uncaught TypeError: Cannot read property 'x' of undefined` error threw me off for a good 2 hours.

I read almost every line of the Call Stack in chrome debugger, ( it lead _equalizePoints() ), going back and forth until I discovered, that I had specified the images object like this:

```
image.push({ src: "http://----.jpg", width: 100, height 100 });
```

As it turns out, the expected keys for width & height are `w` and `h`, and not `width` or `height`.

I assume that because PhotoSwipe is still in beta, there is no throwing of error helpful error messages, when data is missing. A _"No width or height of image found"_ would have been very helpful, instead I tried to inspect the bounds of my images, try to figure out when and what is called, etc.

**Comment by merqurio** [comment]
thanks @justnorris this saved my day

**Comment by gabfusi** [comment]
thanks @justnorris , same as above

**Comment by quikchan** [comment]
Mine is not this, all properties with the correct name, but the error persists...

I did a console.log and the first object of the array is a little odd, it show more info than {src, h, w} ...

**Comment by oguzhankahyaoglu** [comment]
i was using the jquery init script in documentation however, i was randomly facing the issue. I am using this with jquerymobile by the way. 
The way i solved was; i changed .pswp selector code (because it was referring the first pswp template, in jquerymobile, lots of pages are cached in document and it was easily referring to inactive page's pswp template
`        var pswpElement = $('.pswp', page())[0], `
to
`        var pswpElement = document.querySelectorAll('.pswp')[0], `

Note: `page()` is a shortcut for `$.mobile.activePage` btw.

**Comment by m2gleason** [comment]
@ghost how did you managed to solve this problem. I have this problem too. thanks

**Comment by oguzhankahyaoglu** [comment]
> @m2gleason I told you the story :) you have to find the second line (document.querySelectorAll) in source code and replace it with the first.
Reason of the issue was, jquery mobile is actually caching pages, thus, document.querySelectorAll('.pswp') code refers to multiple photoswipe divs, which are located at inactive pages. 
page() was a shortcut by the way!

**Comment by Ronnyrr** [comment]
I'm also facing this issue. My code did work for a few times. I don't know what I've changed but it ain't work anymore. 

No jQuery involved. I use vanilla JS and ES6.
`const pswpElement = document.querySelectorAll('.pswp')[0];`
and for images
`const galleryImgs = document.querySelectorAll('.gallery__image');`

All elements exists. 

`const gallery = new PhotoSwipe(pswpElement, false, imgArray); // galleryOptions
gallery.init();`

Any idea?
What can be done to fix this?

**Comment by chesio** [comment]
Hi @Ronnyrr,

You can get the same message for a different reason - you should start a new thread (note that this one is resolved/closed) and provide a stack trace for the error message.

Greets,
Česlav

**Comment by fkamlesh** [comment]
Hello @justnorris ,

Can you describe were I have change to sole this problem.

I have same issue, Please help

**Comment by fkamlesh** [comment]
I is solve for me, when I unique the html.
ie; I am using this piece of in kendo ui multiple view.

Now I change it and use in single view, than it running fine.

Thank you all. :)

**Comment by anil826** [comment]
Same issue not working some time in chrome
All elements exists.
const gallery = new PhotoSwipe(pswpElement, false, imgArray); // galleryOptions gallery.init();

Any idea?
What can be done to fix this?

**Comment by ciaala** [comment]
thanks !
It helped me.

**Comment by edgarberlinck** [comment]
I use angular.js and solved this problem moving the pswp div to my index.html. Works fine!

**Comment by anilenbake** [comment]
I do the same but not working it's working on page load for ipad devices and browser.
Can you describe were I have change to sole this problem.
I have same issue, Please help

**Comment by AlessandroDallafina** [comment]
Just read this thread because I had the same issue. I solved it when coming across a typo.  

Make sure to double check all the sizes especially the `x` symbol.  In my case, this code `1280×1323 ` was triggering the error. 

`×` (&#215;) is a totally different char than `x` (&#120;) besides being visually very similar.
Dumb mistakes are always the toughest to spot! Hope this can help someone out there!

**Comment by rafaelboschini** [comment]
I had the same issue works on angular2.

"TypeError","description":"Cannot read property 'x' of undefined"
"TypeError","description":"Cannot read property 'lastChild' of undefined"
"TypeError","description":"Cannot read property 'top' of undefined"

**Comment by kkcode24** [comment]
You can add HTML code dynamically via JS ，And Then: 
```
var pswp = new PhotoSwipe(/* ... */);

pswp.listen('close', function(e, target) { 
    // remove html dom
});

```

**Comment by rafaelboschini** [comment]
Not work :(

**Comment by edgarberlinck** [comment]
@rafaelboschini I had this issue on Angular 1.6 because my controller was referencing a "non exists anymore element". I don't work with angular 2 but I think if you read all responses on this thread you will find the solution

**Comment by LJ906** [comment]
thanks,I had the same issue as yours, I suddenly realize the mistake when I read this.

**Comment by MaxPower01** [comment]
Thank you @justnorris !! I lost about 2 hours today because of this... Pretty glad to have found your answer

**Comment by Furqan311** [comment]
I have also faced the same error, I thought I should post the solution; it might help someone.

I have solved the problem by providing the value to `data-size="1600x1068"` attribute.
