### ISSUE TITLE
Crash on iPhone

### ISSUE THREAD

**Issue by hadrienl** [dimsemenov/PhotoSwipe#670]
Hi,

I've integrated PhotoSwipe on my photoblog by using your script in get started page. It works very well, but not on iPhone. On Chrome and iOS simulator, no problem, but on my iPhone 6 plus, the page crash everytime the photoswipe is init and the page reload. You can test it here : http://hadrien.photo/2014/10/tgs-2014.html

**Comment by Alcorn888** [comment]
А какие размеры изображений должны быть, чтобы галерея работала в ios? Попробовал jpeg 440x440px и повисло всё, это изображение даже меньше, чем экран iphone 5. Может там какая-то бесконечная рекурсия вешает мобильный сафари? И можно ли как-то это обойти?
