### ISSUE TITLE
zoom to 100% on retina displays

### ISSUE THREAD

**Issue by turboooo** [dimsemenov/PhotoSwipe#698]
Hi,

currently Photoswipe zooms to 200% on retina devices like the retina Macbook Pro and iPads when you click/tap in an image - as a viewer you get the impression that the images are not sharp..could you address that issue?

**Comment by turboooo** [comment]
Thanks for looking into this!
Although the getDoubleTapZoom option is set to 1 for mouseclicks it still zooms to 200% on retina Macbooks - on regular screens it works perfect. Same goes for retina iPads, if set to 1 it will zoom to 200%. Setting it to 0.5 would probably fix it for retina displays but then not work on legacy displays.

**Comment by dimsemenov** [comment]
@turboooo, as I posted before, it's by design. If you want different behaviour - modify `getDoubleTapZoom` option so it depends on `window.devicePixelRatio` and returns 0.5 when devicePixelRatio is >2.

**Comment by turboooo** [comment]
@dimsemenov cool thx, i got that working now.

**Comment by JoxC** [comment]
For retina screen, the item image width and height should be scaled down by the devicePixelRation, then zoom level being 100% will be okay for any case.  Right?
