### ISSUE TITLE
Adding your own hooks behind menu button - Android

### ISSUE THREAD

**Issue by devshisiyani** [dimsemenov/PhotoSwipe#699]
I have managed to add my own hooks behind the photoswipe menu options. I did this my changing the file photoswipe-ui-default.js. Modified code 

```
shareButtons: [
				{id:'share', label:'Share', url:'shareImage(' + "'"+ '{{raw_image_url}}'+ "'"+ ')'},
				{id:'download', label:'Download image', url:'downloadImage(' + "'"+ '{{raw_image_url}}'+ "'"+ ')', download:true}
```

and also code

```
"shareButtonOut += '<a href="#" onClick="'+shareURL+ '"; class="pswp__share--' + shareButtonData.id + '" ' + '>' + shareButtonData.label + '</a>'"
```

This generated the correct html code onClick.
This calls to javascript function 'downloadimage' and it works but the menu option stays active and does not close until i move onto next image or click somewhere else in the window.
Adding target="_blank" in the html menu code creates appears to work but creates new window.

All I want to do is when user clicks download, I want my javascript function to be called to download on android. Is there a better way?

**Comment by dimsemenov** [comment]
Closed by https://github.com/dimsemenov/PhotoSwipe/commit/27ee76d1be2a17975c83a5a99cd3be3b5b216048 and https://github.com/dimsemenov/PhotoSwipe/commit/44220ae173ca420f62368980d27a724b73a3b3b4
