### ISSUE TITLE
getCurrentIndex does not always return integer

### ISSUE THREAD

**Issue by thexeos** [dimsemenov/PhotoSwipe#701]
pswp.getCurrentIndex() is said to return integer, however if the options array contained string representation of the number, the returned value would be string as well. It does not affect the core functionality, however it causes problems for things like PhotoSwipeUI_Default:

    [line 648] pswp.getCurrentIndex() + 1

For index '0' in a gallery of 12 elements, it would return '01/12' and for index '10' it would return '101/12'.

It sounds like it would be the dev's fault for passing the options argument which is not integer, but on other side, the exposed method (getCurrentIndex) is documented to return integer at all times.

**Comment by dimsemenov** [comment]
> if the options array contained string representation of the number, the returned value would be string as well

Options object must contain Integer representation of index, not String. Currently there are no plans to parse option value, you should do this by yourself (`parseInt( ..., 10)`).
