### ISSUE TITLE
image quality on @2x screens

### ISSUE THREAD

**Issue by turboooo** [dimsemenov/PhotoSwipe#704]
When zoomed at 100%, images are not displayed correctly on Safari and Chrome (they loose sharpness, contrast and detail). Firefox renders pixel perfect already.
I think there are subpixel translations going on that decrease display quality and maybe performance, too. When i change the following translate3d values to integer values in webkit inspector, it will display pixel perfect on chrome and safari:
   ` <div class="pswp__zoom-wrap" style="transform: translate3d(-205.935982339956px, -663.715231788079px, 0px) scale(0.5);">`

Maybe changing the way that browsers do the downscaling interpolation from bilinear or cubic to nearest neighbor or so can improve performance and sharpness even further.

![sharpness](https://cloud.githubusercontent.com/assets/10312848/5596241/68feeaec-9289-11e4-81ea-07e4608ce198.jpg)

**Comment by dimsemenov** [comment]
Please download the latest version of core JS file and let me know if you see any improvements.

Pan offset is now always rounded when image is static (after animation or gesture). But during the animations and gestures pan offset is still not rounded. Tests showed that animations look much more smooth when position is not rounded.

**Comment by turboooo** [comment]
Great, now they display correctly at 100% and the animations are as smooth as before!
