### ISSUE TITLE
time to idle timeout should be reset also on mouse click events (actually only on mouse move)

### ISSUE THREAD

**Issue by fabiocaccamo** [dimsemenov/PhotoSwipe#706]

**Comment by dimsemenov** [comment]
It's quite questionable. I don't think that it's bad that controls hide when user clicks on next/prev buttons or on image to zoom it. Please provide more details on why do you think that it's important.

**Comment by fabiocaccamo** [comment]
scenario: I'm looking a gallery and I'm clicking on the next button every 2 seconds, after some seconds the control under my mouse disappear but I can continue to click it. I don't think it's correct.

**Comment by dimsemenov** [comment]
It'll cause UI flickering, e.g. you examine image for 3 seconds - controls hide - you clicks next - controls appear - you examine second image for 3 seconds - controls hide - you clicks next - controls appear...

It's much more pleasant to view images without any distractions.

Maybe forcing visibility of element when mouse is over it will be a solution, e.g.:

```css
.pswp__button--arrow--right:hover {
    opacity: 1 !important;
}
```

**Comment by fabiocaccamo** [comment]
To prevent flickering I could work in this way:
if the controls are hidden, they don't appears, but if the controls are still visible just reset the timeout to prevent that controls disappears immediately after a click.

**Comment by dimsemenov** [comment]
I'll think about it.
