### ISSUE TITLE
custom picture id to use for history

### ISSUE THREAD

**Issue by fabiocaccamo** [dimsemenov/PhotoSwipe#708]
Actually pictures ids are based on photo index (this is good as default behavior), 
but indexes could change in galleries that gets updated or in galleries where it's possible to apply some filters.

The consequence is that a direct link will not point always to the same photo, 
so whenever possible it could be nice having the possibility to use a custom picture id.

**Comment by dimsemenov** [comment]
It's a good idea. but I'll code this not earlier than in a month, as there are more important things for now.

So feel free to submit pull request for `history.js`.

**Comment by luger95** [comment]
I also have the same need. What is this development?

Can we use aliases? Example: my-photo-50

Thank you.

**Comment by rogerbinns** [comment]
Hopefully the implementation could be as simple as adding a label in the slides with a fallback to the slide number.

**Comment by swa66** [comment]
Need this to get the reference working as the selection of pictures I want to show isn't static ...
(e.g. show 30 pictures out of a collection of a few thousand)
The mere sequence number it was when previously shown is not enough to make sure it's included in the current set.
Really need a "permanent" ID that I can set myself in the items/slides array.

**Comment by mwarwick** [comment]
I just submitted a pull request to facilitate this important feature. Once merged, the items array may contain "pid" properties (e.g. {src: 'foo', w: 123, h: 456, pid: 'photo789'} ) and these will carry forward into the history hash as the gallery is browsed. Suggestions for detection of custom pid aliases on page view may be found in the pull.

**Comment by dimsemenov** [comment]
Done: http://photoswipe.com/documentation/faq.html#custom-pid-in-url

Also code from Gettings Started section of docs modified to support custom PIDs http://photoswipe.com/documentation/getting-started.html#dom-to-slide-objects  https://github.com/dimsemenov/PhotoSwipe/commit/907d45aed47f2a402490b8baffe90eef3d8d0f4b

If you have some feedback – please post.
