### ISSUE TITLE
The 4.0.3 release doesn't have the version number updated.

### ISSUE THREAD

**Issue by kelan** [dimsemenov/PhotoSwipe#710]
I just noticed that the 4.0.3 release (downloaded from [here](https://github.com/dimsemenov/PhotoSwipe/releases/tag/v4.0.3), or via `bower`) has `4.0.2` in its `bower.json`, instead of `4.0.3`.

It looks like it does indeed include the change from the previous commit (e1e01f89f82), so it's functionally correct, but it is a little confusing.

**Comment by dimsemenov** [comment]
Yea, I messed up, fixed now.

**Comment by kelan** [comment]
:+1: Thanks!
