### ISSUE TITLE
Adding slides dynamically - caching issue

### ISSUE THREAD

**Issue by dave8401** [dimsemenov/PhotoSwipe#711]
Commit b2af02f4 got dynamic images mostly working for me. However I do face a strange *caching* issue:

I use [Array.prototype.splice](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) to add new items like this:

    photoSwipeInstance.items.splice(index, 0, {
      id: child.get('id'),
      src: child.get('src'),
      msrc: child.get('msrc'),
      w: child.get('w'),
      h: child.get('h')
    });

Should the current slide be affected (insert before current index, current slide, next slide) I call:

    photoSwipeInstance.invalidateCurrItems();
    photoSwipeInstance.updateSize(true);
    photoSwipeInstance.goTo(newIndex);

The index (Slide X/Y) is correctly updated and I stay on the correct slide.  
My issue is that when I swipe left/right the slides sometimes show 'old' images. 

I noticed that when I swipe to the *last slide* and iterate over the slides again (start at 1/X) the issue disappears. For the time being I hacked together a *cache buster* like this:

    // cache buster ... otherwise img may be 'stuck' until next slide cycle
    for (var i = 0; i < photoSwipeInstance.items.length; i++) {
      photoSwipeInstance.next();
    }

Is that *caching* intentional? Can I somehow clear the cache and force a re-render for selected slides?

**Comment by dimsemenov** [comment]
I see, looking into it.

> For the time being I hacked together a cache buster like this:

It's a very bad idea to clear cache like so. Don't do that.

**Comment by dimsemenov** [comment]
Try [updated photoswipe.js](https://gist.github.com/dimsemenov/3d29969b301c46b0dc10) and let me know if it fixes your issue.

If you'll find any other bugs related to dynamic adding/removing items, I'll be grateful if you let me know.

If everything is ok, I'll push changes to main repo.

**Comment by dave8401** [comment]
This version is much better. Thank you very much! 

Occasionally I do end up with a *black* slide or with a stuck one but I'm not able to consistently reproduce it (very rarely). From my tests it seems to be best to always call

    photoSwipeInstance.invalidateCurrItems();
    photoSwipeInstance.updateSize(true);
    photoSwipeInstance.ui.update();

after slides have been added. Maybe that's because I'm testing with very few slides (1-4) right now.

**Comment by dimsemenov** [comment]
Theoretically, there might be issue when going from 3 to 2 or 1, as `loop` option is automatically disabled when less than 3 slides are used. 

So if you have low number of slides, set loop:false initially.

**Comment by dave8401** [comment]
Thanks! Could you cut a new version 4.0.4 and publish?
