### ISSUE TITLE
After update from 4.0.0 to 4.0.3 iOS safari no longer has zoom transition?

### ISSUE THREAD

**Issue by lasseyls** [dimsemenov/PhotoSwipe#712]
I updated photoswipe from 4.0.0 to 4.0.3 and now the photos no longer zoom in/out upon opening/closing the gallery? Did some setting change or do you have any idea why this is the new behavior? 

Great gallery by the way! Some really cool ideas put in to it!

**Comment by dimsemenov** [comment]
Can you repeat the issue on main demo page? What iOS version and device?

**Comment by lasseyls** [comment]
No that page works. However the transitions works fine on desktop and in chrome while emulating an iPhone. It's just on the actual device it doesn't work, is there anywhere you could point me that seems logical in correspondence with the above? Somewhere where there is a check and logic switch that detects the device? Or could it be something memory related that breaks the transition on device?

**Comment by dimsemenov** [comment]
Can you link to page with issue?

**Comment by dimsemenov** [comment]
Make sure that images aren't huge, it's the only reason I can think of for now.

**Comment by lasseyls** [comment]
Yeah, I have e-mailed you a private test link. The same problem occurs with small images.

**Comment by dimsemenov** [comment]
Not sure if I can find style `-webkit-transition: -webkit-transform ...` on `pswp__zoom-wrap` element on your page https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe.css#L92

**Comment by lasseyls** [comment]
You are correct, I guess maybe that was prefixed in main.scss in version 4.0.0? Anyway I added autoprefixer to my build script and now it works perfect.
