### ISSUE TITLE
links dont work's in container with my class-simple-gallery

### ISSUE THREAD

**Issue by FEAR93** [dimsemenov/PhotoSwipe#713]
links dont work's in container with my class-simple-gallery.
You can fix this?

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by FEAR93** [comment]
Example gallery with thumbnails reproduces the problem.

**Comment by dimsemenov** [comment]
Please describe the problem more precisely. And provide a reduced test case that reproduces the problem.

**Comment by FEAR93** [comment]
Пытаюсь адаптировать Вашу галерею к phpBB.
Класс  my-simple-gallery получается присвоить только всему сообщению. Галерея работает отлично, только остальные ссылки в посте не работают.
Как уже говорил, пример используется этот http://codepen.io/dimsemenov/pen/ZYbPJM
Вот html код, который у меня генерируется
<div class="content my-simple-gallery" data-pswp-uid="5">
  <figure itemscope="" itemtype="http://schema.org/ImageObject">
    <a href="./download/file.php?id=18&mode=view" itemprop="contentUrl" data-size="1362x2048">
      <img src="./download/file.php?id=18&t=1" itemprop="thumbnail" alt="FiC1t_8nspw.jpg">
    </a>
  </figure>
  <figure itemscope="" itemtype="http://schema.org/ImageObject">
    <a href="./download/file.php?id=18&mode=view" itemprop="contentUrl" data-size="1362x2048">
      <img src="./download/file.php?id=18&t=1" itemprop="thumbnail" alt="FiC1t_8nspw.jpg">
    </a>
  </figure>
  <figure itemscope="" itemtype="http://schema.org/ImageObject">
    <a href="./download/file.php?id=18&mode=view" itemprop="contentUrl" data-size="1362x2048">
      <img src="./download/file.php?id=18&t=1" itemprop="thumbnail" alt="FiC1t_8nspw.jpg">
    </a>
  </figure>
</div>
Если ссылка находится в сообщении, то есть внутри сло <div class="content my-simple-gallery" data-pswp-uid="5"> она не работает. То есть при нажатии на ссылку ничего не происходит.

**Comment by dimsemenov** [comment]
You'll need to modify code from documentation, this line:

```
galleryElements[i].onclick = onThumbnailsClick;
```

binds click event.

If you're not experienced in JS - I can't assist you, sorry.

**Comment by FEAR93** [comment]
thank you

**Comment by lexbi** [comment]
Just had this.

It was because I had not included the hidden markup that you're meant to include on the page.
