### ISSUE TITLE
Share Menu item stays visible

### ISSUE THREAD

**Issue by devshisiyani** [dimsemenov/PhotoSwipe#715]
On android phone using phonegap, I have successfully managed to add my own hooks to the share menu buttons. I have managed to get the download image and share buttons working. One issue I have is that when the share menu item is clicked the share menu item stays up and is visible. When I move to the next image the menu item  is still visible and displayed. When this visible down load button is selected again the previous image is selected and downloaded. This does not happen on chrome browser only android phones. Not sure how to close down the share menu Item when the next image is selected using finger swipe. The menu is only removed if you tap on the image which appears to refresh the page and the menu item disappears. 

How can get rid of the menu item when the user moves onto the next image using finger swipe.

Thank for you help.

**Comment by dimsemenov** [comment]
So you're saying that after share modal is open, tap on dark overlay refreshes the page? Please get unmnified version of UI and debug why it refreshes the page, function that redirects to sharing website is `_openWindowPopup` https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L191

> How can get rid of the menu item when the user moves onto the next image using finger swipe.

"Hide share modal during swipe gesture" will be done.
