### ISSUE TITLE
Bad print image

### ISSUE THREAD

**Issue by protoror** [dimsemenov/PhotoSwipe#716]
If i zoom image and click print preview in ff i get 3 page (http://savepic.ru/6610672.jpg)
test page: http://termoteks.ru/catalog/2014

Не понимаю почему отображается 3 страницы в предварительном просмотре, в идеале картинка должна занимать всю страницу. Может как вариант добавить кнопку печать?

**Comment by dimsemenov** [comment]
Printing won't work properly with fixed-positioned elements. You'll need to code custom print function, for example like described here - http://stackoverflow.com/questions/20612870/print-image-with-javascript or http://stackoverflow.com/questions/2909033/using-javascript-to-print-images

**Comment by protoror** [comment]
could you add print button to default UI?

**Comment by protoror** [comment]
beautiful print made in the implementation of a viewing in inbox app, after click preview image

**Comment by protoror** [comment]
may be u add print image like download image in drop menu?
