### ISSUE TITLE
Photoswipe does not open if page is scrolled

### ISSUE THREAD

**Issue by anonrab** [dimsemenov/PhotoSwipe#718]
If the page is scrolled, the gallery is not displayed and the page scrolls up. If not scrolled - displayed correctly.
In the console no errors displayed.
Example http://codepen.io/anonrab/pen/yyMYar

Если страница прокручена, галерея не отображается, а страница прокручивается наверх. Если не прокручена - отображается корректно. 
В консоль никаких ошибок не выводится. 
Пример на сайте codepen http://codepen.io/anonrab/pen/yyMYar

**Comment by anonrab** [comment]
If link contains #, photoswipe do not shows.
Проблема в ссылках - href="#" прокручивает страницу наверх, но при этом каким то образом блочит photoswipe.

**Comment by dimsemenov** [comment]
If you link to `#` and won't call preventDefault on click (or `return false`) - page scrolls to top. As PhotoSwipe closes when user scrolls - it opens and immediately closes.

change to:

```js
res += '<a class="html-journal" onclick=\"showGallery(%id);return false;\" href=\"#\">Журнал %id</a>'
```

and you'll be fine
