### ISSUE TITLE
Problem with page refresh in IE11

### ISSUE THREAD

**Issue by dogsout** [dimsemenov/PhotoSwipe#719]
Hi. The plugin looks great , thank you very much . But testing it locally there is a problem in IE11. When I refresh the page when lightbox opened , and after the close lightbox browser address bar changes (for example, C:\xampp\htdocs\mysite\index.html changes to C:\C:\xampp\htdocs\mysite\index.htm). As a result, the next page refresh I see "page not found" massage. In Chrome and Firefox all works perfectly.

**Comment by dimsemenov** [comment]
Have you tried opening page on webserver, not directly file?

**Comment by dogsout** [comment]
Unfortunately at the moment I can not try, but I hope that everything will work well. 1 more question. With some plugin as  masonry be successfully used PhotoSwipe? There is some advice? Ty!

**Comment by dogsout** [comment]
Sorry. Isotop plagin  is works very well. When I finish a site for my sister ( she was an artist ) , I will send you a link to it !
