### ISSUE TITLE
Manipulating PhotoSwipeUI_Default

### ISSUE THREAD

**Issue by ikixxx** [dimsemenov/PhotoSwipe#723]
I don't see any API for manipulating `PhotoSwipeUI_Default`
Most of all I have no idea how to translate the `share` buttons and add more.

**Comment by dimsemenov** [comment]
- UI options are on options page http://photoswipe.com/documentation/options.html (Default UI section at the bottom), including share buttons.
- If you need some big change, you may fork PhotoSwipeUI_Default to fit your needs.

**Comment by ikixxx** [comment]
Yes, I've read that page. However I thought that there is an api for customizing the UI.
So If I want to push another share button object to `shareButtons` array , how would I do that ?
I can't seem to find a way to get the  `shareButtons` array.
And just to make sure, if I want translation for the button I will need to fork `PhotoSwipeUI_Default`?

**Comment by dimsemenov** [comment]
Have you looked into `shareButtons` option?

**Comment by ikixxx** [comment]
`PhotoSwipeUI_Default.shareButtons` is `undefined` (tried it in console) that's what is puzzling me.

**Comment by dimsemenov** [comment]
`shareButtons ` option can be added as all other options, using `options` object. http://photoswipe.com/documentation/getting-started.html (step 3)

If you want to change it dynamically after PhotoSwipe is opened, you can access options via `yourPhotoSwipeInstance.options.shareButtons`.

**Comment by ikixxx** [comment]
Ok, although it seems confusing, because you are passing `PhotoSwipeUI_Default` to the instance, and in order to modify the `ui` your are passing the modifications to the `options` object, as opposed to `PhotoSwipeUI_Default` , which I was trying to do.
Thanks.

**Comment by dimsemenov** [comment]
thanks, I've added some clarifications to documentation options page.

**Comment by Slipkipu** [comment]
Hi all!

I want to integrate Google + buttons , Tumblr and email sharing button , but I do not really understand the Photoswipe documentation here: http://photoswipe.com/documentation/getting-started.html (step 3) on how process. Is there someone who has already made ​​these changes? And above all , what code do I fit in? It seems different to each button.
Thank you in advance.
