### ISSUE TITLE
Problem with adding image dynamically

### ISSUE THREAD

**Issue by kotenarok** [dimsemenov/PhotoSwipe#726]
I'm using ajax to load more images, and add to Photoswipe. The problem is when I tried to close Phowoswipe after I swipe to the new image, I got error "Uncaught TypeError: Cannot read property 'getElementsByTagName' of undefined". And the script crashed.

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by kotenarok** [comment]
Ok, I'm digging around and found the problem. I'm using the code as this link http://codepen.io/dimsemenov/pen/ZYbPJM/. The problem is this code
```
getThumbBoundsFn: function (index) {
    // See Options -> getThumbBoundsFn section of docs for more info
    var thumbnail = items[index].el.getElementsByTagName('img')[0], // find thumbnail <b>PROBLEM</b>
    pageYScroll = window.pageYOffset || document.documentElement.scrollTop,
    rect = thumbnail.getBoundingClientRect();

    return {x: rect.left, y: rect.top + pageYScroll, w: rect.width};
}
```
The added items have no "el". I'm using your code in the document "Adding slides dynamically".

**Comment by kotenarok** [comment]
I did it!! just add "el" into the code
```
el.each(function (index) {
    var $anchor = $(this).find('a');
    var dimension = $anchor.data('size').split('x');
    var width = parseInt(dimension[0]);
    var height = parseInt(dimension[1]);
    gallery.items.push({
        el: $(this)[0], // <== ADD
        src: $anchor.attr('href'),
        w: width,
        h: height
    });
    gallery.ui.update();
});
```
Thank you for your support.
