### ISSUE TITLE
Dynamic Photo gallery

### ISSUE THREAD

**Issue by AgentSource** [dimsemenov/PhotoSwipe#727]
I'm running into an issue were it creates a new gallery every time I break a row in my HTML.

```
<seciton class="gallery-container">
<div class="gallery-row">
<figure></figure>
<figure></figure>
</div>
<div class="gallery-row">
<figure></figure>
<figure></figure>
</div>
</section>
```

The code above is a basic example of HTML. If there away to have it target only the figure elements and ignore the div rows?

**Comment by dimsemenov** [comment]
PhotoSwipe does not control initial markup. JS example from [getting started](http://photoswipe.com/documentation/getting-started.html) supports markup with figures as child nodes. You need to modify it if your markup differs.
