### ISSUE TITLE
Double-tap handler belongs in core, not ui

### ISSUE THREAD

**Issue by asadovsky** [dimsemenov/PhotoSwipe#729]
Since pinch-zoom is in the core layer, doubleTap-zoom should be as well. But currently, it's in the optional UI layer:
https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/ui/photoswipe-ui-default.js#L560

As a workaround I added this to my own code, but I shouldn't need to:

	pswp.listen('doubleTap', function(pt) {
		var level = pswp.currItem.initialZoomLevel;
		if (pswp.getZoomLevel() !== level) {
			pswp.zoomTo(level, pt, 333);
		} else {
			pswp.zoomTo(pswp.options.getDoubleTapZoom(false, pswp.currItem), pt, 333);
		}
	});

**Comment by dimsemenov** [comment]
In some cases developer needs a full control of what double-tap does. I'd gladly move "pinch" to UI too, but it's very hard technically.
