### ISSUE TITLE
did Photo Swipe Compatible with lastest JqueryMobile ?

### ISSUE THREAD

**Issue by pangch2010** [dimsemenov/PhotoSwipe#736]
i downloaded
 - Photo swipe 4.0.5 version
 -Jquerymobile 1.4.5

when i try to integrate Photo swipe into my Jquerymobile project , it has many error.
can provide me a sample how to integrate into jquerymobile ?

*I can run photo swipe with standalone project without any framework

**Comment by fvsch** [comment]
Do you get any JavaScript errors in the console?
