### ISSUE TITLE
Minor:  getting started says default-skin.css is optional

### ISSUE THREAD

**Issue by rogerbinns** [dimsemenov/PhotoSwipe#737]
http://photoswipe.com/documentation/getting-started.html

The initialisation section says that default-skin.css is optional.  I left it out, and kept trying to diagnose why the buttons didn't work and were in the top left corner.  In reality some skin css is required (especially in the context of getting started).

It would be clearer if it wasn't marked as optional.  In the tips you can point out that it is good starting point for customising appearance.

**Comment by dimsemenov** [comment]
done :beers:
