### ISSUE TITLE
Thumbnail not removed after full img load

### ISSUE THREAD

**Issue by lorensr** [dimsemenov/PhotoSwipe#739]
The thumbnail appears first, and fills the width. The full image is subsequently loaded, but since it is taller than it is wide, it looks like photoswipe is showing it smaller so that it's not too tall. When it does this, it should remove the thumbnail.

![image](https://cloud.githubusercontent.com/assets/251288/5889874/5555c874-a3f2-11e4-9081-82eaf17c2b46.png)

**Comment by dimsemenov** [comment]
Dimensions (w/h ratio) of thumbnail image must match dimensions of large image. If it doesn't - you can not use this feature, and `msrc` property should be skipped.

You may crop thumbnails via CSS and use tecnhiques described in faq http://photoswipe.com/documentation/faq.html

**Comment by lorensr** [comment]
The ratio is the same. `msrc`'s width is being stretched.

```js
        w: 600
        h: 900
        src: "600x900.jpg"
        msrc: "100x150.jpg"
```

**Comment by lorensr** [comment]
![screen shot 2015-01-25 at 2 32 24 am](https://cloud.githubusercontent.com/assets/251288/5891178/842ef416-a43a-11e4-8df0-7ac5d62986f1.png)

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by lorensr** [comment]
I'm sorry, I am indeed giving the wrong slide dims. The problem might be that FileReader and Image don't account for orientation when giving width and height? Has anyone encountered this problem before that you know of?

http://stackoverflow.com/questions/28135787/why-are-the-width-and-height-of-some-js-image-objects-switched

Example JSBin and image:

http://jsbin.com/zicanaroce/1/edit?html,console,output
https://pwme.s3.amazonaws.com/TbR6fWPNZxMMJMZGH/1422184501.jpeg

**Comment by dimsemenov** [comment]
see https://github.com/dimsemenov/PhotoSwipe/issues/725
