### ISSUE TITLE
Setting the option 'captionEl' to false throws a javascript error

### ISSUE THREAD

**Issue by Erftralle** [dimsemenov/PhotoSwipe#740]
If option 'captionEl' is set to false the following javascript error occurs when opening PhotoSwipe:
TypeError: p2 is undefined (in PhotoSwipe/_equalizePoints())

Thank you for providing PhotoSwipe!

**Comment by dimsemenov** [comment]
I see. This can be avoided if you add option `barsSize: {top:44, bottom:0}`. http://photoswipe.com/documentation/options.html

But i'll fix it anyway.

**Comment by Erftralle** [comment]
:+1: Thanks!
