### ISSUE TITLE
open full images in main windows (from iframe)

### ISSUE THREAD

**Issue by reaux998** [dimsemenov/PhotoSwipe#742]
hi,
i have an iframe with a page with a gallery photoswipe.
Is possible to open the slideshow in a main window and not only in the iframe ?

I search an workaround for use photoswipe in Adobe Muse.. this is one way..

Thanks

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.
