### ISSUE TITLE
Oops, I passed the index variable in options to the new slideshow as a string!

### ISSUE THREAD

**Issue by pvandrunen** [dimsemenov/PhotoSwipe#743]
I was storing the index of my thumbnails as a data attribute.  When I pass the image index in the options it was cast as a string. 

The correct thumbnail would appear, but the counter in the corner would show "1" for the first image and "11" for the second thumbnail. Next and previous buttons were unreliable and usually didn't work.

Consider adding parseInt() or something to make sure the index value is an integer.

**Comment by dimsemenov** [comment]
Thank you for suggestion, I'll consider this.
