### ISSUE TITLE
IE9 IE11 no images

### ISSUE THREAD

**Issue by Cipa** [dimsemenov/PhotoSwipe#744]
Hi,

I implemented the code successfully and it works in chrome/firefox but I can't get it to work in IE9 and IE11(the ones I tested so far). It's like the img tag is not being generated in the DOM for IE.

Any ideas?

![screen shot 2015-01-30 at 11 29 33 am](https://cloud.githubusercontent.com/assets/293377/5979269/3d829c50-a874-11e4-9299-9246d3a0389d.png)

Here's the code used to generate the img array

```
<script type="text/javascript" >
$(window).load(function (){

	$(".photo-album-item").on("click", function(e){

		e.preventDefault();

		var pswpElement = document.querySelectorAll(".pswp")[0];

		var options = {
			index: 0,
			history: false
		};

		var items = [];

		options.index = $(this).index() +  $(this).parent().parent().attr("data-per-row") * $(this).parent().index();

		//console.log($(this).parent().parent().attr("data-per-row"));
		//console.log(options.index);

		$(this).parents(".photo-album-container").find(".photo-album-item").each(function(index) {
			var sizes= $(this).find("img").attr("data-size");
			var size = sizes.split("X");

			//console.log($(this).find("img").attr("data-caption"));

			// create slide object
			item = {
				src: $(this).find("a").attr("href"),
				w: parseInt(size[0], 10),
				h: parseInt(size[1], 10),
				title: $(this).find("img").attr("data-caption")
			};
			items.push(item);
		});

		gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
		gallery.init();
	})

});
</script>
```

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by Cipa** [comment]
Here you go:
http://codepen.io/anon/pen/OPjqop

Not working in ie11
codepen doesn't work in ie9 so I can't test there

**Comment by dimsemenov** [comment]
`var item`

**Comment by Cipa** [comment]
I should have known that :(
Thx
