### ISSUE TITLE
Prevent image Zoom in Desktop Mod by click event  

### ISSUE THREAD

**Issue by katche70** [dimsemenov/PhotoSwipe#747]
Hi, i have following code to select next picture on click.  
```javascript

       gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
       gallery.init();

        gallery.listen('unbindEvents', function() { 
		  gallery.framework.bind( gallery.scrollWrap, 'pswpTap', nextOnClick,true)
		});
		
	gallery.framework.bind( gallery.scrollWrap, 'pswpTap', nextOnClick );

	function nextOnClick(e) {
			  if (e.detail.pointerType == 'mouse' && e.detail.target.className == 'pswp__img') {
				  if (gallery.getCurrentIndex() == gallery.items.length-1 ) {
					 gallery.close();
				  } else {
					  gallery.next();
				  }	
				  return false;		
			  }
			  
	 }
```
it works, but if i set  
```javascript
   options.showAnimationDuration = 333;
```
for opening animation. By clicking the image is zoomed and going to next picture. 

Is it possible to unbind image zoom on click without modifying the library?

**Comment by dimsemenov** [comment]
```js
gallery.toggleDesktopZoom = function() {};
```

... will destroy function that toggles desktop zoom. You can do the same thing with any other public function, e.g. `gallery.ui.onGlobalTap = function() { alert('tap or click'); }`.

Don't be afraid to modify default UI, it's created as a separate file and just via public methods, so developers could edit it.

**Comment by katche70** [comment]
perfect. nice!

**Comment by shchukin** [comment]
Hello.

I am trying to repeat it. Works fine but gallery close itself by click if image is smaller than viewport side.
And it seem that it happens with default options when nothing to zoom. Short video example: 
https://dl.dropboxusercontent.com/u/22619948/photoswipe-click-close.mov

Is it possible to cancel this gallery closing?

**Comment by dimsemenov** [comment]
@shchukin, https://github.com/dimsemenov/PhotoSwipe/issues/844#issuecomment-103847383

**Comment by shchukin** [comment]
**clickToCloseNonZoomable: false**
@dimsemenov many thanks!
