### ISSUE TITLE
If "PhotoSwipe (.pswp) element" is added to DOM within form element it submit the form on close

### ISSUE THREAD

**Issue by lexbi** [dimsemenov/PhotoSwipe#748]
If "PhotoSwipe (.pswp) element" is added to DOM within form element it submits the form on close of photoswipe, can you add a return false on those buttons?

Works fine if you take them out, but might catch some other people out.

**Comment by dimsemenov** [comment]
Duplicate of https://github.com/dimsemenov/PhotoSwipe/issues/677
