### ISSUE TITLE
Issue with RTL

### ISSUE THREAD

**Issue by louy** [dimsemenov/PhotoSwipe#751]
This library has some UI issues when the website is using an RTL layout. The problem was hard to track but was easy to fix. Simply, we need to add `direction: ltr; text-align: left;` to the main pswp element.

**Comment by dimsemenov** [comment]
It seems:

```css
.pswp__img {
  left: 0;
  top: 0;
}
```

... fixes the problem. Can you please test?

I don't want to apply `direction:ltr` style, as you suggested in pull request, as some elements of the gallery might need the RTL direction (e.g. caption).

**Comment by louy** [comment]
Yes, you're right! I'll modify my pull request.
