### ISSUE TITLE
How to add html tag in caption

### ISSUE THREAD

**Issue by victorngkp** [dimsemenov/PhotoSwipe#754]
Following the example exactly shown in http://codepen.io/dimsemenov/pen/ZYbPJM, I noticed that when I insert html code in the `<figcaption>` tag, they are escaped and treated as normal text. I have a link in the `<figcaption>` tag, how do I show the link in the lightbox? Thanks.

**Comment by dimsemenov** [comment]
I can't repeat the problem. 

Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by victorngkp** [comment]
I tried the codepen and it worked. Looks like it's my problem. I'll try on my end. Thanks.
