### ISSUE TITLE
Normal image shows repeated bottom?

### ISSUE THREAD

**Issue by ChristianGerdes** [dimsemenov/PhotoSwipe#756]
As you can see, when I open the image it repeats a part of the image at the bottom. This is only the opened image and it works fine on the other images when sliding.
If i keep sliding for a while the image showed properly.

Can somebody help?

![skaermbillede 2015-02-11 kl 12 27 47](https://cloud.githubusercontent.com/assets/5636214/6146122/8fa4d8c6-b1e9-11e4-8f8b-30b6e443b547.png)

**Comment by boducoscar** [comment]
Hi Christian,

I have the same issue and just fixed a couple minutes ago. Please follow the tag below and it will be fixed, i think it load these attribute (data-size and href) in the a tag

<a class="demo-gallery__img--main" data-size="<?=$w30.'x'.$h30?>" href="images/timthumb.php?src=<?=$sqlImageSrc?>&w=<?=$w30?>">
	<img src="<?=$sqlImageSrc?>" alt="<?=$data->album_title?>">
</a>

**Comment by dimsemenov** [comment]
@ChristianGerdes, it means that size is incorrect, or size of thumbnail (width/height ratio) doesn't match size of large image. Or you're forcing some style to image via CSS.
