### ISSUE TITLE
How to use a grid?

### ISSUE THREAD

**Issue by scottx** [dimsemenov/PhotoSwipe#758]
Hi, this is an implementation question.

I'm creating my gallery based on the demo-gallery available on this document:
https://github.com/dimsemenov/PhotoSwipe/blob/master/website/index.html

However, whenever I try to put any html element inside the gallery between the A elements, the gallery will stop working (I can no longer swipe between images).

How can I place the photos inside a grid maintaining the gallery working properly?

Thank you so much!
My website at the moment: www.santosalves.com/santosalves2

**Comment by scottx** [comment]
Thanks to @nanuneves help I managed to find a solution.
We added a class element named galleryitem on each A element.
Then instead of iterating through the gallery's child nodes, we cycled through the 'galleryitem' elements using the each() function from jQuery.

**Comment by scottx** [comment]
Thanks to @nanuneves help I managed to find a solution.
We added a class element named galleryitem on each A element.
Then instead of iterating through the gallery's child nodes, we cycled through the 'galleryitem' elements using the each() function from jQuery.

**Comment by forgedone** [comment]
Was this a simple fix? I don't know jQuery, and have run into the same issue - any necessary html elements to format results in separate galleries (which is useless). Any help on how to implement this change?

**Comment by scottx** [comment]
It depends on our experience with JavaScript :)

In the end I decided to use https://github.com/ed-lea/jquery-collagePlus to make the grid which is a lot more flexible than the one from Foundation. It adapts to any screen and reorganizes all thumbnails independently of the aspect ratio for each photo.

See if you can get any help just by reading the source code from my homepage:
http://www.santosalves.com/

If you need any extra help, perhaps if you share the link to what you have now, I might give a hand.

Regards.
