### ISSUE TITLE
Orientation change breaks layout if there are exactly 2 images in the PhotoSwipe

### ISSUE THREAD

**Issue by prud** [dimsemenov/PhotoSwipe#759]
First of all: great piece of code you wrote there! I love it and will use it current (and probably future) projects.

However I found an issue with device orientation and how PhotoSwipe adapts to it. Everything works fine if there is 1 image or 3+ images in the gallery. If there are exactly 2, the image position will be off after a few orientation changes. I investigated the issue on iPhones and Android devices. Here is a demo:

- http://patrickrudolph.de/pswp/index-1.html - works
- http://patrickrudolph.de/pswp/index-2.html - buggy
- http://patrickrudolph.de/pswp/index-3.html - works

Just open it on your mobile, switch between the images and rotate a few times.

**Comment by dimsemenov** [comment]
Strangely, I can't repeat the issue, not on my Android phone, not on a few iOS devices.

Should I just open the page and click on "Open PhotoSwipe gallery" and then rotate device a few times?
Please let me know the exact device and OS in which you get this problem.

**Comment by prud** [comment]
Here are some steps to reproduce it.

1. Open  http://patrickrudolph.de/pswp/index-2.html in your mobile browser
2. Press the "Open PhotoSwipe gallery" button
3. Swipe between the two pictures a couple of times
4. Being on the first picture, rotate the device a few times
5. Being on a different orientation than the intial one, slowly swipe to the 2nd picture to see if it might be a bit off.

Following these 5 steps, I get the issue about 50% of the time. Here are some screenshots with the bug while swiping in between the two pictures:

![img_1279](https://cloud.githubusercontent.com/assets/2361882/6209075/99b50120-b5c1-11e4-98a9-f17894363127.PNG)

![img_1280](https://cloud.githubusercontent.com/assets/2361882/6209076/9c7a9eb0-b5c1-11e4-8335-f4627833cd9a.PNG)

This was tested on iPhone 5s (iOS 8.1.3) and Nexus 7 (Android 5.0.2).

**Comment by dimsemenov** [comment]
Thanks for the detailed explanation, I was able to reproduce the problem.

Just pushed commit https://github.com/dimsemenov/PhotoSwipe/commit/e0d1042e893e1ea51cd7b9e446b695bc19b513f9 , please get the latest version of PhotoSwipe JS file and let me know if it fixes your problem - https://github.com/dimsemenov/PhotoSwipe/tree/master/dist

**Comment by prud** [comment]
This is looking just fine, thank you for the timely fix.
