### ISSUE TITLE
Is it possible to disable closing Photoswipe when clicking outside the photo?

### ISSUE THREAD

**Issue by exhtml** [dimsemenov/PhotoSwipe#762]
Sorry if is a silly question, but I've read all the 'options' documentation and can't find if it's possible to disable that clicking outside the photo (black overlay area) closes photoswipe. Is there an option to set this to false?
Thank you very much in advance!

**Comment by ShinyChang** [comment]
[PhotoSwipe Options](http://photoswipe.com/documentation/options.html)

```js
// Element classes click on which should close the PhotoSwipe.
// In HTML markup, class should always start with "pswp__", e.g.: "pswp__item", "pswp__caption".
// 
// "pswp__ui--over-close" class will be added to root element of UI when mouse is over one of these elements
// By default it's used to highlight the close button.
closeElClasses: ['item', 'caption', 'zoom-wrap', 'ui', 'top-bar'],
```

I think this can solve your problem. :)

**Comment by exhtml** [comment]
Thank you very much ShinyChang, it works!
I want to recopilate an implementation of photoswipe I'm doing for a wordpress site (not a plugin Dimitri, only a implementation :) and I would like to share with all of you, maybe you'll find interesting.
Cheers!

**Comment by vs323** [comment]
is it possible to disable closing the modal window when click on the image. I tried removing zoom-wrap but nothing happened :(

**Comment by dimsemenov** [comment]
@vs323, `clickToCloseNonZoomable` http://photoswipe.com/documentation/options.html

**Comment by vs323** [comment]
Thanks very much @dimsemenov I should ve read the documentation more carefully!! :) all working!

**Comment by Alf21** [comment]
Is it possible to prevent closing and enable it after an action?

e.g.:
```
gallery.listen('close', function() {
            var activeStep = $(gallerySelector).hasClass("guide-active");
            if (activeStep) {
              return false;
            }
          });
```

If there is return false, the close action won't be performed? Or is it only possible with changing the options? The Problem then is, that i cant reset them after doing one action because i cannot detect the close event anymore.

Thanks :)

**Comment by infinitetrinity** [comment]
Is this depreciated? Couldn't find the "closeElClasses" option now.
How should I prevent it closing when clicking outside now?
Thank you
@dimsemenov

**Comment by dimsemenov** [comment]
@infinitetrinity `bgClickAction` option should help https://photoswipe.com/click-and-tap-actions/
