### ISSUE TITLE
Photoswipe and jqm 1.4.5

### ISSUE THREAD

**Issue by freelancer12** [dimsemenov/PhotoSwipe#763]
Hello,

First thank you for this plugin, i have just a question, is photoswipe comptaible with jquery mobile 1.4.5  i find an issue, the seconde question is when i'm using photoswipe in another page i have to load script with  data-ajax="false" .

Any suggestions or a working example with jqm 1.4.5 ?

Best regardes,

**Comment by dimsemenov** [comment]
Hello,

New PhotoSwipe does not have any built-in integration with jQuery mobile. It's just an element that is added to DOM.

If you want to override default `#hash` behaviour, set `history:false` or fork [history module](https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/history.js).
