### ISSUE TITLE
Clicking anywhere in figureElement opens the gallery

### ISSUE THREAD

**Issue by sohan5005** [dimsemenov/PhotoSwipe#764]
Hi, I'm working with my custom markup in html. my markup is like this:

    <div id="demo-test-gallery" class="lightbox-gal">
        <figure>
            <img src="small-image.jpg" class="thumbnail" alt="Image description" />
            <div class="entry-header">
                <h3>Title</h3>
                <h5>Status</h5>
            </div>
            <div class="entry-content">
                <a href="large-image.jpg" class="lightbox" data-size="600x400">Zoom image</a>
                <a href="#">link</a>
            </div>
            <div class="entry-footer">
                Some other content
            </div>
        </figure>
    </div>

The gallery is loading just fine. But the gallery opens clicking anywhere in the <figure> element. Any other links are not working and opening the gallery. I have selected the linkElement correctly in js.
All i want to do is, open the gallery only when I click the <a></a> tag with .lightbox class. Because I want to include other links in the figure element and I don't want the gallery to open by clicking on them.

**Comment by sohan5005** [comment]
Ok, I have solved my issue myself. Just on the javascript, I had to change the selector if onclick event. :)

By the way, I want to use it on a premium wordpress theme which I will sell over marketplace. Am I allowed to use this?

**Comment by dimsemenov** [comment]
@sohan5005, yes, you can use it in themes.

**Comment by lwilson1973** [comment]
@sohan5005 - please could you post your code?
