### ISSUE TITLE
photoswipe closedown control

### ISSUE THREAD

**Issue by devshisiyani** [dimsemenov/PhotoSwipe#765]
For the PhotoSwipe v4.0.3 i had added close down java code "window.history.go(-2);" to the file photoswipe-ui-default.js as follows
close: function() {
		if(!_isOpen) {
			return;
		}
		_isOpen = false;
		_isDestroying = true;
		_shout('close');
		_unbindEvents();

		_showOrHide( self.currItem, null, true, self.destroy);
		window.history.go(-2);
	}, 
added the code "window.history.go(-2);"  and on the mobile back button event code function onBackKeyDown(event) {
				send_alert ("back button presssed");
				event.preventDefault();
				window.history.go(-2);
				//window.close();
}
This worked great !!! no problems. 
Upgraded the code to use  PhotoSwipe v4.0.5
This area of the code has changed and now I can't  get the code to return to previous page on DOM using window.history.go(-2).
Where in the file photoswipe-ui-default.js  can i best add code "window.history.go(-2);" to return previous page on the dom.

**Comment by devshisiyani** [comment]
sorry, found the file "photoswipe.js" and area "close: function() {" where I need to add code "window.history.go(-2);"
if there is a better place to add "window.history.go(-2);" to close the photoswipe page and goback to previous page let me know.
Thx

**Comment by jamminjames** [comment]
Thanks, this helped a lot! This is needed for apps, as otherwise, closing the gallery just left a blank white page. With this addition, it returns to the app's home page.

**Comment by jamminjames** [comment]
Actually, after more testing, this didn't work for me. Had to add a listener for the close button and direct it to index.html of the app, like so:
`<script>`
document.getElementById("close").addEventListener("click", function(){
    	window.history.pushState(null, null, 'index.html' );
		location.reload(); 
});
`</script>`
