### ISSUE TITLE
Add dialog (no-photo) option

### ISSUE THREAD

**Issue by lorensr** [dimsemenov/PhotoSwipe#767]
Is it possible to put custom HTML in place of the photo in photoswipe? Like Magnific Popup's dialog:

http://dimsemenov.com/plugins/magnific-popup/documentation.html#inline-type

If not, consider this a FR! Can't find any other library with as good mobile swipe support.

**Comment by dimsemenov** [comment]
http://photoswipe.com/documentation/custom-html-in-slides.html ?

**Comment by lorensr** [comment]
Oops, thank you! Might be nice to add info on that to homepage.
