### ISSUE TITLE
Zoom-in animation not playing

### ISSUE THREAD

**Issue by groovy354** [dimsemenov/PhotoSwipe#768]
I'm implementing PhotoSwipe (currently active on small thumbnails on http://jakub-orlik.pl/portfolio/aspazja). Everything works fine, except for the zoom-in animation. which seems to be missing. I've ensured that `showAnimationDuration` is larger than zero and I'm using the default css files. Unfortunately the zoom-in animation does not show... Am I missing something obvious?

**Comment by dimsemenov** [comment]
- You need to define `msrc` property for each slide object (src of thumbnail).
- You need to define `getThumbBoundsFn `, a function that should calculate position of thumbnail on page.
