### ISSUE TITLE
_initalClassName problem

### ISSUE THREAD

**Issue by kshnurov** [dimsemenov/PhotoSwipe#770]
In some cases after closing the gallery `.pswp` element left with all the classes: `pswp--open pswp--animate_opacity ...`. It happens because they're stored in `_initalClassName` (can't really tell you how they got there before opening, but they are there).

It leads to `.pswp` element left open and blocking everything on the page. I can propose 3 solutions:
- completely remove `_initalClassName`, explicitly set `className = 'pswp'` on destroy [here](https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe.js#L970) (I've used this one)
- completely remove `_initalClassName` and remove all the classes used by PhotoSwipe on destroy, e.g.: `framework.removeClass(template, 'pswp--open pswp--animate_opacity pswp--touch pswp--notouch ...`
- at least explicitly remove `pswp--open` class on destroy

**Comment by dimsemenov** [comment]
Can you repeat the issue on PhotoSwipe homepage? Or it happens just with some specific options?

If not, please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem. You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by kshnurov** [comment]
It happens in a pretty specific environment with a lot of other JS and CSS on a page. I'll try to reproduce it later in a clean one.
