### ISSUE TITLE
move zoom to double-click

### ISSUE THREAD

**Issue by mastef** [dimsemenov/PhotoSwipe#773]
PhotoSwipe is great, really loving it! We just replaced an old slider and ported it to Angular - works like a charm.

So from another ticket, I've seen that you can re-declare what happens on desktop zoom, by simply overriding it with : gallery.toggleDesktopZoom = function() { /* ... */ };

However, how could we move zoom events to double-clicks/double-taps, and re-use single-clicks/single-taps for other events - is there a way without having to change core?

**Comment by dimsemenov** [comment]
If you need many modifications, simply edit default UI or create your own, it's intentionally added as a separate file, so you can edit it.

https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L737

**Comment by mastef** [comment]
Thanks @dimsemenov - that's what we ended up with! It's a bit harder to keep it up-to-date but it works.

Do you have any plans on releasing an angular directive - to prevent DOM binding?

**Comment by dimsemenov** [comment]
Not for now. Pull requests are very welcome.
