### ISSUE TITLE
High resolution images crash iOS chrome

### ISSUE THREAD

**Issue by jimbojetlag** [dimsemenov/PhotoSwipe#774]
When swiping an image of high enough resolution (it happens with 6000 x 4000) on iOS, chrome crashes.

**Comment by dimsemenov** [comment]
Please read FAQ http://photoswipe.com/documentation/faq.html

**Comment by jimbojetlag** [comment]
- photoswipe claims to solve the swipe problem on mobile devices.
- mobile devices do hav native support for high resolution images without crashing the browser app.
- photoswipe breaks this support on mobile.

This is a shame.

**Comment by dimsemenov** [comment]
Shame is that you haven't read the first block of the documentation and posting useless reply. Keep looping for the library that will animate you 6000x4000px image without tiling.
