### ISSUE TITLE
Photoswipe crashes on Samsung 10in SM-T530 moving from one image to another swipe 

### ISSUE THREAD

**Issue by devshisiyani** [dimsemenov/PhotoSwipe#775]
The Photoswipe app works ok on Mobile android Samsung, HTC etc. 
The issue i have is on tablet -  Samsung Tab4 10in SM-T530. The android version is 4.4.2. 
In photo swipe moving from one image to another the app crashes. This  fails consistently after moving to either second or third image. If I swipe slowly I can get to 3th image before crash. The total images on the list is 12.  I have tried it with 4 images with same issue. I get message Unfortunate <App> has stopped. Report/ok
My app uses Phonegap V3.6.3 and photoswipe version 4.0.5
The crash dump I get is in hex available in Google play console store which I can provide if required.
If you need more information to track it let me know. 

The other issue is the image display coverage. On the old photo swipe v3.05 which my old app uses. Image below.
![photosw_3 05](https://cloud.githubusercontent.com/assets/5080924/6432306/ea212670-c043-11e4-9efb-47b9511e3c6c.jpg) 
The image is fully displayed covering the whole display.
On the photo swipe V4.05 with  my current app in beta version the image does not cover the full screen.
![photosw4 06](https://cloud.githubusercontent.com/assets/5080924/6432308/14e99d1a-c044-11e4-9a33-4301207b6bbb.jpg) 
Is this configurable ? 
How can you set this.
The mobile version works fine on all screen size and nicely occupies the full screen.

**Comment by dimsemenov** [comment]
What image size do you use?

**Comment by devshisiyani** [comment]
they do vary in size as I get different people load different size.
However most of them are generally landscape 800*540 and portrait 434*600
If I use pinch to zoom out they open to fill the screen.

**Comment by dimsemenov** [comment]
- Do you have anything else running on a page, behind the PhotoSwipe?
- Can you repeat the issue via default browser on the same device? (e.g. on PhotoSwipe homepage)
- Test memory usage.
- Try disabling history option if you haven't yet.

**Comment by devshisiyani** [comment]
I use JQuery pages. The sequence is:
I first start the App and it opens on the first Jquery Mobile page. The page is display using phonegap WebView. I then click a button which starts the Photoswipe html page in webview. At this stage the DOM should only have the first start-up JQUERY page. Photoswipe displays the first image. Finger swipe to select the next image and it crashes. The crash error reported is signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 3f800000. The trace shows /system/lib/libwebviewchromium.so, /system/lib/libc.so (__thread_entry+72).
Investigation indicates its an invalid access to memory.
Secondly, I can disable the history as a temporary test, but I do need history enabled to return back to my jquery page.
I will also check memory usage but its difficult to understand why the app would run out of memory at the first swipe image.

**Comment by dimsemenov** [comment]
> I will also check memory usage but its difficult to understand why the app would run out of memory at the first swipe image.

New slide is created as script keeps only three slides in DOM at once, previous version did the same thing though.

You haven't replied to "Can you repeat the issue via regular browser (not PhoneGap) on the same device? (e.g. on PhotoSwipe homepage)"

**Comment by devshisiyani** [comment]
I have tested PhotoSwipe homepage on the Samsung Tab4 10in  chrome browser and this works fine. Also tested with Samsung  built-in browse and that also works fine. Also noticed where I have 4 images in the gallery and they are smaller in size (42.5KB), this works fine without crashing. Gallery with 12 images and images of size 157kb crashes. Not sure if this helps

**Comment by dimsemenov** [comment]
try adding style:

```
.pswp img {
   -webkit-backface-visibility:hidden;
   -webkit-transform: translateZ(0);
}
```

also, are you using default ui? Have you made any customizations?

**Comment by devshisiyani** [comment]
replace style .pswp img { max-width: none; } with style .pswp img { -webkit-backface-visibility:hidden;-webkit-transform: translateZ(0);}  in file photoswipe.css.
Also updated phonegap to latest 3.7.1
The photo swipe action now stops after 5th photo image. Now you get a message app unfortunately stopped.
The  photo swipe file photoswipe-ui-default.js has some minor code change. The shareButtons code changed to allow download and share on android phone. 
I will see if I can debug using eclipse connected to  to where its stops working. If you have any ideas on how to debug photo swipe actions that would help. 
Thanks
