### ISSUE TITLE
Add an option to opt-in to a mouse scroll infinite zoom

### ISSUE THREAD

**Issue by JSteunou** [dimsemenov/PhotoSwipe#776]
Hi,

I saw you prevent the mouse scroll to zoom in/out multiple times with a `stopPropagation` so the zoom-in just occur once, and then the mouse is used to scroll up & down.

But I which to be able to zoom-in / out without limits and let the user move into the image with the pointer.

Could you consider adding an option for that? I did not try in depth, but I think it would work with just an `if` around that [stopPropagation](https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/desktop-zoom.js#L111)

**Comment by dimsemenov** [comment]
Please see https://github.com/dimsemenov/PhotoSwipe/pull/746
