### ISSUE TITLE
Thumbnail Pages

### ISSUE THREAD

**Issue by shahroq** [dimsemenov/PhotoSwipe#777]
Hi,
Just wondered if your plugin has the ability to create a grid of thumbnails? for the gallery page (thumbnails that clickable for opening photoswipe modal)?
Or even more? create a grid with "bigger first image", like the http://photoswipe.com/ home page "demo gallery style" ?

**Comment by dimsemenov** [comment]
Not sure if I understand the question, gallery with grid of thumbnails is explained in documentation http://photoswipe.com/documentation/getting-started.html
