### ISSUE TITLE
Strange render on IE8

### ISSUE THREAD

**Issue by XavierDupessey** [dimsemenov/PhotoSwipe#778]
Hello,

I get a visual bug on IE8 only. If my IE window is "too big", the picture is not displayed well...

Let's see:

Small window, OK:
![smallwindow_ok](https://cloud.githubusercontent.com/assets/1449888/6484232/51853fbc-c27a-11e4-8d33-0dda1dda2983.jpg)

Big window, problem:
![bigwindow_problem](https://cloud.githubusercontent.com/assets/1449888/6484231/5183a832-c27a-11e4-87db-b8dfaa1cfa8a.jpg)

Did I miss a point to make it IE8 friendly?
The only obvious difference I see between my case and your example is my thumbnail's aspect ratio which is not the same as the big photo's one.

Do you think this can break the render on IE8?

Please answer only if you know it, I will debug it later otherwise.
By the way, thank you for your work, it's great! :)

Xavier

**Comment by dimsemenov** [comment]
Have you included html5shiv? aren't you applying any styles on images? have you tried using image from PhotoSwipe demo?

Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). 

You can download example from CodePen via `Share -> Export .zip`, and upload test case to your server.

**Comment by XavierDupessey** [comment]
Yes, html5shiv is included:
    

I disabled all styles and scripts to make my sample case as simple as possible. I still have the issue with my photos (in fact, it works with square and portrait photos and fails with landscape photos). But it works with your example's photos!

Here is my sample case with my photos (not working properly): http://xavierdupessey.com/albumsphotos/porto-portugal/
Here is my sample case with yours (working): http://xavierdupessey.com/albumsphotos/photoswipe-test/

Any idea ?

**Comment by dimsemenov** [comment]
Please redownload photoswipe.js and css and let me know if the issue fixed.

**Comment by XavierDupessey** [comment]
I confirm, it is fixed, thank you.
