### ISSUE TITLE
Facebook Share Thumbnail Issue

### ISSUE THREAD

**Issue by ahmetsali** [dimsemenov/PhotoSwipe#779]
Hi, first of all great plugin, thank you. 

- when i try to share an image on facebook, everything is right except the thumbnail image on facebook post, it doesn't show the image that i shared, just shows another image in the same page, however the url is correct. Are there any fix for this.

Thank you.

**Comment by dimsemenov** [comment]
See https://github.com/dimsemenov/PhotoSwipe/issues/749

**Comment by yasirmehboob** [comment]
The thumbnails are coming from the open graph protocols, currently photoswipe doesnt update the og:image properties by itself, you have to update it on your own. 
examples of such Meta tags:

<meta property=”og:title” content=” “/>
<meta property=”og:type” content=””/>
<meta property=”og:url” content=””/>
<meta property=”og:image” content=””/>
<meta property=”fb:admins” content=””/>
<meta property=”og:site_name” content=””/>
<meta property=”og:description” content=””/>
