### ISSUE TITLE
pswp.next() and pswp.prev() cause error

### ISSUE THREAD

**Issue by goodghost** [dimsemenov/PhotoSwipe#782]
Just wanted to implement next and prev API options to assigned it to different elements, but when clicking close button then I gen "Uncaught TypeError: Cannot read property 'beforeChange' of null".

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by goodghost** [comment]
Just look at this example:

http://codepen.io/anon/pen/xbMbZy

It uses the basic gallery provided as the example. What I modified:

1, I've added jquery library.
2. I've added wrapper $(window).load at the beginning
3. I've added .pswp__button--next element to trigger next gallery element on click

Problem: If you visit codepen link the gallery is automatically opened. You can use "Next" button and it works fine, but if you close gallery and open it again "Next" button doesn't work anymore. It gives an error which I've mentioned in first post.

**Comment by dimsemenov** [comment]
You just aren't unbinding click event after gallery is closed, and creating memory leak.

**Comment by goodghost** [comment]
I'm sorry, don't get it. So, how should I use this next() method properly in this example to make it work?

**Comment by dimsemenov** [comment]
```js
$(".pswp__button--next").click(function() {
      gallery.next();
    });
    gallery.listen('close', function(name) {
        $(".pswp__button--next").off('click');
    });
```

**Comment by goodghost** [comment]
thank you very much
