### ISSUE TITLE
Gallery stops working on Ubuntu + Firefox 36

### ISSUE THREAD

**Issue by Petr-Ledvina** [dimsemenov/PhotoSwipe#783]
I have tried PhotoSwipe gallery, example: http://www.ledvinovi.cz/photoswipe/?akce=116 It work very good on Ubuntu/Chromium, Ubuntu/Opera 12.60, Windows 7/FF, Windows 7/Chrome, Android/Chrome. But
on Ubuntu 14.04 LTS+newest Firefox 36 (two different computers) I have problem. I clicked on e.g. first thumb and then -> (or arrow right) and than still arrow right. After 10-20 images, I have a) image and can’t changed  to next images OR b) black screen. I must used "esc" and return to thumbs and continue.
I have "not so bad computer: core i7, 8 GB RAM and fast internet connection. Some memory leak?

**Comment by rogerbinns** [comment]
I can reproduce this on your site as well as mine.  It happens on the ninth image on both sites.  Firefox latest on Ubuntu 14.10.  No such problems on other browsers.  Core i7, 30 mbits internet, 32GB ram.

I did look in the browser error console for any clues but didn't see any.

**Comment by dimsemenov** [comment]
>  After 10-20 images, I have a) image and can’t changed to next images OR b) black screen

When it's black screen, controls aren't visible too? When you inspect the slide with dev tools what do you get in the middle of viewport? If you decrease browser window size can you get further than 10 pictures?

Downloading Ubuntu VM :zzz:

**Comment by dimsemenov** [comment]
Please try adding style:

```css
.pswp__scroll-wrap {
    will-change: auto !important;
}
```

**Comment by DanielMuller** [comment]
Applying the style change fixed the issue for me

**Comment by rogerbinns** [comment]
I can also confirm that adding the style fixed it for me too

**Comment by Petr-Ledvina** [comment]
Now is everything perfekt (Ubuntu 14.04 + FF 36), thank you Dmitry. 
Please change the main "repositary" or main CSS files.
