### ISSUE TITLE
Cordova iOS jquery mobile: PhotoSwipe is closing right after opening

### ISSUE THREAD

**Issue by johanvanw** [dimsemenov/PhotoSwipe#787]
On Cordova iOS using jquery mobile in addition to photo swipe.

If I click on a button that initializes and opens the gallery it flashes on the screen and then disappears unless I quickly move my mouse pointer to the center of the image.

**Comment by dimsemenov** [comment]
Please provide more details. What's the size of images? Have you tried to lower number of images? Have you tried removing all other elements except PhotoSwipe?

**Comment by johanvanw** [comment]
I added a console.log to shout
[Log] SHOUT: firstUpdate (console-via-logger.js, line 173)
[Log] SHOUT: initialLayout (console-via-logger.js, line 173)
[Log] SHOUT: beforeResize (console-via-logger.js, line 173)
[Log] SHOUT: resize (console-via-logger.js, line 173)
[Log] SHOUT: gettingData (console-via-logger.js, line 173)
[Log] SHOUT: parseVerticalMargin (console-via-logger.js, line 173)
[Log] SHOUT: initialZoomIn (console-via-logger.js, line 173)
[Log] SHOUT: initialZoomInEnd (console-via-logger.js, line 173)
[Log] SHOUT: gettingData (console-via-logger.js, line 173)
[Log] SHOUT: parseVerticalMargin (console-via-logger.js, line 173)
[Log] SHOUT: gettingData (console-via-logger.js, line 173)
[Log] SHOUT: parseVerticalMargin (console-via-logger.js, line 173)
[Log] SHOUT: bindEvents (console-via-logger.js, line 173)
[Log] SHOUT: beforeChange (console-via-logger.js, line 173)
[Log] SHOUT: afterChange (console-via-logger.js, line 173)
[Log] SHOUT: afterInit (console-via-logger.js, line 173)
[Log] SHOUT: imageLoadComplete (console-via-logger.js, line 173, x3)
[Log] SHOUT: preventDragEvent (console-via-logger.js, line 173)
[Log] SHOUT: pointerDown (console-via-logger.js, line 173)
[Log] SHOUT: firstTouchStart (console-via-logger.js, line 173)
[Log] SHOUT: pointerUp (console-via-logger.js, line 173)
[Log] SHOUT: preventDragEvent (console-via-logger.js, line 173)
[Log] SHOUT: touchRelease (console-via-logger.js, line 173)
[Log] SHOUT: close (console-via-logger.js, line 173)
[Log] SHOUT: unbindEvents (console-via-logger.js, line 173)
[Log] SHOUT: initialZoomOut (console-via-logger.js, line 173)
[Log] SHOUT: destroy (console-via-logger.js, line 173)

**Comment by dimsemenov** [comment]
Try calling preventDefault and stopPropagation on click/tap event that
opens gallery.
20 марта 2015 г. 12:34 пользователь "johanvanw" <notifications@github.com>
написал:

**Comment by johanvanw** [comment]
Worked perfectly. Thanks :)
