### ISSUE TITLE
Mobile Device Not Showing Share/Close Icons

### ISSUE THREAD

**Issue by DonaldKerr** [dimsemenov/PhotoSwipe#788]
I am using Photoswipe with Bootstrap. The icons for sharing and closing show on my desktop but not on my Android mobile phone. I get the image count at the top left but no icons at the top right.

![screenshot_2015-03-19-19-59-53](https://cloud.githubusercontent.com/assets/1557299/6739862/9ae04544-ce73-11e4-8678-7dbc7f586daf.png)

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by DonaldKerr** [comment]
If it helps, I have it live as a test website just now here: www.weboffice247.com

**Comment by dimsemenov** [comment]
You just haven't uploaded SVG file http://www.weboffice247.com/Content/default-skin.svg

**Comment by DonaldKerr** [comment]
Spot on though the problem was not that the file wasn't present on the server.

The exact error on that file was:

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

The file was there but the web server was not serving it.

I had to add the following 'mimeMap' code code to the 'system.webServer' section. After that, the mobile version now works perfectly.

```
<system.webServer>
	<staticContent>
		<mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
	</staticContent>
</system.webServer>
```

Thank you very much for your assistance though it was not actually a Photoswipe problem.

**Comment by DonaldKerr** [comment]
I have some further information on this problem and how to sort it.

Once I had added the above setting to Web.config, the svg worked remotely but stopped working locally with the following error:

```
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

Cannot add duplicate collection entry of type 'mimeMap' with unique key attribute 'fileExtension' set to '.svg'
```

In order to sort that so that it works both locally and remotely, you have to first remove the setting then reset it in the Web.config file as follows:

```
<system.webServer>
	<staticContent>
		<remove fileExtension=".svg" />
		<mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
	</staticContent>
</system.webServer>
```
