### ISSUE TITLE
Issue with css transform scale property

### ISSUE THREAD

**Issue by bmsedat** [dimsemenov/PhotoSwipe#789]
When changing the body or html with transform scale property like

body{
    transform:scale(0.9,0.9);
}
, photoswipe doesn't work.

**Comment by bmsedat** [comment]
Okey, I solved the problem.

When scaling I don't know why but Photoswipe doesn't work.

After changing adding a height to pswp class it's solved.

In my case, I scaled the body with 0.9 so height should be 1 / 0.9 bigger than body so it fits the screen.

So I added this to head

.pswp{
    height : 111.1111vh;    // 1vh is 1% of viewport height
}

**Comment by dimsemenov** [comment]
Just wondering why do you apply transform to body like so... You might get anti-aliasing issues on some browsers, like Safari.

**Comment by bmsedat** [comment]
Well I have my reasons but anti-aliasing will not make big differences even it'd work with issues
