### ISSUE TITLE
Broken link to codepen.io

### ISSUE THREAD

**Issue by mrkiffie** [dimsemenov/PhotoSwipe#790]
Hey Dmitry.

I've found a broken link in the generated options.html
- [source file](https://github.com/dimsemenov/PhotoSwipe/blob/master/website/documentation/options.md) line 82 
- broken link is http://codepen.io/dimsemenov/pen/NPGOob/

Would have submitted a pull request had I known what should have been found there. 

Just wanted to let you know.
Shout if I can help in any way.

Thanks for sharing your great work.

**Comment by dimsemenov** [comment]
Thank you!
