### ISSUE TITLE
Prevent from zooming

### ISSUE THREAD

**Issue by pierrea** [dimsemenov/PhotoSwipe#791]
Is there a simple way to prevent the user from zooming? I would like to disable double-tap as well as the magnifier cursor...
Thanks!

**Comment by dimsemenov** [comment]
Click and double-tap zoom is implemented from UI. You'll need to edit it to fit your needs.

https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L563

https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L741

https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe.css#L39

**Comment by pierrea** [comment]
All good, thank you @dimsemenov!
