### ISSUE TITLE
"A problem occurred with this webpage so it was reloaded" in IOS 8.1

### ISSUE THREAD

**Issue by yuval-a** [dimsemenov/PhotoSwipe#792]
I'm using PhotoSwipe in a website I built. There is an iPhone 4S with IOS 8.1 that shows this error when launching PhotoSwipe. In all other systems it works ok (tested on numerous desktop browsers, and several iPhone 5 with IOS8.2 & IOS7). Any idea what can cause this?
![error1](https://cloud.githubusercontent.com/assets/646274/6823140/1ca18196-d2ee-11e4-932d-7769c45644e8.PNG)

You can go to 
http://www.mariarosenblatt.com/Artists/
and click on any image to test it.

**Comment by dimsemenov** [comment]
It's because you've set image size (`w`, `h` properties) to 4000px+.

**Comment by yuval-a** [comment]
Yeah you're right. I thought I set it to use lower values. Thank you :)
