### ISSUE TITLE
Start lightbox with zoomed version

### ISSUE THREAD

**Issue by skerbis** [dimsemenov/PhotoSwipe#795]
Is it possible to open the Images allways zoomed.? So the user has to click on (-) to fit the image?
Is ist possible to start with Desktop-Zoom?

**Comment by dimsemenov** [comment]
For now there is no option to set start zoom level. But this feature is planned.

You can do this via API using `zoomTo` method http://photoswipe.com/documentation/api.html

**Comment by skerbis** [comment]
thx

**Comment by aaronransley** [comment]
@dimsemenov,

Do you have a recommendation for when to invoke zoomTo so that users never see a reduced size of the image? 

Currently, I am attaching the `zoomTo` calls to `beforeChange` and `afterChange`:

```javascript
var autoZoom = function() {
  pswp.zoomTo(
    pswp.currItem.fitRatio,
    { x: pswp.viewportSize.x/2, y: pswp.viewportSize.y/2 },
    0
  );
};

pswp.listen('beforeChange', autoZoom);
pswp.listen('afterChange', autoZoom);
```

However, when swiping left or right from the current slide, the image off screen scrolls into view at the reduced size before popping to the proper zoom (once `afterChange` fires).

**Comment by dimsemenov** [comment]
@aaronransley, for now there is no option to apply zoom level not on the current item. And it's not possible to start all items "zoomed" without direct modifications of PhotoSwipe. 

There are some problems regarding memory usage and performance of swipe, that aren't solvable for now without tiling. But I'm working on this problem.

**Comment by aaronransley** [comment]
@dimsemenov, thanks for the info. I'll look into possibly modifying the core of PhotoSwipe for this edge case. If I come up with anything worth sharing I'll submit a pull request.

**Comment by slavajacobson** [comment]
Did anybody have luck with this?

**Comment by fabiocaccamo** [comment]
+1

**Comment by Tzolkin** [comment]
+1

**Comment by iperdiscount** [comment]
+1

**Comment by dimsemenov** [comment]
This will be implemented in the new version, a basic prototype is already ready. Memory usage issue is partly fixed.

**Comment by farissi** [comment]
@dimsemenov This is a really interesting feature and I will be happy to see it released to public soon, by the time, could you please share this feature with us on it's current state please ?

**Comment by dimsemenov** [comment]
@farissi, here is example - http://codepen.io/dimsemenov/pen/jrpwEZ , just don't use it in production until the official release.

**Comment by michaelpumo** [comment]
@dimsemenov The demo in the last comment you made appears to be broken. Assets are linking to /test/ directory on the PhotoSwipe website, which probably isn't there.

**Comment by michaelpumo** [comment]
Has anyone managed to solve this? I have a single image 'gallery' I'd like to initialise as zoomed in from the start, but trying the example with zoomTo method does not work.

**Comment by bakura10** [comment]
@michaelpumo I've had to change the source of the library to add a new zoom level which would respect the "initialZoomLevel" you could set on per item. You can see the change here: https://github.com/dimsemenov/PhotoSwipe/issues/1424

Having said that I'd love to have an option to do that automatically, like : defaultZoomFactor: 2 which would automatically open the image twice as its original size, for instance.

**Comment by cshold** [comment]
Did this ever get implemented? 
`zoomTo` method after initialization causes some janky rendering and can't see the demo of using `openZoomed` anymore

**Comment by verybigelephants** [comment]
so has this been implemented that it is closed now? or it will not be implemented?
