### ISSUE TITLE
Add a list of selectable thumbnail images ("view all" feature) to design?

### ISSUE THREAD

**Issue by Fredyus** [dimsemenov/PhotoSwipe#797]
Hi, dimsemenow! I appreciate your great work on the photoswipe gallery. You're doing an amazing job. I'd like you, or someone else, to help with this.

I'm making a representational web. I want to add a "View all photos" block to default Pswp design, so it displays a list of thumbnails photos from items [ ] array.

Thumbnails selectable like this: http://i.imgur.com/98kGRQs.png

Any suggestions/solutions? Do you have any plans to add this feature, so people can set it in options = {};?

**Comment by dimsemenov** [comment]
There are no plans to add this feature, as by default there is already a grid of thumbnails from which PhotoSwipe is opened (http://codepen.io/dimsemenov/pen/ZYbPJM).

You'll need to fork default UI, and add "all thumbnails" somewhere after closing `pswp__scroll-wrap`.

**Comment by Fredyus** [comment]
thanks for the answer!

any idea how to make this example work http://codepen.io/dimsemenov/pen/ZYbPJM
for a pswp gallery so it's initiated once again for a selected image?

I couldn't get it working in a folder locally. I've included the <scripts> <styles> etc. All the latest of Photoswipe.

Can you add a folder version of those working examples? Would be very appreciated.

**Comment by zslabs** [comment]
Even though this was closed, I'd still love to see a thumbnail overview wrapper. The use-case here would be for a real estate property (example) and a single image as a "trigger" to launch the initial gallery without needing to show all of the thumbnails, but still giving the user a way to navigate to a specific slide within the pop-up and not be forced to keep sliding through however many photos it may take for them to get to the specific photo they'd actually want to see.

**Comment by dimsemenov** [comment]
@zslabs, http://photoswipe.com/documentation/custom-html-in-slides.html
