### ISSUE TITLE
photoswipe in <li> grid

### ISSUE THREAD

**Issue by sooobi** [dimsemenov/PhotoSwipe#799]
Hi i have a website with dynamic photo gride where every image is <li></li> when i put code into <li> i cannot swipe the images to another one, and i dont see counter.
Could You tell me what i should change to fix it?
Help

**Comment by dimsemenov** [comment]
Default example in the documentation ((How to build an array of slides from a list of links)[http://photoswipe.com/documentation/getting-started.html]) just looks for child elements, you'll need JS knowledge to modify it.
