### ISSUE TITLE
Not correctly working in IE8 with large images

### ISSUE THREAD

**Issue by Petr-Ledvina** [dimsemenov/PhotoSwipe#800]
PhotoSwipe is super!!! I have problem only on a IE8 (Win XP). When the images are smaller than screen, everything is good, example: http://www.ledvinovi.cz/?akce=35 , when pictures are bigger than screen, IE8 has a problem, like here:  http://www.ledvinovi.cz/?akce=114  (As you can see, I am using the PS without tags figures and figcaption.)
Thanx.

**Comment by dimsemenov** [comment]
Yea, sorry, my fault, 98184cf6adda090b5bb61b4495ad7bdac585e573 broke it, didn't test 4.0.7 it in ie8 enough. Should work now with last patch.

**Comment by Petr-Ledvina** [comment]
Thanks!
And could you update your "main repository", too? I am using/including "your"  file http://photoswipe.s3.amazonaws.com/pswp/dist/photoswipe.css. Or is better make a local copy of css and js? I am using "your" server, because of the newest version of files.

**Comment by dimsemenov** [comment]
Should be updated now. Don't use it on production site.
