### ISSUE TITLE
problem with photoswipe confilct with jquery-2.1.3.js

### ISSUE THREAD

**Issue by subweb** [dimsemenov/PhotoSwipe#803]
Hello
I created a web page with other jquery application

other application run with
<script src="//code.jquery.com/jquery-2.1.3.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.js"></script>

photoswipe while the problem seems to be right with Jquery
<script type="text/javascript" src="/JQuery/photoswipe/jquery-1.6.1.min.js"></script>

if I enter the line does not work for me if I remove other applications Jquery not working photoswipe

someone can tell me where is the problem?
Thank You

**Comment by subweb** [comment]
Hello
I created a web page with other jquery application

other application run with
script src = // code.jquery.com/jquery-2.1.3.js
script src = // code.jquery.com/jquery-migrate-1.2.1.js
photoswipe while the problem seems to be right with Jquery

if I enter the line does not work for me if I remove other applications Jquery not working photoswipe
script type=text/javascript src=JQuery/photoswipe/jquery-1.6.1.min.js
someone can tell me where is the problem?
Thank You

**Comment by dimsemenov** [comment]
Hello,

New PhotoSwipe doesn't use jQuery. It also doesn't use its namespaces (`$`, `jQuery`). Can't assist you with old version.

http://photoswipe.com/documentation/getting-started.html
