### ISSUE TITLE
Listeners object is null when calling gallery.goTo(index)

### ISSUE THREAD

**Issue by PekkaPLeppanen** [dimsemenov/PhotoSwipe#804]
### Steps reproduce
* Init and open PhotoSwipe
* Browse through photos.
* Browse through photos via goTo(index) API call
* At some point there's an error in console.
* Events are no longer handled correctly.

### Error message in console:
Uncaught TypeError: Cannot read property 'beforeChange' of null (photoswipe.js:425)

### Call stack
```
_shout (photoswipe.js:425)
publicMethods.updateCurrItem (photoswipe.js:1101)
publicMethods.goTo (photoswipe.js:1037)
(anonymous function) (gallery.js:645)
jQuery.event.dispatch (jquery-1.11.2.js:4665)
jQuery.event.add.elemData.handle (jquery-1.11.2.js:4333)
```

### photoswipe.js:425
```javascript
var listeners = _listeners[name];
// _listeners is null when error happens
```

**Comment by dimsemenov** [comment]
I can't repeat the issue on the default example.

Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server. You may overlay button with will do goTo API call over PhotoSwipe element via CSS.

**Comment by PekkaPLeppanen** [comment]
Hope this works
http://codepen.io/anon/pen/xboVOj

I discovered one extra to repro this. You have to first open the gallery from image. Close gallery and then open the gallery again. And then error appears.

**Comment by dimsemenov** [comment]
You just aren't clearing the setInterval after gallery is opened. That's why `listeners` is `null`. Every time you open gallery new interval and gallery object is created.

**Comment by PekkaPLeppanen** [comment]
Yep, that can explain why I had this issue at first place, although I didn't use setInterval. I have to debug my own code a bit harder then. :)

But thank you for your time and amazing gallery component.

**Comment by mitomm** [comment]
@PekkaPLeppanen : Did you ever manage to find your bug? 

I have the exact same issue. Not using any interval, but when I close the gallery and reopen it, I also get 
`TypeError: null is not an object (evaluating '_listeners[name]')`

when calling:

`gallery.goTo(index)`

**Comment by PekkaPLeppanen** [comment]
Sorry. Too many years have passed and don't recall the solution or have the code available to check.

**Comment by mitomm** [comment]
Alright so it seems that I found a solution.

So I had a function called `openPhotoSwipe()` that I used to define all the Photoswipe options, create a new PhotoSwipe object, attach listeners etc... 

The issue is, that inside that openPhotoSwipe () function I also bound a click event to a custom Button that I added to the Photoswipe gallery. Inside that click event I then used the goTo() function. 

The issue is that this click event is bind to my button multiple times if the gallery is opened multiple time. Thus, to solve the issue you either have to bind the click event outside the openPhotoSwipe() fucntion, or remove it after the gallery has been closed inside `pswp.listen('close', function() { });` callback. 

Hopefully that helps other people encountering the same issue.

**Comment by jgthms** [comment]
@mitomm Just wanted to say thanks for sharing your solution! That was exactly my problem: event listeners with the wrong reference after opening the gallery a second time.

**Comment by williamswgb** [comment]
@mitomm I encounter the exact problem and I also have the same function as openPhotoSwipe(). Can you elaborate more on your solution? Which click event that should be handled in this case?

**Comment by mitomm** [comment]
Hi @williamswgb . I was doing something like this:

	
	function openPhotoSwipe(picIndex) {
		var pswpElement = document.querySelectorAll('.pswp')[0];

		[....]

		var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, mediaArray, options);
		gallery.init();

	
		gallery.listen('close', function() {
			$(".photoSwipeThumbNailCont .slickImgContainer").off("click");  // important to remove the click event here so it does not get attached twice after closing and reopening
		});


		$(".photoSwipeThumbNailCont .slickImgContainer").click(function(){
			var index = parseInt($(this).attr('img-index'));
			if (Number.isInteger(index)) {
				gallery.goTo(index);
			}
		});
	};


I hope that helps.

**Comment by williamswgb** [comment]
@mitomm Thank you so much for sharing your solution. I just have 1 last question for you. How and when do you trigger your openPhotoSwipe function? Do you have something like a button to trigger this function to open / close the photoswipe?

**Comment by stef-van-looveren** [comment]
Can confirm that @mitomm was right. Make sure you initialise a new gallery object on click. for example: 
`      // var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, galleryItems, galleryOptions);

      $(document).once().on('click', '.gallery-item', function (e) {
        var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, galleryItems, galleryOptions);
        currentlyViewing = $(this).data('index');
        gallery.init();
        gallery.goTo(currentlyViewing);
      });`

**Comment by im-kaka** [comment]
A new beta version is out, but here's a solution.

move location instead of "gallery.goTo(index)"

location.href("/#&gid=1&pid="+index);
same result.
