### ISSUE TITLE
Link with history id and the zoomed image won't close

### ISSUE THREAD

**Issue by LekeFly** [dimsemenov/PhotoSwipe#805]
Trying to open a copy pasted link that contains the #&gid=1&pid=1 and using the close button doesn't work, the image keeps opening it self. scrolling will close it however.

Please see the video here: http://cl.ly/072Z2l1H2t3i

**Comment by dimsemenov** [comment]
Hard to tell. Can you repeat the issue on PhotoSwipe homepage? Do you get any JS errors in console? PhotoSwipe can't open itself, only calling init() method will open it, so make sure that you aren't triggering it somehow.

Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.
