### ISSUE TITLE
gallery.getCurrentIndex() and other not working. Need an example.

### ISSUE THREAD

**Issue by Inlesco** [dimsemenov/PhotoSwipe#806]
var gallery = new photoswipe(pswpEl, pswp_default_ui, items, options);

gallery.getCurrentIndex() and other properties in the documentation are not working (listed here: http://photoswipe.com/documentation/api.html) as I call them as methods? Could you provide a working example on this?

Also, how do I extend the new Photoswipe ( ); constructor to accept more values? Do I need to edit the core? I've got all of my custom Options coded into photoswipe-default-ui.js. I could post a commit for a review then.

Pswp is great and seeing its functionality expanded would be good. Thanks, Dim!

**Comment by dimsemenov** [comment]
```
var gallery = new PhotoSwipe( ...
gallery.init();

...

gallery.getCurrentIndex();
```

**Comment by Inlesco** [comment]
Thanks for the reply!
Solved the issue with window.gallery = new Pswp (...); as the object wasn't global since it's executed in an external .js file.

Any idea why onClick="gallery.shout("myCustomScriptName");" is not working? The fn is written as "gallery.listen("myCustomScriptName", function () {});", as per documentation. Any help greatly appreciated.
