### ISSUE TITLE
Minor: Escape {{ in documentation

### ISSUE THREAD

**Issue by rustamli** [dimsemenov/PhotoSwipe#807]
It seems website generator corrupts the following section because of not escaping `{{` `}}` :

```
// Available variables for URL:
// {{url}}             - url to current page
// {{text}}            - title
// {{image_url}}       - encoded image url
// {{raw_image_url}}   - raw image url
```

On [the website](http://photoswipe.com/documentation/options.html) it us rendered as:
 
```
// Available variables for URL:
//              - url to current page
//             - title
//        - encoded image url
//    - raw image url
```

Had to check with source to get `getImageURLForShare` working

**Comment by dimsemenov** [comment]
Nice catch, thank you. :beers:
