### ISSUE TITLE
TypeError on Site Load

### ISSUE THREAD

**Issue by Pit2002** [dimsemenov/PhotoSwipe#810]
I´ve tried to implement photoswipe on my local web server. I´ve tested it with xammp or lighttpd but i get the same issue.

[Error] TypeError: Attempted to assign to readonly property.
	(anonyme Funktion) (photoswipe.js, line 2924)
	_shout (photoswipe.js, line 432)
	init (photoswipe.js, line 868)
	global code (index.php, line 115)

Whats the problem here?
The same failure is with photoswipe.min.js.

**Comment by jaybloke** [comment]
I'm getting the same problem in Safari 8.0.8... works in Chrome and Firefox. How did you solve this?

**Comment by sebastiendan** [comment]
Same error here, any solution?
