### ISSUE TITLE
Issue on iPhone 6 portrait

### ISSUE THREAD

**Issue by martiniboy** [dimsemenov/PhotoSwipe#812]
Hi I'm having an issue with photoswipe on iPhone 6 and possibly iphone 6+, when photoswipe is enabled/activated the image does not sit central, especially in portrait view, if it's a long page sometimes image does not appear within viewport.  Any advice?
Also on a Mac the controls are not showing but are on a pc?

**Comment by dimsemenov** [comment]
Can you repeat the issue on the main demo page?

**Comment by martiniboy** [comment]
No sorry, I had an unclosed div, d'oh.  Sorry
