### ISSUE TITLE
Crash on iPhone 6 plus , large images

### ISSUE THREAD

**Issue by xlkit456852** [dimsemenov/PhotoSwipe#814]
device: iPhone 6 plus
image size: 1000px ~3000px
situation: the broswer crash after I swipe 2 or 3(it depends) pages. 
You can test it here : http://app.suisun.cn/wap.php/ashow/index2?dir2=da0878e03fa97ab571d2e9e5e11429bb
I know that the image size is too large and will cause some problem like crash, but I must ensure the quality of the images , so I can't make them to 500~1000px , are there any solution for me on this situation ? Thank you.

**Comment by dimsemenov** [comment]
You can't animate two 3000px images on mobile Safari for now.  If you need to serve huge images, just open them in a new page, or use libraries that support tiling like Leaflet.
