### ISSUE TITLE
disabling "esc" effect

### ISSUE THREAD

**Issue by Danny-weebo** [dimsemenov/PhotoSwipe#815]
Hey, awesome plugin you got here @dimsemenov, well done.
I wonder how can I disable the "esc" button and the clicking on some other parts of the frame so user won't be able to get out of the gallery frame.
if the plugin doesn't have any option for that is there any "hack" I can do (with css maybe) that can solve this ?

thanks!

**Comment by dimsemenov** [comment]
`escKey` http://photoswipe.com/documentation/options.html ?

**Comment by Danny-weebo** [comment]
yes, but its not only about the `escKey` , look at the image that I attached, if you click on the red parts it has the same affect of the escKey, how can I avoid this ?

thank you

**Comment by dimsemenov** [comment]
`closeElClasses` http://photoswipe.com/documentation/options.html

**Comment by Danny-weebo** [comment]
thanks a lot (:

**Comment by Danny-weebo** [comment]
hey, I've re-tested it after adding 
`closeElClasses: []` to the options, and I found that by swiping down or up you still can get "outside". 
can you think about a way to avoid it ? maybe disabling swiping up and down ?
