### ISSUE TITLE
Example Codepens not working documentation page.

### ISSUE THREAD

**Issue by dkay59** [dimsemenov/PhotoSwipe#816]
Example Codepens not working getting started documentation page.

http://photoswipe.com/documentation/getting-started.html

**Comment by dimsemenov** [comment]
Everything works on my side, in what browser do you test?

**Comment by dkay59** [comment]
Chrome

**Comment by dimsemenov** [comment]
If you Share -> Export on CodePen and open page locally, does it work?

**Comment by dkay59** [comment]
Thanks, (and thanks for replying on a weekend!) it worked perfectly when I exported this. There must be a problem with the way codepen embeds on a webpage
