### ISSUE TITLE
Add check to createZoomPanRotate for this.toolbar.fadeOut();

### ISSUE THREAD

**Issue by JPustkuchen** [dimsemenov/PhotoSwipe#817]
Version: 3.0.5
Line: 5516:

**Context:** Opening an image in Photoswipe 3.0.5

**Problem:** The Toolbar always fades out when zooming in. This is a problem for example in iOS Apps because the iOS HID Guidelines don't allow to show pages without a back / close - button. There is no possibility to configure that the toolbar should not fade out.

**Proposed solution:**
Change the following line to check the setting:
`if (!Util.isNothing(this.toolbar) && this.toolbar.isVisible) {`
TO
`if (!Util.isNothing(this.toolbar) && this.toolbar.isVisible && this.settings.captionAndToolbarAutoHideDelay > 0) {`
OR
Add a new setting completely:
`if (!Util.isNothing(this.toolbar) && this.toolbar.isVisible && this.settings.hideScrollbarOnZoom) {`

**Comment by JPustkuchen** [comment]
UPDATE: An even better solution is to replace
´this.toolbar.fadeOut();´
by
´fadeOutToolbarIfVisible´

**Comment by dimsemenov** [comment]
Sorry, old version of PhotoSwipe (4.0 and before) is not maintained. You may fork it if you need some modifications.

**Comment by JPustkuchen** [comment]
Thanks a lot, no problem. Feel free to close this, but let's keep it as documentation for others. Perhaps you can use that guess for the latest version to supply a setting for that if it doesn't exist yet.

**Comment by dimsemenov** [comment]
ok, thanks!
