### ISSUE TITLE
Large GIF files which crash the browser, possible solution

### ISSUE THREAD

**Issue by jamiepk** [dimsemenov/PhotoSwipe#820]
Hi, thanks for the Photoswipe updates.

This isn't an issue, just thought I would share something I have learnt and the community could improve on it (or tell me I'm wrong and archive).

I'm unfortunately in a situation where I have very large GIFs and am unable to serve responsively. As your FAQs mention, there are browser issues with large files and I crash out every time. (I'm currently only testing in iOS Safari)

Through trial and error I have discovered that if you just change the dimensions, the browser no longer crashes. So far my code is still a WIP but I've combined the suggestion made by gincius (thank you as I also really needed this!) from https://github.com/dimsemenov/PhotoSwipe/issues/796 to resize the image based on double screen size. 

Thought it may help people in similar situation. Thanks!

======================================

    gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options );
    gallery.listen('gettingData', function( index, item ) {

        if ( item.w < 1 || item.h < 1 ) { // unknown size
                img.onload = function() { // will get size after load
                var winWidth = window.innerWidth,
                    winHeight = window.innerHeight,
                    ratio,
                    zoom = 2;

                // Determine if image is too big
                if ( this.width > winWidth || this.height > winHeight ) {
                    // If image is too wide
                    if ( this.width > winWidth ) {
                        ratio = this.width / ( winWidth * zoom );
                    // If image is too tall
                    } else {
                        ratio = this.height / ( winHeight * zoom );
                    }

                    // Reset width/height
                    item.w = this.width / ratio;
                    item.h = this.height / ratio;
                } else {
                    item.w = this.width;
                    item.h = this.height;
                }
                gallery.invalidateCurrItems(); // reinit Items
                gallery.updateSize(true); // reinit Items
            }
          img.src = item.src; // let's download image
        }
    });

**Comment by dimsemenov** [comment]
It's a good point. Thanks for sharing. What's the size of your gifs?

**Comment by jamiepk** [comment]
The ones I have been testing probably range from 2000px to 4000px wide
