### ISSUE TITLE
It does not work for switching slides restructured

### ISSUE THREAD

**Issue by extiser** [dimsemenov/PhotoSwipe#827]
Good afternoon. Firstly thanks for the realization of this slider!
but a question. I changed a little bit and now the structure of the slides are not switched. The structure, unfortunately, can not pomenyatsya (when you hover over the thumbnail - there are buttons for editing and deleting images).
How to make the switch worked?
Link to the project: http://svadbavo.ru/catalog/firm/id2

P.S. sorry for my clumsy English

**Comment by dimsemenov** [comment]
Sorry, I can't assist with such installation questions. If you're using default code from the documentation, make sure that `parseThumbnailElements` loops through the correct elements, if you know JS – every line of it is self-explanatory.
