### ISSUE TITLE
getThumbBoundsFn not updating the currItem property

### ISSUE THREAD

**Issue by donzorro** [dimsemenov/PhotoSwipe#829]
For my understanding, getThumbBoundsFn is sort of a callback to update the position (and possible some other data) about the currentItem when the selection changes. I see the properties dont get propagated to the currItem property. i think we should use the framework.Extend to update all values returned from getThumbBoundsFn to the currItem.

**Comment by dimsemenov** [comment]
`getThumbBoundsFn ` is called only when opening or closing the PhotoSwipe. It should just return the position and size of the area to which (or from which) closing (or opening) animation will start. Not sure if I understand what `currItem` has to do with it, please elaborate...

**Comment by donzorro** [comment]
you are correct, my bad. i think what i mentioned would be a breaking change since in your document you specify exactly what it needs to be returned from the getThumbBoundsFn.

The point that i wanted to make before is that, when we create the PhotoSwipe we pass the array of elements with w,h, the url of the photo and extra fields that we might find useful. 
It would be nice to have a callback when image is to be shown or closed, where we have a chance to update the properties of the currItem, in case something changed from when we passed it at creation time. Yes, there are events i can hookup, but a single method would be useful too.

**Comment by dimsemenov** [comment]
Got it.

The `gettingData` event is created exactly for this 

http://photoswipe.com/documentation/api.html
Example of usage: http://photoswipe.com/documentation/responsive-images.html

**Comment by donzorro** [comment]
amazing! thanks a lot i will use it
