### ISSUE TITLE
&pid=1 always

### ISSUE THREAD

**Issue by JvanderHeide** [dimsemenov/PhotoSwipe#835]
On http://photoswipe.com/ the `&pid=n` changed to the corresponding image's index.
However on my local environment the `pid` is always `1` no matter what image in the gallery I open first.
Once opened and then navigating, the `pid` does update with `+1` and `-1`, limited by the total number of images in the gallery. 

Anyone have any idea what causes this? 
Local environment. 
Currently using random lorempixel images.

**Comment by dimsemenov** [comment]
No idea, get unminified version and debug what's wrong. Here is the part that sets the first item index:

```js
_listen('firstUpdate', function() {
    _currentItemIndex = _parseItemIndexFromURL().pid;
});
```

https://github.com/dimsemenov/PhotoSwipe/blob/master/src/js/history.js#L207

If you won't be able to resolve, please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by JvanderHeide** [comment]
I'm sorry my index function was returning 0 falsely :pensive:
