### ISSUE TITLE
captions go unescaped (or double escaped)

### ISSUE THREAD

**Issue by swa66** [dimsemenov/PhotoSwipe#836]
It's actually a choice:
should captions be delivered already escaped (but for what ), or should they be unescaped.

If unescaped: 
- "<", ">", "&", "'" and '"'should be escaped using htmlentities where innerHTML is set 
    - Throws errors in browsers that are in XML mode if not. e.g.:
        "Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document."
    - is a (potential) XSS security vulnerability for the website  if a user could contribute captions like 
         < s c r i p t>...< / s c r i p t >    [sorry for the spaces ... got filtered here otherwise]

if escaped:
- the innerHTL inserting code is ok,
- but then the code that outputs the text in the UI to post it to e.g. pinterest needs to not urlescape the already htmlentity escaped string ... as the likes of pinterest now see & q u o t e ; instead of " in the text they urldecode. 
This would require reversing the htmlentities ...  

If it were up to me: I'd vote for unescaped captions, and use output filters where needed. (reversing htmlentities sounds harder than just filtering the 5 needed polyglot htmlentities that might need it.  

(take care with IE8: it's not handling & a p o s ; properly - but you probably know that)

**Comment by dimsemenov** [comment]
PhotoSwipe by default just uses raw `innerHTML` to change caption. Content is retrieved from `title` property of slide object, it's not escaped anyhow.

If you want to modify this behaviour, all you need is to change `addCaptionHTMLFn ` option from the default UI http://photoswipe.com/documentation/options.html

If you want to modify text that is shared through share buttons – use `getTextForShare` option.

**Comment by swa66** [comment]
I had read that, but was left wondering what the purpose was. 
Now it all makes much more sense. Thanks for clarifying!

I will try to put an output filter to the addCaptionHTMLFn in options.

**Comment by swa66** [comment]
I'm sure it can be optimized and improved, but a quick test shows

```javascript
addCaptionHTMLFn: function(item, captionEl, isFake) {
          if(!item.title) {
           captionEl.children[0].innerHTML = '';
           return false;
          }
          var str=item.title;
          var replace = new Array('&', '<', '>');
          var by = new Array('&amp;','&lt;','&gt;');
          for (var i=0; i<replace.length; i++) {
            str = str.replace(replace[i], by[i]);
          }
          captionEl.children[0].innerHTML = str;
          return true;
         }
```
Tested it quickly. (modern browser, IE8, ... just a very few)
Does not give errors in application/xml served content (where appropriate) and leaves the post to e.g. pinterest working as expected as well. (obviously this also means the item array needs to be a raw [UTF-8 in my case] string (no htmlentities) and it'll also prevent any attempts at using html.
