### ISSUE TITLE
PhotoSwipe Next/Previous Arrow

### ISSUE THREAD

**Issue by apr77** [dimsemenov/PhotoSwipe#839]
PhotoSwipe Next/Previous Arrow. missing right & left arrow for mobile device.? android & iphone

**Comment by Inlesco** [comment]
Search default-skin.css for 'display: none' on mobile designs.

**Comment by dimsemenov** [comment]
Arrows on mobile are hidden via CSS https://github.com/dimsemenov/PhotoSwipe/blob/master/src/css/default-skin/default-skin.scss#L128
