### ISSUE TITLE
Possible to add HTML slide to a gallery from list of links?

### ISSUE THREAD

**Issue by 51graphix** [dimsemenov/PhotoSwipe#843]
My gallery is built using an array of slides from a list of links. I would like a custom HTML slide to appear after the last image in the gallery, is this possible using this method?

**Comment by dimsemenov** [comment]
Just push one more object to your slides array that you pass during the initialization.

http://photoswipe.com/documentation/custom-html-in-slides.html

**Comment by 51graphix** [comment]
Hi Dmitry, thanks for the quick reply. I was able to add an HTML slide by adding this in the initialization:

```
customHTMLslide =  {
  html: '<div><h1>Any HTML <a href="http://example.com">content</a></h1></div>'
}
items.push(customHTMLslide); 
```

This created a problem though, when you navigate to the slide, and try using the escape button or click the X to close out the viewer, it would freeze up. I believe I could have disabled getThumbBoundsFn to correct this, but I was able to keep the animation enabled by adding the if statement below to the function:

```
getThumbBoundsFn: function(index) {
    // See Options -> getThumbBoundsFn section of documentation for more info
    if (typeof items[index].html == 'undefined') {
      var thumbnail = items[index].el.getElementsByTagName('img')[0], // find thumbnail
        pageYScroll = window.pageYOffset || document.documentElement.scrollTop,
        rect = thumbnail.getBoundingClientRect();
      return {x:rect.left, y:rect.top + pageYScroll, w:rect.width};
   }
}
```
