### ISSUE TITLE
Fullscreen image

### ISSUE THREAD

**Issue by JuanStevens** [dimsemenov/PhotoSwipe#849]
This is a feature request. I'm not a coder but a pro photographer. Is there a way to make the image actual fullscreen. By that I mean stretch to the borders of the browser. The image stops to where the toolbar is but I'd like it stretched default to the edge.

**Comment by dimsemenov** [comment]
This option is already present, choose "minimal" style on homepage. http://photoswipe.com/

**Comment by brsd617** [comment]
Is there a way to specify certain images in a gallery that will stretch to fill the width of the viewport, like object-fit:cover, while default images fit viewport height like "minimal" example? Thanks.

**Comment by thefewminutes** [comment]
is there a way to get slides to fit viewport width instead of height? Similar to object-fit: cover?
