### ISSUE TITLE
Conflict including PS into my website container

### ISSUE THREAD

**Issue by rocc** [dimsemenov/PhotoSwipe#852]
My website's navigation bar, on top of it, has background: rgba(0, 0, 0, 0.75); and various z-index to style it.
PS Controls on top of the slide area, are somehow affecting the transparency of my navigation bar: it lose completely its background rgba.

I've tried to play around the z-index of photoswipe.css and default-skin.css, but to me it does not seem being an issue with z-index.

Please, anyone have any idea how can I solve this? Thanks so much!

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by rocc** [comment]
Here's the gallery: http://www.condominiumprod.com/dev/riviera/
user: carmelo
psw: gavotta
If you navigate the website, you can see how the navigation bar is correctly displayed with its background rgba, and how is losing it with PS - you can notice that when you zoom in the pictures.

**Comment by dimsemenov** [comment]
I get 403 Forbidden on the page that you linked.

**Comment by rocc** [comment]
sorry. please try now.

**Comment by dimsemenov** [comment]
Your layout is made in a very strange way, your have a separate element that adds background for navbar with z-index lower than z-index of content, that's why it overlaps it.

I can not assist with such issues here.

**Comment by rocc** [comment]
I see. Thanks for explaining me my z-index issues. I'll have to fix my layout, then.
