### ISSUE TITLE
Orientation change support

### ISSUE THREAD

**Issue by zslabs** [dimsemenov/PhotoSwipe#862]
Hi,
Thanks for building this! Was running it through address test and noticed the galley dimensions do not update on device orientation change - was this something in the plans to address? Thanks!

**Comment by dimsemenov** [comment]
Please elaborate what exactly test and what exactly device.

**Comment by zslabs** [comment]
Using an iPhone 5S on iOS 8.3, if I load a webpage with PhotoSwipe in portrait mode and then flip the phone landscape (change orientation), the dimensions of the gallery do not change; the dark overlay does not expand to fit the rest of the screen and images do not expand to fit the available area. I need to close out of the gallery and re-open in order for the dimensions to be calculated. Potentially https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe.js#L822 needs to also have a trigger for this update:

````window.addEventListener("orientationchange", function() {
}, false);````

**Comment by dimsemenov** [comment]
PhotoSwipe listens for `resize` event. Can you repeat the issue on PhotoSwipe homepage or just one some site?

**Comment by zslabs** [comment]
This was through the PhotoSwipe site through Tweetbot's built-in browser. Regular browsers are fine. Obviously a huge edge case, but wouldn't hurt to make sure it listens for orientation change to make sure everything is covered.

**Comment by swa66** [comment]
I'd verify the html has     <meta name="viewport" content="width=device-width, initial-scale=1" />
(not the scale, it's important!) in the html, if it's nto there, an iPhone will not resize on orientation change (it will zoom instead).
