### ISSUE TITLE
PhotoSwipe Next/Previous Arrow. missing right & left arrow for mobile device.? android & iphone 

### ISSUE THREAD

**Issue by alvaro562003** [dimsemenov/PhotoSwipe#869]
Hello,

i read carefully the  case  "PhotoSwipe Next/Previous Arrow #839 ".
I download  https://github.com/dimsemenov/PhotoSwipe/blob/master/src/css/default-skin/default-skin.scss in the app/css directory.

I modified the part below 
/* no arrows on touch screens */
.pswp--touch { .pswp__button--arrow--left, .pswp__button--arrow--right {visibility: hidden;}
by
/* no arrows on touch screens */
.pswp--touch { .pswp__button--arrow--left, .pswp__button--arrow--right {visibility: visible;}
and the arrows do not appear.

The is only other css file is photoswipe.css
I am using "intel xdk" to simulate android/IOS devices.

**Comment by alvaro562003** [comment]
After some search, i have found the cause (...not an explanation!!).

In the working version : <link href="photoswipe.css" type="text/css" rel="stylesheet" />
in the NON-working version <link href="css/photoswipe.css" type="text/css" rel="stylesheet" />

**Comment by alvaro562003** [comment]
After some search, i have found the cause (...not an explanation!!).

In the working version : "href="photoswipe.css"
in the NON-working version "href="css/photoswipe.css"

**Comment by dimsemenov** [comment]
Arrows on touch devices are hidden just via this visibility:hidden style, nothing else. If it doesn't work for you, make sure that it isn't applies.
