### ISSUE TITLE
Detect swipe event

### ISSUE THREAD

**Issue by freiserg** [dimsemenov/PhotoSwipe#870]
Hi!

How to detect swipe event? I would like hide controls when I swipe images on mobile. 

Thank you.

**Comment by dimsemenov** [comment]
`beforeChange ` - slides switched

`mainScrollAnimStart` - animation after swipe

`mainScrollAnimComplete` - animation after swipe ended

http://photoswipe.com/documentation/api.html

**Comment by freiserg** [comment]
Thanks for your reply.

```mainScrollAnimStart``` starts late swipe.

How to distinguish tap and swipe event?
