### ISSUE TITLE
thumbnail has more than 14 images issue

### ISSUE THREAD

**Issue by neve021** [dimsemenov/PhotoSwipe#871]
There is a big blank when the photos among is more than 14.
Here is the screenshot:
http://i.imgur.com/QXIc05R.png

How could I solve the problem?

Thank you for provide the PhotoSwipe

Julius

**Comment by dimsemenov** [comment]
PhotoSwipe does not control initial markup (grid of images). What you see in CodePen demo is just a simple list of images as an example.

You can creates simple grid via CSS, or use JS scripts like Masonry http://masonry.desandro.com/
