### ISSUE TITLE
Get Zoom Spread & DoubleTap Center Coordinates 

### ISSUE THREAD

**Issue by vin-ni** [dimsemenov/PhotoSwipe#872]
Hi,
I've been trying for hours to get the Spread/Double Tap Center Coordinates when zooming with an ipad. On ZoomStart I want to push those coordinates into an array. 

Does anyone know where I can acess that information within photoswipe.js?

Thanks a lot!
Vinni

**Comment by vin-ni** [comment]
My Idea was to use:
```
pswp.framework.bind( pswp.scrollWrap /* bind on any element of gallery */, 'pswpTap', function(e) {
    console.log('tap', e, e.detail);
    // e.detail.origEvent  // original event that finished tap (e.g. mouseup or touchend)
    // e.detail.target // e.target of original event
    // e.detail.releasePoint // object with x/y coordinates of tap
    // e.detail.pointerType // mouse, touch, or pen
});
```
But I dont know which variables i can read and where to put the code.

**Comment by dimsemenov** [comment]
Do you need coordinates after zoom gesture or during it?

Also, please explain why you need this data.

**Comment by vin-ni** [comment]
actually theres no difference. I just want to get the center coordinates of the zoom.
I'm working on a feature that enables to show a zoom-heatmap. To render it correctly i need all zoom center coordinates.

**Comment by dimsemenov** [comment]
For now there is no public method to get pan offset, only zoom level (`getZoomLevel`), you'll need to directly read transform style. I might add something in next update.

On where to check these, check PhotoSwipe events `zoomGestureEnded` (`pswp.listen('zoomGestureEnded', function() { });`) and `pointerUp`.
