### ISSUE TITLE
Layout breaks after orientation change

### ISSUE THREAD

**Issue by releaf** [dimsemenov/PhotoSwipe#873]
I'm having an issue with the latest vewrsion (v4.0.8) of PhotoSwipe on mobile where everything is fine after the first orientation change but then when the orientation changes back to portrait, the resize event appears to fire twice. The first time, the image is automatically centered, but then resize fires again and pushes the image out of view and breaks the layout. From that point on, PhotoSwipe's layout is broken.

Here's a gif to show you the behavior:
![image](http://f.cl.ly/items/2b0H151C2M291t3G0Y0v/photoswipe-bug.gif)

Heres are the relevant parts of my code:
    
       createPhotoItemsArray = function(){
			for(var i = 0; i < slideCount; i++){
				var
					href = $($slides[i]).data('zoom'),
					width = 320,
					height = 240,
					photoSwipeItem = {
						src : href,
						w : width,
						h : height,
						fitRatio: 1
					}
				;
				photoSwipeItems.push(photoSwipeItem);
			}

			return photoSwipeItems;
		},

		initPhotoSwipe = function(slideIndex){
			var
				items = createPhotoItemsArray(),
				options = {
					index: slideIndex,
					bgOpacity: 1,
					showHideOpacity: true,
					history: false,
					loop: false,
					getNumItemsFn: function() {
						return slideCount;
					}
				}
			;
			pswp = new PhotoSwipe($photoSwipeHtml, PhotoSwipeUI_Default, items, options);
			pswp.init();
		},

		photoSwipeEvents = function(){
			$slick.on('click', '.slide', function() {
				slideIndex = $(this).data('slick-index');
				initPhotoSwipe(slideIndex);
			});
		}

and then:

    $(function(){
		photoSwipeEvents();
	});

I'm using the markup provided in the documentation verbatim so I'm not exactly sure what is going on. Any ideas? Thanks for your help.

**Comment by dimsemenov** [comment]
What's in your meta viewport tag? Can you provide link to isolated example
that reproduces the problem?

22 июня 2015, в 22:37, releaf <notifications@github.com> написал(а):

I'm having an issue with the latest vewrsion (v4.0.8) of PhotoSwipe on
mobile where everything is fine after the first orientation change but then
when the orientation changes back to portrait, the resize event appears to
fire twice. The first time, the image is automatically centered, but then
resize fires again and pushes the image out of view and breaks the layout.
From that point on, PhotoSwipe's layout is broken.

Here's a gif to show you the behavior:
http://cl.ly/image/1Q1B0b1m3E28/download/photoswipe-bug.gif

Heres are the relevant parts of my code:

   createPhotoItemsArray = function(){
        for(var i = 0; i < slideCount; i++){
            var
                href = $($slides[i]).data('zoom'),
                width = 320,
                height = 240,
                photoSwipeItem = {
                    src : href,
                    w : width,
                    h : height,
                    fitRatio: 1
                }
            ;
            photoSwipeItems.push(photoSwipeItem);
        }

        return photoSwipeItems;
    },

    initPhotoSwipe = function(slideIndex){
        var
            items = createPhotoItemsArray(),
            options = {
                index: slideIndex,
                bgOpacity: 1,
                showHideOpacity: true,
                history: false,
                loop: false,
                getNumItemsFn: function() {
                    return slideCount;
                }
            }
        ;
        pswp = new PhotoSwipe($photoSwipeHtml, PhotoSwipeUI_Default,
items, options);
        pswp.init();
    },

    photoSwipeEvents = function(){
        $slick.on('click', '.slide', function() {
            slideIndex = $(this).data('slick-index');
            initPhotoSwipe(slideIndex);
        });
    }

and then:

$(function(){
    if($isMultiPhoto){
        $slick.slick(slideSettings);
        updatePhotoCount();
        bindSwipe();

        $(window).on('orientationchange', function() {
            var currentSlide = $slick.slick('slickCurrentSlide');
            $slick
                .slick('unslick')
                .slick(slideSettings)
                .slick('slickGoTo', currentSlide)
            ;
            bindSwipe();
        });
    }

    videoControls();
    photoSwipeEvents();
    // trackEvents();
});

I'm using the markup provided in the documentation verbatim so I'm not
exactly sure what is going on. Any ideas? Thanks for your help.

—
Reply to this email directly or view it on GitHub
<https://github.com/dimsemenov/PhotoSwipe/issues/873>.

**Comment by releaf** [comment]
meta viewport is not set. The site is a mobile specific site built on a fork of twitter bootstrap. Unfortunately, I'm developing this locally and am not able to release the code to our live environment in its current state. I'm not sure if this will help you or not but here's a subset of the code, along with the entire javascript file.
http://codepen.io/releaf/pen/mJqEYq

I only see the issue on an actual iPhone or iOS emulator. My iPhone is on iOS8 and the emulator uses iOS7. 

If I do `console.log(item.initialPosition.x, item.initialPosition.y)` in `_applyZoomPanToItem` I get the following:

    On init: 0 110
    Rotate to landscape: 124 40
    Rotate back to portrait: 124 110

![image](https://cloud.githubusercontent.com/assets/4107042/8315912/b111bcaa-19c1-11e5-963d-c54fb1d4a40b.png)


I'm guessing the first value (124) after the last rotation back to portrait is incorrect which is what is causing the images to get cut off. Shouldn't that be 0, like it was on init? Also, even if I `pswp.destroy();` the gallery, when it opens up again, it's still messed up so it seems those values are getting cached somehow.

**Comment by dimsemenov** [comment]
So have you tried to add proper viewport meta tag? http://getbootstrap.com/css/#overview-mobile

**Comment by releaf** [comment]
Yes I've tried both `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">` and `<meta name="viewport" content="width=device-width, initial-scale=1">` but neither make a difference.

**Comment by dimsemenov** [comment]
I can't assist much without live [reduced test case](https://css-tricks.com/reduced-test-cases/) that reproduces the problem.

**Comment by releaf** [comment]
Well, I created a reduced test case and the problem is no long there so I guess it's something on my end. What that something is escapes me. 

Are there any methods I can use to recalculate the position after resize?

**Comment by releaf** [comment]
Nevermind - I found the issue. We have a check in our system that sets the document width at 250ms interval to fix an android orientation change bug. This was causing a recalculation of the document width after PhotoSwipe had already gotten its width from the viewport width. 

Thanks for your help and sorry if I sent you down a rabbit hole.
