### ISSUE TITLE
Modifying JSON for a huge gallery

### ISSUE THREAD

**Issue by 3zzy** [dimsemenov/PhotoSwipe#875]
I'm using PhotoSwipe in an unconventional manner — to display scanned images of a book. 

Its going good so far except that the JSON file is unnecessarily huge because of the `required` width and height objects. 

In my case, all slides (or pages) of the gallery (book) will have the exact same width and height so I could just mention that once in the JSON and have it applied to all slides, so something like:

    [
        [
            964,
            1024
        ],
        [
            "/path/to/slide1",
            "/path/to/slide2",
            "/path/to/slide3"   
        ]
    ]

... but I'm not sure how to do that, would be great if possible.

Thanks!

**Comment by dimsemenov** [comment]
Use `gettingData` event, e.g.:

```js
pswp.listen('gettingData', function(index, item) {
    item.w = 964;
    item.h = 1024;
});
```

... just make sure that you bind it before `init()`. You can use it to modify any property, not just w and h.

http://photoswipe.com/documentation/api.html

**Comment by 3zzy** [comment]
Thanks, that works! :)
