### ISSUE TITLE
Transition lag on Android <=ICS and iOS (iPhone4)

### ISSUE THREAD

**Issue by 3zzy** [dimsemenov/PhotoSwipe#876]
Although I don't have anything fancy going in and I did check the performance tips section, but still the experience on **Moto G 1st Gen** (Lollipop),  **Redmi Note** (IceCream Sandwich, but a fairly fast phone) ** and **iPhone 4** (iOS 7) is super-laggy, almost unusable. On **iPhone 5S** its smooth though.

Surprisingly, the official demo on PhotoSwipe website works perfectly fine on the same devices, so I'm hoping its just a configuration thing. 

Images are **960 x 1585** at approx **70KB** each.

**HTML** is just the default pswp template. 

**JS**:

    $('#library').on('click', '.book', function() {
        var bookID = this.id;
        var bookData = "books/"+ bookID + ".json";
        var pswpElement = $('.pswp')[0];
        $.getJSON(bookData, function(data, status) {
            var options = {
                getThumbBoundsFn: function(index) {
                    var thumbnail = $("#"+ bookID + ' .cover img')[0];
                    var pageYScroll = window.pageYOffset || document.documentElement.scrollTop; 
                    var rect = thumbnail.getBoundingClientRect(); 
                    return {x:rect.left, y:rect.top + pageYScroll, w:rect.width};
                },
                showAnimationDuration: 500,
                hideAnimationDuration: 500,
                closeOnVerticalDrag: false,
                spacing: 0.05,
                history: false,
                focus: false,
                barsSize: {top:88, bottom:'auto'},
                closeEl: false,
                captionEl: false, 
                fullscreenEl: false,
                zoomEl: false,
                shareEl: false,
                arrowEl: false
            };
            var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, data, options);
            gallery.listen('gettingData', function(index, item) {
                item.w = 960;
                item.h = 1585;
            });
            gallery.init();
        });
        
    });

What am I doing wrong?

(Unrelated: Does PS use Velocity.js for animations? If not, that would significantly improve the performance I believe, I'll look into it next. )

Thanks!

**Comment by dimsemenov** [comment]
- Size of images might be the case (not necessarily image itself, but values that you pass in `w` & `h`).
- Also, can be some element(s) or action on page with the PhotoSwipe that causes layout thrashing.

Without reduced test case that reproduces the problem – I can't help much.

> Does PS use Velocity.js for animations? If not, that would significantly improve the performance I believe, I'll look into it next

It won't.

**Comment by 3zzy** [comment]
You can see it working here: http://ezzy.me/ebook/

Most of the code is PS related, nothing else really.

**Comment by dimsemenov** [comment]
So have you tried to reduce w/h properties on mobile?

**Comment by 3zzy** [comment]
That indeed fixed the issue but one cannot really consider Redmi Note a *slow* phone because its octa core and generally performs really well. So I wonder if this slowness is due to some browser or memory limitation? 

For now, I'm just detecting mobile from user-agent, but If its possible to detect the limit and then set the image size accordingly, that would be great so faster/newer and/or devices with larger limits can use high-res images.
