### ISSUE TITLE
Disabling click/touch on certain elements

### ISSUE THREAD

**Issue by 3zzy** [dimsemenov/PhotoSwipe#877]
I've added a [scrubber] (https://github.com/desmosinc/scrubber) and using it like so:

    scrubber.onValueChanged = function (value) {
      gallery.goTo(value);
    };
    gallery.listen('afterChange', function() { scrubber.value(gallery.getCurrentIndex()); });
    gallery.listen('close', function() { $('.pswp__scrubber').empty(); });

.. it seems to work well except that when I'm interacting with the scrubber, PS slides the images. How do I disable slide/drag *only* on the **.pswp__scrubber** element?

I tried this, but the slides still "shake" when I use the scrubber:

    gallery.listen('preventDragEvent', function(e, isDown, preventObj) {
        if ( $(".thumb.dragging") ) {
            console.log(1);    
            isDown = false;
            preventObj.prevent = true;
        }
    });

(the scrubber handle has class **dragging** while its being used)

EDIT:

Also tried:

    gallery.listen('preventDragEvent', function(e, isDown, preventObj) {
        if (e.target.className === "scrubber" || e.target.className === "track" || e.target.className === "thumb" ) {
            isDown = false;
            preventObj.prevent = true;
            console.log(e.target.className);
        }
    });

... but its the same.

**Comment by dimsemenov** [comment]
Put elements outside of `.pswp__scroll-wrap`.

`preventDragEvent` only controls on which elements `preventDefault()` should be called.

**Comment by 3zzy** [comment]
That worked like a charm! Thanks!

**Comment by Giampietro** [comment]
Hi, is possible to disable drag in desktop view?
Thank you

**Comment by dimsemenov** [comment]
@Giampietro, you can not. "desktop" is a very wide term. You can unbind mousedown event from `pswp__scroll-wrap` element, but it might affect some mobile browsers that support only mouse events.

**Comment by ianthedev** [comment]
> Put elements outside of `.pswp__scroll-wrap`.
> 
> `preventDragEvent` only controls on which elements `preventDefault()` should be called.

Not sure how that works. I need to place similar interactable objects inside slide elements and prev/next functionalities need to work, too.

**Comment by namespace-dave** [comment]
@dimsemenov do you have an example for the best approach to unbind `pointerdown` from `.pswp__scroll-wrap` ?

**Comment by dimsemenov** [comment]
@namespace-dave yep, that's correct, I was typing the same thing before I saw your edit
