### ISSUE TITLE
Extending tapToToggleControls

### ISSUE THREAD

**Issue by 3zzy** [dimsemenov/PhotoSwipe#878]
I need to show/hide certain elements (scrubber) based on the visibility of the controls. So something like this would be ideal:

    if(controlsVisible) {
    	// do x 
    } else {
    	// do y
    }

.. is there any existing function for it that I can use.

**Comment by dimsemenov** [comment]
UI does not dispatch any events. Edit it direclty, or override function, e.g.:

```
pswpInstance.ui.defaultHideControls = pswpInstance.ui.hideControls;
pswpInstance.ui.hideControls = function() {
    console.log('hello wold');
    pswpInstance.ui.defaultHideControls();
};
```

.. same for showControls.

**Comment by 3zzy** [comment]
Great, that worked! 

Thanks :)
