### ISSUE TITLE
Conditional Share Links

### ISSUE THREAD

**Issue by prohtex** [dimsemenov/PhotoSwipe#882]
I need to implement PhotoSwipe with conditional share links. In other words, certain slides have additional share links based on their image properties. My PHP can determine which slides meet the criteria (in this case, large image size), and add an additional variable to the item array. But it seems the share links are defined on a per-gallery basis with the PhotoSwipe constructor. Is there a way to define a share link in an individual slide object?

**Comment by dimsemenov** [comment]
You may toggle the visibility of the element in events like `beforeChange`. 

Or modify the UI directly to fit your needs.

**Comment by prohtex** [comment]
The problem for me is that the buttons are configured on gallery init, not per-slide. I managed to perform what I needed by embedding and positioning a div in my captions. Not ideal, but much less work! Thanks.
