### ISSUE TITLE
Hide caption on zoom

### ISSUE THREAD

**Issue by prohtex** [dimsemenov/PhotoSwipe#884]
I have a PhotoSwipe site with quite a few large multi-line captions. Is it possible to hide the caption block when zoom is triggered, and show it again when the image is zoomed out? Any pointers would be appreciated.

**Comment by prohtex** [comment]
I also noticed that on a touch device, a tap will hide the controls, and the caption. On the desktop, moving the controls will hide on mouseout, but not the caption. Can the caption be hidden on this action?

**Comment by prohtex** [comment]
I answered my own question, it can be done with the following CSS:
.pswp__ui--idle .pswp__caption {
  opacity: 0; }

**Comment by UberGruber** [comment]
Thank's for the heads up, I was looking for something like this! 
May I suggest to place it in the docs somewhere?

**Comment by axelson** [comment]
For anyone else finding this, I believe that this CSS is an improvement over https://github.com/dimsemenov/PhotoSwipe/issues/884#issuecomment-116262231 

```
.pswp--zoomed-in .pswp__caption {
  opacity: 0;
}
```

Since it is actually operating on the zoomed-in state rather than idle.

**Comment by dujoducom** [comment]
I don't seem to get any zoom state information when using photoswipe on a mobile device (iPad). Is anyone else having this issue?
