### ISSUE TITLE
Antinomic feeling reading a sentence describing PhotoSwipe

### ISSUE THREAD

**Issue by calimou** [dimsemenov/PhotoSwipe#890]
Hi,
From http://photoswipe.com/documentation/getting-started.html I can read
> PhotoSwipe is made simple and fast for end users, not for developers. It ain't simple jQuery plugin, at least basic JavaScript knowledge is required to install.

So in one hand, PhotoSwipe is made simple for the end users, but in another hand that same end user should have JavaScript knowledge to install. I feel a bit confused. Any reaction/explanation welcome ! 

Cheers

**Comment by dimsemenov** [comment]
End user is not a developer who makes the website, it a user that visits the website.

Quoting Paul Lewis from recent article:

> It seems to me that developer ergonomics should be less important than our users’ needs, as painful as that can be for us developers.

**Comment by calimou** [comment]
Ok I understand PhotoSwipe is not a standalone photo gallery software. That's all :) Thanks
