### ISSUE TITLE
Why recreate 'slides' object for each thumbnail click?

### ISSUE THREAD

**Issue by mjau-mjau** [dimsemenov/PhotoSwipe#891]
One thing that eludes me in the documentation examples, is why the entire gallery/slides object is recreated for each thumbnails click. Surely the slides object could be created on page load (after page load or ajax content load), or on first thumbnail-click, and then re-used on consecutive thumbnail clicks? A ```parseThumbnailElements``` function that triggers on each thumbnail click requires looping through all images on page to create the slides object, even though the object is persistent.

I can only see it is done like this by example, to avoid user-implementation pitfalls, or if the gallery is appended upon dynamically. Am I wrong?

The same applies for the options object, but this is of little significance.

Thank you for creating this beautiful script.

**Comment by dimsemenov** [comment]
1. Tests show that the majority of users that use simple gallery, open it once, navigate through images,  close, and never open again. Which means there is no point to store in memory additional data.
2. Init code is not included in core of a script on purpose so you can modify it if it doesn't fit requirements of your content model. For example, if you have huge gallery with hundreds of images, you can parse DOM dynamically as user browses through images using `gettingData` event. http://photoswipe.com/documentation/api.html
3. Parsing anything via JavaScript on page load is generally not a good idea, as it blocks the main thread, so default init code just binds one click event for each gallery, and check the URL. 

Hope it answers the question.

**Comment by mjau-mjau** [comment]
Yes, thanks. I'm gathering that we *could* makes the slides object persistent if it suits our implementation.
