### ISSUE TITLE
Change size / recompute image sizes & redraw itself

### ISSUE THREAD

**Issue by asadovsky** [dimsemenov/PhotoSwipe#892]
In my use of photoswipe, I have a sidebar that can be expanded or collapsed, which affects the width of the container that photoswipe runs in. Unfortunately, it appears that photoswipe doesn't automatically respond to resizes of its container. (Note, the top-level window object is not changing in size.) What's the best way to force photoswipe to recompute image sizes & redraw itself?

**Comment by asadovsky** [comment]
(I tried calling the `updateSize` method, but that didn't work.)

**Comment by dimsemenov** [comment]
- Width can be changed either of `.pswp` or `.pswp__scroll-wrap` elements.
- Size is updated by `updateSize` method, or by `window.resize` event.

**Comment by asadovsky** [comment]
This line of code results in my `.pswp` element picking up a `position: fixed` style rule:
https://github.com/dimsemenov/PhotoSwipe/blob/63de5f1f157c2d1625971e8f73658c8df74118bb/src/js/core.js#L567

That, combined with the top/right/bottom/left being 0, results in the `.pswp` element always filling the entire window, regardless of its container element's dimensions.

I'm using an edited version of the photoswipe CSS, so perhaps it's an error on my side.

Adding the following style rule (thereby overriding the `position: fixed`) results in `updateSize` having the desired effect:

    .pswp {
      position: absolute !important;
    }

**Comment by dimsemenov** [comment]
If you want PhotoSwipe to fill the parent container, like here http://codepen.io/dimsemenov/pen/JogxWM , disable the modal option, there is a small guide in FAQ http://photoswipe.com/documentation/faq.html#inline-gallery

**Comment by asadovsky** [comment]
Ah, thanks! That did the trick.
