### ISSUE TITLE
problem when using rtl language

### ISSUE THREAD

**Issue by uzimedia** [dimsemenov/PhotoSwipe#895]
Hi and thanku for doing photoswipe
I recommend to improve and adding an option for rtl lang
![12](https://cloud.githubusercontent.com/assets/7235377/8593270/e5f703b0-263e-11e5-8fe9-3dcfcfd71a23.PNG)
best regards 
Uzi

**Comment by dimsemenov** [comment]
Thanks!

**Comment by uzimedia** [comment]
if you do this I will be glad to know (-:
