### ISSUE TITLE
Scroll during after-swipe transition breaks the gallery

### ISSUE THREAD

**Issue by InixDesign** [dimsemenov/PhotoSwipe#898]
Hi, there is a bug,
it can be reproduced many times in all browsers:
1. swipe the image by mouse to the right
2. scroll mouse wheel before new image gets to its final position

The image without background will be still on screen showing background and let's You even scroll the page under it.

It works also on: http://photoswipe.com/

Greetings.
![photoswipe_bug](https://cloud.githubusercontent.com/assets/13274605/8619739/a0a5687a-2719-11e5-9877-7c26e5e581ba.jpg)

**Comment by dimsemenov** [comment]
Good catch, will be fixed.
