### ISSUE TITLE
Rename `w` and `h` to `width` and `height`

### ISSUE THREAD

**Issue by AlecRust** [dimsemenov/PhotoSwipe#901]
I notice you require an image object with `w` and `h` values for this plugin to work.

The data I'm passing in to PhotoSwipe matches the required object, except the width and height values are named `width` and `height` rather than `w` and `h`.

I'd argue `width` and `height` are better names than `w` and `h`. Would you be open to merging a PR renaming this if I made one?

**Comment by dimsemenov** [comment]
I really don't want to change existing behaviour. You can pre-parse the data using `gettingData` event, it's executed only when PhotoSwipe reads src or w/h:

```js
...

var pswp = new PhotoSwipe( ... );

pswp.listen('gettingData', function(index, item) {
  item.w = item.width;
  item.h = item.height;
});

pswp.init();
```

**Comment by AlecRust** [comment]
Fair enough, thanks for the advice :+1:
