### ISSUE TITLE
Preload prevents lazyloading

### ISSUE THREAD

**Issue by prohtex** [dimsemenov/PhotoSwipe#904]
I have PS implemented on a site that uses lazysizes on a thumbnail grid (https://github.com/aFarkas/lazysizes). The issue I'm having is that PhotoSwipe will begin to preload images before lazysizes has finished loading high-qualty thumbnails. If I disable the PS init, empty browser cache, and navigate to the page, first low-res thumbs load, then after about .5 seconds, they are replaced by high-quality thumbs. If I enable the PS init on that same page, the loading changes - first, low-res thumbs load, then PS preloads lots of images, then 9 or 10 seconds later, the high res thumbs load. Is there a way for me to prevent PS from preloading until all other elements on the page load? If I use jQuery to poll the elements to see if the high res thumb has loaded, then init PS, this leaves a window where the page is exposed with fallback <a> links.

**Comment by dimsemenov** [comment]
PhotoSwipe does not modify markup of the page. It opens only images that you pass to `PhotoSwipe` constructor. If you don't want PhotoSwipe to stretch thumbnail, do not define `msrc` in slide.

**Comment by prohtex** [comment]
This is not the issue - PS is preventing other elements on the page from loading. I am asking if there is a way to prevent PS from preloading images until it is opened.

**Comment by dimsemenov** [comment]
There is no such option. Just don't open it until it's needed.

**Comment by prohtex** [comment]
Right now, when I init PS, it preloads all the images. The preloading prevents other elements on the page from loading. But if I wait to init, then the clicks to not open the gallery. I need a way to init PS, but to preload only when PS is opened.

**Comment by prohtex** [comment]
I have created a gallery here where the issue can be observed. The high res thumbs do not load until PS has loaded all its slides, which can sometimes take 15 seconds or more!
http://www.thing.gallery

**Comment by prohtex** [comment]
So there's no way to prevent PS from preloading images before lightBox.init();?

**Comment by dimsemenov** [comment]
Again, PhotoSwipe starts loading images only after you create its instance (`new PhotoSwipe()`) and `init()` it

**Comment by prohtex** [comment]
Ok, so in the sandbox I have created, you can see that clicking on the menu items will load the gallery and create a new PhotoSwipe instance. The thumbnail loading is prevented by PhotoSwipe preloading images, even *before* the click event that calls init(). If the PhotoSwipe code is disabled, the thumbs load normally. http://www.thing.gallery

**Comment by prohtex** [comment]
This is my code, with the gallery init commented out:

**Comment by dimsemenov** [comment]
```js
$.each(items, function(index, value) {
        image[index]        = new Image();
        image[index].src    = value['src'];
        });
```

???

**Comment by prohtex** [comment]
Aha! I was wondering why that was in there... Thanks!
