### ISSUE TITLE
what if thumbnail has forced cropped dimensions?

### ISSUE THREAD

**Issue by nicmare** [dimsemenov/PhotoSwipe#911]
my setup:
forced cropped square thumbnails
normal regular big images without cropping

when i click the thumbnails, i have a weird enlargement animation. its because photoswipe expects the same proportions for both the thumbnails and large images.

does someone has an idea how to handle this?

**Comment by dimsemenov** [comment]
Updated faq: http://photoswipe.com/documentation/faq.html#different-thumbnail-dimensions

**Comment by nicmare** [comment]
oh. did not see that. thank you dmitry!

**Comment by markseu** [comment]
The FAQ mentions two possibilities, I found one more:

If thumbnail aspect ratio does not match large image, do not define `msrc` property for slide objects and do not show zoom-in transition (`showHideOpacity:true, showAnimationDuration:0`). What you get is a very quick transition, not the smooth one you usually see but not bad either.

**Comment by nicmare** [comment]
thanks mark
