### ISSUE TITLE
Event on slide change

### ISSUE THREAD

**Issue by prohtex** [dimsemenov/PhotoSwipe#915]
Is it possible to access the slide change event? Maybe in the constructor, such as:
galleryOpenFn - call every time PS is opened
galleryCloseFn - call every time PS is closed
slideChangeFn - call every time slide is changed
?

**Comment by dimsemenov** [comment]
`beforeChange` http://photoswipe.com/documentation/api.html

**Comment by prohtex** [comment]
Sorry should have read the API. Thanks.
