### ISSUE TITLE
Align caption div with edge of photo

### ISSUE THREAD

**Issue by prohtex** [dimsemenov/PhotoSwipe#916]
I am trying to set the caption div width to match the slide, so the caption lines up with the edge of the image. I am using the currItem object to calculate the slide width, then setting the div width on the beforeChange event. This is my code:

	var lightBox = new PhotoSwipe($('.pswp')[0], PhotoSwipeUI_Default, items, options);
	lightBox.init();
	$('div.pswp__caption__center').width(Math.floor(lightBox.currItem.w*lightBox.currItem.fitRatio));
	lightBox.listen('beforeChange', function() {
		console.log($(window).width);
		console.log(lightBox.currItem);
		$('div.pswp__caption__center').width(Math.floor(lightBox.currItem.w*lightBox.currItem.fitRatio));
		//this.updateSize(true);
		});
	lightBox.listen('resize', function() {
		$('div.pswp__caption__center').width(Math.floor(lightBox.currItem.w*lightBox.currItem.fitRatio));
		});

Sometimes, the caption ends up in strange places. On this image for example, with a window width of 1252, the caption is sized to 1088. But the currItem object reports width of 1000 and fitRatio of 1.068. Thus, the caption should be 1068, not 1088.

	http://www.thing.gallery/#&gid=front&pid=13-torben-ribe

On this slide, the caption enters the slide area, but when the window is resized, it “corrects” itself:

	http://www.thing.gallery/#&gid=front&pid=7-lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-sed

I can’t figure out why this is happening! Please help!

**Comment by prohtex** [comment]
Issue can be seen especially on these 2 slides:
http://www.thing.gallery/#&gid=front&pid=7-lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-sed
http://www.thing.gallery/#&gid=front&pid=13-torben-ribe

I have tried some of the other events as well (afterChange etc) with no luck

**Comment by prohtex** [comment]
Also, I have tried other events, such as afterChange, with little success.

**Comment by prohtex** [comment]
Well, the solution to the worst of these problems was simply adding "<!DOCTYPE html>" to the document. I am still finding some positioning quirks and will post an updated issue shortly.

**Comment by prohtex** [comment]
Also - a note: I didn't realize updateSize calls "resize" event. I had created an infinite loop!

**Comment by prohtex** [comment]
https://github.com/dimsemenov/PhotoSwipe/issues/919

**Comment by axelson** [comment]
Here is my own implementation of aligning the caption with the edge of the photo:

```
    function adjustCaptionWidth () {
      var imageDisplayWidth = gallery.currItem.w;
      if (gallery.currItem.fitRatio < 1) {
        imageDisplayWidth = gallery.currItem.w * gallery.currItem.fitRatio;
      }
      imageDisplayWidth = Math.max(imageDisplayWidth, 300);
      $('.pswp__caption__center').width(imageDisplayWidth);
    }

    gallery.listen('afterChange', adjustCaptionWidth);
    gallery.listen('resize', adjustCaptionWidth);
```

Note: `gallery` is the `pswp` gallery object

But with a minimum width of 300px. Also you need to use css to override the default maximum caption width of 420px.

**Comment by fietstouring** [comment]
works perfectly well, thank you.

**Comment by candeecake** [comment]
I'm new to this... where do I add the function adjustCaptionWidth? And how and where do I call the function? I'm trying to align the caption to the photo so it sits under the edge of the photo.
