### ISSUE TITLE
Open photoswipe with a button

### ISSUE THREAD

**Issue by alextjtaylor** [dimsemenov/PhotoSwipe#917]
I haven't seen this mentioned anywhere - is it possible to open photoswipe by clicking on a link instead of a thumbnail?

I have 1 photo on the page, but I'd like to add a 'view more photos' button that then shows 5 more photos from other pages on the site, shown in photoswipe.

I presume I can add these 5 other photos using a data array I saw in one of the examples.

If this is possible, can you please point me to an example or demo? (I can fiddle with js rather than code it, sorry)

Thanks for a great script!

**Comment by prohtex** [comment]
If you're using jQuery, and you've got your slide array set up, you can create the PS instance like this:

var lightBox = new PhotoSwipe($('.pswp')[0], PhotoSwipeUI_Default, items, options);

Then call init() on click event:

$(".button").click(function() {
	lightBox.init();
	}

<div class='button'>my button</div>

**Comment by prohtex** [comment]
Note that you would also want to set the index:

options.index = 0;

**Comment by dimsemenov** [comment]
@alextjtaylor, there is an example with single button that opens PhotoSwipe literally on the first on of the documentation http://photoswipe.com/documentation/getting-started.html

**Comment by jeroendesloovere** [comment]
@dimsemenov That example reinitializes the photoswipe everytime.
That is not what we want.
Is there a function like this? `lightbox.open(pswp-uid);`

**Comment by AvivAvivA** [comment]
@dimsemenov Hello. Now there isn't an example with button: http://photoswipe.com/documentation/getting-started.html 
And all of the other examples were found in the network, do not work too :(

**Comment by AvivAvivA** [comment]
@dimsemenov 
Hello, same question ... 
http://codepen.io/dimsemenov/pen/gbadPv
in this example a lightbox-gallery is opened with some pictures, wich gotten witn js.
but is it possible, to open by external link some photoswipe gallery wich is already is on the page?

**Comment by chesio** [comment]
@jeroendesloovere AFAIK, you have to re-initialize PhotoSwipe every time, there's no other way.

@AvivAvivA Take a look on the last example at [documentation page](http://photoswipe.com/documentation/getting-started.html) (How to build an array of slides from a list of links). You have to include the following in your code:

<pre>
var initPhotoSwipeFromDOM = function(gallerySelector) {

    (...)

    // parse picture index and gallery index from URL (#&pid=1&gid=2)
    var photoswipeParseHash = function() {
        var hash = window.location.hash.substring(1),
        params = {};

        if(hash.length < 5) {
            return params;
        }

        var vars = hash.split('&');
        for (var i = 0; i < vars.length; i++) {
            if(!vars[i]) {
                continue;
            }
            var pair = vars[i].split('=');  
            if(pair.length < 2) {
                continue;
            }           
            params[pair[0]] = pair[1];
        }

        if(params.gid) {
            params.gid = parseInt(params.gid, 10);
        }

        return params;
    };

    (...)

    // Parse URL and open gallery if it contains #&pid=3&gid=1
    var hashData = photoswipeParseHash();
    if (hashData.pid && hashData.gid) {
        openPhotoSwipe( hashData.pid ,  galleryElements[ hashData.gid - 1 ], true, true );
    }
</pre>

Then you are able to open the gallery by an external link like: http://photoswipe.com/#&gid=1&pid=5

Cheers,
Česlav

**Comment by spburden** [comment]
I figured it out:
$('#btn').on('click', function() {
  $('#gallery').find('img').eq(0).trigger('click');
});
