### ISSUE TITLE
How to center vertically thumbnails? Thank

### ISSUE THREAD

**Issue by pierrewebmaster** [dimsemenov/PhotoSwipe#918]
Hi all
firstly, thank you for this work, this plugin is great!
But I don't understand why I can't get thumbnails center vertically on the list? 
I tried:
.my-gallery drawing {
     display: block;
     float: left;
     margin: 0 5px 20px;
     vertical-align: middle;
     width: 140px;
}
and:
.my-gallery img {
     height: auto;
     vertical-align: middle;
     width: 100%;
}
but the thumbnails are always aligned to top.
Thank you for your help

**Comment by dimsemenov** [comment]
PhotoSwipe doesn't control layout of thumbnails. Please use StackOverflow for such questions.
