### ISSUE TITLE
overflow-y:scroll absolutely impossible?

### ISSUE THREAD

**Issue by mjau-mjau** [dimsemenov/PhotoSwipe#920]
I been testing- and searching around for an answer, but it seems that adding an element with overflow-y:scroll is entirely impossible in PhotoSwipe? Even for a single slide with custom html content, it is impossible to apply overflow-y:scroll to a container element, to allow the content within to scroll inside its container if necessary. I understand this could conflict with the photoswipe general functionality, but is there no way in hell one can override this limitation from JS and/or CSS for a single html slide which does not require any specific touch/zoom/pinch/swipe?

**Comment by dimsemenov** [comment]
Check `preventDragEvent ` event http://photoswipe.com/documentation/api.html

But be careful, as older Androids have a lot of bugs when prevetnDefault isn't called on touchstart/move/end.

**Comment by mjau-mjau** [comment]
Thanks, but I can't see that this function does anything else than preventing the PS drag event from firing on touchstart/mousedown/pointerdown on certain objects. I can't see how it allows 'scroll' event on any elements like I am trying to achieve.
![screen](http://d.pr/i/14gXD+)

**Comment by mjau-mjau** [comment]
I guess PhotoSwipe should not be used for this.

**Comment by shaunjc** [comment]
I was able to get scrolling working by stopping event propagation on the scrollable div.

    // My markup contains the div which is scrollable.
    var items = [{html: '<div class="grid center-x-y"><div class="lightbox scrollable">' + imgTag + '</div></div>'}];
    
    // .scrollable is created dynamically, so we add the listener to the item which should always be on the page.
    $('.pswp__container').on('wheel mousewheel DOMMouseScroll', '.scrollable', function(e) {
        // Stop the event propagation bubbling up to the existing photoswipe listener.
        e.stopPropagation();
    });
    
Please note that when the user grabs the scrollable div, this will prevent them from swiping left and right. I've tried adding a specific check for sideways scrolling `!e.originalEvent.deltaX`, but I've been unable to get it working consistently.

**Comment by JacobDB** [comment]
Here's a vanilla JS version that works with PhotoSwipe 5:

```js
lightbox.on("afterInit", () => {
    document.querySelector(".pswp").addEventListener("wheel", (e) => {
        if (e.target.classList.contains("scrollable") || e.target.closest(".scrollable")) {
            e.stopPropagation();
        }
    }, true);
});
```
