### ISSUE TITLE
Caption text is not selectable

### ISSUE THREAD

**Issue by MichaelKubovic** [dimsemenov/PhotoSwipe#922]
I've implemented custom addCaptionHTMLFn, but the text of the caption is not accessible so that the user cannot use mouse to select it. [demo](https://www.t3works.sk/referencie-a-inspiracie)
Can you suggest a way to fix it? Thanks.

**Comment by dimsemenov** [comment]
Use `preventDragEvent ` and add `preventObj.prevent = true;` if event target is caption or its child.
