### ISSUE TITLE
How to put inline edit functionality?

### ISSUE THREAD

**Issue by sk29110** [dimsemenov/PhotoSwipe#927]
I am trying to add inline edit functionality to the plugins and stock on where I can actually called this function so that description can be edit. Here is the url to the plugin
http://www.appelsiini.net/projects/jeditable

After going through the code I think addCaptionHTMLFn is the one but it was called hundred of times
on document ready and as you go through each images with page navigation. I just need to call the function using the specific class where description is specified and url to submit the actual change, but when I call this function I need to have the element rendered in the html document. Where is the best place to put this function?

**Comment by dimsemenov** [comment]
Edit the default UI JS file to fit your needs. It's specifically added separately, so you can modify it if you need some advanced logic.

**Comment by sk29110** [comment]
Thanks. But the function addCaptionHTMLFn get called many times when opening the image is bug or something you expected?

**Comment by dimsemenov** [comment]
It's triggered when items are changed, and on next/prev item based on direction.
