### ISSUE TITLE
Detecting a swipe to trigger an event

### ISSUE THREAD

**Issue by jamminjames** [dimsemenov/PhotoSwipe#930]
I'm trying to detect a swipe, or more accurately, a change of slide content, using the info provided in your API. This isn't doing anything, however. What am I doing wrong? Thanks for any help.

`<script>	`
var pswp = new PhotoSwipe(/* ... */);

$( document ).ready(function() {
    //detect swipe
	pswp.listen('afterChange', function() {
		pswp.shout('helloWorld', 'John');
	});
}); 
`</script>`

**Comment by mjau-mjau** [comment]
I am not seeing all your code, and sounds like ```pswp``` is out of scope somehow. Try ```console.log(pswp)``` inside $(document)ready() ... what does it say?

**Comment by jamminjames** [comment]
I get: 
`Object { initGestures: PhotoSwipe/<.publicMethods.initGestures(), lazyLoadItem: PhotoSwipe/<.publicMethods.lazyLoadItem(), initController: PhotoSwipe/<.publicMethods.initController(), getItemAt: PhotoSwipe/<.publicMethods.getItemAt(), allowProgressiveImg: PhotoSwipe/<.publicMethods.allowProgressiveImg(), setContent: PhotoSwipe/<.publicMethods.setContent(), cleanSlide: PhotoSwipe/<.publicMethods.cleanSlide(), initTap: PhotoSwipe/<.publicMethods.initTap(), onTapStart: PhotoSwipe/<.publicMethods.onTapStart(), onTapRelease: PhotoSwipe/<.publicMethods.onTapRelease(), 31 more… } `

In the list of 31 more, shout and listen are there. What will the result of 'shout' look like? A dialog box? Not getting any result.

Should something go in the `/* ... */` space of the `var pswp = new PhotoSwipe( /* ... */ );` line?

Also, I'm getting this warning: "Will-change memory consumption is too high. Surface area covers 2148304 pixels, budget is the document surface area multiplied by 3 (668624 pixels). All occurences of will-change in the document are ignored when over budget."

**Comment by mjau-mjau** [comment]
My last reply was perhaps a bit premature. In the specific code in your example, you are not really doing anything. The afterChange even may be triggering, but the 'shout' method there won't do anything as it's just an example from the documentation. Try this:
$( document ).ready(function() {
//detect swipe
pswp.listen('afterChange', function() {
console.log('afterChange event. Triggers after slide changes.');
});
}); 

Never mind the 'will-change' notification.

**Comment by jamminjames** [comment]
Sorry, still not doing anything. Nothing shows in the console log when I flip through the slides.  

Here's the complete script as I have it:
<script>

var pswp = new PhotoSwipe( /* ... */ );

$(document).ready(function() {
	pswp.listen('afterChange', function() {
		console.log('afterChange event. Triggers after slide changes.');
	});
});
</script>

**Comment by mjau-mjau** [comment]
Why are you adding the listener inside the document.ready event, while creating the photoswipe instance outside? The listener can go right after the photoswipe instance creation. Also, that is not the 'complete' script I hope? I assume you don't have ```/* ... */``` inside the photoswipe object?

The afterChange event works fine when added to a fork of the main photoswipe demo http://codepen.io/mjau-mjau/pen/XbqBbp. You will see in console that the console logs the ```afterChange``` event.

I can't diagnose your code unless you have a live example or a codepen.

**Comment by jamminjames** [comment]
Sorry I was slow to add this, but for anyone looking for a solution, what worked for me was to use the 'gettingData' hook:

   `gallery.listen('gettingData', function(index, item) {
        if(index === 5) {
		console.log(index);
		}
    });`

...right before the gallery.init(); line.
