### ISSUE TITLE
preloading images

### ISSUE THREAD

**Issue by mustafaarun** [dimsemenov/PhotoSwipe#931]
Hello,
first of all, thank you for such a great slideshow.
my issue is about preloading. altough preload option is [1,1], it preloads all images in gallery. 
and this causes problems in ios, is there a way i can make it preload only one before and one after ?

thank you

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

**Comment by mustafaarun** [comment]
thank you for answer, turns out that loading all images is caused because of preparing script. nothing to do with photoswipe.
now i wonder if i can cancel preloading once for all? i want images to load only when active

**Comment by dimsemenov** [comment]
For now there is no option to set less then `[1,1]`, you can only disable `loop` option so at 1st slide only 2nd will be loaded.

**Comment by mustafaarun** [comment]
but when you continue changing slides,  it preloads 2 more slides, even if i commented the lazyload sectionts in "beforechange" event i can't prevent it. can you direct me to the right peace of code to prevent loading next one ?

thank you.

**Comment by mjau-mjau** [comment]
As far as I understand, PhotoSwipe will *always* preload the two neighboring slides, because they are already made available in the DOM. Thus, it will always make sure the next/previous slides are loaded *after* changing slides also. Not sure why you would not want this behavior, as it is kind of a crucial behavior for photoswipe.

**Comment by mustafaarun** [comment]
even if we use smaller images for large size on IOS sometimes safari crashes, so that i thought that if i cancel the preload event maybe this prevents crashing

**Comment by dimsemenov** [comment]
@mustafaarun, are you using the latest version of PhotoSwipe, what's the size of images?

**Comment by mjau-mjau** [comment]
Been testing feverishly with my iOS (iphone) device lately, and it's never crashed photoSwipe even when using heavy images. It is likely memory-related and perhaps you are testing from an older device? Even if you didn't preload next image, you would need to purge images after new ones are displaying if you consistently want to have only 1 image loaded into Photoswipe. It's not worth it ...

**Comment by mustafaarun** [comment]
latest version works flawlessly, there is one another small issue; sometimes (on ipad retina) when you  zoom before loading large size completed, img replaces with loaded large one but displays zoomed out. on desktop this works as expected
please see attached images
![img_0054](https://cloud.githubusercontent.com/assets/8030368/9132538/e0b743cc-3cfc-11e5-9f4b-9cf8069a0607.jpg)
![img_0052](https://cloud.githubusercontent.com/assets/8030368/9132537/e0b2cc20-3cfc-11e5-9ce7-bedf87b82e79.jpg)

**Comment by dimsemenov** [comment]
@mustafaarun, please provide a reduced test case, like I mentioned if the first reply (if you can't repeat the issue on the main demo page).

**Comment by mustafaarun** [comment]
http://kilim.com:8888/Types/Overdyed-Rugs on this page click one of the images and before large image load complete zoom loading image when large image loading is completed you'll see a blank screen and on top left corner loaded image.

i saw this behavior only on iPad

**Comment by mustafaarun** [comment]
preloading issue is solved with the latest version (v4.1.0), i'm gonna start a new issue for above problem
