### ISSUE TITLE
Why don't items get purged on destroy()?

### ISSUE THREAD

**Issue by mjau-mjau** [dimsemenov/PhotoSwipe#932]
I am wondering if there is any reason why .pswp__item's don't get removed from DOM after PhotoSwipe closes? Surely the items are re-populated if/when PhotoSwipe re-opens, and it would free up memory to remove them?

I did not find any problems with this, apart from in Internet Explorer when loading a Youtube embed into html slide. It displays fine, and closes fine, but when triggering any photoswipe once the Youtube embed is dormant in an item, the browser crashes.

**Comment by dimsemenov** [comment]
After photoswipe is closed its root element is hidden with display:none, which removes all child elements from browser render tree. If it's not enough for your app, you may remove `.pswp` element entirely after PhotoSwipe is closed, and add it back directly before the opening.

**Comment by mjau-mjau** [comment]
Sounds fair. The IE crash was false alarm anyway ... Seems it only triggers in my windows testbox when IE devtools are open.

**Comment by dimsemenov** [comment]
Curious, in what exactly version of IE it happened?

**Comment by mjau-mjau** [comment]
That would be 11.0, but it was only reacting on this youtube slide specifically, and I don't trust this old machine.
