### ISSUE TITLE
Inserting an admob ad as a slide

### ISSUE THREAD

**Issue by jamminjames** [dimsemenov/PhotoSwipe#933]
Would it be possible to use admob (https://github.com/floatinghotpot/cordova-admob-pro) to display an ad in the place of a slide? Can js be inserted into a slide? I tried, and it didn't work for me. 

If not, is there another way to use admob within photoswipe, do you think?

**Comment by mjau-mjau** [comment]
Unless you have some experience with admob, and in their API there is some method to 'get' an add in html, in which case you can inject it as a photoswipe slide. It would have to be done in your own javascript by combining the two plugins' API. Also, if the banners use iframe to load remote ads, you may have another problem.
