### ISSUE TITLE
Top Bar appears/disappears with mouse, but not on mobile

### ISSUE THREAD

**Issue by jamminjames** [dimsemenov/PhotoSwipe#935]
I'd like to have the Top Bar fade out on a mobile device after a swipe, like it does on a desktop when there is no mouseover, however, it stays there. Is that a setting somewhere, because I can't find it. 

Also, a single tap will remove the Top Bar, but also the caption. Is there a way to set it so the caption stays?

**Comment by mjau-mjau** [comment]
The short answer is no. By default, touch devices will simply toggle interface visibility on touch, including topbar and caption. If you want to change it, you would need to disable ```tapToggleControls``` setting, and instead add your own touch-event that triggers a toggle for the arrows and topbar only.

**Comment by mjau-mjau** [comment]
You could hack it with a simple line of CSS, but perhaps not recommended:
```css
.pswp__caption {
  opacity: 1 !important;
}
```
With the above CSS, the caption will not get hidden. The CSS will also apply for mouse devices though ... If you want to avoid that, you would need to add detection for touch only.
