### ISSUE TITLE
I got a problem when i integrate photoswipe with ionic/angular

### ISSUE THREAD

**Issue by goodwinfame** [dimsemenov/PhotoSwipe#937]
I'm using ionic/angular to build an app,
when I tried to use directive to integrate photoswipe,  an error was given by the chrome

![qq 20150812200644](https://cloud.githubusercontent.com/assets/8966984/9223603/2d7bb014-412e-11e5-96b5-296f751c7ecc.png)

my directive is quite simple, it looks like this:

![qq 20150812200717](https://cloud.githubusercontent.com/assets/8966984/9223617/51b4a2ce-412e-11e5-99ea-ab6f7bc2d4f7.png)

call the image service to get the image array, then initialize photoswipe,

![qq 20150812200749](https://cloud.githubusercontent.com/assets/8966984/9223708/22b601ec-412f-11e5-8f7e-4d89110978f6.png)

the trigger of '$scope.photoSwipe' is a picture render by another controller
and I put the photoswipe directive here

![qq 20150812200809](https://cloud.githubusercontent.com/assets/8966984/9223798/cf3d0fdc-412f-11e5-8dc1-3741b0cfaace.png)

**Comment by mjau-mjau** [comment]
The errors are from your angular process when trying to build the photoSwipe slides object before it even gets to photoSwipe. Looks to me like you have some issue in your iteration of the slides object you are creating. Personally I don't have any experience with Angular, and I doubt the plugin author will have time. Perhaps you should post this on stackoverflow.com or in a dedicated Angular support group?

**Comment by jameswyse** [comment]
Angular may be reloading your controller when the URL is changed by PhotoSwipe, causing an infinite loop. Disabling the "history" feature should fix that. (`options.history = false`).

**Comment by jhabdas** [comment]
This issue is stale. Please close it.
