### ISSUE TITLE
zoom before load complete on ios

### ISSUE THREAD

**Issue by mustafaarun** [dimsemenov/PhotoSwipe#938]
as seen in attached image, (even on demo page) after gallery is initiated and click one item, if you double tap on image before large size loading completed, when loading completes large image positions wrongly.

best way to test this is via a slower connection to gain time to double tap before load completes

![img_2049](https://cloud.githubusercontent.com/assets/8030368/9243619/62541e8a-419b-11e5-9d95-983fbd66df3d.PNG)

**Comment by dimsemenov** [comment]
- Can you repeat this on any other device?
- What version of iOS?

**Comment by mustafaarun** [comment]
ios 8.4 iphone 5s
ios 8.2 ipad retina

the issue occurs because of setting wrong zoomlevel on items.
i fixed it by changing _setImageSize function.
i know this is not an elegant solution but works as expected

```javascript
_setImageSize = function (item, img, maxRes) {

                if (!item.src) {
                    return;
                }

                if (!img) {
                    img = item.container.lastChild;
                }

                var w = maxRes ? item.w : Math.round(item.w * item.fitRatio),
                    h = maxRes ? item.h : Math.round(item.h * item.fitRatio);



                if (item.placeholder && !item.loaded) {
                    item.placeholder.style.width = w + 'px';
                    item.placeholder.style.height = h + 'px';
                }

//for keeping zoom level on image load complete
                if (item.loaded && _currZoomLevel >= 1) {
                    w = item.w;
                    h = item.h;
                }

//for fixing next or previous item zoom level
                if (item.ItemIndex != _currentItemIndex)
                {
                    //console.log("w x h" + w + " x " + h);
                    w = Math.round(item.w * item.fitRatio);
                    h = Math.round(item.h * item.fitRatio);
                }

		        img.style.width = w + 'px';
		        img.style.height = h + 'px';
        }
```

**Comment by dimsemenov** [comment]
Please try this photoswipe.js - https://gist.github.com/dimsemenov/0ce324adbff3928df6fe and let me know if it fixes the issue on your side.

**Comment by mustafaarun** [comment]
i tested on iphone and yes this fixes the issue, thank you very much :)
i will test on ipad too and will let you know the result

may i ask you what changes did you make ?
