### ISSUE TITLE
After Open event

### ISSUE THREAD

**Issue by rafinha90** [dimsemenov/PhotoSwipe#942]
Hi, I need something like an after open event. I need to fire some commands just when the lighbox is created. The commands after pswp.init() run before the lightbox is created, so I need to set a timeout, but that is not precise.

Is there any event that fires after the lightbox is created?

Thanks

**Comment by dimsemenov** [comment]
If you mean after zoom-in transition finishes, the event is `initialZoomInEnd`. There is also `afterInit`, but it fires directly after `init()`.

**Comment by rafinha90** [comment]
Thanks, that's what I was looking for. I thought `initialZoomInEnd` was going to fire when I zoomed the image from PhotoSwipe.

**Comment by kampiamodikuesto** [comment]
i would like to call function only after the image is displayed on the lightbox so after init is complete. afterInit not work:

`gallery.listen('afterInit', function() {...});`

**Comment by qinghechaoge** [comment]
gallery.listen('afterInit', function(index, item) {
     debugger
});
gallery.init();

afterInit must write before init()
