### ISSUE TITLE
Documentation doesn't specify 'mainScrollEndFriction' and 'panEndFriction'

### ISSUE THREAD

**Issue by DanielRosenwasser** [dimsemenov/PhotoSwipe#944]
Doing some work correcting TypeScript typings for PhotoSwipe as part of https://github.com/Microsoft/TypeScript/issues/4081.

I'm wondering whether the `mainScrollEndFriction` and `panEndFriction` options are supposed to be documented or not, since [I don't see them documented](https://github.com/dimsemenov/PhotoSwipe/blob/2f1f09ee38d654c9c0d9797277164e6371da053c/website/documentation/options.md) on the website. Just wanted to give a heads up.

**Comment by dimsemenov** [comment]
Thank you. I'm planning to deprecate these options in future version (move to private constant), that's why they aren't in documentation.

**Comment by DanielRosenwasser** [comment]
Got it; think it would be a problem if I included them but added a JSDoc comment with a `@deprecated` tag and mentioned that future versions won't consider the option at all?

**Comment by dimsemenov** [comment]
No, there won't be any issues with that.

**Comment by DanielRosenwasser** [comment]
Thanks for the help!
