### ISSUE TITLE
Smooth animation from cropped thumbnail

### ISSUE THREAD

**Issue by marcel-burkhard** [dimsemenov/PhotoSwipe#948]
The animation from a cropped thumbnail to the full, uncropped image is obviously not smooth.
It would be great if there was a way to do it smoothly.

To be more clear:

**Usage:**
Specify the cropping dimensions on the full image.

**Changes in animation:**
If ```data-crop-dimensions``` or the like is specified, make the animation 2-step.
1. Create two black div's on the left and right of the full image and animate like it does currently
2. Slide away the divs (cropped full size image -> complete full size image)

**Comment by dimsemenov** [comment]
> Create two black div's on the left and right of the full image and animate like it does currently

It's not ideal solution, as gallery bg is transparent during the transition. And what about thumbnails that need expanding more then in two directions...

I wrote about this in [FAQ](http://photoswipe.com/documentation/faq.html#different-thumbnail-dimensions).

**Comment by marcel-burkhard** [comment]
Thank you for your reply.

I suppose this issue can be closed.
