### ISSUE TITLE
Download images not working in Safari for iOS and Desktop.

### ISSUE THREAD

**Issue by JulianTortolo** [dimsemenov/PhotoSwipe#949]
Hi everyone! 

When I select download image, nothing is happened.

Anyone can help me?

I'm using the new version.

thanks!.

@dimsemenov

**Comment by mjau-mjau** [comment]
Download links use "download" attribute in anchor tags, which is not supported by Safari or IE yet.
http://caniuse.com/#feat=download
http://www.w3schools.com/tags/att_a_download.asp

In unsupported browsers, the image will therefore open in a new window, where the visitor can download the image from.

This is just how it is. You can work around it if you build a "download" script on server-side, and force download for a specific file. For example ```download.php?file=image.jpg```. This would require amending the share link also naturally.
