### ISSUE TITLE
Tag images in markup to add to PhotoSwipe

### ISSUE THREAD

**Issue by Sanderha** [dimsemenov/PhotoSwipe#954]
I was wondering if i could put a class or attribute on images (or their wrapper) that need to be included in the PhotoSwipe array. 
With fancybox you can set the rel="" attribute on the a tag surrounding the img, and then images with identical rel attributes will be shown in the lightbox.

Is there any way this can be donewith PhotoSwipe?

Could be really awesome, since PhotoSwipe is such a great plugin

**Comment by dimsemenov** [comment]
PhotoSwipe does not control initial markup of page. Feel free to modify default example in docs if it doesn't fit your needs http://photoswipe.com/documentation/getting-started.html#dom-to-slide-objects
