### ISSUE TITLE
NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by feichter** [dimsemenov/PhotoSwipe#955]
Hope someone can help.
Firebug is reporting NS_ERROR_FAILURE. I've only got the very basic set up and don't really want to continue on the project if it's already reporting problems. Or can it be ignored?
THANKS.

**Comment by mjau-mjau** [comment]
I don't think this is related to Photoswipe. If you have a live example, I would gladly take a look. It is possible this error msg can be ignored, but I can't say for sure unless I know what it is related to.

**Comment by feichter** [comment]
Thanks for your reply.
Sorry, can't give you a live page at the moment, but have included the code below.
I am also using a modified version of http://www.abeautifulsite.net/jquery-file-tree/ which gives me the directories and sub-directories on the site for navigation.
Everything works fine, except that every so often (randomly) the photoswipe goes black. the NS_ERROR_FAILURE still comes up.

<div id="top" class="top">
Welcome <b><?php echo $session->username; ?></b>, you are logged in.
<a href="login/userinfo.php?user=<?php echo $session->username; ?>"></a> || <a href="login/useredit.php" class="white">Edit Account</a> || <a href="login/process.php" class="white">Logout</a>
<?php
include("Library/nav.php");
?>
</div>
<script type="text/javascript">
$(document).ready( function() {

list = [];
	
	$('#fileTreeDemo_1').fileTree({root: '/var/media/KODI_LOUNGE/photos/', script: 'connectors/jqueryFileTree.php', multiFolder: false}, function(file){

	var file = decodeURIComponent(file);
	
	var stripped = file.replace(/^(\/var\/media\/KODI_LOUNGE)/,"");
	
	var dir = stripped;	
	
	var dataString = 'dir=' + dir;
	
	list = "";
	
	$.ajax({
		type: "POST",
		url: "list_files_new.php",
   		data: dataString,
		cache: false,
		dataType: "json",
  			success: function(reply){
				
				list = reply;
				
				start();
				
			}
			
	});

});
});

function start(){

var pswpElement = document.querySelectorAll('.pswp')[0];

items = "";
items.length = 0;
var items = [];

for(i = 0; i < list.length; i++){
	var caption = list[i].filename
	var caption1 = caption.replace(/^.*[\\\/]/, '');
	items.push({"src":list[i].filename,"w":list[i].w,"h":list[i].h,"title":caption1});
}

var template = document.getElementById("gallery"); // .pswp
var options = {
    index: 0,
    //modal: false,
    closeOnScroll: false
};

var photoSwipe = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options);

photoSwipe.listen('updateScrollOffset', function(_offset) {
    var r = template.getBoundingClientRect();
    _offset.x += r.left;
    _offset.y += r.top;
});

photoSwipe.init();
}
</script>
<div id="fileTreeDemo_1" class="folder_nav"></div>

<div class="pswp" id="gallery" tabindex="-1" role="dialog" aria-hidden="true" style="left: 250px; top: 100px; width: 800px; height: 600px">
    <div class="pswp__bg"></div>
    <div class="pswp__scroll-wrap">
        <div class="pswp__container">
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
            <div class="pswp__item"></div>
        </div>
        <div class="pswp__ui pswp__ui--hidden">
            <div class="pswp__top-bar">
                <div class="pswp__counter"></div>
                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                <button class="pswp__button pswp__button--share" title="Share"></button>
                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                <div class="pswp__preloader">
                    <div class="pswp__preloader__icn">
                      <div class="pswp__preloader__cut">
                        <div class="pswp__preloader__donut"></div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                <div class="pswp__share-tooltip"></div> 
            </div>
            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
            </button>
            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
            </button>
            <div class="pswp__caption">
                <div class="pswp__caption__center"></div>
            </div>
        </div>
    </div>
</div>

![black](https://cloud.githubusercontent.com/assets/14124959/9733006/1696aee2-5620-11e5-9a81-61703bdaa2f9.jpg)
![working](https://cloud.githubusercontent.com/assets/14124959/9733005/1690d2ba-5620-11e5-9694-ada0f1bb2fe8.jpg)

Thanks for looking!

**Comment by feichter** [comment]
How do I add code to github?

**Comment by mjau-mjau** [comment]
impossible to check, and doubtful this is directly related to Photoswipe. Chance is this is only an issue on your local server anyway ... I searched for ```NS_ERROR_FAILURE```, and the results insinuate it is some load error related to the server.

> How do I add code to github?

They have instructions for that, but I don't think that would help much. If you are able to recreate it on http://codepen.io/, it could be diagnosed.
