### ISSUE TITLE
Add component.json

### ISSUE THREAD

**Issue by ismay** [dimsemenov/PhotoSwipe#956]
It would be cool if you could add a `component.json`. That would allow people who use the [duo.js](http://duojs.org/) and [component](https://github.com/componentjs/component) package managers to directly require this library from your repo as well.

It's very simple, this is what you'd put in `component.json` (which goes at the root, just like `package.json`), no registration or anything else required:

```json
{
  "name": "photoswipe",
  "repository": "dimsemenov/PhotoSwipe",
  "description": "JavaScript gallery",
  "main": "dist/photoswipe.js",
  "version": "4.1.0",
  "keywords": [
    "gallery",
    "lightbox",
    "photo",
    "image",
    "touch",
    "swipe",
    "zoom"
  ],
  "scripts": [
    "dist/photoswipe.js",
    "dist/photoswipe-ui-default.js"
  ],
  "styles": [
    "dist/photoswipe.css",
    "dist/default-skin/default-skin.css"
  ],
  "license": "MIT"
}
```

I'd really appreciate it. Let me know if you'd like a pull request! Also, the spec for component.json files is [here](https://github.com/componentjs/spec/blob/master/component.json/specifications.md).

**Comment by dimsemenov** [comment]
Aright. Please send a pull request, or I'll add it by myself in a few days.

**Comment by ismay** [comment]
Done, let me know if there's anything that needs to be changed.

**Comment by dimsemenov** [comment]
:+1:
