### ISSUE TITLE
is there any way to remove zoom out function that close photoswipe

### ISSUE THREAD

**Issue by jjhangu** [dimsemenov/PhotoSwipe#959]
when zoom out more than percentage, photo swipe is closed.
I want to prevent zoom out compare to original image if it is possible

**Comment by mjau-mjau** [comment]
You mean when using "pinch" on touch devices? There is an option ```pinchToClose```, which can be disabled. I am not sure what you mean be "compare to original image".

> Pinch to close gallery gesture. The gallery’s background will gradually fade out as the user zooms out. When the gesture is complete, the gallery will close.

**Comment by jjhangu** [comment]
Thank you~!!!!! I changed option pinchToClose.
