### ISSUE TITLE
Feature: not fullscreen-only layout.

### ISSUE THREAD

**Issue by ikr0m** [dimsemenov/PhotoSwipe#965]
@dimsemenov As you mentioned https://github.com/dimsemenov/PhotoSwipe/issues/689 and as far as I know photoswipe works only in fullscreen mode. 

Are you planning to add *not* fullscreen-only layout? It would be very helpful if photoswipe works on targeted element.

There is a forked branch of photoswipe which supports not fullscreen layout. https://github.com/Persgroep/PhotoSwipe But it is not maintaining anymore.

**Comment by dimsemenov** [comment]
This might help – http://photoswipe.com/documentation/faq.html#inline-gallery

**Comment by ikr0m** [comment]
Thanks! I will try it.
