### ISSUE TITLE
<input> elements within HTML slides cannot be focused with left click.

### ISSUE THREAD

**Issue by silentzor** [dimsemenov/PhotoSwipe#969]
<input> elements inside an HTML slide cannot be focused with left click, they only gain focus when right clicked. Tried it locally and on your codepen example, same behaviour on both.

**Comment by dimsemenov** [comment]
Refer to:

- `isClickableElement` option http://photoswipe.com/documentation/options.html
- and `preventDragEvent` http://photoswipe.com/documentation/api.html

**Comment by silentzor** [comment]
Thanks "isClickableElement" was exactly what I needed.
