### ISSUE TITLE
Add new button

### ISSUE THREAD

**Issue by herocd** [dimsemenov/PhotoSwipe#975]
I want to add new button to top bar but it isn't working in mobile. please help me. Thank!
![capture](https://cloud.githubusercontent.com/assets/13325501/10010442/ba1024fe-6115-11e5-9589-e80ba1814aa0.PNG)
when i click button, pswp__top-bar hidden!

**Comment by dimsemenov** [comment]
To add button, modify the UI JS file, https://github.com/dimsemenov/PhotoSwipe/blob/master/dist/photoswipe-ui-default.js#L438 (take a look how share or close buttons are added)

as well as `pswp__ui` part of `.pswp` element:

```
...
<div class="pswp__ui pswp__ui--hidden">

            <div class="pswp__top-bar">

                <div class="pswp__counter"></div>

                <button class="pswp__button pswp__button--like" title="My custom like button"></button>
```

**Comment by herocd** [comment]
great. it works. I want to call the event when swipe down in photoswipe. How does it work? and when add new item, it does not work in your chrome browser (mobile). thank you very much!

**Comment by dimsemenov** [comment]
>  I want to call the event when swipe down in photoswipe

Look for onVerticalDrag in UI js file.

> when add new item, it does not work in your chrome browser (mobile)

Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server."

**Comment by herocd** [comment]
Thank you very much! problem solved. :+1:
