### ISSUE TITLE
Unneeded return value generates warning

### ISSUE THREAD

**Issue by morganwdavis** [dimsemenov/PhotoSwipe#978]
Google's Closure Compiler generates a warning in _calculateItemSize on the "return false;" statement at the end of the function:

```
WARNING:
     'type' => 'JSC_UNREACHABLE_CODE',
     'file' => 'Input_0',
     'lineno' => 2792,
     'charno' => 2,
     'warning' => 'unreachable code',
     'line' => '                return false;',
```

That  statement is never executed due to the if/else logic that precedes it.

**Comment by dimsemenov** [comment]
Thanks, good catch :+1:
