### ISSUE TITLE
Feature request/suggestion

### ISSUE THREAD

**Issue by Hk1020** [dimsemenov/PhotoSwipe#99]
Safari on iPad has the feature that if you tap and hold an image you can save it.  This seems to work only if you do that to an img element (though I haven't thoroughly checked that). In the photoswipe image gallery this doesn't work as you are hovering over something else apparently. Would it be possible to modify photoswipe accordingly? Would be really cool if you could save images that way.

**Comment by bindiry** [comment]
+1

**Comment by exophunk** [comment]
So 5 years later, this function is still broken?

**Comment by chesio** [comment]
@exophunk It's not broken, rather not implemented. As per comments in #1216, it might be not that easy to implement.

**Comment by lost-an** [comment]
+1

**Comment by bora89** [comment]
+1

**Comment by mvzen** [comment]
> As per comments in #1216, it might be not that easy to implement.

Can some beer money be thrown somewhere to get this looked into?

**Comment by capuski** [comment]
I still miss this default long press behavior.
I did some tests again, and seems to work (Chrome on IOS [yes, i know]) just changing CSS:

body .pswp__img {
  -webkit-touch-callout: default !important;
  touch-callout: default !important;
  -webkit-user-select: text !important;
  -moz-user-select: text !important;
  -ms-user-select: text !important;
}

But in Safari I can't solve this problem, sadly.

**Comment by JayWii** [comment]
@capuski I have made some modifications and encapsulation to photoswipe in the past few days , and it seems that I have fixed the problem that we can't save image through long press in safari. Maybe you can take a look

**Comment by capuski** [comment]
@JayWii I tested the demo page in IOS and it worked perfectly (Safari and Chrome). I will implement it. Thank you so much!

**Comment by capuski** [comment]
@JayWii have you changed a lot of the plugin? I noticed some changes in how you interact with the open photo. There is no hiding the top and bottom bars (close and caption). I consider this property very important because it allows you to view the photo in real full screen. Is there anything more significant that you have changed in the plugin?
Thanks

**Comment by JayWii** [comment]
@capuski Thanks for your feedback, i have not changed a lot of the plugin, just about long press save in Safari . About the question of 'no hiding the top and bottom bars',  when you set `tapToClose` to `false`, click action will hide the top and bottom bars, btw, i add a new option `topBarEl` , so you can hide the top-bar without click,  today i update some code, and now you can use `options` to use the plugin (Photoswipe) original options, just like this: 

```js
// JS
var options = {
    closeEl: true,
    tapToClose: false,
    topBarEl: true
}
PhotoPackage.init(imageArr, '.img-selector', options);
```
Vue-component is also support, you can check the readme.

**Comment by capuski** [comment]
@JayWii Great. I will take a look with more attention. Thank you again :)

**Comment by capuski** [comment]
@JayWii Can I use your script without changing my JS calls? My site Scripts are a little bit complex to me, lots of functions calling functions. And I use cash plugins that complicate even more.
http://nadalinfotografia.com.br/ensaio-pet-amanda-tequila/

**Comment by JayWii** [comment]
@capuski Of course, you don't have to use my plugin, you can find a script `photoswipe.min.js`  in /build folder, and you just need use this script file to replace your old `photoswipe.js` or `photoswipe.min.js` without any change of your code

**Comment by capuski** [comment]
@JayWii Strange because I just replace the `photoswipe.min.js` and I got error that PhotoSwipe is not defined.
![captura de tela 2017-11-29 as 13 35 26](https://user-images.githubusercontent.com/4540678/33383409-62b1ab68-d50a-11e7-960b-bc1baa3ad4f0.png)

**Comment by JayWii** [comment]
@capuski sorry, it's my fault, i uploaded a wrong file an I have just reposted it correctly, you can try again. btw, I'm going to bed. Good night & Good Luck

**Comment by capuski** [comment]
@JayWii Thank you so much for your help and attention. Implementing just de `photoswipe.min.js` causes a lot of bugs to me. Maybe with more time I will try to use your entire plugin. I will atach here 2 videos with the bugs that I mentioned (IOS Mobile in Safari and Chrome) just to share the problem. 
Thank you again dude!

Videos: https://drive.google.com/drive/folders/1dmBzPgZ91RSq58jCkLgGV9U1u_a99pcK?usp=sharing

**Comment by JayWii** [comment]
@capuski maybe you need FastClick.js. I guess。。。
