### ISSUE TITLE
Not loading with styles and consistently crashing on iOS Safari

### ISSUE THREAD

**Issue by tridium79** [dimsemenov/PhotoSwipe#990]
I am trying to load this URL: http://www.dpreview.com/sample-galleries/1025395973/iphone-6s-sample-image-gallery

Works on: 
 - all desktop browsers (with mobile emulation)
 - Android phones
 - iOS Chrome

Fails on: 
 - iOS Safari

It loads the page without the proper scale - the text "1/45" is in large text and the image is somewhere to the bottom-right. When I scroll left / right it navigates to the previous / next image.

This happens only with my particular implementation of Photoswipe because it works on other parts of the site. Exactly the same implementation except for the provided image files and metadata, which work in all other browsers. I've made sure that jQuery is loading before Photoswipe and reduced the image size from 2400px on the longest edge to 1200px. Nothing changed. 

I'm at a loss since in every other possible configuration it works except for iOS Safari.

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

Also, you aren't using the latest version and you should read about `<meta name="viewport" content="width = device-width, initial-scale = 1.0"> ` tag.

**Comment by tridium79** [comment]
Thanks for the reply. After trying to create an isolated test case, I discovered iOS / Safari was not playing nicely with the tracking code (Google Analytics, comScore, Alexa, etc.) included in the page. Still need to figure out why they're not playing nicely together but in the meantime, removing it seems to have fixed it.
