### ISSUE TITLE
how to remove this space and make image fill it instead? (screenshot)

### ISSUE THREAD

**Issue by fotorunedotcom** [dimsemenov/PhotoSwipe#992]
how to remove this space and make image fill it instead? (screenshot)

website:
http://fotorune.com/

![fotorunedotcom](https://cloud.githubusercontent.com/assets/15047252/10390241/ad581e64-6e77-11e5-9241-436f33a6e8be.jpg)

**Comment by dimsemenov** [comment]
`barsSize: {top:0, bottom:0}` http://photoswipe.com/documentation/options.html

**Comment by fotorunedotcom** [comment]
Thank you so much!!
