### ISSUE TITLE
image portrait (exif) becomes landscape

### ISSUE THREAD

**Issue by fghhfg** [dimsemenov/PhotoSwipe#995]
On my pc, I try second example in http://photoswipe.com/documentation/getting-started.html

Problem: image portrait becomes landscape if you have portrait orientation tag of exif.

Clicks thumbnail, photoswipe opens lightbox. After one sec. later, it becomes landscape.
The bigger problem is light part in the screen still keep portrait, which means height of image would be extended...

or am I the only one who has this problem?

**Comment by dimsemenov** [comment]
PhotoSwipe does not parse exif image data, which imples that rotation info is ignored.
