### ISSUE TITLE
iphone rotates portait images

### ISSUE THREAD

**Issue by cooperjbrandon** [dimsemenov/PhotoSwipe#996]
When in gallery view on iphone, photoswipe is rotating portrait images 90 degrees. This doesn't happen for landscape photos, nor does it occur in a laptop or android device.

After perusing google, I see that there was a similar issue 3-4 years ago when in UIWebView, but I'm just using basic safari. Also, I don't think that answer is relevant today, as it said to enable `enableUIWebViewRepositionTimeout` to `true`, but I can't seem to find that variable in photoswipe now.

Here is the issue from 4 years ago. It's similar but not quite the same: https://github.com/dimsemenov/PhotoSwipe/issues/141

**Comment by dimsemenov** [comment]
Please provide a [reduced test case](http://css-tricks.com/reduced-test-cases/) (isolated example) that reproduces the problem.
 
You may create it based on CodePens in PhotoSwipe documentation: [raw gallery](http://codepen.io/dimsemenov/pen/gbadPv), [gallery with thumbnails](http://codepen.io/dimsemenov/pen/ZYbPJM), [custom HTML content in slides](http://codepen.io/dimsemenov/pen/MYexrm). If you're not comfortable with CodePen, you may export code via `Share -> Export .zip`, and upload test case to your server.

Also, please provide screenshot of an issue. And are you using the latest iOS?

**Comment by cooperjbrandon** [comment]
Here's the codepen: http://codepen.io/anon/pen/QjOeBp?editors=101 . The first image is portrait, and the second image is landscape. Viewing it on a laptop, everything is OK, but if you navigate to the link on an iPhone, the first image is sideways. I'm using the latest iOS with a 6s.

So I'm not quite if its my photo orientation, or photoswipe. I actually noticed that when navigating directly to the portrait image's s3 link, the portrait photo downloads sideways. So that could be an explanation of why it's showing up sideways in photoswipe-gallery. However, why would it behave differently on a iphone as opposed to a laptop?

**Comment by dimsemenov** [comment]
Issue is caused by the image itself, if you try to just embed it on page using simple IMG tag, it'll be rotated too.

It's caused by exif rotation data, your image is rotated 90°.

**Comment by cooperjbrandon** [comment]
makes sense. thanks. but why would it render correctly on a laptop?

**Comment by cooperjbrandon** [comment]
ahhh, sry. It's an iphone issue. iPhone in portrait mode says that the orientation is a `6`, or `Rotate 90 CW`.

**Comment by tphelps19** [comment]
Was this issue ever fixed?  Any picture with exif rotation info doesn't display correctly in Photoswipe.  Works fine from computer, but on iOS image is skewed.  Is there a fix?
